[백진영]week4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #102
Opened 2023-12-16 17:06 UTC by jinyoung1018

## 요구사항

### 기본

- [x] [기본]이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지가 보이나요?
- [x] [기본]이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 input에 빨강색 테두리와 아래에 “올바른 이메일 주소가 아닙니다.” 빨강색 에러 메세지가 보이나요?
- [x] [기본]이메일 input에서 focus out 일 때, input 값이 test@codeit.com 일 경우 input에 빨강색 테두리와 아래에 “이미 사용 중인 이메일입니다.” 빨강색 에러 메세지가 보이나요?
- [x] [기본]비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, input에 빨강색 테두리와 아래에 “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 빨강색 에러 메세지가 보이나요?
- [x] [기본]비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input에 빨강색 테두리와 아래에 “비밀번호가 일치하지 않아요.” 빨강색 에러 메세지가 보이나요?
- [x] [기본]회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 빨강색 테두리와 에러 메세지가 보이나요?
- [x] [기본]이외의 유효한 회원가입 시도의 경우, “/folder”로 이동하나요?
- [x] [기본]이메일: test@codeit.com, 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동하나요?
- [x] [기본]비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?
- [x] [기본]이외의 로그인 시도의 경우 이메일, 비밀번호 input에 빨강색 테두리와 각각의 input아래에 “이메일을 확인해주세요.”, “비밀번호를 확인해주세요.” 빨강색 에러 메세지가 보이나요?
- [x] [기본]회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 되나요?
- [x] [기본]이메일, 비밀번호 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?

### 심화

- [x] [심화]눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?
- [x] [심화]비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?
- [ ] [심화]로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용했나요?

## 주요 변경사항

- 이메일, 비밀번호 유효성 체크
- 눈모양 아이콘 클릭 시 동작 기능

## 스크린샷

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-18 08:13 UTC, Jun-12 commented on script/signup.js
> +        location.href = "/folder";
location.href는 데이터 전송 없이 브라우저의 주소창을 변경하거나 새로운 페이지로 이동 할 때 사용하는 것으로 알고있습니다. form 태그에 id를 부여한 후 데이터를 전송하는 방식을 사용해보는 건 어떨까요?
```suggestion
const form = document.getElementById('#form');
form.action = '/folder.html';
form.method = 'POST';
form.submit();
```

2023-12-18 18:28 UTC, wonsss requested changes
안녕하세요 진영님 😄 깔끔하게 코드를 작성해주셨네요.  👍 
수고 많으셨습니다. 
리뷰 확인해주시고, 피드백 반영 후 다시 리뷰받고 싶으실 때 DM주세요 🚀

2023-12-18 18:28 UTC, wonsss commented on signin.html
> +                <div class="sign-input-box">
id와 class 이름을 지을 때, 어떤 표기법을 사용하실지 정한 후 일관성 있게 사용하시면 좋을 것 같아요.
현재는 카멜케이스와 스네이크케이스 등이 혼용된 것 같습니다.

2023-12-18 18:28 UTC, wonsss commented on signin.html
> +            <a class="login_btn" id="signinBtn">로그인</a>
"로그인" 버튼의 역할은 form을 submit 시키는 거예요. 
페이지를 이동시킬 때 사용하는 앵커 태그는 이 상황에서 적절하지 않습니다.

대신에 submit type의 button으로 수정하고 
form 요소 내로 옮겨주세요.
```html
  <form>
      <-- 생략 -- >
    <button type="submit" class="login_btn" id="signinBtn">로그인</button>
  </form>
```

아래 링크 등을 통해 form에 대해 더 알아보시면 좋을 것 같아요.
https://tecoble.techcourse.co.kr/post/2021-05-22-html-form-tag/
https://developer.mozilla.org/ko/docs/Web/HTML/Element/form
https://developer.mozilla.org/ko/docs/Glossary/Submit_button

2023-12-18 18:28 UTC, wonsss commented on signin.html
> +          <script src="./script/signin.js"></script>
일반 스크립트 대신에 module을 사용해보세요.

```suggestion
          <script type="module" src="./script/signin.js"></script>
```
<img width="916" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/8615b162-5612-427e-8362-cd23e860187f">

https://ko.javascript.info/modules-intro#ref-992 에서 모듈에 대해 더 알아보시면 좋을 것 같아요 😄

2023-12-18 18:28 UTC, wonsss commented on signup.html
> +            <a class="login_btn" id="signupBtn">회원가입</a>
signin 에서 설명드린 것처럼 이 부분도 수정해주세요.

2023-12-18 18:28 UTC, wonsss commented on signup.html
> +        <script src="./script/signup.js"></script>
모듈 스크립트 적용해주세요

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +const inputPwIcon = document.querySelector("#inputPwIcon");
저는 변수 이름을 지을 때 그 이름이 변수가 나타내는 것을 완전하고 정확하게 설명하는 지를 가장 중요하게 고려합니다.
이런 관점에서 여러 가지 경우로 해석될 여지가 있는 약어(pw, err, btn 등)는 잘 사용하지 않습니다.
프로젝트 협업자와 함께 특정 약어에 대해 컨베션으로 하기로 합의를 하셨다면 괜찮을 수도 있으나, 그렇지 않았다면 맞춤법에 맞게 네이밍해주시는 것이 기본일 것 같아요.

그리고 VScode에서 Code Spell Checker 익스텐션 사용해보세요. 맞춤법 틀림 예방에 정말 좋습니다

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +    const email_format =
자바스크립트에서 일반적인 변수명은 카멜케이스(emailFormat)를 사용합니다. 
그런데 상수를 표현하고 싶으셨다면, 
`EMAIL_FORMAT` 처럼 모두 영어 대문자에 띄어쓰는 부분은 언더바를 적습니다.

그리고 EMAIL_FORMAT 보다는 정규표현식이니까 EMAIL_REGEX 가 더 나은 이름으로 보이는데 진영님은 어떻게 생각하세요?

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +    }
if, else if, else 가 많이 이어지고 있네요. 
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else문을 사용하지 않아도 됩니다.

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +    const passwordRegex = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,16}$/;
좋은 변수명이네요 👍

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +signinBtn.addEventListener("click", signIn);
회원가입 버튼에 직접 클릭 이벤트를 달지 마시고, form을 이용하여 submit 이벤트에 핸들러를 등록해보세요.
예시 코드를 전달드리니 참고해보세요. 그리고 참고로 event.preventDefault()는 submit의 기본 동작을 방지하기 위한 메서드입니다. submit의 기본 동작은 새로고침인데 그럴 필요가 없어서 추가합니다. 
 
```js
const signinForm = document.getElementById('signin-form');

function handleFormSubmit (event) {
  event.preventDefault();

    if (
        inputEmail.value === "test@codeit.com" &&
        inputPw.value === "codeit101"
    ) {
        location.href = "/folder";
    } else {
        emailError.textContent = "이메일을 확인해주세요.";
        pwError.textContent = "비밀번호를 확인해주세요.";
    }
}

signinForm.addEventListener('submit', handleFormSubmit);
```

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +        inputPw.value === "codeit101"
'test@codeit.com', 'codeit101' 과 같은 도메인과 관련된 `매직 리터럴`은 별도의 파일에 상수로 분리하여 모듈화한 후 관리해주시면 좋습니다.

매직 넘버(Magic number)나 매직 리터럴(Magic Literal)은 코드에서 하드 코딩된 일정한 값을 의미하는 숫자나 문자열을 의미합니다. 
예를 들어 'test@codeit.com' 코드 내에서 여러 곳에서 사용되고 있지만, 이 값의 의미나 목적은 현재 코드에서 명확하게 알려져 있지 않습니다.

매직넘버나 매직리터럴은 가독성이 떨어지고 유지보수를 어렵게 만들며, 예상치 못한 버그를 발생시키는 원인이 될 수 있습니다.

따라서 이들을 상수로 분리하고 해당 매직넘버의 역할을 정확한 이름으로 붙여서 사용하시는 것이 좋습니다. 그리고 상수로 분리해두면 값을 변경할 때 일괄적으로 변경할 수 있으므로 코드의 유지보수성과 가독성이 향상됩니다.

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +        location.href = "/folder";
form의 action 속성을 사용하시면 location 객체의 href 속성으로 페이지를 이동시킬 필요가 없습니다. 
form의 action 속성은 폼 내부에 데이터를 보내는 목적지 url을 지정합니다.

2023-12-18 18:28 UTC, wonsss commented on script/signup.js
> +let passwordConfirmValid = false;
이와 같은 전역변수는 사용을 지양해야 합니다.
현재 해당 변수들은 check 함수 내에서 조건의 결과로 값이 변경되고, 이 변수들이 회원가입 시도 시 해당 핸들러의 함수 내에서 통과 조건으로 사용되고 있는 것 같네요.

대안으로서, 해당 전역변수들을 제거하고, check 함수 내에서 `emailValid = false `와 같은 변수 값 변경 대신 `return false ` 처럼 boolean 값을 return 하도록 변경해보세요.
그리고 회원가입 핸들러 함수 내에서는 check 함수를 불러서 실행합니다. check 함수의 결과값이 boolean이며 이전의 valid 전역변수와 같은 역할을 할 수 있습니다.

2023-12-18 18:28 UTC, wonsss commented on script/signup.js
> +        emailValid = true;
위에서 설명드린 내용(early return, 그리고 전역변수 제거) 을 적용하면 다음과 같습니다.
```suggestion
    if (!inputEmail.value) {
        emailError.textContent = "이메일을 입력해주세요.";
        inputEmail.className = "error-box";
        return false;
    }
    
      if (!email_format.test(inputEmail.value)) {
        emailError.textContent = "올바른 이메일 주소가 아닙니다.";
        inputEmail.className = "error-box";
        return false;
    }
    
      if (inputEmail.value === "test@codeit.com") {
        emailError.textContent = "이미 사용 중인 이메일입니다.";
        return false;
    } 

      emailError.textContent = " ";
      inputEmail.className = "inputbox";
      return true;
```

2023-12-18 18:28 UTC, wonsss commented on script/signup.js
> +        inputPwConfirm.className = "error-box";
early return 패턴으로 리팩터링 해보세요!

2023-12-18 18:28 UTC, wonsss commented on script/signup.js
> +    const email_format =
변수 표기법 확인해주세요

2023-12-18 18:28 UTC, wonsss commented on script/signup.js
> +    }
위에서 설명드린 내용 참고하여 조건문 리팩터링하시면 좋을 것 같아요. 😄 

밑에 있는 다른 조건문도 다 같이 해주시면 더 좋습니다!

2023-12-18 18:28 UTC, wonsss commented on script/signup.js
> +signupBtn.addEventListener("click", signUp);
siginin 에서 설명드린 것과 같이 submit 이벤트 리스너 사용해보세요

2023-12-18 18:28 UTC, wonsss commented on signin.html
> +                <input type="email" id="inputEmail" class="inputbox" />
첫번째 input 태그에 autofocus 속성을 주시면 페이지가 새로고침되자마자 이 첫 input에 focus가 있어서 사용자가 인풋을 클릭할 필요 없이 바로 입력할 수 있어서 사용자 경험에 좋을 것 같아요.

<img width="923" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/799de619-e497-4137-b355-7e4c7a8301ce">

2023-12-18 18:28 UTC, wonsss commented on signup.html
> +                <input type="email" id="inputEmail" class="inputbox" />
form의 첫번째 input에 autofocus 하시면 사용자 경험에 좋을 것 같아요.

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +function showPasswordToggle(element_icon, element_input) {
함수 매개변수의 이름 표기법이 스네이크 케이스네요.
카멜케이스로 수정해주세요 😄

2023-12-18 18:28 UTC, wonsss commented on script/signin.js
> +const inputEmail = document.querySelector("#inputEmail");
코드를 전체적으로 가독성 좋게 작성해주셨네요 👏 
상단에는 DOM에서 선택된 요소 변수들을 모아두셨고,
중간에는 이벤트 핸들러인 함수 정의를 모아두셨고,
하단에는 이벤트 리스너를 모아두셔서 확인하기 편했습니다.

2023-12-20 17:43 UTC, jinyoung1018 commented on script/signup.js
> +        location.href = "/folder";
c46f41b7543040621436ca4e1d6cd5e2dda536c3 생각하지 못한 부분인데 알려주셔서 감사합니당! 그렇게 수정했습니다!!

2023-12-20 17:47 UTC, jinyoung1018 commented on signin.html
> +            <a class="login_btn" id="signinBtn">로그인</a>
6b74b4e51da915e7128cc37baf7ee873ea4df9e5 알려주신 자료 모두 읽어보고 수정완료하였습니다!

2023-12-20 17:48 UTC, jinyoung1018 commented on signin.html
> +          <script src="./script/signin.js"></script>
0c782ada4bb3f76d1855f6efd7dcbff9fb343b0e 일반 스크립트와 module의 차이점에 대해 더 자세하게 알게되었습니다! 모두 module로 수정하였습니다!

2023-12-20 17:52 UTC, jinyoung1018 commented on signup.html
> +            <a class="login_btn" id="signupBtn">회원가입</a>
f2428561e89750b56c5136e28b92dc30cc753626 이 부분도 수정하였습니다!

2023-12-20 17:53 UTC, jinyoung1018 commented on signup.html
> +        <script src="./script/signup.js"></script>
ef93ff728a6a54757db67d4ae219b703dd99471c 적용했습니다!!

2023-12-20 17:53 UTC, jinyoung1018 commented on script/signin.js
> +const inputPwIcon = document.querySelector("#inputPwIcon");
3c23c07a8c35645af60b54a5d4b47788de7facc1 변수명 모두 수정하였습니다!

2023-12-20 17:56 UTC, jinyoung1018 commented on script/signin.js
> +    const email_format =
3c23c07a8c35645af60b54a5d4b47788de7facc1 이 부분도 수정하였습니다! 앞으로 변수명 설정할 때 더욱 주의해야겠어용!!

2023-12-20 17:58 UTC, jinyoung1018 commented on script/signin.js
> +    }
e561ff35cc4fc3f862271d1dfb79b9196d91d0f0 early return에 대해 알게되었습니다! 코드 가독성 측면에서 훨씬 좋은 것 같습니다! 모두 수정했습니다!

2023-12-20 18:01 UTC, jinyoung1018 commented on script/signin.js
> +signinBtn.addEventListener("click", signIn);
6b74b4e51da915e7128cc37baf7ee873ea4df9e5 f2428561e89750b56c5136e28b92dc30cc753626 form submit에 대해 확실하게 알게된 것 같아요!! 모두 수정하였습니다!

2023-12-20 18:03 UTC, jinyoung1018 commented on script/signin.js
> +        inputPw.value === "codeit101"
5ce5706179828d4c7a8dfae835fb0b33cebb57ce 앞으로 항상 주의해야 할 부분인 것 같아요!! 따로 모듈로 분리해봤는데 이렇게 하는게 맞을까용??

2023-12-20 18:04 UTC, jinyoung1018 commented on script/signin.js
> +        location.href = "/folder";
c46f41b7543040621436ca4e1d6cd5e2dda536c3 데이터를 전송하는 목적까지 생각하지 못하고 너무 단순하게 생각한 것 같아요ㅠㅠ 수정하였습니다!

2023-12-20 18:06 UTC, jinyoung1018 commented on script/signup.js
> +let passwordConfirmValid = false;
6d11dcffe36a18b98b0cf4a71d8064c7805a6d9d 이런 대안으로 불필요한 전역변수 사용을 막을 수 있군요!! 새롭게 알게되었습니다! 모두 수정완료하였습니다!

2023-12-20 18:07 UTC, jinyoung1018 commented on script/signup.js
> +        emailValid = true;
e561ff35cc4fc3f862271d1dfb79b9196d91d0f0 모두 수정했습니다!!

2023-12-20 18:07 UTC, jinyoung1018 commented on script/signup.js
> +        inputPwConfirm.className = "error-box";
e561ff35cc4fc3f862271d1dfb79b9196d91d0f0 앞에 알려주신 것 처럼 모두 수정했습니다!

2023-12-20 18:08 UTC, jinyoung1018 commented on script/signup.js
> +    const email_format =
이 부분도 수정하였습니다!

2023-12-20 18:08 UTC, jinyoung1018 commented on script/signup.js
> +    }
e561ff35cc4fc3f862271d1dfb79b9196d91d0f0 조건문 모두 수정하였습니다!

2023-12-20 18:09 UTC, jinyoung1018 commented on script/signup.js
> +signupBtn.addEventListener("click", signUp);
f2428561e89750b56c5136e28b92dc30cc753626 넵 그렇게 수정하였습니다!

2023-12-20 18:11 UTC, jinyoung1018 commented on signup.html
> +                <input type="email" id="inputEmail" class="inputbox" />
f28a4a99637ea71bb18f12acd270414500039539 사용자 경험 측면에서도 앞으로 더 고민하는 개발자가 되겠습니당!!  autofocus추가했습니당!

2023-12-20 18:11 UTC, jinyoung1018 commented on script/signin.js
> +function showPasswordToggle(element_icon, element_input) {
3c23c07a8c35645af60b54a5d4b47788de7facc1 모두 카멜케이스로 수정했습니다!

2023-12-20 18:13 UTC, jinyoung1018 commented on script/signin.js
> +const inputEmail = document.querySelector("#inputEmail");
항상 자세한 리뷰 너무 감사드립니다!! 원석님 덕분에 매번 리뷰 받을 때마다 새로운 것도 많이 알게되고 많이 성장하는 것 같아용!!

2023-12-21 06:04 UTC, wonsss commented on script/signin.js
> +const inputPwIcon = document.querySelector("#inputPwIcon");
수고 많으셨습니다 ㅎㅎ

2023-12-21 06:04 UTC, wonsss commented on script/signin.js
> +    const email_format =
변수 네이밍은 계속 어려운 것 같아요 ㅋㅋㅋ ㅠ

2023-12-21 06:06 UTC, wonsss commented on script/signin.js
> +    }
수고하셨습니다

2023-12-21 06:06 UTC, wonsss commented on script/signin.js
> +signinBtn.addEventListener("click", signIn);
수고하셨어요~!

2023-12-21 06:07 UTC, wonsss commented on script/signin.js
> +        inputPw.value === "codeit101"
파일명부터 "나 상수야" 하는 느낌으로 명시적으로 해주셔도 좋아요. ㅎㅎ 
`constants.js`

2023-12-21 06:10 UTC, wonsss commented on script/signin.js
> +        location.href = "/folder";
아 그런데 form method 를 post로 하셨다면, 
api에 post 요청 보내시고
페이지 이동은 별도로 location.href 를 이용해서 이동시키는 게 맞을 것 같아요. ㅎㅎ

이건 다음 미션에 좀 더 보시죠 ㅎㅎ

2023-12-21 06:30 UTC, wonsss approved these changes
안녕하세요. 진영님. 리뷰 꼼꼼히 반영해주셨군요. 👍  
수고 많으셨어요.
다음 미션에서 뵈어요 😄

2023-12-21 06:30 UTC, merged