[이치현] Week4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #103
Opened 2023-12-16 19:13 UTC by DanteSnow

## 요구사항

### 기본

- [x] 로그인 페이지의 이메일, 비밀번호 input 유효성 검증에 필요한 함수를 만들고 적용해 주세요.
- [x] Github에 위클리 미션 PR을 만들어 주세요.
- [x] React와 같은 UI 라이브러리를 사용하지 않고 진행합니다.
- [x] 회원가입 페이지의 이메일, 비밀번호, 비밀번호 확인 input에 필요한 유효성 검증 함수를 만들고 적용해 주세요.

### 심화

- [x] 비밀번호를 확인할 수 있는 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 합니다.
- [x] 로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용해 주세요.

## 주요 변경사항

- 자바스크립트 작성 및 모듈화 (input focusout 시 에러 문구 출력 및 input 테두리 색 red로 변경, 비밀번호 확인 아이콘 기능 삽입)

## 스크린샷
![스크린샷 2023-12-17 오전 4 12 33](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/150772344/ecb1278b-35c0-48f9-b469-ce0ae3418e78)

![스크린샷 2023-12-17 오전 4 12 53](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/150772344/084a0391-081a-4ed7-9bd5-5719dac715a0)

## 멘토에게

- 항상 감사드립니다.👍🏻
- [https://657df4f34f9e7f6335fa9778--eclectic-toffee-5d18bb.netlify.app/](url)

2023-12-19 15:53 UTC, goldfrosch requested changes
고생 많으셨습니다. 제가 기본적으로 금주 과제 위주로 확인을 하지만 전체적으로 css를 더 깔끔하게 처리하려고 노력하는 모습이 많이 보입니다. 고생 많으셨습니다!

전체적인 피드백 드립니다.
var, let, const의 차이와 var를 사용하면 안되는 이유에 대해 더 고민해보는게 좋아보여요.
직접 onClick이나 onfocus등 직접 element에 주입하지 않고 addEventListener에 주입한 이유가 궁금합니다. 이 부분 사유 설명 부탁드립니다!

고생했어요 확인 부탁드립니다~

2023-12-19 15:53 UTC, goldfrosch commented on sign_moduel.js
> +  } else if (!email.includes('@')) {
[중요도: 높음] 정규식에 대해서 알아보는게 좋겠습니다! 이메일의 경우 @만 들어간다고 되는게 아니라 .com .net 등의 형식이 들어가야하니까요. 이렇게 작성하게되면 @만 있으면 되는거니까 a@ 도 이메일이라고 인지하니 문제가 될 수있어요

2023-12-19 15:53 UTC, goldfrosch commented on sign_moduel.js
[중요도: 중간] 파일명 바꿔주세요. module입니다 ㅎㅎ

2023-12-19 15:53 UTC, goldfrosch commented on sign_moduel.js
> +  }
```suggestion
  if (email.length === 0) {
    emailError.textContent = '이메일을 입력해주세요.';
    emailError.style.display = 'block';
    emailInput.classList.add('input-error');
    
    return;
  }
  
  if (!email.includes('@')) {
    emailError.textContent = '올바른 이메일 주소가 아닙니다.';
    emailError.style.display = 'block';
    emailInput.classList.add('input-error');
    
    return;
  }
  
  emailError.style.display = 'none';
  emailInput.classList.remove('input-error');
```

[증요도: 중간] 이런 early return 방식도 추천 드립니다. 불필요하게 else if문으로 여러개 가는 것 보다 특정 상황에서 더이상 진행할 필요 없을 경우에 주로 사용하고 특정 if문으로 끝나면 바로 이탈시키는 방식이라 이렇게 쓰는 것도 편합니다.

2023-12-19 15:53 UTC, goldfrosch commented on sign_moduel.js
> +  var email = emailInput.value;
[중요도: 높음] var를 사용하지말고 let이나 const를 사용해주세요.
지금 경우는 변하지 않는 값이기에 const가 적절해보입니다.

혹은 var를 사용한 이유가 있을까요?

2023-12-19 15:53 UTC, goldfrosch commented on signin.js
> +import { validateEmail, validatePassword, togglePasswordVisibility } from './sign_moduel.js';
모듈화 후 import 처리 매우 훌륭합니당 ㅎㅎ

2023-12-19 15:53 UTC, goldfrosch commented on signin.js
> +  var eyeButtons = document.querySelectorAll('.eye-button');
[중요도: 높음] 전체적으로 const로 바꾸는 것을 권장드립니다.
[중요도: 중간] querySelector보다 id 기반으로 가져올 꺼면 getElementById, class로 가져올 때는 getElementByClassName으로 하면 더 명시적일 것 같네요~

2023-12-19 15:53 UTC, goldfrosch commented on signin.js
> +  });
[중요도: 높음] focusout을 사용하게 될 경우 이벤트 버블링이 발생해 상위 엘리먼트들에도 불필요한 이벤트도 발생합니다. 당장 보이지 않겠지만 나중에 영향이 있을 수 있으니 focus가 빠져나간 곳만 반영되는 blur를 써보는 거는 어떻게 생각하시나요?

혹시 부모쪽에도 event가 반영되어야하는 이유가 있을까요?

2023-12-19 15:53 UTC, goldfrosch commented on signup.html
> +<html lang="kr">
[중요도: 높음] kr이 아니라 ko입니다 ㅎㅎ

2023-12-19 15:53 UTC, goldfrosch commented on signup.html
> +  <script type="module" src="signup.js"></script>
[중요도: 높음] 
이거는 면접에서도 자주 나오는 (거의 단골)질문인데요.
웹 페이지의 렌더링 과정에 대해 물어봅니다. JS 즉 스크립트를 가져오고 어떻게 처리되는지에 대해서도 신입분들에게는 단골 질문이 되죠

https://beomy.github.io/tech/browser/browser-rendering/#%EC%B0%B8%EA%B3%A0-javascript%EC%99%80-css

여기 설명이 그나마 깔끔해서 같이 가져오게 되었는데
핵심은 script를 로드할 때 까지 html 렌더링을 기다리기 때문에 만약script를 가져오는 위치가 미국이라던가 엄청 느린 서버에서 가져오게 되면 html자체도 안보이게 될 수 있겠죠?

그래서 script 태그에 defer나 async 옵션을 사용해서 html 렌더링과는 별개로 script 로드를 시켜 렌더링 속도를 줄여주는거죠.
흔히 멀티태스킹을 한다 라고 생각하시면 좀 이해하기 편할겁니다!
멀티태스킹을 하는 사람은 집중을 잘 못하는 사람이라고 말하지만 컴퓨터는 뭐든 집중 잘하는 친구니까 오히려 멀티태스킹을 하게된다면 한번에 하나 처리하는 것 보다 더 빠르게 처리하겠죠?

두개의 차이는 밑의 글을 참고해서 한번 어떤걸 넣어야할지 한번 봐보세요!
https://beomy.github.io/tech/browser/async-defer/#%EB%AC%B4%EC%97%87%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%A0-%EA%B2%83%EC%9D%B8%EA%B0%80

이분 글 홍보는 아닙니다 ㅎㅎ;

2023-12-19 15:53 UTC, goldfrosch commented on src/reset.css
> +/* user agent stylesheet 초기화 */
이거는 이제 왜 사용하는지 찾으셨나요 ㅎㅎ

2023-12-19 16:09 UTC, goldfrosch commented on signin.js
> +    var correctPassword = 'codeit101';
[중요도: 중간] 우선 변하지 않는 2개는 const로 바꾸고 상수니까 UPPER_SNAKE_CASE로 변경해주시면 좋을 것 같아요.
그리고 이런 테스트 코드의 경우는 최상단 addEventListener보다도 더 위에 (import 바로 밑줄 정도여도 되겠네요) 거기로 옮기신다면 테스트에 더 용이할 수 있습니다~

2023-12-20 16:52 UTC, DanteSnow commented on sign_moduel.js
> +  } else if (!email.includes('@')) {
아, 너무 얕게 생각했습니다 ㅠㅠ! 더 제대로 공부한 후 코드 수정하겠습니다! 감사합니다!

2023-12-20 16:52 UTC, DanteSnow commented on sign_moduel.js
앗... 오타 수정하겠습니다!!

2023-12-20 16:54 UTC, DanteSnow commented on sign_moduel.js
> +  }
감사합니다! 아직 효율적인 코드 작성에 대해서 생각하기엔 역량이 부족한 것 같습니다. 더 공부하겠습니다!

2023-12-20 16:57 UTC, DanteSnow commented on sign_moduel.js
> +  var email = emailInput.value;
강의를 통해서 let, const를 사용하는 것이 더 좋다고 인지는 했습니다.
최근에 프로그래머스스쿨로 lv.0 자바스크립트 문제를 계속 풀고있는데 사람들의 풀이와 챗지피티에서 var를 항상 사용해서 자연스럽게 var를 사용하게 된 것 같습니다.
앞으로 let과 const만을 사용하겠습니다! 코드도 수정하겠습니다! 감사합니다!

2023-12-20 16:57 UTC, DanteSnow commented on signin.js
> +import { validateEmail, validatePassword, togglePasswordVisibility } from './sign_moduel.js';
감사합니다!!!

2023-12-20 16:58 UTC, DanteSnow commented on signup.html
> +<html lang="kr">
아....죄송합니다.... 수정하겠습니다

2023-12-20 16:59 UTC, DanteSnow commented on signin.js
> +  var eyeButtons = document.querySelectorAll('.eye-button');
querySelector를 사용하면, id나 class를 모두 가져올 수 있어서 제가 편하려고 선택했습니다.
명시적인 부분을 더 중요하게 생각하겠습니다. 감사합니다!

2023-12-20 17:15 UTC, DanteSnow commented on signin.js
> +  });
과제에서 focus out을 주라고 해서 생각없이 focusout을 사용했습니다, blur라는 이벤트가 있는줄은 몰랐습니다! 이벤트들에 대해서 더 공부하겠습니다!

2023-12-20 17:16 UTC, DanteSnow commented on signup.html
> +  <script type="module" src="signup.js"></script>
좋은 자료 감사합니다🥹🥹🥹 공부하겠습니다!!🥹🥹🥹🥹🥹

2023-12-20 17:19 UTC, DanteSnow commented on src/reset.css
> +/* user agent stylesheet 초기화 */
네! 브라우저들 마다 기본으로 제공하는 스타일이 달라서, 이를 초기화함으로써 웹페이지 요소들이 모든 브라우저에서 동일하게 보이기 위함입니다! 감사합니다👍🏻

2023-12-20 17:21 UTC, DanteSnow commented on signin.js
> +    var correctPassword = 'codeit101';
감사합니다!! 앞으로 변수 선언은 let과 const로 꼭 사용하겠습니다.
테스트 코드 최상단 배치 이유는 제가 직접 구글링해서 공부하겠습니다!!👍🏻

2023-12-20 17:27 UTC, DanteSnow commented
전체 피드백

var, let, const의 차이와 var를 사용하면 안되는 이유에 대해 더 고민해보는게 좋아보여요.
- 강의를 통해서 let, const를 사용하는 것이 더 좋다고 인지는 했습니다. 최근에 프로그래머스스쿨로 lv.0 자바스크립트 문제를 계속 풀고있는데 사람들의 풀이와 챗지피티에서 var를 항상 사용해서 자연스럽게 var를 사용하게 됐습니다. 앞으로 let과 const만을 사용하겠습니다! 코드도 수정하겠습니다! 감사합니다!

직접 onClick이나 onfocus등 직접 element에 주입하지 않고 addEventListener에 주입한 이유가 궁금합니다. 이 부분 사유 설명 부탁드립니다!
- 제가 제대로 이해한 태그 선택법이 addEventListener 밖에 없어서 사용했습니다.😭 아직 인터랙티브 자바스크립트 강의를 100% 이해를 하지 못해서 더 효율적이고 좋은 방법이 있다는 것을 인지하지 못하고 있습니다. 복습 확실히 하겠습니다. 감사합니다!

2023-12-23 01:52 UTC, goldfrosch approved these changes

2023-12-23 01:52 UTC, merged