[최유정] Week4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #108
Opened 2023-12-17 06:45 UTC by yoojungChoii

## 요구사항

### 기본
[기본]이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지가 보이나요?

[기본]이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 input에 빨강색 테두리와 아래에 “올바른 이메일 주소가 아닙니다.” 빨강색 에러 메세지가 보이나요?

[기본]이메일 input에서 focus out 일 때, input 값이 test@codeit.com 일 경우 input에 빨강색 테두리와 아래에 “이미 사용 중인 이메일입니다.” 빨강색 에러 메세지가 보이나요?

[기본]비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, input에 빨강색 테두리와 아래에 “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 빨강색 에러 메세지가 보이나요?

[기본]비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input에 빨강색 테두리와 아래에 “비밀번호가 일치하지 않아요.” 빨강색 에러 메세지가 보이나요?

[기본]회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 빨강색 테두리와 에러 메세지가 보이나요?

[기본]이외의 유효한 회원가입 시도의 경우, “/folder”로 이동하나요?

[기본]이메일: test@codeit.com, 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동하나요?

[기본]비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?

[기본]이외의 로그인 시도의 경우 이메일, 비밀번호 input에 빨강색 테두리와 각각의 input아래에 “이메일을 확인해주세요.”, “비밀번호를 확인해주세요.” 빨강색 에러 메세지가 보이나요?

[기본]회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 되나요?

[기본]이메일, 비밀번호 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?

### 심화

- [x]
[심화]눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?

[심화]비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?

[심화]로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용했나요?
- []

## 주요 변경사항

-
-

## 스크린샷

![스크린샷 2023-12-17 154526](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151714134/b690fbca-0ac5-4b85-ac4f-27c76c37ef40)

## 멘토에게

- signup 페이지에선 눈 이미지 클릭시 토글 적용이 되지 않습니다. 수정을 다 해보았는데 왜 안되는지 이유를 잘 모르겠습니다..
- https://subtle-daffodil-95443f.netlify.app/
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-19 16:28 UTC, goldfrosch requested changes
고생많으셨습니다 :) js 를 잘 쓰신 것 같고 const를 활용 잘하셨네요! early return과 일부 동작 안하는 이슈가 보여 이부분 확인 부탁드립니다 :)

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +const eyeImageConfirm = document.querySelector('#eyeImageConfirm');
[중요도: 중간] 밖으로 빼서 선언한 것 매우 좋습니다!
[중요도: 높음] document.querySelectorAll('.email')[0]; 같은 형식이 보입니다. className으로 객체를 찾으시게되고 거기서 첫번째 객체를 바라보게 되어있는데 이런 경우 email이라는 className을 가진 element가 늘어나고 순서가 변경되었을 때 크리티컬한 이슈가 발생할 수 있어요.

특정 하나의 element를 가져올 때는 id(하나의 element에만 할당이 가능한)값을 넣고
<div id="test"></div>
 document.getElementById('test');
 
 이런식으로 가져오는게 좋습니다!
 
 id와 class의 차이를 이해해보고 querySelector보다 getElementById or getElementByClassName 에 대해 더 알아보면 좋을 것 같네요!

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +const pattern = /^[A-Za-z0-9_]+[A-Za-z0-9]*[@]{1}[A-Za-z0-9]+[A-Za-z0-9]*[.]{1}[A-Za-z]{1,3}$/;
정규식 잘썻네요 좋습니다!

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +let link = '/folder';
[중요도: 중간] 변하지 않는 값이라면 let보다 const가 낫고 보통 상수의 개념은 전체 대문자를 사용하는 UPPER_SNAKE_CASE를 사용합니다 (꼭 이래야한다는 아니지만 국룰 컨벤션이에요!)
+ 변수명이 너무 포괄적이여서 변수명 변경을 추천드립니다.
```
  const LINK = '/folder';
```

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  }
[중요도: 높음]
if문의 조건 passInput의 value가 ''인지랑 else if 에서 passInput의 value가 ''이 아닌지 인 다음에는 의미 없는 조건으로 보입니다. 이미 if와 else if에서 모든 경우 수를 다 가져다가 썻기 때문에 의미없는 조건이라 else는 제거해주세요. 혹은 어떤 예외케이스가 있었다면 적어주세요!

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  }
```suggestion
  if (emailInput.value === '') {
    errorMail.textContent = '이메일을 입력해주세요.';
    emailInput.classList.add('error'); // 에러 클래스 추가
    return;
  } 
  
  if (!pattern.test(emailType)) {
    errorMail.textContent = '올바른 이메일 주소가 아닙니다.';
    emailInput.classList.add('error'); // 에러 클래스 추가
    return;
  } 
  
  if (emailInput.value !== '') {
    errorMail.textContent = '이메일을 확인해주세요.';
    emailInput.classList.add('error'); // 에러 클래스 추가
    return;
  } 
  
  if (emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101') {
    location.href = link;
    return;
  }
  
  errorMail.textContent = '';
  emailInput.classList.remove('error'); // 에러 클래스 제거
```

early return을 쓰면 조금 더 깔끔하게 사용이 가능합니다. 이렇게 사용하는 이유는 사실 동작 자체는 비슷합니다. (사실 똑같습니다) 다만 이렇게 사용했을 경우 장점이라고 하면 if문의 위치를 다른 곳으로 뺼 수 있습니다. if else if else 형태로 사용된다면 하나의 if문에 같이 종속되어야하는 경우가 생기지만 if문에 early return을 사용하게 된다면 각각의 if문이 떨어져있는 상태라서 사용하기도 조금 편합니다 :) (아직은 이해를 못하실 수는 있습니다...!)

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +// const errorMessage = document.getElementsByClassName('error-message')[0];
[중요도: 높음] 불필요한 주석은 지워주세요

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  } else if (emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101') {
[중요도: 높음] test@codeit.com, codeit101 이 2개는 테스트를 위한 상수값입니다. 이렇게 조건문에 직접 박아버리면 나중에 이 값을 변경하려할 때 찾기 조금 번거로울 수 있고 다른 사람들이 봤을 때 바로 이해못할 수도 있습니다.

최상단에 document.querySelectorAll 쓰셨던 위치까지 옮기셔서 선언 후 사용하시면 더 편하게 사용 가능합니다.
```suggestion
  (2~3번째 쯤 줄)
  const TEST_CORRECT_EMAIL = 'test@codeit.com';
  const TEST_CORRENT_PASSWORD = 'codeit101'


  } else if (emailInput.value === TEST_CORRECT_EMAIL  && passInput.value === TEST_CORRENT_PASSWORD ) {
```

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  eyeImagePass.src = (currentType === 'password') ? 'img/eye-cross.png' : 'img/eye.png';
깔끔한 삼항연산자 좋습니다 :) (currentType === 'password')의 괄호는 불필요해 보이긴 하는데 상관없습니다. 나중에 코드 컨벤션 정해서 하다보면 자동으로 없어지든 생기든 하는 거니까요

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +passConfirmInput.addEventListener('focusout', checkPassConfirm);
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/103#discussion_r1431481346

치현님께 드린 피드백 같이 드립니다. focusout보다 blur가 이벤트 버블링이라는 것이 일어나지 않아 불필요한 이벤트 일어날 가능성이 사라집니다~

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  } else if (emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101') {
```suggestion
  } else if (emailInput.value !== '') {
    errorMail.textContent = '이메일을 확인해주세요.';
    emailInput.classList.add('error'); // 에러 클래스 추가
  } else if (emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101') {
```

여기 로직이 정상적으로 돌아가나요?
지금 보기에는 emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101' 조건에 들어오기 전에 emailInput.value !== ''여기서 걸릴 것 같아 보이네요...? 순서 변경이 필요해보입니다.

2023-12-19 16:28 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  } else if (!pattern.test(emailType)) {
이거 사이트에서는 동작을 제대로 안하는 것 같은데 확인 한번 가능할까요?
https://www.regextester.com/
정규식 테스트 사이트를 통해 테스트해볼때는 맞는데... 이상하게 배포 사이트에서는 동작을 제대로 안하는 것 같네요~

2023-12-21 14:29 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +const eyeImageConfirm = document.querySelector('#eyeImageConfirm');
감사합니다! 차이를 제대로 알아보고나서 알맞게 수정하겠습니다.

2023-12-21 14:38 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +const eyeImageConfirm = document.querySelector('#eyeImageConfirm');
특정 하나의 element를 가져올 때는 id값을 넣는게 더 좋다면, 기존의 클래스로 지정한 HTML태그를 id로 변경해야할까요? 이전에 CSS 때는 id사용보단 class 사용을 우선 하라고 하셔서 궁금합니다.

2023-12-21 14:42 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +let link = '/folder';
감사합니다! 변경하겠습니다!
궁금했던 것이 있는데, const 사용시 여러 예시코드를 보면 UPPER_SNAKE_CASE로 거의 작성이 되어있지 않더라고요. 코드잇 강의에서도 그랬고요. 혹시 사용하는 케이스와 아닌 케이스가 나뉘기도 하나요?

2023-12-21 14:53 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  }
헉 그렇네요.. 에러 클래스 제거를 하면 빨간 에러 라인이 없어질 줄 알았는데 쓸모 없는 동작이었던 것 같습니다. 삭제하겠습니다.

2023-12-21 14:59 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  }
와 이렇게 쓸 수 있군요....! 저는 하나의 비슷한 동작들을 꼭 if문으로 한번에 묶어야 한다고 생각했습니다. 그래야 코드가 짧아지기도 하고요.. 그런데 멘토님이 알려주신대로 보니 훨씬 눈에도 잘 들어오고 종속적이지 않아 수정하기도 편할 것 같습니다. 감사합니다!

2023-12-21 15:03 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  }
수정해주신 코드 중 38번줄에 있는 코드는 else문을 아예 밖으로 빼버리신 것 같은데 맞나요? 잘 이해되지 않아 여쭈어봅니다.

2023-12-21 15:03 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +// const errorMessage = document.getElementsByClassName('error-message')[0];
넵!

2023-12-21 15:20 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  } else if (emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101') {
이해했습니다! 감사합니다.

2023-12-21 15:21 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  eyeImagePass.src = (currentType === 'password') ? 'img/eye-cross.png' : 'img/eye.png';
참고하겠습니다! 감사합니다!

2023-12-21 15:23 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +passConfirmInput.addEventListener('focusout', checkPassConfirm);
감사합니다! 저도 focusout이벤트를 사용하라고 해서 별 생각 없이 사용했는데 조언 감사합니다!

2023-12-21 15:47 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  } else if (emailInput.value === 'test@codeit.com' && passInput.value === 'codeit101') {
여기가 좀 이상하다고 생각했는데 계속 봐도 왜 걸리는지 이해가 되지 않습니다.. 두 코드 모두 따로 동작하는 것 아닌가요? 각각 if문으로 따로 떼서 얼리 리턴을 적용하면 상관없어지나요?

2023-12-21 16:01 UTC, yoojungChoii commented on JavaScript/sign-script.js
> +  } else if (!pattern.test(emailType)) {
왜 동작이 정상적으로 안되는지 계속 해봐도 잘 모르겠습니다ㅠ 방법을 찾아보겠습니다.

2023-12-25 11:32 UTC, goldfrosch commented on JavaScript/sign-script.js
> +  }
네 맞습니다 early return을 하게되면 else가 없어도 나머지는 맨 밑에 적어두면 else처럼 실행됩니다.

2023-12-25 11:34 UTC, goldfrosch commented on JavaScript/sign-script.js
> +let link = '/folder';
아에 변하지 않는 상수 (특정 함수를 통해 가져오지 않는 상수 값)은 UPPER_SNAKE_CASE로 작성합니다.
이렇게 해야 한다 안하면 에러가 발생한다는 아닙니다. 다만 국룰 컨벤션이라고 생각하시면 됩니다.

ex.
MINUTE = 60;
HOUR = 60 * 60;

const eyeImageConfirm = document.querySelector('#eyeImageConfirm'); (함수를 통해 가져옴)

2023-12-25 11:35 UTC, goldfrosch commented on JavaScript/sign-script.js
> +const eyeImageConfirm = document.querySelector('#eyeImageConfirm');
이 부분은 토요일 멘토링 때 설명드렸습니다~ (참고 부탁드립니다~)

2023-12-25 11:35 UTC, goldfrosch commented
전체적인 피드백 토요일날 완료. Merge 처리

2023-12-25 11:35 UTC, merged