[권지민] Week5
codeit-bootcamp-frontend/3-Weekly-Mission pull request #132
Opened 2023-12-22 17:24 UTC by mingzzi96

## 실행법
1. 로컬로 clone합니다.
2. npm install을 터미널에 입력해 package.json을 설치합니다.
3. index.html 등 원하는 파일을 클릭해 확인합니다.
## Netlify 주소
[Netlify 메인](https://dashing-gumdrop-02d554.netlify.app/)
[Netlify 로그인](https://dashing-gumdrop-02d554.netlify.app/signin)
[Netlify 회원가입](https://dashing-gumdrop-02d554.netlify.app/signup)

## 요구사항

### 기본
- [x]  [기본] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받고 “/folder”로 이동하나요?
- [x]  [기본] 이메일 input에서 “test@codeit.com”으로 “/api/check-email” 이메일 중복 확인 POST 요청하면 이메일 중복 에러를 확인할 수 있나요?
- [x]  [기본] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요?
### 심화

- [x]  [심화] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장했나요?
- [x]  [심화] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 “/folder” 페이지로 이동하나요?

## 주요 변경사항

- 로그인 회원가입 api 비동기 처리
- axios/async/await 활용

## 멘토에게

- axios npm 설치하여 사용하고 싶었는데, 불러와지지 않아서,, html cdn으로 넣어주었습니다... 🥲

2023-12-25 07:43 UTC, wonsss requested changes
수고하셨습니다 지민님 👍 
몇 가지 리뷰 남겼어요. 반영 후 재리뷰 원하시면 연락주세요! 😄

2023-12-25 07:43 UTC, wonsss commented on signin.html
> +        <script src="/script/sign/signIn.js" type="module"></script>
## 질문에 대한 답변
> axios npm 설치하여 사용하고 싶어서 설치를 완료 했습니다. 그런데 불러와지지 않더라구요,,
그래서 결국 html cdn으로 넣어주었습니다... 🥲 구글링해보니까 불러와지지 않으면 대부분 cdn으로 해결했다는 글만 있더라구용,, 다른 해결법이 있을까요?

eslint처럼 IDE 개발 환경에서만 사용할 라이브러리가 아니라, 사용자가 접할 서비스의 코드 내에 포함되어야 하는 라이브러리를 설치하시면서 문제가 발생하셨군요.

좋은 시도입니다!
서비스에 포함되어야 할 axios 같은 외부 라이브러리를 받는 방법은 크게 1.CDN과 2.패키지관리자(npm, yarn 등) 두 가지가 있습니다.

CDN을 사용하여 HTML 내 script 태그에 해당 CDN 경로를 지정해두면, 사용자가 페이지 접속 시 브라우저가 HTML 렌더링을 하다가 script 태그를 만나면 해당 url을 통해 라이브러리 코드를 다운받아서 사용할 수 있게 됩니다.
간단한 토이 프로젝트의 경우에는 이처럼 CDN을 사용하셔도 됩니다.

그러나 외부 CDN 서버에 의존성이 커지는 문제와 사용하는 라이브러리의 버전 관리 문제 등이 발생할 수 있으므로, 패키지 매니저를 통해 라이브러리 관리하는 방식이 실무에서 사용됩니다.

패키지 매니저를 통해 라이브러리를 import하시려면 모듈 번들러인 webpack을 사용하여 해결하실 수 있습니다.

해결 방법은 https://onlydev.tistory.com/167 글에서 자세히 설명해주고 있는 것 같네요.  😄

2023-12-25 07:43 UTC, wonsss commented on script/sign/signCommon.js
> +    const EMAIL_REGEX =
상수화 컨벤션 수정 좋네요 👍 

그리고 자주 사용될 것 같다면, 별도의 constants.js 같은 파일에 분리하여 import 해서 사용하셔도 될 것 같아요.

2023-12-25 07:43 UTC, wonsss commented on script/sign/signin.js
> +const handleSubmit = async (e) => {
70번째 라인에 checkEmailExist 함수가 호출되는데, 로그인 form submit handler에서 해당 함수 호출이 필요한가요?
checkEmailExist 함수 내에서 이메일 중복 확인 API 를 호출하고 있던데, 로그인 시에 이메일 중복 확인을 할 필요는 없을 것 같아서요. 😄

2023-12-25 07:43 UTC, wonsss commented on script/sign/signin.js
>      }
axios를 통해 네트워크 에러 핸들링을 쉽게 잘 하셨네요!

추가적으로 만약 400 응답이 아닌 이외의 에러 케이스에는 사용자에게 어떻게 알려줄지에 대해서도 고민해보면 좋을 것 같아요.

2023-12-25 07:43 UTC, wonsss commented on script/sign/signup.js
>      ) {
조건문을 잘 작성해주셨네요 👍

2023-12-25 07:43 UTC, wonsss commented on script/sign/signup.js
>          emailInputElement.focus();
이메일 인풋에 문제가 있는 경우 focus 해주는 것도 디테일한 사용성이 좋네요 👍

2023-12-25 07:43 UTC, wonsss commented on script/sign/signup.js
> +        );
이러한 API 로직을 별도의 파일에 분리하고 함수 이름을 각각 붙여서 사용하는 것도 좋을 것 같아요.

2023-12-25 07:43 UTC, wonsss commented on script/sign/signup.js
> +            );
요구사항이 localStorage 로 accessToken을 관리하는 거였죠.
그런데 나중에 관리 방식이 localStorage가 아니라 다른 것이 될 수도 있을 것 같아요. 
사실 클라이언트에 토큰 관리 방식으로 로컬스토리지는 보안상 이슈가 있어서, Cookie 를 사용하곤 해요. 
이 부분은 지금 수정할 필요는 없으나 참고만 하시면 좋겠습니다.
[LocalStorage vs. Cookies: JWT 토큰을 안전하게 저장하기 위해 알아야할 모든것](https://hshine1226.medium.com/localstorage-vs-cookies-jwt-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%B4-%EC%95%8C%EC%95%84%EC%95%BC%ED%95%A0-%EB%AA%A8%EB%93%A0%EA%B2%83-4fb7fb41327c)

그러나 미리 해두시면 좋은 리팩터링은 현재 accesToken을 쓰고 읽는 `localStorage.setItem` `localStorage.getItem` 로직을 함수로 만들어 모듈화하고 이를 import하여 사용하는 것입니다. 이렇게 하면 나중에 로컬스토리지가 아닌 쿠키 등 다른 방식으로 변경할 때, 사용처를 일일이 가서 수정하는 게 아니라 해당 함수 내 로직만 수정하면 되어서 유지보수에 간편할 것 같아요.

2023-12-25 07:43 UTC, wonsss commented on script/sign/signup.js
> +            window.location.href = "/folder.html";
참고로 location.assign("/folder.html") 도 동일한 효과입니다.

참고 링크: https://developer.mozilla.org/en-US/docs/Web/API/Window/location

2023-12-25 07:49 UTC, wonsss commented on script/sign/signCommon.js
> +        if (errorResult.status === 409) return true;
if (condition) doSomething()과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다. 
만약 if문 중괄호가 없는데 아래와 같이 실수로 줄바꿈이 되었다면 에러가 발생합니다.
```js
if (errorResult.status === 409)
return true; 
```
이처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋기 때문에 한줄이라도 중괄호를 쓰는 코딩 스타일을 일관성있게 유지하시길 바랍니다. 😄 

추가적인 코딩스타일은 아래 문서 참고 바랍니다.
[코딩스타일](https://ko.javascript.info/coding-style)

2023-12-25 14:22 UTC, mingzzi96 commented on script/sign/signCommon.js
> +    const EMAIL_REGEX =
8066c8af5f9e8e16e9c0eb012e9beed6716cda0b 아하 자주 사용될 것 같은 상수는 아예 constansts 와 같은 파일로 빼놓는 것이 좋은 것이군요! 수정하였습니다.

2023-12-25 14:32 UTC, mingzzi96 commented on script/sign/signup.js
>      ) {
헿ㅎㅎㅎ 앞으로도 이렇게 해보겠습니당 (ง •̀_•́)ง

2023-12-25 14:36 UTC, mingzzi96 commented on script/sign/signup.js
>          emailInputElement.focus();
<img width="200" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/c5e2a497-7064-4cd8-8661-906f40270e10">
앞으로는 더 잘해보겠습니당 헿ㅎㅎㅎ

2023-12-25 15:10 UTC, mingzzi96 commented on script/sign/signup.js
> +            window.location.href = "/folder.html";
헉 assign은 처음 들어보는데 감사합니당 ㅎㅎ

2023-12-25 15:40 UTC, mingzzi96 commented on script/sign/signCommon.js
> +        if (errorResult.status === 409) return true;
371b997e13591987f77e20cdac3be6e618aaa88b 헉 줄바꿈에 대해서는 생각해보지 못했는데 확실히 오류가 날 확률이 존재하긴 하겠군요! 수정했고 참고 문서도 읽어보았습ㄴ다.

>코드가 간단하다면 세 번째 예시같이 한 줄에 몰아서 작성해도 괜찮습니다. 그렇지만 네 번째 예시처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋으므로 이 방법을 추천합니다.

기억해 두도록 하겠습니다!

2023-12-25 16:36 UTC, mingzzi96 commented on script/sign/signCommon.js
@wonsss  `checkEmailExist` 함수 이름을 `hasEmail`로 수정해 보았는데, 좀 더 직관적으로 바뀌는 선택이 맞았을까요..?

2023-12-25 17:22 UTC, mingzzi96 commented on script/sign/signin.js
> +const handleSubmit = async (e) => {
a9633774d1c75810c6cdad5b9ba9da03da88bfa7 다시 한번 확실하게 확인해 주고 싶었던건데, 확실히 없는게 더 맞는 것 같네요! 삭제해 주었습니다.
삭제하고 보니 더 가벼워진 것 같아용!!

2023-12-26 14:19 UTC, wonsss commented on script/sign/signCommon.js
1. `checkEmailExist` 함수 이름은 `hasEmail`보다 기존처럼 checkEmailExist 이 더 나은 것 같습니다. 
왜냐하면, `has`, `should`, `can`, `is` 같은 접두사는 boolean 타입의 변수의 이름에 주로 사용하기 때문이에요.
함수 이름으로 시작하는 동사는 동적인 행동을 의미하는 동사를 쓰는 것이 좋습니다. 그래서 check로 시작하는 것이 괜찮은 것 같아요.

2. check라는 동사로 시작하는 함수 이름은 check로 그대로 하거나 맥락에 따라서 validate로 변경해도 괜찮은 것 같습니다. 그런데 is는 위에서 설명한 것처럼 boolena 타입의 변수 이름에 쓰는 게 적합하므로 함수 이름에는 사용 안하는 게 좋을 것 같아요. 😄

2023-12-26 14:22 UTC, wonsss approved these changes
리뷰 잘 반영해주셨네요. 수고 많으셨습니다! 👍 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/1b94063d-c59f-46fa-bc38-709aaaecae7d)

2023-12-26 14:22 UTC, merged