[김성훈] Week5
codeit-bootcamp-frontend/3-Weekly-Mission pull request #134
Opened 2023-12-23 05:21 UTC by huniiiiii

## 요구사항

### 기본

- [x]  [기본] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받고 “/folder”로 이동하나요?
- [x]  [기본] 이메일 input에서 “test@codeit.com”으로 “/api/check-email” 이메일 중복 확인 POST 요청하면 이메일 중복 에러를 확인할 수 있나요?
- [x]  [기본] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요?

### 심화

- [ ]  [심화] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장했나요?
- [ ]  [심화] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 “/folder” 페이지로 이동하나요?

## 주요 변경사항

- 로그인/회원가입 페이지 비동기화

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/2bfa9c94-1b35-4e88-8e5f-88f022697d61)

signin post 확인

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/2c132abe-e861-4f27-975c-d499f3246044)

signup post 확인

## 멘토에게

-더 추가해야될 부분들은 커밋하도록 하겠습니다 😀

2023-12-25 06:16 UTC, wonsss requested changes
안녕하세요 성훈님. 수고 많으셨습니다.
API 통신과 비동기, 에러 핸들링 등에 대해 많이 익히시게 된 것 같네요. 👍 
시간이 되시면 심화 요구사항 및 리팩터링 등을 해보시면 좋을 것 같습니다. 😄 
반영 후 추가 리뷰를 받고 싶으시면  다시 연락주세요.

2023-12-25 06:16 UTC, wonsss commented on signin/index.js
> +      signinForm.submit();
여기서 의도하신 동작은 siginIn API 응답이 성공하면 folder.html 로 페이지 이동시키려는 것 같네요.
그리고 페이지 이동을 하기 위해서 form submit의 GET method를 사용하셨어요.

우선 이미 form submit 시 API에 전달하는 post 방식을 사용하셨는데, submit 이벤트 핸들러 내에서 한번 더 submit 이벤트를 발생시킬 필요가 없습니다.
페이지 이동을 시키고 싶다면, 아래와 같이 페이지 이동시키는 location의 메서드를 사용하시는 것이 적절할 것 같습니다.
[참고: MDN - Window.location](https://developer.mozilla.org/en-US/docs/Web/API/Window/location)
```js
 location.assign('../etc/folder.html');
```

그리고  아래와 같이 작성하신 코드는 현재 form 태그에 method를 지정해주지 않아서 기본값인 get이 메서드에 지정된 상태입니다.
```js
      signinForm.action = '../etc/folder.html';
      signinForm.submit();
```
GET 방식은 URL에 폼 데이터를 추가하여 서버로 전달하는 방식입니다. GET 방식은 form 필드 값들이 url의 쿼리스트링에 포함되어 전송되므로, 보안상 취약점이 존재합니다.

성훈님 사이트에서 로그인을 하면, 아래 스크린샷과 같은 url의 페이지로 이동하게 됩니다. url을 살펴보시면 쿼리스트링에 이메일과 비밀번호가 그대로 노출되고 있는데, 이렇게 되면 보안상 큰 문제가 생기겠죠? 😢 

<img width="869" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/caa10638-c9fe-43ab-b5aa-171725f9717a">

이 때문에 중요한 데이터는 POST 방식을 사용하여 요청하는 것이 좋습니다.

2023-12-25 06:16 UTC, wonsss commented on signin/index.js
> +      handlePasswordError('비밀번호를 확인해주세요.');
해당 함수의 이름에는 handle 이라는 접두사가 적절하진 않을 것 같아요.
handle은 어떤 이벤트를 핸들링하는 이벤트 핸들러 함수일 때 붙여주면 컨벤션에 더 적절할 것 같아요.
그런데 이 함수들은 이벤트 핸들러 역할은 아니고, 화면을 조작하는 역할을 하는 것 같네요.
showEmailError, showPassowrdError 같은 함수명이면 이름만으로 그 의도가 더 적절히 파악될 수 있을 것 같습니다.

2023-12-25 06:16 UTC, wonsss commented on signup/index.js
> +  sendSignUpRequest();
참고로 form data는 직접 DOM 요소 선택하여 그 값을 가져오는 방법 외에도,
form의 이벤트 핸들러 내에서 this를 FormData 생성자에 전달하여 formData 객체를 가져오는 방법도 있습니다.
그냥 참고로만 알아두시면 될 것 같아요. 😄 
[참고링크: FormData 객체](https://ko.javascript.info/formdata)
```js
  const formData = new FormData(this);
  const email = formData.get('email');
  const password = formData.get('password');
  const passwordCheck = formData.get('password-check');
```

2023-12-25 06:16 UTC, wonsss commented on javascript/api.js
> +    const response = await fetch(
async await를 잘 사용하셨네요! 👍

2023-12-25 06:16 UTC, wonsss commented on javascript/api.js
> +  }
try-catch 문 내에서 fetch API 호출 중에 발생하는 HTTP 400 또는 500 응답과 같은 네트워크 에러를 핸들링하려는 의도로 catch 블럭에서 Error를 던지신 것 같네요.
response.ok는 HTTP 상태 코드가 200에서 299 사이인지 확인합니다. try 블럭 내에서 response.ok 가 아닌 경우에 Error를 던져서 바로 해당 에러를 catch블럭에서 잡아서 console.error를 하도록 하는 게 성훈님 의도에 더 맞을 것 같습니다. 


```suggestion
    if (!response.ok) {
      throw new Error('이메일 중복 확인 요청 실패');
    }

    return response;
  } catch (error) {
    console.error('Error:', error);
  }
```

2023-12-25 06:16 UTC, wonsss commented on javascript/api.js
> +  }
그런데 에러를 던져서 어떻게 활용할지 의도가 없는 것 같은데, try catch 문을 제거하고 로직을 일단 심플하게 만드는 게 더 나을 것 같습니다.

```js
export function checkDuplicateEmail(emailValue) {
  return fetch('https://bootcamp-api.codeit.kr/api/check-email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      email: emailValue,
    }),
  });
}
```

2023-12-25 06:16 UTC, wonsss commented on signup/index.js
>  }
이 함수 내에도 if 문이 중첩되고 try catch 문도 중첩되며, catch 블럭 내에서 Error를 다시 던지는 등 로직이 심플하게 보이지 않는 것 같습니다.

아래와 같이 조금 더 심플하게 리팩터링해보시는 것은 어떠실까요?

```js
async function sendSignUpRequest() {
  const emailValue = emailInput.value;
  const passwordValue = passwordInput.value;
  const passwordcheckValue = passwordcheckInput.value;

  const checkEmailResponse = await checkDuplicateEmail(emailValue);

  if (!checkEmailResponse.ok) {
    handleEmailError('이미 존재하는 이메일입니다.');
    return;
  }

  if (
    !validateEmail(emailValue) ||
    !validatePassword(passwordValue) ||
    !validatePasswordcheck(passwordValue, passwordcheckValue)
  ) {
    return;
  }

  const signUpResponse = await signUp(emailValue, passwordValue);

  if (!signUpResponse.ok) {
    handleEmailError('이메일을 확인해주세요.');
    handlePasswordError('비밀번호를 확인해주세요.');
    handlePasswordcheckError('비밀번호를 확인해주세요.');
    return;
  }

  window.location.href = '../etc/folder.html';
}
```

2023-12-25 06:16 UTC, wonsss commented on javascript/api.js
> +export async function signUp(emailValue, passwordValue) {
다른 코멘트 참고하셔서 이 부분도 로직을 간단하게 리팩터링해보면 좋을 것 같습니다.

2023-12-25 06:16 UTC, wonsss commented on javascript/api.js
> +export async function signIn(emailValue, passwordValue) {
다른 코멘트 참고하셔서 이 부분도 로직을 간단하게 리팩터링해보면 좋을 것 같습니다.

2023-12-25 06:16 UTC, wonsss commented on signin/index.js
> +  event.preventDefault();
event.preventDefault();를 적절하게 잘 사용해주신 것 같아요. 
혹시 여기서 `event.preventDefault();` 는 어떤 역할을 하는지 설명해주실 수 있으실까요? 😄

2023-12-25 06:16 UTC, wonsss commented on signup/index.js
>    handlePasswordcheckError('');
이 함수들 모두 이름의 접미사로 handle이 아닌 show가 적절할 것 같아요.

handleEmailInputFocusout 는 EmailInput 요소의 Focusout 이벤트 발생 시 핸들링하는 함수이므로 적절한 이름입니닷 👍

2023-12-25 09:08 UTC, huniiiiii commented on signin/index.js
> +      signinForm.submit();
c83bf6173fc3dc17b8a16af4a6702131070177ae

4주차에 했던 action부분과 submit부분을 활용해보려고 했는데 저런 취약점이 있었군요.. 
post방식을 사용하도록 수정해보았습니다!

2023-12-25 09:09 UTC, huniiiiii commented on signin/index.js
> +      handlePasswordError('비밀번호를 확인해주세요.');
c83bf6173fc3dc17b8a16af4a6702131070177ae

적절한 함수명을 사용해보록 노력하겠습니다! 수정하였습니다😅

2023-12-25 09:12 UTC, huniiiiii commented on signin/index.js
> +  event.preventDefault();
HTML폼을 제출할때 페이지가 로드되거나 새로운 페이지로 이동하는데 이러한 동작을 방지하기 위해 사용하는것으로 알고있습니다😀

2023-12-25 09:13 UTC, huniiiiii commented on signup/index.js
>    handlePasswordcheckError('');
c83bf6173fc3dc17b8a16af4a6702131070177ae

수정하였습니다 !

2023-12-25 09:17 UTC, huniiiiii commented on signup/index.js
> +  sendSignUpRequest();
this의 사용법이 익숙치 않아서 this를 활용할수있는 방법이 많은데 제대로 써먹지 못하는거같네요.. 알려주신것은 많은데 좀 더 알아보고 다방면으로 활용하여 적용해보도록 노력해보겠습니다😥

2023-12-25 09:18 UTC, huniiiiii commented on javascript/api.js
> +    const response = await fetch(
감사합니다! 배운것을 써먹어보려고 노력해보았습니다😀

2023-12-25 09:40 UTC, huniiiiii commented on javascript/api.js
> +  }
210358a7e97054bc25c72d73cf72c2c19169a4b1

말씀하신대로 에러를 던졌지만 활용할 방법은 따로 없어서 코드만 길어지게 되었네요. 필요한때만 에러를 활용하도록 해보겠습니다😅 말씀하신부분을 이용하여 좀 더 간단하게 수정하였습니다 !

2023-12-25 09:41 UTC, huniiiiii commented on javascript/api.js
> +export async function signUp(emailValue, passwordValue) {
210358a7e97054bc25c72d73cf72c2c19169a4b1

확인 후 수정하였습니다 !

2023-12-25 09:41 UTC, huniiiiii commented on javascript/api.js
> +export async function signIn(emailValue, passwordValue) {
210358a7e97054bc25c72d73cf72c2c19169a4b1

확인 후 수정하였습니다 !

2023-12-25 10:29 UTC, huniiiiii commented on signup/index.js
>  }
14b193f4093c66fdaf21fddc024a3c552bf1bf1b

다시보니 함수가 너무 중첩된게 많아서 코드가 지저분해보였네요 😅 알려주신대로 불필요한 부분 제거하고 다시 수정하였습니다 !

2023-12-26 15:03 UTC, huniiiiii commented
말씀하신부분 수정하고 어쭤보았던 import부분도 그룹화시켜보았습니다 ! 
원석님이 pr로 많이 알려주신덕에 많이 알아가는것 같습니다. 감사했습니다!

2023-12-26 15:37 UTC, wonsss approved these changes
성훈님~! 리뷰 꼼꼼하게 잘 반영해주셨네요. 수고 많으셨어요. 감사합니다.👍 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/ed8f3df1-39b8-4a7d-86f8-e09b4a5785ce)

2023-12-26 15:37 UTC, merged