[조성경] WEEK5
codeit-bootcamp-frontend/3-Weekly-Mission pull request #137
Opened 2023-12-23 09:36 UTC by whtjdrud

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-25 08:37 UTC, wonsss requested changes
성경님. 수고하셨어요 👍 
여러 멋진 시도를 해주셨네요. 
리뷰 확인해주시고 반영 후 다시 리뷰 받길 원하시면 말씀해주세요 😄

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/config/errorMessage.js
> +const getErrorMessage = errCode => errorMessages[errCode];
더 좋은 이름인 것 같네요. 👍

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/config/errorMessage.js
> +const getErrorMessage = errCode => errorMessages[errCode];
만약에 해당 객체에 없는 프로퍼티에 접근하려고 하면 undefined가 반환될 거에요.
이러한 사용자의 실수를 예방하기 위해 Default Case를 고려하는 의식적인 노력이 필요합니다.
switch 문이었다면, default 를 지정해줘야 하는 것처럼, 
비슷한 역할을 하는 이 객체에서는 null 병합 연산자(`??`)를 사용해서 Default Case를 써주는 것도 필요해보입니다.

```js
const getErrorMessage = errCode => errorMessages[errCode] ?? '알 수 없는 에러가 발생하였습니다';
```

그리고 참고로 나중에 타입스크립트를 쓰면 이런 사용자 실수는 미리 예방될 수 있긴 합니다

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/service/signUpService.js
> +  handlerViewErrorMessage(resultValidated) {
해당 함수의 이름이 `handler`로 시작하는데, 어떤 의도로 네이밍해주셨는지 설명해주실 수 있으실까요?
함수 이름은 동사로 시작해야 합니다. 그런데 `handler`는 동사가 아니라서 오해의 소지가 있을 것 같습니다.
그리고 동사인 `handle`의 오타라고 하더라도 해당 함수가 이벤트 핸들러로서 역할을 하는 것은 아닌 것 같아서 더 적절한 이름으로 변경하면 좋을 것 같습니다. 😄

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/domain/user.js
> +export default class User {
User라는 클래스는 다른 클래스와 달리 어떤 역할을 담당하나요?

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/service/loginService.js
> +  async LoginUser(e, emailTag, passwordTag) {
해당 메서드 이름을 대문자로 시작하게 한 이유가 있으실까요?
함수나 메서드 이름은 소문자 카멜케이스가 컨벤션입니다.
대문자로 시작한다면 클래스 등으로 오해할 수 있습니다.

2023-12-25 08:37 UTC, wonsss commented on signin.html
> +    <script type="module" src="/assets/js/sign/login.js"></script>
MVC 패턴으로 리팩터링을 하셨네요. 👍 
페이지 각각에 MVC 패턴의 코드를 작성하셨는데, 현재 폴더 구조가 domain, controller, service, view 이런 식으로 기능 중심으로 나누어져 있는 것 같아요.
이렇게 하는 것도 좋지만, 페이지 각각 분리된 MVC 패턴 로직을 작성했다면, 페이지별로 폴더를 구성해서 응집시키는 것도 또 하나의 방법일 것 같아요.
예를 들어, login 폴더 signUp 폴더 각각 안에 index.js, controller.js, view.js, service.js 같은 파일들이 존재할 수 있겠네요. html 파일도 해당 폴더에 같이 있을 수도 있겠구요.

이렇게 하면, 예를 들어 로그인 페이지를 수정할 때 폴더 간에 이리 저리 왔다갔다할 필요가 적어지고 코드 안에 의존성을 살피지 않더라도 폴더로 응집된 것만 보더라도 쉽게 의도를 알 수 있을 것 같아요. 
성경님은 어떻게 생각하시나요 ? 😄

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/signup.js
> +  const controller = new SignUpController(signUpView, user, signUpService);
SignUpController 인스턴스 생성하고, 변수에 담을 필요까지는 없을 것 같네요. 😄 해당 변수를 사용하는 곳이 없어서요.

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/service/signUpService.js
> +  }
부정조건문보다는 긍정조건문이 읽기 더 쉽습니다.
가능하면 긍정조건문으로 쓰는 게 더 나을 것 같아요.

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/service/signUpService.js
> +  }
if (condition) doSomething()과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다. 
만약 if문 중괄호가 없는데 아래와 같이 실수로 줄바꿈이 되었다면 에러가 발생합니다.
```js
if (signUpResult.valid) 
window.location.href = '/folder.html';
```
이처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋기 때문에 한줄이라도 중괄호를 쓰는 코딩 스타일을 일관성있게 유지하시길 바랍니다. 😄 

추가적인 코딩스타일은 아래 문서 참고 바랍니다.
[코딩스타일](https://ko.javascript.info/coding-style)

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/login.js
> +  const accessToken = localStorage.getItem('accessToken');
요구사항이 localStorage 로 accessToken을 관리하는 거였죠.
그런데 나중에 관리 방식이 localStorage가 아니라 다른 것이 될 수도 있을 것 같아요. 
사실 클라이언트에 토큰 관리 방식으로 로컬스토리지는 보안상 이슈가 있어서, Cookie 를 사용하곤 해요. 
이 부분은 지금 수정할 필요는 없으나 참고만 하시면 좋겠습니다.
[LocalStorage vs. Cookies: JWT 토큰을 안전하게 저장하기 위해 알아야할 모든것](https://hshine1226.medium.com/localstorage-vs-cookies-jwt-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%B4-%EC%95%8C%EC%95%84%EC%95%BC%ED%95%A0-%EB%AA%A8%EB%93%A0%EA%B2%83-4fb7fb41327c)

그러나 미리 해두시면 좋은 리팩터링은 현재 accesToken을 쓰고 읽는 `localStorage.setItem` `localStorage.getItem` 로직을 함수로 만들어 모듈화하고 이를 import하여 사용하는 것입니다. 이렇게 하면 나중에 로컬스토리지가 아닌 쿠키 등 다른 방식으로 변경할 때, 사용처를 일일이 가서 수정하는 게 아니라 해당 함수 내 로직만 수정하면 되어서 유지보수에 간편할 것 같아요.

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/domain/user.js
> +  settingLocalStorage(responseData) {
메서드 이름이 setting 으로 시작하기 보다는 동사로 시작하도록 변경하는 게 좋을 것 같습니다. 😄

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/domain/user.js
> +    localStorage.setItem('refreshToken', responseData.data.refreshToken);
api에서 refreshToken도 응답해주고 있나요?

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/controller/signUpController.js
> +    this.view.emailInput.addEventListener('focusout', () => this.service.validateSignUpEmail(this.view.emailInput));
controller 역할은 view, user, service 들을 연결시켜서 이벤트리스너 등록을 하는 것으로 한정지으셨군요.

controller의 역할 중 일부를 service라는 것으로 분리하신걸까요?
분리함으로써 controller가 추가로 분리된 것들을 연결시켜주면서 코드 가독성이 조금 떨어지지 않을까 싶어요.

controller 클래스에 service 클래스 코드를 합친다면,
이러한 코드가
```js
this.view.emailInput.addEventListener('focusout', () => this.service.validateSignUpEmail(this.view.emailInput));
```

이렇게 될 수 있을 것 같아요. 
```js
this.view.emailInput.addEventListener('focusout', this.validateSignUpEmail.bind(this));
```
 
의도를 갖고 여러 시도를 해보시는 것 너무 멋집니다.  👍 
제 의견도 참고해보시면 좋을 것 같아요 😄

2023-12-25 08:37 UTC, wonsss commented on assets/js/sign/domain/user.js
> +  }
view에서 showErrorMessage 함수의 재사용성을 늘리기 위해 이런 식으로 tag 도 반환해주시는 거군요. 좋은 아이디어인 것 같아요.

다만, 제 생각에는 showErrorMessage 함수를 각각 요소에 제한적인 것으로 분리하여 showEmailErrorMessage, showPasswordErrorMessage 처럼 만들고 각각 함수의 인자로 에러메세지 문자열 하나만 받도록 해도 충분할 것 같고 복잡도가 줄 것 같다는 생각이 듭니다.

2023-12-25 11:45 UTC, whtjdrud commented on assets/js/sign/domain/user.js
> +    localStorage.setItem('refreshToken', responseData.data.refreshToken);
넵 과제 요청사항에는 accessToken 만 언급되고 있는데 실제 응답시에는 refreshToken도 있어서 일단 추가해줬습니다.

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/d05d2364-9014-484f-b318-06f4f35d15d7)

2023-12-25 12:01 UTC, whtjdrud commented on assets/js/sign/domain/user.js
> +export default class User {
원래 최초에는 user에 id, email, accesstoken, refreshtoken 변수를 만들어서 넣고 가지고 다니게 만들려고 했습니다.

fe

- 그런데 아직 유저 객체를 가지고 다닐 내용 없음
- 토큰 값도 객체가 아닌 브라우저의 localStorage 사용

등의 이유로 변수를 만드는게 의미가 있나라는 생각이 들어
최초의도와 다르게 사실상 validation.js와 form.js가 합쳐둔 함수 덩어리가 되어버렸습니다.....

2023-12-25 12:04 UTC, whtjdrud commented on assets/js/sign/config/errorMessage.js
> +const getErrorMessage = errCode => errorMessages[errCode];
이렇게 수정 했습니다.
```javascript
const getErrorMessage = errCode => errorMessages[errCode] ?? '알 수없는 에러가 발생하였습니다.';
```
commit : 0440864ef2bfc805f9cf6333b6740539c355230c

2023-12-25 12:06 UTC, whtjdrud commented on assets/js/sign/service/loginService.js
>      }
함수명을 이렇게 수정해봤습니다.

commit : 5c8bc9dc29431c9e1449bf18c4b7bf640d4c83e0

2023-12-25 12:07 UTC, whtjdrud commented on assets/js/sign/service/signUpService.js
> +  handlerViewErrorMessage(resultValidated) {
코드를 어떻게 떼와야하는지 잘 모르겠네요 ㅠ
이렇게 변경해봤습니다.

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/137/commits/5c8bc9dc29431c9e1449bf18c4b7bf640d4c83e0#r1436074373

2023-12-25 12:11 UTC, whtjdrud commented on assets/js/sign/domain/user.js
> +  settingLocalStorage(responseData) {
```javascript
setTokenInLocalStorage(responseData) {
}
```
함수명을 고민하다가 함수명이 조금은 길더라도 명확하게 표현하도록 이름을 수정해보았습니다.

commit : cbc2b63fae10e9c7283646a3e876c85446977d41

2023-12-25 12:12 UTC, whtjdrud commented on assets/js/sign/service/loginService.js
> +  async LoginUser(e, emailTag, passwordTag) {
사소하게 보이지만 중요한것을 놓친것 같습니다.
주의하도록 하겠습니다. ㅠ

commit : 5c8bc9dc29431c9e1449bf18c4b7bf640d4c83e0

2023-12-25 12:19 UTC, whtjdrud commented on assets/js/sign/signup.js
> +  const controller = new SignUpController(signUpView, user, signUpService);
사실 new로 만들면 변수에 담아놔야 할것같습니다.... 어색해요...
말씀하신대로 수정해뒀습니다.

```javascript
document.addEventListener('DOMContentLoaded', () => {

  const loginView = new LoginView();
  const user = new User();
  const loginService = new LoginService(loginView, user);

  new LoginController(loginView, user, loginService);
});
```


commit : d10535ea1e9fba32b54f6966775fa6f576e39d52

2023-12-25 12:52 UTC, whtjdrud commented on assets/js/sign/service/signUpService.js
> +  }
```javascript
  if (signUpResult.valid) {
      window.location.href = '/folder.html';
    }
```
이런식으로 전부 수정해두었습니다.

2023-12-25 13:24 UTC, whtjdrud commented on assets/js/sign/controller/signUpController.js
> +    this.view.emailInput.addEventListener('focusout', () => this.service.validateSignUpEmail(this.view.emailInput));
정말 너무나도 어려운 문제 인것 같습니다. 최초에는 말씀해주신대로 처리 했다가
controller가 슈퍼 컨트롤러가 되는게 아닐까라는 생각이 들어서 고민하다 분리를 시켰습니다.

이런 부분은 정말 어렵네요 ㅠ

2023-12-25 20:32 UTC, whtjdrud commented on signin.html
> +    <script type="module" src="/assets/js/sign/login.js"></script>
폴더트리를 아래와 같이 변경하였습니다.
약간 예전으로 다시 돌아간것 같기는 한데요.

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/ae26472f-2ac2-4e56-8d6b-0366d601643c)

추가로 듣던 강의중 queryselector, querySelectorAll, addEventListener 등의 함수를 래핑해서 사용하면 보기 좋다고 한 부분이 있어 약간 적용해 보았습니다.

pages/config/helper.js 에 추가해두고 함수를 다 변경하였습니다.
```javascript
export function qs(selector, scope = document) {
  if (!selector) throw 'no selector';
  return scope.querySelector(selector);
}

export function qsAll(selector, scope = document) {
  if (!selector) throw 'no selector';
  return Array.from(scope.querySelectorAll(selector));
}
export function on(target, eventName, handler) {
  target.addEventListener(eventName, handler);
}

```

적용한 모습
```javascript
  #initEventListener() {
    on(this.emailInput, 'focusout', () => this.validateEmail(this.emailInput));
    on(this.passwordInput, 'focusout', () => this.validatePassword(this.passwordInput));
    on(this.view.signForm, 'submit', event => this.loginUser(event, this.view.emailInput, this.passwordInput));

    this.view.eyes.forEach(button => {
      on(button, 'click', event => this.view.eyeToggle(event));
    });
  }
```

commit : 0648862168358b050e6bb6b10241546383f3e6ac

2023-12-25 20:34 UTC, whtjdrud commented on assets/js/sign/service/signUpService.js
> +  }
조건문을 아래와 같은 느낌으로 변경하였습니다.
```javascript
  if (response.ok) {
        const responseData = await response.json();
        this.setTokenInLocalStorage(responseData);

        return true;
      }
      return 'INVALID_LOGIN_CREDENTIALS';
      ```
commit : aa16a0eaf3c379e8494755c0eadd985705866c6a

2023-12-25 20:39 UTC, whtjdrud commented on assets/js/sign/controller/signUpController.js
> +    this.view.emailInput.addEventListener('focusout', () => this.service.validateSignUpEmail(this.view.emailInput));
service 를 삭제하였고 service의 기능을 controller로 이동하였습니다.

commit : 3d5285fddbc0ca48742aba0ddd47b861b86df1c8

후에 user 클래스의 역할이 2가지로 나누어져있고, Model의 역할은 없다고 생각하여 아래와 같은 느낌으로 수정하였습니다.

- validate 함수는 삭제 하고 서버와 통신하는 메소드만 남기기
- validate 역할의 함수는 controller로 이동
- 변수 추가 (userid, private로 accesstoken, refreshtoken 생성) / 보안상의 이유로 안할거 같지만. 추가 하였습니다.
- 나중에 추가 될것 같은 메소드 생성

```javascript
 getUserId() {
    return this.userId;
  }

  isLoggedIn() {
    return this.#userAccessToken !== null;
  }

setTokenInLocalStorage(responseData) {
    localStorage.setItem('accessToken', responseData.data.accessToken);
    localStorage.setItem('refreshToken', responseData.data.refreshToken);

    this.#userAccessToken = responseData.data.accessToken;
    this.#userRefreshToken = responseData.data.refreshToken;
  }

  clearToken() {
    localStorage.removeItem('accessToken');
    localStorage.removeItem('refreshToken');

    this.#userAccessToken = null;
    this.#userRefreshToken = null;
  }

```

commit : cd833d05d887ceade0f47355b6a4899a076bd1c4

2023-12-25 20:44 UTC, whtjdrud commented on assets/js/sign/domain/user.js
> +export default class User {
해당 글을 많이 고민한 끝에 아래와 같이 변경하였습니다.
혹시 조금 더 의미있거나 다른 관점으로 생각할 부분이 있다면 열렬히 피드백 부탁드립니다.

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/137#discussion_r1436150789

2023-12-25 21:10 UTC, whtjdrud commented on assets/js/sign/login.js
> +  const accessToken = localStorage.getItem('accessToken');
처음에는 js 파일을 생성해서 작업해보려고 했으나 생각해보니 user 클래스에 isLoggedIn() 메소드가 있어 사용했습니다.

login.js
```javascript
if (user.isLoggedIn()) {
    window.location.href = '/folder.html';
    return;
  }
```

user 클래스
```javascript
  isLoggedIn() {
    return this.#userAccessToken !== null;
  }
```

2023-12-25 21:20 UTC, whtjdrud commented on assets/js/sign/domain/user.js
> +  }
해당 부분에 대해서 많이 고민해봤습니다.

showEmail, showPassword 등으로 새롭게 만들어볼까 고민해씅나 이럴 경우 그럴 경우는 없지만 나중에 회원가입에 대한 내용이 늘어날 경우 메소드가 많이 늘어나기 때문에 저는 오히려 줄이고 싶어 졌습니다. 

다만 service를 없애고 validate 부분을 controller 로 이동하면서 함수를 아래와 같이 수정하였습니다.

```javascript
  toggleErrorMessage(returnValue, tag, message) {
    if (returnValue === false) {
      return this.view.showErrorMessage(tag, message);
    }
    return this.view.clearErrorMessage(tag);
  }
```

해당 함수 호출부는 아래와 같이 변경하였습니다.
```javascript
if (username.length === 0) {
      return this.toggleErrorMessage(false, emailTag, 'EMPTY_EMAIL_FIELD');
    }
```
기존에는 Service 와 view 를 연결하고 / Service와 User 클래스를 연결하면서 복잡하게 값을 가지고 왔지만
Validate 부분을 Controller 에서 실행하면서 태그를 사실상 직접 입력해도 상관없다는 생각이 들었습니다.

그렇게 되면 말씀하신대로 에러메시지 문자열로만 처리가 가능하다는 생각이 들어 아래와 같이 수정하였습니다.

user.js
```javascript
 if (response.ok) {
        // 처리 내용
        return true;
  }
      return 'INVALID_LOGIN_CREDENTIALS';  
```

그리고 실제 작동하는 `toogleErrorMessage`를 아래와 같이 변경했습니다.
호출할때
```javascript
//정상 처리가 아닐때
 this.toggleErrorMessage(false, emailTag, loginResult);
//정상처리 일때
this.toogleErrorMessage(true, emailTag);
```javascript
  toggleErrorMessage(returnValue, tag, message) {
    if (returnValue === false) {
      return this.view.showErrorMessage(tag, message);
    }
    return this.view.clearErrorMessage(tag);
  }
```

(기존에 handlerViewErrorMessage 함수명을 위와 같이 변경하였습니다.)

2023-12-26 14:35 UTC, wonsss commented on assets/js/sign/controller/signUpController.js
> +    this.view.emailInput.addEventListener('focusout', () => this.service.validateSignUpEmail(this.view.emailInput));
자세한 설명 감사합니다.
service를 controller에 합치셨군요. 👍 
User 클래스도 의도를 알 수 멤버변수를 추가해주니 의도를 잘 알겠습니다.

그리고 어차피 지금 멀티 페이지 앱이라서 페이지 이동할 때 해당 html부터 다시 읽고 자바스크립트 새로 컴파일하는 거라서, 현재 구조상 의도하신 user 객체를 페이지별로 새로 생성하지 않고 그대로 유지할 수 없습니다.  이제 리액트에서 싱글페이지앱(SPA)를 구현하면서 그런 의도를 잘 풀으시면 될 것 같아요.

2023-12-26 14:37 UTC, wonsss commented on assets/js/sign/domain/user.js
> +  }
아하 이해하였습니다. 자세한 설명 감사합니다.  👍

2023-12-26 14:37 UTC, wonsss commented on assets/js/sign/domain/user.js
> +  settingLocalStorage(responseData) {
명시적인 이름이네요 👍

2023-12-26 14:42 UTC, wonsss approved these changes
리뷰도 잘 반영해주셨고 많은 고민을 하셨네요.  수고 많으셨어요. 성경님 👍
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/2b798400-ccdf-418d-8232-01a5d1286a7d)

2023-12-26 14:43 UTC, merged