Part1 박준수 week5
codeit-bootcamp-frontend/3-Weekly-Mission pull request #141
Opened 2023-12-23 16:58 UTC by Jnnsu

## 요구사항

### 기본
- [x]  [기본] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받고 “/folder”로 이동하나요?
- [x]  [기본] 이메일 input에서 “test@codeit.com”으로 “/api/check-email” 이메일 중복 확인 POST 요청하면 이메일 중복 에러를 확인할 수 있나요?
- [x]  [기본] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요?

### 심화

- [ ]  [심화] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장했나요?
- [ ]  [심화] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 “/folder” 페이지로 이동하나요?

## 주요 변경사항

- 로그인, 회원가입 페이지에서 필요한 api 요청을 보내는 기능 추가

## 스크린샷

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-25 09:10 UTC, wonsss requested changes
수고하셨습니다. 준수님 😄 
말씀드렸던 내용들 잘 반영하여 여러 시도를 하셨네요. 👍 
리뷰 드린 내용 참고하여 반영 후 다시 리뷰받길 원하시면 말씀해주세요.~!

2023-12-25 09:10 UTC, wonsss commented on sign/constants.js
> +export const ERROR_MESSAGES = {
에러 메세지 상수를 잘 분리해주셨네요. 상수 프로퍼티들 네이밍도 깔끔히 잘해주신 것 같아요.

2023-12-25 09:10 UTC, wonsss commented on sign/constants.js
> +};
API 엔드포인트에 대한 상수화 분리도 좋은 시도인 것 같습니다.

2023-12-25 09:10 UTC, wonsss commented on sign/signin/controller.js
> +const getErrorMessage = (errCode) => ERROR_MESSAGES[errCode] ?? '알 수 없는 에러가 발생했습니다.';
null 병합 연산자를 써서 fallback 메세지를 잘 넣어주셨네요.

2023-12-25 09:10 UTC, wonsss commented on sign/signin/controller.js
> +  validateUser() {
사용자가 로그인이 되어 있으면 페이지를 리다이렉트하는 메서드네요.

해당 메서드의 역할을 고려한다면 validateUser 라는 이름보다 더 좋은 이름이 있을 것 같습니다.

2023-12-25 09:10 UTC, wonsss commented on sign/signin/controller.js
> +  }
이 메서드에서 async / await 가 필요한 건지 확인해보시면 좋을 것 같아요.

2023-12-25 09:10 UTC, wonsss commented on sign/signin/signin.html
>  </html>
현재 폴더 구조에 따라 해당 html의 경로와 이름이 sign/signin/signin.html 입니다.
signin 폴더 안에 html이 하나밖에 없을테니까 signin.html 대신 index.html 로 수정해줘도 괜찮지 않을까요?
<img width="573" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/2e69e682-7d99-4b2d-89d0-f82109c45e57">

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +    this.view.passwordInput.addEventListener('keydown', () => this.handlePasswordInputKeydown());
패스워드인풋에서 keydown 이벤트에 대한 핸들러를 왜 등록하셨는지 궁금합니다.
혹시 form submit을 위해서 하셨다면 해당 이벤트는 필요 없을 것 같아요.
form 태그 내에서 enter key를 누르면 submit이 되는 기본 동작이 이미 있습니다.

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +  }
handleInPasswordInputFocusout 이라는 메서드 자체가 존재하지 않습니다. 확인 부탁드려요.

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +    this.view.emailInput.addEventListener('keydown', () => this.handleEmailInputKeydown());
이 이벤트핸들러 역시 꼭 필요한 건가요?

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +    this.view.formElement.addEventListener('submit', (e) => this.handleFormSubmit(e));
화살표 함수 대신 bind를 사용해서 이렇게 하실 수도 있습니다.
[MDN - bind](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) 참고해보세요. 😄 
```suggestion
    this.view.formElement.addEventListener('submit',  this.handleFormSubmit.bind(this));
```

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +    this.view.passwordRepeatInput.addEventListener('keydown', () =>
이 이벤트핸들러 역시 꼭 필요한 건가요? 🤔

2023-12-25 09:10 UTC, wonsss commented on sign/view.js
> +export default class SignView {
view 로직을 깔끔하게 정리하셨네요

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +      const response = await fetch(getAPI('SIGN_UP_API'), {
이메일 중복 체크하고, 중복되지 않은 경우에만 회원가입 API 호출하도록 잘 구현하셨네요.

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +      const response = await fetch(getAPI('SIGN_UP_API'), {
response 변수명을 signUpResponse 처럼 구체적으로 지으면 더 좋을 것 같아요. 변수명은 항상 되도록 구체적으로 짓는 습관을 들이는 게 좋아요.

2023-12-25 09:10 UTC, wonsss commented on sign/signin/controller.js
> +      location.href = '/folder.html';
참고로 location.assign("/folder.html") 도 동일한 효과예요. ㅎㅎ 그냥 참고만 하세요.

참고 링크: https://developer.mozilla.org/en-US/docs/Web/API/Window/location

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +        );
매개변수로 element 와 message 두 개를 받도록 하여 showErrorMessage의 재사용성을 늘리셨네요. 👍 좋은 시도인 것 같아요.
또는 매개변수로 message만 받도록 하고 showEmailErrorMessage, showPasswordErrorMessage 처럼 재사용성은 제한적이지만 명시적이고 단순한 함수를 사용하는 것도 나쁘지 않을 것 같습니다.

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +          getErrorMessage('PASSWORD_CHECK_FAILED'),
그리고 getErrorMessage 라는 함수와 에러메세지 상수를 정의하셔서, message를 관리하는 것도 좋은 시도인 것 같습니다.
다만, 이는 API에서 errorCode가 전달되었을 때 해당 errorCode를 매개변수로 전달함으로써 메세지를 반환하는 경우에 더 적절할 것 같아요.

2023-12-25 09:10 UTC, wonsss commented on sign/signup/controller.js
> +    this.setAccessTokenCookie(accessToken, 1);
여기서 두번째 인자로 전달한 `1`은 매직넘버에 해당되겠네요. 이 부분도 상수로 분리해주면 좋을 것 같아요.

2023-12-26 05:49 UTC, Jnnsu commented on sign/signin/controller.js
> +  validateUser() {
해당 메서드는 사용자가 토큰이 있는지 확인하는 역할만 하도록 변경해보았습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/949fd69fbbb4a0a36eb89f08494dcdddc0b5b320](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/949fd69fbbb4a0a36eb89f08494dcdddc0b5b320)
그리고 토큰 관련된 메서드를 모두 Model로 옮겨주었습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3)
토큰이 한 종류 뿐이라 token으로 네이밍 변경해주었습니다.

아래는 변경 사항입니다.


```js
// 변경 전
validateUser() {
  const cookies = document.cookie.split(';');
  cookies.forEach((cookie) => {
    const trimmedCookie = cookie.trim();
    if (trimmedCookie.startsWith('accessToken=')) {
      location.href = '/folder.html';
      return;
    }
  });
}

// 변경 후
hasToken() {
  const cookies = document.cookie.split(';');
  return cookies.some((cookie) => {
    const trimmedCookie = cookie.trim();
    return trimmedCookie.startsWith('token=');
  });
}
```

2023-12-26 06:01 UTC, Jnnsu commented on sign/signin/controller.js
> +  }
해당 부분은 async / await이 없어도 잘 작동하더라구요..! 불필요한 것 같아 삭제해주었습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/bebada65ba685aa6fa4737666e530d245676f9ba](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/bebada65ba685aa6fa4737666e530d245676f9ba)

2023-12-26 06:02 UTC, Jnnsu commented on sign/signin/signin.html
>  </html>
해당 부분 수정하였습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/5ca2aa0060d137e1252d68c76314bce7056d7cce](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/5ca2aa0060d137e1252d68c76314bce7056d7cce) [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/8e09dec48408deb5d86e7e0b63617d25f546539a](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/8e09dec48408deb5d86e7e0b63617d25f546539a)

2023-12-26 06:07 UTC, Jnnsu commented on sign/signup/controller.js
> +    this.view.passwordInput.addEventListener('keydown', () => this.handlePasswordInputKeydown());
keydown 이벤트 핸들러를 따로 등록해뒀던 이유는 이전에 focusout 이벤트 핸들러의  return값(Boolean)을 사용해 폼 submit 을 통과시킬지 결정했었는데, 이렇게 하니 focusout 하지 않은 상태로 엔터키를 누르면  잘못된 값을 입력해도 페이지가 넘어갔지 때문이었습니다.. 지금은 완전히 수정된 부분이라 불필요할 것 같습니다! 해당 이벤트 핸들러는 삭제하였습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/1a7862479549ba42b2f55a3f3eb9c8a7db6dabe5](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/1a7862479549ba42b2f55a3f3eb9c8a7db6dabe5)

2023-12-26 06:08 UTC, Jnnsu commented on sign/signup/controller.js
> +    this.view.emailInput.addEventListener('keydown', () => this.handleEmailInputKeydown());
위와 마찬가지로 삭제하였습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/1a7862479549ba42b2f55a3f3eb9c8a7db6dabe5](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/1a7862479549ba42b2f55a3f3eb9c8a7db6dabe5)

2023-12-26 06:10 UTC, Jnnsu commented on sign/signup/controller.js
> +    this.view.passwordRepeatInput.addEventListener('keydown', () =>
위와 마찬가지로 수정하였습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/1a7862479549ba42b2f55a3f3eb9c8a7db6dabe5](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/1a7862479549ba42b2f55a3f3eb9c8a7db6dabe5)

2023-12-26 08:53 UTC, Jnnsu commented on sign/signup/controller.js
> +      const response = await fetch(getAPI('SIGN_UP_API'), {
넵 꼭 신경쓰도록 하겠습니다..!! 항상 네이밍 부분에서 고민이 많이 됩니다ㅠ 특히 접두사와 접미사 사이의 단어들의 순서를 어떤식으로 해야 가독성이 좋고 명시적일지 감이 잘 안잡히네요..

보조하는 단어와 중요도가 높은 단어의 순서를 "중요 - 보조" 순서로 나열하는 것이 좋을까요? ex) `InputEmail`, `ERROR_SIGN_UP`

일단 `response` 변수명을 `emailDuplicateCheckResponse` 로 변경해주고 해당 API 상수명도 `EMAIL_DUPLICATE_CHECK_API`으로 변경해주었는데 원석님은 어떻게 생각하시는지 궁금합니다!

[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3#diff-7b897cb9560cf573c15512f32f93f4514f27a1ec9e9a2b633a7bb31ac71dbb49R97](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3#diff-7b897cb9560cf573c15512f32f93f4514f27a1ec9e9a2b633a7bb31ac71dbb49R97)
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/949fd69fbbb4a0a36eb89f08494dcdddc0b5b320#diff-7b897cb9560cf573c15512f32f93f4514f27a1ec9e9a2b633a7bb31ac71dbb49R161](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/949fd69fbbb4a0a36eb89f08494dcdddc0b5b320#diff-7b897cb9560cf573c15512f32f93f4514f27a1ec9e9a2b633a7bb31ac71dbb49R161)

2023-12-26 08:57 UTC, Jnnsu commented on sign/signup/controller.js
> +    this.setAccessTokenCookie(accessToken, 1);
해당부분 반영하였습니다.
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3#diff-c44d4e0a2a4cf11d143ce7189300f5e15679a0baee2a7c480244802eba8b4b70R29](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3#diff-c44d4e0a2a4cf11d143ce7189300f5e15679a0baee2a7c480244802eba8b4b70R29)
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3#diff-8d8b29948838f0843b21ff9f924610de24a813cca106254b4273620b921b5c20R13](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/22d44eb13d0baf107d07bbd5dc1b8f0695c79bf3#diff-8d8b29948838f0843b21ff9f924610de24a813cca106254b4273620b921b5c20R13)

2023-12-26 09:00 UTC, Jnnsu commented on sign/signup/controller.js
> +  }
오타가 났었군요.. 해당부분 수정하였습니다! 
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/949fd69fbbb4a0a36eb89f08494dcdddc0b5b320#diff-7b897cb9560cf573c15512f32f93f4514f27a1ec9e9a2b633a7bb31ac71dbb49R75](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/949fd69fbbb4a0a36eb89f08494dcdddc0b5b320#diff-7b897cb9560cf573c15512f32f93f4514f27a1ec9e9a2b633a7bb31ac71dbb49R75)

2023-12-26 09:52 UTC, Jnnsu commented on sign/signup/controller.js
> +    this.view.formElement.addEventListener('submit', (e) => this.handleFormSubmit(e));
오 bind를 사용해서도 this를 지정할 수 있군요!! call만 최근에 알았었는데 새로운 메소드를 알았네요 감사합니다!!

2023-12-26 10:01 UTC, Jnnsu commented on sign/signin/controller.js
> +      location.href = '/folder.html';
알려주셔서 감사합니다ㅎㅎ locatioion.href를 location.replace로 변경해보았습니다! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/834f940421c5417af8dc6cfe313f93ddbc169ea2](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/834f940421c5417af8dc6cfe313f93ddbc169ea2)

2023-12-26 10:37 UTC, Jnnsu commented on sign/signup/controller.js
> +        );
말씀하신대로 Input별로 분리시켜보았습니다!! removeErrorMessage도 마찬가지로 수정하였습니다.
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/0962922b0f4e04cc7dca99711bc4142f1629b58f](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/0962922b0f4e04cc7dca99711bc4142f1629b58f)

2023-12-26 10:38 UTC, Jnnsu commented on sign/signup/controller.js
> +          getErrorMessage('PASSWORD_CHECK_FAILED'),
errorCode를 사용하지 않고 바로 에러메세지 상수에 접근하는 방식으로 수정했습니다!
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/0962922b0f4e04cc7dca99711bc4142f1629b58f](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/141/commits/0962922b0f4e04cc7dca99711bc4142f1629b58f)

2023-12-26 14:51 UTC, wonsss commented on sign/signup/controller.js
> +      const response = await fetch(getAPI('SIGN_UP_API'), {
이름에서 단어의 context가 더 높은 것을 앞에 두는 게 맞을 것 같네요 ㅎㅎ 아래 링크 참고해보세요.

[네이밍, 프로그래머가 가장 힘들어하는 그것](https://velog.io/@jjanmo/%EB%84%A4%EC%9D%B4%EB%B0%8D-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EA%B0%80-%EA%B0%80%EC%9E%A5-%ED%9E%98%EB%93%A4%EC%96%B4%ED%95%98%EB%8A%94-%EA%B7%B8%EA%B2%83#actions)
<img width="1038" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/140e9557-5087-4796-87cc-50d50068a19f">

2023-12-26 14:53 UTC, wonsss approved these changes
준수님 리뷰 꼼꼼히 잘 반영해주셨네요. 감사합니다. 
수고 많으셨어요 👍 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/5853eaae-8404-4585-a6c9-553d1fafde4c)

2023-12-26 14:53 UTC, merged