[백진영] week5
codeit-bootcamp-frontend/3-Weekly-Mission pull request #142
Opened 2023-12-23 17:47 UTC by jinyoung1018

## 요구사항

### 기본

- [x][기본] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받고 “/folder”로 이동하나요?
- [x][기본] 이메일 input에서 “test@codeit.com”으로 “/api/check-email” 이메일 중복 확인 POST 요청하면 이메일 중복 에러를 확인할 수 있나요?
- [x][기본] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요?

### 심화

- [x][심화] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장했나요?
- [][심화] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 “/folder” 페이지로 이동하나요?

## 주요 변경사항

-로그인 회원가입 api연동
-

## 스크린샷

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-25 09:34 UTC, wonsss requested changes
안녕하세요 진영님. 😄 수고하셨습니다!
요구사항 반영을 위해 필요한 코드를 깔끔하게 추가하여 작성해주셨네요. 👍 
가독성이 좋아 잘 읽혔습니다!
리뷰 반영 후 추가 리뷰 받길 원하시면 말씀해주세요 😄

2023-12-25 09:34 UTC, wonsss commented on script/signin.js
> +    location.href = "/folder";
참고로 location.assign("/folder.html") 도 동일한 효과입니다. 
페이지 이동시키는 여러 가지 방법 참고해보세요 ㅎㅎ

참고 링크: https://developer.mozilla.org/en-US/docs/Web/API/Window/location

2023-12-25 09:34 UTC, wonsss commented on script/signin.js
> +        localStorage.setItem("accessToken", result.data.accessToken);
요구사항이 localStorage 로 accessToken을 관리하는 거였죠.
그런데 나중에 관리 방식이 localStorage가 아니라 다른 것이 될 수도 있을 것 같아요. 
사실 클라이언트에 토큰 관리 방식으로 로컬스토리지는 보안상 이슈가 있어서, Cookie 를 사용하곤 해요. 
이 부분은 지금 수정할 필요는 없으나 참고만 하시면 좋겠습니다.
[LocalStorage vs. Cookies: JWT 토큰을 안전하게 저장하기 위해 알아야할 모든것](https://hshine1226.medium.com/localstorage-vs-cookies-jwt-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EC%A0%80%EC%9E%A5%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%B4-%EC%95%8C%EC%95%84%EC%95%BC%ED%95%A0-%EB%AA%A8%EB%93%A0%EA%B2%83-4fb7fb41327c)

그러나 미리 해두시면 좋은 리팩터링은 현재 accesToken을 쓰고 읽는 `localStorage.setItem` `localStorage.getItem` 로직을 함수로 만들어 모듈화하고 이를 import하여 사용하는 것입니다. 이렇게 하면 나중에 로컬스토리지가 아닌 쿠키 등 다른 방식으로 변경할 때, 사용처를 일일이 가서 수정하는 게 아니라 해당 함수 내 로직만 수정하면 되어서 유지보수에 간편할 것 같아요.

2023-12-25 09:34 UTC, wonsss commented on script/signup.js
> +console.log(localStorage);
콘솔로그는 제거해주시면 좋을 것 같아요 😄

2023-12-25 09:34 UTC, wonsss commented on script/signup.js
> +async function checkEmailConflict() {
checkDuplicateEmail 이름도 괜찮을 것 같습니다!

2023-12-25 09:34 UTC, wonsss commented on script/signup.js
> +    if (response.status === 409) {
409 외에 다른 에러가 올 수도 있어서, boolean값인 response.ok 를 사용해보시는 것도 제안드립니다. 
ok는 200번대 응답 외에 다른 응답이 오는 경우 false를 반환합니다.

2023-12-25 09:34 UTC, wonsss commented on script/signup.js
> +        return false;
false를 return 하는 이유가 궁금합니다. 
checkEmailConflict 함수의 반환값을 사용하는 경우가 있나요? 🤔

2023-12-25 09:34 UTC, wonsss commented on script/signup.js
>      ) {
아래와 같이 if 조건문을 ealry return 패턴으로 리팩터링하면 조건문 중첩이 사라지겠네요. 😄 
```suggestion
    if (
        !checkEmail() ||
        !checkPassword() ||
        !passwordConfirm()
    ) {
       return;
    }
```

2023-12-26 13:47 UTC, jinyoung1018 commented on script/signin.js
> +    location.href = "/folder";
알려주신 자료 잘 읽어보았습니다! 앞으로 더 다양한 방법을 활용해보겠습니다!

2023-12-26 13:49 UTC, jinyoung1018 commented on script/signin.js
> +        localStorage.setItem("accessToken", result.data.accessToken);
540494b27f4e9c19c1b50bfaa35d19f425a876bd localStorage와 cookie에 대해 더 자세하게 알게되었습니다!! accessToken관리 로직은 따로 모듈로 분리하였습니다!!

2023-12-26 13:50 UTC, jinyoung1018 commented on script/signup.js
> +console.log(localStorage);
46e5247dc08b58d3f945e5e6af37d09b913aab8d 제거하는걸 깜빡했네용 ㅠㅠ 제거했습니다!!

2023-12-26 13:50 UTC, jinyoung1018 commented on script/signup.js
> +async function checkEmailConflict() {
6cd59efc27174a6243883147f1c0c1bedd3b1dab checkDuplicateEmail이 더 좋네용! 변경했습니다!

2023-12-26 13:51 UTC, jinyoung1018 commented on script/signup.js
> +    if (response.status === 409) {
61f0c8abd586c967b203faca823900c73a3f88c6 네넵! response.ok값을 활용하여 모두 수정했습니다!

2023-12-26 13:54 UTC, jinyoung1018 commented on script/signup.js
> +        return false;
checkEmail함수 내에서 이메일에 문제가 있는 경우에 다 false값을 반환하여 마지막 signUp함수내에서 사용했습니다!

2023-12-26 13:57 UTC, jinyoung1018 commented on script/signup.js
>      ) {
9fd17ef2ce61a3260ec2669e3740009a6393c212 early return 패턴으로 수정하였습니다! 앞으로 조건문 중첩에 대해 더 신경써서 가독성 좋은 코드를 작성할 수 있도록 노력하겠습니다!!

2023-12-26 14:54 UTC, wonsss commented on script/signin.js
> +        localStorage.setItem("accessToken", result.data.accessToken);
리팩터링 잘 하셨네용  👍

2023-12-26 15:29 UTC, wonsss commented on script/signup.js
> +        return false;
해당 함수 사용처가 아래와 같은 스크린샷밖에 없던데, checkEmailConflict 의 반환값이 아래와 같은 checkEmail 함수 내에서 반환되지 않고 있어요. response.status === 409 여도 checkEmail 함수 내에서 checkEmailConflict 함수의 반환값 false가 checkEmail 함수의 코드 실행을 중지시키지도 못하고 checkEmail 함수의 반환값이 되지도 못합니다. 

<img width="802" alt="스크린샷 2023-12-26 오후 11 56 12" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/3346205b-832e-4bb5-b21f-f16d28844eb8">

아래와 같이 수정되어야 할 것 같아요.
```js
function checkEmail() {
// 생략
    if(!checkEmailConflict()) {
       return false;
    }
// 생략
}
```

그리고 checkEmailConflict 가 Promise를 반환하니까, 이에 대해서도 async/await를 해줘야 할 것 같네요.
checkEmailConflict는 fetchCheckEmail 로 이름을 변경해서 fetch만 하는 한가지 역할만 하도록 바꿔봤어요.
아래 예시 코드 참고해보세요. 😄 
```js
function fetchCheckEmail() {
    return fetch("https://bootcamp-api.codeit.kr/api/check-email", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            email: inputEmail.value,
        }),
    });
}

async function checkEmail() {
 // 생략

    const response = await fetchCheckEmail();

    if (!response.ok) {
        emailError.textContent = "이미 중복된 이메일입니다";
        inputEmail.className = "error-box";
        return false;
    }

    emailError.textContent = "";
    inputEmail.className = "inputbox";
    return true;
}

async function signUp(event) {
    event.preventDefault();
    const isAvailableEmail = await checkEmail();

    if (
        isAvailableEmail === true &&
// 생략
```

2023-12-26 15:32 UTC, wonsss approved these changes
진영님 😄 수고 많으셨습니다! 리뷰 잘 반영해주셨네요. 감사합니다 👍 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/498505f0-d7b1-4f68-9d49-65720657eee4)

2023-12-26 15:38 UTC, merged