Part1 이치현 week5
codeit-bootcamp-frontend/3-Weekly-Mission pull request #159
Opened 2023-12-25 20:31 UTC by DanteSnow

## 요구사항

### 기본
- [x] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받고 “/folder”로 이동하나요?
- [x] 이메일 input에서 “test@codeit.com”으로 “/api/check-email” 이메일 중복 확인 POST 요청하면 이메일 중복 에러를 확인할 수 있나요?
- [x] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요?

### 심화
- [x] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장했나요?
- [x] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 “/folder” 페이지로 이동하나요?

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-26 15:45 UTC, goldfrosch requested changes
고생했습니다! 브랜치 관리를 매우 잘하셔서 file changed 수가 없네요 :)
매우 좋습니다. 수정한 파일만 PR에 보여지게 하는 것도 리뷰어 입장에서도 보기 편하고 현업에서도 정말 좋죠 (사실 현업에서는 기본이긴 합니다만 배우는 입장에서는 쉽지 않죠!)

일부 PR에 대해 request changed 요청 드립니다 고생했어요!

2023-12-26 15:45 UTC, goldfrosch commented on sign_module.js
> -
[중요도: 중간] 불필요한 주석은 제거해주세요

2023-12-26 15:45 UTC, goldfrosch commented on sign_module.js
>    const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/
[중요도: 높음] emailRegex같은 상수의 경우 UPPER_SNAKE_CASE로 작성해주세요. 또한 함수 선언할 때 마다 새로 할당할 필요가 없는 값이니 최상단으로 올려 처음에 선언 후 계속 사용할 수 있게 하는게 좋겠어요!

2023-12-26 15:45 UTC, goldfrosch commented on signin.js
> +  let requestOptions = {
[중요도: 높음] requestOptions와 raw의 경우 readonly 즉 const로 사용해도 될 것 같네요. 한번 선언 후 변하지 않고 api 호출할 때만 사용하니까요

2023-12-26 15:45 UTC, goldfrosch commented on signin.js
> +    const response = await fetchSignIn(emailInput.value, passwordInput.value);
async await을 활용했군요 좋습니다!
async await은 어떨 때 사용하고, 사용했을 때 then, catch 같은 promise 형태로 사용하는 것보다 편할까요? 편하다면 이유가 뭘까요?

2023-12-27 04:46 UTC, DanteSnow commented on sign_module.js
> -
네, 확인했습니다!

2023-12-27 04:48 UTC, DanteSnow commented on sign_module.js
>    const emailRegex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/
피드백 감사드립니다! 수정 반영하겠습니다!👍🏻

2023-12-27 04:51 UTC, DanteSnow commented on signin.js
> +  let requestOptions = {
넵! 수정 반영하겠습니다! 피드백 감사드립니다!👍🏻

2023-12-27 05:01 UTC, DanteSnow commented on signin.js
> +    const response = await fetchSignIn(emailInput.value, passwordInput.value);
전통적인 방식의 promise 형태보다 가독성이 좋고 그 덕분에 사용하기도 훨씬 편한 장점이 있습니다!
비동기인 promise를 동기적으로 보이게 만들어 줌으로써 코드를 봤을 때 이해하기가 쉽습니다!

예를 들어 then을 많이 사용해야 할 때,  async await을 사용하면 가독성이 좋아집니다.

2023-12-29 13:07 UTC, goldfrosch approved these changes

2023-12-29 13:07 UTC, merged