[오영곤] Week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #16
Opened 2023-12-01 02:42 UTC by ohddang

## 요구사항

### 기본

- [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [x] [기본] Netlify에 파일 배포가 아닌 포크한 Github 레포지토리로 연결했나요?
- [x] [랜딩 페이지] 아래로 스크롤 해도 “Linkbrary” 로고와 “로그인” 버튼이 있는 상단 네비게이션 바(Global Navigation Bar)영역이 최상단에 고정되게 했나요?
- [x] [로그인 페이지, 회원가입 페이지 공통] Linkbrary 로고 클릭시 루트 페이지(“/”)로 이동하나요?
- [x] [로그인 페이지, 회원가입 페이지 공통] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일한가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus in 일 때, 테두리 색상이 파랑색인가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus out 일 때, 테두리 색상이 회색인가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] SNS 아이콘들은 클릭시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동하나요?
- [x] [로그인 페이지] “회원 가입하기”는 클릭시 “/signup” 페이지로 이동하나요?
- [x] [회원가입 페이지] “로그인 하기”는 클릭시 “/signin” 페이지로 이동하나요?

### 심화

- [x] [심화] palette에 있는 color값들을 css 변수로 등록하고 사용했나요?
- [x] [심화] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가했나요?

## 주요 변경사항

- 회원가입, 로그인 페이지 추가
- 홈페이지 네이게이션 바 추가
- CSS변수 사용

## 스크린샷

<img width="952" alt="11" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68732996/dacf9984-06a2-4174-9560-b4050b703fd2">
<img width="950" alt="22" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68732996/769b4be1-35fd-4c63-9bea-d352465a4d82">
<img width="947" alt="33" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68732996/2cebd59b-0506-4fe2-8e0f-e378da9b2a00">

## 멘토에게

- 잘 부탁드립니다

2023-12-02 16:28 UTC, airman5573 requested changes
위클리 미션 하시느라 수고 많으셨습니다.
전반적으로 노력하신게 많이 보입니다.
다만, 레이아웃을 잡으실때 포토샵 하듯이 딱 그 위치에 고정하시려고 하셨던것 같아요.
이 부분은 일일이 다 말씀드리기가 어렵고 ㅠ 여러 좋은 예제들을 보면서 감을 익히시는걸 추천드립니다.

- [youtube.com/watch?v=QRrPE9aj3wI](https://www.youtube.com/watch?v=QRrPE9aj3wI)
- https://www.youtube.com/watch?v=65GVcdESj3s&list=PLUWqFDiirlsuVOx2WWruGfw5nnuaWHNvI

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +  <title>Linkbrary</title>
title 설정 좋습니다 👍

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +<html lang="en">
lang="ko"로 설정해주세요.
검색 엔진이 이 html 파일을 읽을때 도움 됩니다.

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +        <div class="linkbrary">
linkbrary로 감싸지 않고 a 태그만 있어도 될것 같습니다.

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +          <a href="./index.html"><img src="resources/svg/linkbrary.svg"></a>
폴더명을 잘 지어주셨네요 👍 
참고로 resources도 괜찮은 용어지만, 보통은 assets이라는 말을 더 자주 사용합니다.

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +          <a href="signin/index.html" class="login button_font">로그인</a>
.button_font로 공통 클래스를 잘 추출해 주셨네요 👍

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +        <div class="main_des"><span class="main_des_gradient">세상의 모든 정보를</span><br>쉽게 저장하고 관리해 보세요</div>
desc 처럼 뒤에 c까지 붙여주는게 더 자연스러워 보입니다. 수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +        <div class="section_des des_1_position"><span class="section_des_gradient1 gradient_font">원하는 링크를</span><br> 저장하세요</div>
클래스를 여러개 써서 css 코드 중복을 줄여주셨네요 👍

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +          <div class="card_list">
list는 <ul> 이 더 어울립니다. 수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +          <img src="resources/image/folder.png" class="section_img2">
section_img2 보다는 section_content에 section_content_2를 추가하고,
css에서는 .section_content_2 .section_img 로 1,2,3,4를 구분하는 편이 더 자연스러워 보입니다. 수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on index.html
> +      <div class="sns">
여기도 <ul> 이 더 자연스러워 보입니다. 수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  padding: 2rem 6.5rem 4rem 6.5rem;
푸터 패딩이 너무 많이 들어갔습니다. 약간 낮춰주세요.
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/3791f539-68a3-428f-b32c-a7a803dda323)

2023-12-02 16:28 UTC, airman5573 commented on signin/style.css
> +:root{
css variable 사용하면 일관성을 유지할 수 있죠 👍 
다만, 일반적으로 Red -> red 이런식으로 소문자를 많이 사용합니다.
수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on signin/style.css
> +  box-sizing: border-box;
👍

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +
body에 마진이 들어가 있습니다. 0으로 지정해주세요.
<img width="1108" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/07bcd81c-ea90-40a6-8149-753b30cdcca4">

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  align-self: stretch;
이곳에서 align-self는 작동하지 않는 속성입니다.
삭제해 주세요.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  gap: 0.5rem;
일관적으로 rem을 사용하시네요 👍 
다만, 처음에는 px이 작업하시기가 좀 편하실겁니다.
수정하지 않으셔도 되나 다음 미션부터는 px 사용을 추천드립니다.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  width:100%;
div 태그는 기본적으로 full-width이기 때문에 따로 100%을 주지 않으셔도 됩니다.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  position: fixed;
content에서 fixed를 해주시면 전체 높이가 적용되지 않습니다.
<img width="967" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/13a3709b-ce32-4cde-9782-011fef87641a">

높이가 들어가도록 수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  position: absolute;
absolute보다는 부모에서 flex를 주고 justify와 padding으로 조절하시는 편이 더 안정적입니다.
수정해주세요.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +.login:hover{
hover없이 기본적으로 cursor를 pointer로 지정해 주세요.

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +.section_area .section_content:nth-child(1){
nth-child를 사용하셨군요 👍

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +.des_3_position{
css 네이밍의 어려움을 극복하기 위해 tailwindcss 라는 프레임워크도 있습니다.
나중에 참고해주세요.
https://tailwindcss.com/

2023-12-02 16:28 UTC, airman5573 commented on style.css
> +  object-fit: cover;
👍

2023-12-04 06:47 UTC, ohddang commented on style.css
> +  padding: 2rem 6.5rem 4rem 6.5rem;
패딩이 많이 들어갔다는 영역이 어디일까요?? 요소 3개간 간격일까요 혹시?

2023-12-06 05:45 UTC, merged