[Week6] 조현진
codeit-bootcamp-frontend/3-Weekly-Mission pull request #165
Opened 2023-12-30 03:42 UTC by ahrrrl

![01_모코코콘1_02_눈물팡_](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/126558640/55d7e7df-1c5f-4c65-9355-439e52f30891)

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?

- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?

- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?

- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?

- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?

- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?

- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [x] 커스텀 hook을 만들어 활용했나요? 

## 멘토에게

- 많은 일이 있었습니다

2024-01-01 14:19 UTC, goldfrosch requested changes
고생하셨습니다. 첫번째로 내신 것을 축하드리며 생각보다 과제의 퀄리티도 나쁘지 않아 좋네요 :)
관련해서 PR남겨뒀으니 확인 부탁드립니다~

2024-01-01 14:19 UTC, goldfrosch commented on src/App.js
> +      <Footer />
적당한 컴포넌트로 잘 나누셨네요 :)
[중요도: 중간] 다만 Section의 경우 이름을 조금 구체적으로 적으면 좋을 것 같습니다.

2024-01-01 14:19 UTC, goldfrosch commented on public/index.html
> -    <noscript>You need to enable JavaScript to run this app.</noscript>
[중요도: 중간] noscript의 역할은 뭐고 이것을 왜 지웠는지 알 수 있을까요?

2024-01-01 14:19 UTC, goldfrosch commented on src/App.js
>  function App() {
[중요도: 높음] export default를 맨 위로 올린 이유가 뭘까요?

function을 사용하는 컴포넌트의 경우는
```suggestion
export default function App() {
```
위에 처럼 한번에 적어도 무방합니다.

2024-01-01 14:19 UTC, goldfrosch commented on src/api.js
> +  return body;
[중요도: 중간]
```suggestion
  return await response.json();
```
으로 해보는건 어떨까요?

2024-01-01 14:19 UTC, goldfrosch commented on src/api.js
> +    "https://bootcamp-api.codeit.kr/api/sample/user",
[중요도: 중간]
API의 baseUrl은 상수화 해보는 것도 좋아보입니다.
```
const API_BASE_URL = "https://bootcamp-api.codeit.kr"
```

2024-01-01 14:19 UTC, goldfrosch commented on src/components/DateUtils.js
> +export { getTimeDifference, formatCreatedAt };
[중요도: 중간] 여기도 export를 맨 위로 끌어올렸네요.

export function ~~~ 형식으로 작성하는 것도 좋습니다~

2024-01-01 14:19 UTC, goldfrosch commented on src/components/DateUtils.js
> +  }
[중요도: 중간] time 관련 숫자들은 상수화해서 쓰면 더 편하게 사용하실 수 있을거에요. 무엇보다 가독성이 좋아집니다!
const MINUTE = 60;
const HOUR = MINUTE * 60;
const DAY = HOUR * 24;
const MONTH = DAY * 30 (사실 이 부분은 특정 월은 31일까지나 28일까지 있는 경우가 있어서 추후 보완은 필요해보이네요~)
const YEAR = MONTH * 12;

이런식으로 쓰고 사용한다면 더 가독성와 왜 이렇게 숫자를 썻는지 이해하기 쉽겠죠?
```
else if (timeDifferenceInSeconds < DAY) {
```

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Footer.js
> +            </a>
alt태그와 a태그에 href를 잘 넣어 시멘틱 마크업을 유지하셨군요 좋습니다 :)

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Header.js
> +  const loginImg = <img src="/imgs/로그인.png" alt="로그인"></img>;
[중요도: 높음] 굳이 위에 상수로 선언하고 밑에 선언할 필요는 없어보입니다.
사실 조금 심화적인 내용으로 들어가면 해당 코드는 안티패턴입니다. UserProfileInHeader가 리렌더링(즉 해당 컴포넌트의 업데이트) 될 때 마다 loginImg도 새로 렌더링을 해야하기 때문이죠

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Header.js
> +          ></img>
[중요도: 중간] React의 경우 여러분들의 기존과 하던 순수 html과 다르게 굳이굳이 element를 닫지 않아도 됩니다.
```suggestion
          <img
            className="user-profile-login-img"
            src={user.profileImageSource}
            alt="사용자 이미지"
          />
```

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Header.js
> +      )}
[중요도: 중간] 굳이 빈 span 태그를 넣어주는 삼항연산자보다 && 연산자를 쓰는게 더 나아보이네요~
```suggestion
      {userFolder && (
        <>
          <img
            className={"userfolder-content-img"}
            src={userFolder.folder.owner.profileImageSource}
            alt="폴더 사용자 이미지"
          ></img>
          <span className="userfolder-content-name">
            {userFolder.folder.owner.name}
          </span>
          <span className="userfolder-content-foldername">
            {userFolder.folder.name}
          </span>
        </>
      )}
```

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Section.js
> +      <input></input>
[중요도: 중간] 굳이 이 빈 input이 필요한가요?
필요하다면 <input />로 변경해주시고 적어도 name과 type을 적어 무슨 용도였는지라도 남겨주는게 좋겠군요

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Section.js
> +}
[중요도: 낮음] 위에 적으려다 여기에 한번에 적는게 좋을 것 같아 말씀드리면 개인적으로는 하나의 파일에는 하나의 컴포넌트를 적는 것을 권장드립니다. (멘토 본인의 취향도 조금 섞여있지만...) 제가 했던 실무에서는 항상 하나의 파일에 컴포넌트가 2개 이상이 된다면 꼭 재사용을 위해 export를 선언해야하고 그렇게 될 때 컴포넌트 찾기가 매우 힘들어지는 경우가 있더라구요. 참고 해주세요 이건 꼭 지켜야한다는 아니지만 제 경험상 그랬었습니다~

2024-01-01 14:19 UTC, goldfrosch commented on src/components/Section.js
> +};
[중요도: 낮음] 컴포넌트에 맞는 코드는 아닌 것 같아 별도의 util파일 혹은 하나의 컴포넌트에서만 사용한다면 컴포넌트 내부로 넣어주세요. 물론 이렇게하면 리렌더링 때 성능 자체의 문제는 해결될 수 있으나 저정도로 리렌더링 성능이 엄청 개선되는 것도 아니고, 코드량이 많아진다면 가독성이 안좋아질 것 같네요.

2024-01-02 07:40 UTC, ahrrrl commented on src/components/Section.js
> +};
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/46e7ff399a3933aa48246fea972a88a59ba18420

만들고 나서 해당 컴포넌트에 넣는 걸 깜빡했나봅니다!

2024-01-02 07:43 UTC, ahrrrl commented on src/components/Section.js
> +      <input></input>
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/f44ffef9b0d7c8997d8e69baabf5813086a080e0

폴더 검색을 하는 인풋 태그인데 아직 기능까지는 안들어가서 className으로 용도를 남겼습니다.
엘리먼트에 css연결 시켰던 걸 따로 className을 만들어 연결했습니다.

2024-01-02 07:44 UTC, ahrrrl commented on src/components/Header.js
> +      )}
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/2e221d0fe074940b7671e41e966c76110ba336c8

&&연산자가 깔끔하게 좋군요!

2024-01-02 07:46 UTC, ahrrrl commented on src/components/Header.js
> +          ></img>
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/263d22342bbb797183ed1575c371f278fb83f1dd

이미지 태그 끝을 수정했고 변수에 이미지를 담지 않고 바로 return에 이미지 태그를 넣었습니다.

2024-01-02 07:47 UTC, ahrrrl commented on src/components/Header.js
> +  const loginImg = <img src="/imgs/로그인.png" alt="로그인"></img>;
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/263d22342bbb797183ed1575c371f278fb83f1dd

이미지 태그 끝을 수정했고 변수에 이미지를 담지 않고 바로 return에 이미지 태그를 넣었습니다

2024-01-02 07:51 UTC, ahrrrl commented on src/App.js
>  function App() {
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/03cd01f745111df3e52834073e7da952793cc653

모든 export를 다시 작성했습니다!
굳이 맨 위로 올린 이유는 어디에 export를 적는게 좋을지 아무도 누구도 알려주지 않았기 때문입니다!!

2024-01-02 07:53 UTC, ahrrrl commented on public/index.html
> -    <noscript>You need to enable JavaScript to run this app.</noscript>
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/02ac8248d2deffc1581f321e4d4f07c1624bde54
다시 넣었습니다!
noscript가 자바스크립트가 비활성화 됐을 때 안에 메시지가 나오는 경고창 같은 거라고 설명을 들었는데
솔직히 잘 와닿지가 않습니다!

2024-01-02 07:54 UTC, ahrrrl commented on src/api.js
> +    "https://bootcamp-api.codeit.kr/api/sample/user",
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/57a324dc546ed0ce2eea6fb019e1347773d45ef5

보기 좋게 상수화를 했긴 했는데 
const API_BASE_URL = "https://bootcamp-api.codeit.kr"를 함수밖에 선언하는게 좋을지 안에 선언하는 게 좋을지 모르겠습니다!

2024-01-02 07:55 UTC, ahrrrl commented on src/api.js
> +  return body;
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/165/commits/763f7eb933a47f07d641e59a6268fa9da048cc96

수정했습니다!
군더더기가 붙어있었군요

2024-01-04 13:36 UTC, goldfrosch commented on public/index.html
> -    <noscript>You need to enable JavaScript to run this app.</noscript>
그거 맞습니다 :)
실제로 발생하는 경우는 클라이언트 설정에 JS 로드 설정을 끄는 경우 발생할 수 있습니다.
꼭 추가하라는 말은 아니였지만 이참에 배워가길 바라며 적었으니 참고해주세요 :)

2024-01-04 13:36 UTC, goldfrosch commented on src/App.js
>  function App() {
아차차

2024-01-04 13:37 UTC, goldfrosch commented on src/api.js
> +    "https://bootcamp-api.codeit.kr/api/sample/user",
함수 밖에 선언하셔야합니다. 해당 내용은 변하지 않는 값이기 때문에 굳이 함수안에 넣어서 함수가 호출되며 선언될 때 새로 할당을 해줄 이유가 없습니다!

2024-01-04 13:38 UTC, goldfrosch commented on src/components/Header.js
> +      )}
조건부 렌더링에 대해 알아보심 좋습니다.

2024-01-04 13:38 UTC, goldfrosch approved these changes
고생하셨습니다 :)

2024-01-04 13:38 UTC, merged