[노진석] week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #168
Opened 2023-12-30 13:25 UTC by SiWooJinSeok

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
- [ ] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
- [ ] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

- 미완성입니다.
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-01 06:14 UTC, wonsss commented
@SiWooJinSeok 님, 안녕하세요~! 이번 미션 PR에서 merge into 될 레포 브랜치는 `codeit-bootcamp-frontend:part1-노진석` 이 아니라 `codeit-bootcamp-frontend:part2-노진석` 여야 할 것 같아요. 시간되실 때 확인 후 수정 부탁드려요.

2024-01-01 06:49 UTC, wonsss commented
Git 커밋 메세지 컨벤션에 따라 커밋을 하시는 것을 추천드립니다. 커밋 컨벤션을 준수하면, 더 좋은 커밋 로그 가독성, 더 나은 협업과 리뷰 프로세스, 더 쉬운 코드 유지보수가 가능해지는 장점이 있습니다.
대표적인 컨벤션으로 AngularJs에서 만든 컨벤션이 있습니다. 아래 링크에서 해당 문서를 참고해보세요. :) 
- [AngularJS Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w)
	- 번역: [[Git] 커밋 메시지 규약 정리 (the AngularJS commit conventions](https://velog.io/@outstandingboy/Git-%EC%BB%A4%EB%B0%8B-%EB%A9%94%EC%8B%9C%EC%A7%80-%EA%B7%9C%EC%95%BD-%EC%A0%95%EB%A6%AC-the-AngularJS-commit-conventions)

2024-01-01 09:57 UTC, wonsss requested changes
안녕하세요. 진석님! 첫 리액트 미션을 잘 해주셨네요. 수고 많으셨습니다.
리뷰 남겨드린 내용 확인 후, 댓글 부탁드려요. 관련하여 수정하셨으면 댓글에 해당 커밋 링크 첨부도 부탁드립니다.

그리고 PR 내용에 `설치 및 실행 방법` 에 대해 적어주시면 좋습니다. 😄

2024-01-01 09:57 UTC, wonsss commented on src/styles/CardList.css
> +.card {
React 프로젝트 구조 설계를 파일의 유형에 따라 분류하신 것 같네요. 이렇게 설계하시는 것도 좋습니다. 
일반적으로, 자주 함께 변경되는 파일들을 같이 보관하는 것이 좋은 방법이에요. 이러한 원칙을 “코로케이션(colocation)“이라고 불러요.

예를 들어, CardList.js와 CardList.css를 CardList 라는 폴더 안에 같이 두는 것도 이런 면에서 좋을 수 있을 것 같습니다. 
React는 컴포넌트 기반 라이브러리로서, 프로젝트 구조를 컴포넌트에 중점을 두고 설계하는 것이 좋습니다. 각각의 기능 또는 화면은 독립적인 컴포넌트로 나누어져야 합니다. 이는 각 컴포넌트의 재사용성을 높입니다.

협업, 확장성, 유지보수성 측면에서 어떤 방식이 좋을지 생각해보시면 좋을 것 같아요.
관련해서 리액트 공식 문서 내용을 참고해보세요. :) 
https://ko.legacy.reactjs.org/docs/faq-structure.html

2024-01-01 09:57 UTC, wonsss commented on src/Components/Card.jsx
> +import React from "react";
폴더명은 일반적으로 소문자로 시작합니다.
현재 Components 폴더명으로 되어 있는데, components로 수정하면 좋을 것 같아요. 이러한 사소한 일관성도 고민하면서 개발하면 협업 시 좋습니다. :)

2024-01-01 09:57 UTC, wonsss commented on src/index.js
> +  </>
`<Fragment> (<>...</>)` 를 사용하셨는데, 이 경우에는 제거하셔도 될 것 같아요. 자세한 사용법은 공식 문서 확인해보세요. 😄 
https://ko.react.dev/reference/react/Fragment

2024-01-01 09:57 UTC, wonsss commented on src/index.js
> +  </>
그리고 `<React.StrictMode>` 로 App을 감싸면, 개발 중에 컴포넌트에서 일반적인 버그를 빠르게 찾을 수 있습니다. 
아마 CRA로 프로젝트 시작하셨으면, 기본으로 있었을텐데 수정하신 것 같네요. 
이유가 있으셨을 것 같은데, 이유가 궁금합니다. 
그리고 자세한 내용은 문서 참고해보세요 😄 
https://ko.react.dev/reference/react/StrictMode

2024-01-01 09:57 UTC, wonsss commented on src/pages/Shared.jsx
> +import React, { useEffect, useState } from "react";
해당 Shared.jsx 파일은 페이지 단위의 컴포넌트라고 보기 어려울 것 같아요. pages 폴더가 아닌 components 폴더 하위로 이동시켜야 할 것 같아요. 그리고 Shared라는 컴포넌트명도 포괄적인 것 같습니다. 해당 컴포넌트 역할에 맞는 명시적인 이름을 붙이면 좋을 것 같아요.

2024-01-01 09:57 UTC, wonsss commented on src/apis/api.js
> +export async function bodyResponseJson(url) {
공통된 로직을 함수로 분리하셨군요. 👍 좋은 시도인 것 같아요.

다만, 함수의 이름은 동사로 시작해야 합니다. 
함수의 역할을 명확하게 전달하기 위해 함수명을 좀 더 명확하게 바꿔도 좋을 것 같습니다. 예를 들어, fetchJson과 같은 이름으로 변경하는 것이 좋을 수 있습니다.

그리고 나중에 API별로 각각 다른 에러 처리나 파싱을 하는 경우가 생기면, 해당 공통 함수를 사용하지 못할 수도 있을 것 같아요.  그래서 아직 여기서는 이렇게 함수 분리까진 안해도 될 것 같습니다. 😄

2024-01-01 09:57 UTC, wonsss commented on src/Components/Navbar.jsx
> +  //   const userName = user.name;
사용하지 않는 주석은 제거해주세요 😄

2024-01-01 09:57 UTC, wonsss commented on src/index.js
> +    <App />
현재 라우팅을 하지 않으셨네요. 아마 미션 요구사항에 포함되지 않은 걸까요? 🤔 

react에서 싱글 페이지 애플리케이션 구현 시, `react-router-dom` 라이브러리를 설치하여 라우팅을 쉽게 구현하실 수 있습니다.

클라이언트 사이드 라우팅이라고도 하며 사용자가 요청한 URL에 따라서 이에 맞는 컴포넌트를 렌더링 해주는 것을 의미합니다. 서버에게 별다른 요청을 보내지 않고 클라이언트의 브라우저 단에서만 페이지를 이동하는 기능입니다.

예를 들어,  사용자가 `/folder` 경로의 url로 접속했을 때, 현재 구현하신 페이지를 렌더링하고 싶다면 이전처럼 `folder.html` 파일을 서버에 요청하여 다운로드 후 브라우저에서 새로고침하여 렌더링하는 것이 아니라 라우팅 설정한 코드에 의해 페이지 새로고침 없이 클라이언트의 브라우저 단에서만 페이지를 이동시킬 수 있씁니다.

예를 들어 아래와 같은 Router.jsx 파일을 작성하여 앱 전체의 라우팅을 관리하는 것입니다.

```jsx
// Router.jsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import FolderPage from "./pages/FolderPage";

export default function Router() {
	return (
		<BrowserRouter>
			<Routes>
				<Route path='/folder' element={<FolderPage />} />
			</Routes>
		</BrowserRouter>
	);
}
```


react-router-dom 버전6 사용법은 아래 블로그나 공식문서를 참고하여 시작해보세요 😄 
https://velog.io/@soryeongk/ReactRouterDomV6
https://github.com/remix-run/react-router?tab=readme-ov-file

2024-01-01 09:57 UTC, wonsss commented on src/utils/util.js
> +export const getTimeDifference = (createdTime) => {
해당 함수 매개변수명으로 `createdTime` 을 하셨군요!
이 이름도 좋은 이름 같아요.
인자로 넘겨지는 값이 "2022-11-27T12:24:09Z" 와 같은[ ISO8601 표준](https://ko.wikipedia.org/wiki/ISO_8601) 형식의 문자열이네요.

조금 더 명시적으로 짓기 위해, 날짜만 있는 경우와 날짜와 시간까지 함께 있는 경우를 구분하고 string 타입 여부까지 구분한다면, `dateTimeString` 이라는 이름도 적합할 수 있을 것 같습니다.  그리고 해당 함수 내부 맥락에서는 created라는 이름은 불필요할 것 같구요.

실무에서 ISO8601 표준 형식의 dateTimeString 을 자주 사용하니, 무엇인지 이해하고 계시는 것도 좋습니다.

https://262.ecma-international.org/11.0/#sec-date-time-string-format

2024-01-01 09:57 UTC, wonsss commented on src/utils/util.js
> +  }
조건을 깔끔히 잘 작성하신 것 같습니다. 👍 

다만, else if, else 문이 불필요하게 있는 것 같아요.
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else나 else-if문을 사용하지 않아도 됩니다.

early return 패턴은 아래 참고 링크 등에서 참고해보세요.
https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90

2024-01-01 09:57 UTC, wonsss commented on src/utils/util.js
> +  }
'2', '60*24' 등과 같은 도메인과 관련된 `매직 넘버`나 `매직 리터럴`은 변수에 할당하여 상수화해주시는 것이 좋습니다.

매직 넘버(Magic number)나 매직 리터럴(Magic Literal)은 코드에서 하드 코딩된 일정한 값을 의미하는 숫자나 문자열을 의미합니다. 
예를 들어 '2', 나 '60*24' 등의 숫자는 코드 내에서 여러 곳에서 사용되고 있지만, 이 값의 의미나 목적은 현재 코드에서 명확하게 알려져 있지 않습니다.

매직넘버나 매직리터럴은 가독성이 떨어지고 유지보수를 어렵게 만들며, 예상치 못한 버그를 발생시키는 원인이 될 수 있습니다.

따라서 이들을 상수로 분리하고 해당 매직넘버의 역할을 정확한 이름으로 붙여서 사용하시는 것이 좋습니다. 그리고 상수로 분리해두면 값을 변경할 때 일괄적으로 변경할 수 있으므로 코드의 유지보수성과 가독성이 향상됩니다.

참고로 자바스크립트에서 상수를 선언하는 컨벤션은
`MINUTE` 처럼 모두 영어 대문자에 띄어쓰는 부분은 언더바를 적습니다.

```
const MINUTE = 1;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;
const MONTH = 30 * DAY;
const YEAR = 12 * MONTH;
```

2024-01-01 09:57 UTC, wonsss commented on src/Components/Footer.jsx
> +  const instagramUrl = "https://www.instagram.com/";
매직 리터럴이네요. 상수이므로 `YOUTUBE_URL`나 객체로 묶어서 SNS_URL.YOUTUBE 처럼 호출하여 사용하시는 것도 좋아보입니다. 😄 

```js
const SNS_URL = {
    YOUTUBE: "https://www.youtube.com/"
};

SNS_URL.YOUTUBE
```

2024-01-01 09:57 UTC, wonsss commented on src/App.js
> +      userInfo = await getUser();
`let userInfo;` 처럼 변수를 let으로 선언해두실 필요가 없습니다.
12번째 라인에서 바로 `const userInfo = await getUser();` 처럼 const 쓰시는 게 낫습니다

2024-01-01 09:57 UTC, wonsss commented on src/App.js
> +      }
if 조건에 걸리지 않는 경우(userInfo 가 없는)에는 어떤 처리를 하는지 정의되어 있지 않네요. 이건 요구사항에 정의되어 있지 않아서 아마 하지 않으신 것일 수도 있지만, 예상치 않은 상황이라면 Error를 던지도록 하여 아래 캐치문에서 잡히도록 하는 것도 염두해볼 수 있겠습니다.

2024-01-01 09:57 UTC, wonsss commented on src/App.js
> +  const userCheck = async () => {
함수 이름은 동사로 시작하는 것이 좋습니다.

2024-01-01 09:57 UTC, wonsss commented on src/Components/CardList.jsx
> +        : ""}
빈 문자열 대신 null을 반환하는 것이 좋습니다.

2024-01-01 09:57 UTC, wonsss commented on src/Components/Footer.jsx
> +          <a href={facebookUrl} rel="noreferrer noopener" target="_blank">
앵커 태그의 rel 속성으로 noreferrer noopener 를 사용해주셨군요 👍 
관련 내용을 한번 읽어보시면 좋습니다.

[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

2024-01-01 09:57 UTC, wonsss commented on public/index.html
> +    <div id="root"></div>
브라우저가 스크립트를 비활성화한 경우에는 리액트 싱글페이지애플리케이션이 정상동작하지 않을 것이기 때문에, 이런 경우에 표시될 대체 메세지를 정의해두는 것도 좋습니다. 이를 위해 noscript 요소를 추가하면 됩니다.

```js
	<body>
		<noscript>You need to enable JavaScript to run this app.</noscript>
		<div id="root"></div>
	</body>
```

> HTML `<noscript>` 요소는 페이지의 스크립트 유형을 지원하지 않거나, 브라우저가 스크립트를 비활성화한 경우 보여줄 HTML 구획을 정의합니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/noscript

<img width="1294" alt="스크린샷 2024-01-01 오후 5 59 02" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/26f409d6-bd96-49c3-be25-1b635fce8bfa">

2024-01-01 09:57 UTC, wonsss commented on src/assets/images/1.png
이러한 assets들은 public 폴더 하위로 옮기는 게 적절합니다.
public 폴더는 앱이 컴파일될 때 사용하지 않는 자원들을 모아둡니다. index.html, images, fonts 와 같은 정적파일들이 담깁니다.
아래 문서 내용을 참고해보세요 😄 
https://create-react-app.dev/docs/using-the-public-folder/#when-to-use-the-public-folder

2024-01-01 09:57 UTC, wonsss commented on src/styles/Footer.css
> +.footer {
CSS 작성 방법으로 현재 `css`를 사용하셨네요.
리액트 프로그래밍을 할 때는 `컴포넌트`를 중심으로 생각하는 게 좋습니다. UI는 컴포넌트의 조합으로 표현되며, 컴포넌트 하나를 잘 만들어서 여러 곳에 재사용하는 게 좋습니다. 그렇게 하기 위해서 각 컴포넌트는 서로 간의 의존성을 최소화하면서 내부적으로는 `응집도`를 높여야 합니다.
`응집도`가 높은 컴포넌트를 작성하기 위해 `CSS 코드`도 `컴포넌트 내부`에서 관리하는 게 좋습니다.

컴포넌트 내부에서 CSS 코드를 관리하는 방법으로 `css-module`, `css-in-js` 등이 있습니다.

css-module을 사용하면 일반적인 css 파일에서 클래스명이 충돌할 수 있는 단점을 극복할 수 있습니다. 컴포넌트 단위로 스타일을 적용할 때 좋습니다.
CRA에서는 css 파일 이름을 다음과 같이 작성하면 css module이 됩니다. `{이름}.module.css`
css-module은 클래스명 정보를 담고 있는 객체를 내보내며, css 파일에서 정의한 클래스명은 style 객체의 속성 이름으로 존재합니다. 각 클래스명에 고유한 해시값이 들어 있어서 클래스 이름이 겹치지 않도록 방지합니다.
CSS Module을 적용한 아래 예시 코드를 참고해보세요.
```jsx
// CardList/CardList.module.css
.card {
   background-color: red;
}

// CardList/CardList.jsx
import styles from "./CardList.module.css";

export default function CardList({ itemList }) {
	return (
		<div className={styles.card}>
      생략
		</ul>
	);
}
```

CSS Module에 대해서는 아래 링크들을 더 참고해보시기 바랍니다.

[Adding a CSS Modules Stylesheet](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)
[What are CSS Modules and why do we need them?](https://css-tricks.com/css-modules-part-1-need/)

이외의 CSS 작성 방법으로 css-in-js 방식은 css-module 방식을 경험해본 후 다음에 해보시길 바랍니다.

2024-01-01 09:57 UTC, wonsss commented on src/Components/Card.jsx
> +    <a href={url} rel="noreferrer noopener" target="_brank">
`_brank` 는 오타입니다.
`_blank`로 수정해주세요. 😄 
https://developer.mozilla.org/ko/docs/Web/HTML/Element/a

2024-01-01 09:57 UTC, wonsss commented on src/Components/Card.jsx
> +    <a href={url} rel="noreferrer noopener" target="_brank">
오타를 내지 않는 것도 매우 중요합니다.
VSCode 익스텐션의 도움을 받아보실 것을 추천드려요. 

이름: Code Spell Checker
ID: streetsidesoftware.code-spell-checker
설명: Spelling checker for source code
버전: 3.0.1
게시자: Street Side Software
VS Marketplace 링크: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2024-01-01 09:57 UTC, wonsss commented on src/Components/Footer.jsx
> +          <a href="/privacy">Privacy Policy</a>
리액트의 싱글 페이지 애플리케이션을 구현하신다면, 앵커 태그(`<a>`) 대신에 react-router-dom 라이브러리의 `<Link>` 컴포넌트를 사용하시는 것이 좋습니다.

Link는 html의 앵커 태그와 역할은 같습니다. 
하지만, 앵커 태그는 페이지를 새로고침 시키기 때문에, 싱글페이지 애플리케이션에서는 앱 내 페이지 이동할 때는 이 대신 Link 컴포넌트를 사용합니다. 

주의사항으로는 Link 컴포넌트는 Router안에서만 동작합니다.

공식문서나 관련 블로그 내용을 참고해보세요.
https://reactrouter.com/en/main/components/link

https://www.daleseo.com/react-router-basic/

2024-01-01 09:57 UTC, wonsss commented on package.json
> +  },
CRA로 간편하게 프로젝트를 시작하면, 기본으로 설치되어 있는 라이브러리입니다. 
그런데 현재 구현하신 부분에서는 아직 test, express, web-vitals 등을 활용하지 않으신 것 같습니다. 
그렇다면 불필요한 라이브러리는 제거해주시는 게 좋습니다. 😄

2024-01-02 09:56 UTC, SiWooJinSeok commented on src/index.js
> +  </>
제가 나간 진도 기준으로 실습에서 사용하고 있지 않아서 시작과정에서 제거하고 시작한 것 같습니다. 정확한 기능을 몰랐어서 꼭 필요한 기능이 아니라고 판단했었습니다!

2024-01-03 10:11 UTC, SiWooJinSeok commented on src/styles/CardList.css
> +.card {
[chroe: 폴더 구조 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/a7a8e600f306efd66d452fb38ed2c83397759d17) 이렇게 수정해 봤습니다.

2024-01-03 10:12 UTC, SiWooJinSeok commented on src/Components/Card.jsx
> +import React from "react";
[chroe: 폴더 구조 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/a7a8e600f306efd66d452fb38ed2c83397759d17) 여기서 같이 수정하였습니다!

2024-01-03 10:16 UTC, SiWooJinSeok commented on src/index.js
> +  </>
[chore: StrictMode 추가](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/2fd7706a25c77d630edd1b9f54341b544cbb7cd8) 추가했습니다!

2024-01-03 10:19 UTC, SiWooJinSeok commented on src/pages/Shared.jsx
> +import React, { useEffect, useState } from "react";
이 부분은 피그마에선 Shared라는 페이지가 따로 있기에 pages 폴더에 넣었습니다! 나중에 라우팅 기능을 추가할 때 다시 수정할 부분이 있는지 찾아보겠습니다!

2024-01-03 10:25 UTC, SiWooJinSeok commented on src/apis/api.js
> +export async function bodyResponseJson(url) {
[chore: api 공통함수 이름 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/89f3a3f0ab2bf91250980fee72633271f3902669) 여기서 fetchJson으로 수정했습니다! 아직 동사로 시작하는게 익숙하지 않은 것 같습니다. 변수명이랑 함수명 생각하는 것도 생각보다 어렵네용..! ㅎㅎ
칭찬 감사합니다. 공통함수는 나중에 에러 처리나 파싱을 하는 경우가 생길 때 한번 수정해보겠습니다!

2024-01-03 10:27 UTC, SiWooJinSeok commented on src/Components/Navbar.jsx
> +  //   const userName = user.name;
[chore: 필요없는 주석 제거](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/f030ae6943143479ac04686ceb65f5c2a3bb3f3f) 제거했습니다.

2024-01-03 10:30 UTC, SiWooJinSeok commented on src/index.js
> +    <App />
좋은 정보 감사합니다! 이번주에 라우터를 배울 예정이여서 이번주 과제에서 사용해 보겠습니다!

2024-01-03 10:49 UTC, SiWooJinSeok commented on src/utils/util.js
> +export const getTimeDifference = (createdTime) => {
[refactor: util.js 파일 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/30c5641ff43199b58adb9f2ea05b00d146fc10c5) 여기서 수정하였습니다!

2024-01-03 10:49 UTC, SiWooJinSeok commented on src/utils/util.js
> +  }
[refactor: util.js 파일 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/30c5641ff43199b58adb9f2ea05b00d146fc10c5) 여기서 수정하였습니다!

2024-01-03 10:50 UTC, SiWooJinSeok commented on src/utils/util.js
> +  }
[refactor: util.js 파일 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/30c5641ff43199b58adb9f2ea05b00d146fc10c5) 여기서 수정하였습니다!

2024-01-03 10:56 UTC, SiWooJinSeok commented on src/Components/Footer.jsx
> +  const instagramUrl = "https://www.instagram.com/";
[refactor: Footer.jsx Url부분 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/d50e183e522d7a948ce6bb10cabf7d626024bb7b) 수정했습니다! 객체 방식이 좋아보입니다!

2024-01-03 11:09 UTC, SiWooJinSeok commented on src/App.js
> +      userInfo = await getUser();
[refactor: App.js 파일 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/dd1c27cb500e69fa8b49364f788ae13b06498178) 여기서 수정했습니다! try문에서만 처리해서 const가 맞는 것 같습니다!

2024-01-03 11:10 UTC, SiWooJinSeok commented on src/App.js
> +      }
[refactor: App.js 파일 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/dd1c27cb500e69fa8b49364f788ae13b06498178) 일단 임시로 Error를 던져보았습니다! 에러에 대한 요구사항이 없었다보니 급히 다른 기능에 먼저 신경 쓴 것 같습니다!

2024-01-03 11:11 UTC, SiWooJinSeok commented on src/App.js
> +  const userCheck = async () => {
[refactor: App.js 파일 리펙토링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/dd1c27cb500e69fa8b49364f788ae13b06498178) 여기서 checkUser로 변경해보았습니다!

2024-01-03 11:17 UTC, SiWooJinSeok commented on src/Components/CardList.jsx
> +        : ""}
[chore: 삼항 연산자에서 빈문자열을 null로 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/965f97b448eb9f95c757d89292b04d06b3c73c8a) 여기서 변경 했습니다. 혹시 빈 문자열로 반환 하면 메모리가 더 소비되는 것 일까요?

2024-01-03 11:17 UTC, SiWooJinSeok commented on src/Components/Footer.jsx
> +          <a href={facebookUrl} rel="noreferrer noopener" target="_blank">
정보 감사합니다!

2024-01-03 11:21 UTC, SiWooJinSeok commented on public/index.html
> +    <div id="root"></div>
[chore: index.html noscript 추가](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/dabb32aa50afb556c0b4bdf974876139e1adc697) 추가했습니다. 영상으로 따라 하면 지우는 경우도 있었던 것 같아서 지운 것 같습니다!

2024-01-03 11:22 UTC, SiWooJinSeok commented on src/styles/Footer.css
> +.footer {
넵 다음 과제할 때 모듈css 먼저 시도해보겠습니다!

2024-01-03 11:25 UTC, SiWooJinSeok commented on src/Components/Card.jsx
> +    <a href={url} rel="noreferrer noopener" target="_brank">
[chore: Card.jsx 오타수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/d4a23ecce922ec0fd6d1b700b6f90bbc33e19d70) 큰 이상이 없어서 오타가 있는 줄 몰랐습니다! 수정했습니다! 익스텐션도 깔아서 사용중입니다! 좋은 정보 감사합니다!

2024-01-03 11:26 UTC, SiWooJinSeok commented on src/Components/Footer.jsx
> +          <a href="/privacy">Privacy Policy</a>
좋은 정보 감사합니다! 라우터 구현할 때 a태그들을 Link태그로 바꿔서 사용해 봐야겠네요!

2024-01-03 11:32 UTC, SiWooJinSeok commented on package.json
> +  },
혹시 package.json에서만 제거 하면 되는 건가요? 추가적으로 해야하는 작업이 있을까요?

2024-01-03 11:58 UTC, SiWooJinSeok commented on src/Components/Card.jsx
> +import React from "react";
[캐시 클리어 후 커밋](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/168/commits/e7e11e8670012cac6d01444d40978494dc0be619) 위에서 적용이 안되어 이 커밋으로 해결 했습니다.

2024-01-03 15:14 UTC, wonsss commented on src/styles/CardList.css
> +.card {
좋네요 👍  
사소한 거지만 한 가지 더 여쭙자면, `Components` 폴더명이 다른 폴더들과 달리 혼자 이름이 대문자로 시작하는데 의도하신걸까요?
일관성있게 가면 좋을 것 같아요.

2024-01-03 15:15 UTC, wonsss commented on src/Components/Card.jsx
> +import React from "react";
수고하셨습니다 👍

2024-01-03 15:16 UTC, wonsss commented on src/apis/api.js
> +export async function bodyResponseJson(url) {
이름 짓는 거 어렵죠 ㅎㅎ 저두 ㅠㅠ 
그래도 계속 의식적으로 좋은 이름을 고민하면서 개발하는 습관을 들이는 게 중요한 것 같아요. 수고하셨습니다 ! 👍

2024-01-03 15:17 UTC, wonsss commented on src/utils/util.js
> +  }
코드가 훨씬 깔끔해졌네요!

2024-01-03 15:17 UTC, wonsss commented on src/Components/Footer.jsx
> +  const instagramUrl = "https://www.instagram.com/";
좋네요!

2024-01-03 15:19 UTC, wonsss commented on src/App.js
> +      }
넵 ㅎㅎ 기능 개발이 우선이죠! 
그래도 개발할 때, 엣지 케이스나 에러 처리도 고민하면 더 안전한 코드를 만들 수 있습니다. 👍

2024-01-03 15:48 UTC, wonsss commented on src/Components/CardList.jsx
> +        : ""}
null, 빈 문자열 등을 반환하면 모두 어떤 node도 렌더링하지 않습니다. 
하지만 첨부한 스크린샷과 같이 리액트 공식문서에서 아무것도 반환하지 않고 싶을 때는 null 을 사용할 것을 안내하고 있습니다.

<img width="1323" alt="스크린샷 2024-01-04 오전 12 47 03" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/6123ea6e-1d88-4db9-81c9-ca220b2d3e24">
버그 방지를 위해 명시적인 코드를 작성하는 것이 중요합니다.
null을 반환하면 명시적으로 어떤 것도 반환하지 않았다는 의도를 드러냅니다.
그러나 빈 객체나 빈 문자열은 무언가 반환되었음을 암시할 수 있고, 실수로 다른 값을 넣을 수도 있기 때문에, 아무것도 반환하지 않으려면 일관성있게 null을 사용하는 것이 나을 것 같습니다.

2024-01-03 15:50 UTC, wonsss commented on package.json
> +  },
수정하고 npm install 명령어 다시 돌려서 재설치해주시면 됩니다.
재설치하는 것은 진석님 컴퓨터에 노드모듈 재설치하는 것입니다~!

2024-01-03 15:51 UTC, wonsss approved these changes
진석님~ 리뷰 반영을 아주 잘해주셨네요!
꼼꼼하게 잘 해주셔서 감사합니다.
해당 PR 어프로브하겠습니다. 다음 미션에서 뵈어요 😄

2024-01-03 15:51 UTC, merged