[고기호] Week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #169
Opened 2023-12-30 14:17 UTC by GihoKo

## 요구사항

### 기본

-[x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
-[x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했 
     나요?
-[x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
-[x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
-[x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
-[x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
-[x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
-[x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
-[x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

-[] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

- 
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-01 17:37 UTC, wonsss requested changes
안녕하세요. 기호님! 첫 리액트 미션을 잘 해주셨네요. 수고 많으셨습니다.
리뷰 확인 후, 각각 리뷰에 의견이나 반영 여부 등에 대한 댓글을 남겨주시길 부탁드려요. 관련하여 수정하셨으면 댓글에 해당 커밋 링크 첨부도 부탁드립니다.

그리고 PR 내용에 설치 및 실행 방법 에 대해 적어주시면 좋습니다. 😄

### 질문에 대한 답변

> 컴포넌트에 따라 디렉토리를 나누고 해당 디렉토리에 js파일과 css파일을 정리하는 방식으로 디렉토리 구조를 만들었습니다. 그런데 컴포넌트 내부의 요소들이 많아질수록 점점 구조가 복잡해지고 깊어지는 문제가 발생하는데 멘토님께서는 어떤 방식으로 디렉토리 구조를 만들면서 컴포넌트를 관리하시는지 궁금합니다.

관련 내용 리뷰에 남겼습니다. 😄 

> 함수를 모듈로 빼긴 해야할 것 같은데 바닐라 JS를 사용했을 떄는 공통적으로 사용되는 함수를 따로 뒀는데 리액트도 그런식으로 하면 될까요?

넵! 맞습니다. 공통 유틸 함수를 분리하면 좋아요. 그리고 커스텀훅을 적용하시면,  마찬가지로 공통 커스텀 훅도 분리할 수 있습니다.

> 확실히 컴포넌트가 많아짐에 따라 css 파일이 많아지고 왔다갔다 하는 시간들이 많이 늘어나는 것 같습니다... css 라이브러리가 벌써부터 필요하다고 느껴집니다

네! 그러한 필요성을 느끼게 된다면, css-in-js 라이브러리를 택하여 사용해보시는 것을 추천드립니다.
그리고 css-module 방식도 한번 경험해보시구요

> eslint와 prettier를 npm으로 다운을 받아서 사용해보는 중인데 생각보다 수정을 해야한다고 나오는 부분이 많아서 깜짝 놀랐습니다. 그리고 eslint에서 여러 오류를 던져주면 npm run build가 안되더라구요. 그래서 /* eslint-disable*/를
사용해서 일단은 급한 불은 껐는데... 해당부분은 뭔가 공부가 더 필요할 것 같습니다.

eslint 관련 설정이 약간 복잡한 것 같아요. 이 부분은 멘토링 시간에 설명드릴게요!

> 커스텀 훅의 경우 아직 공부하지 않아서 못했지만 진도를 나가면 적용해 보도록 하겠습니다.

커스텀 훅을 사용하여 비즈니스 로직과 UI 로직을 분리하는 것도 중요합니다. 화이팅입니다~!

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.js
파일 내에서 jsx 문법을 사용하시면 해당 파일 확장자는 jsx로 해주시는 게 좋아요.
파일 확장자를 js로 하더라도 기능적 차이는 없지만, JSX가 표준 Javascript가 아니기 때문에, 파일 내에 jsx 문법을 사용하셨다면 jsx 확장자로 해주시는 것이 권장됩니다.
Airbnb Coding Style에서도 리액트 컴포넌트에는 `.jsx` 확장자를 사용할 것을 기본 규칙으로 설정해두었습니다. https://github.com/airbnb/javascript/tree/master/react#naming

<img width="934" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/a80daf3f-c25c-4724-8dea-226eedc7cee4">


그리고 이와 관련한 스택오버플로우 게시물도 있으니 관심 있으시면 참고바랍니다. 
https://stackoverflow.com/questions/46169472/reactjs-js-vs-jsx

2024-01-01 17:37 UTC, wonsss commented on .eslintrc
> +  "parser": "babel-eslint",
해당 설정 때문에 현재 eslint에서 에러가 발생하고 있습니다. 확인 부탁드려요! 
<img width="1112" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/f78a1110-b682-44ad-9c25-94ae63c9531f">

2024-01-01 17:37 UTC, wonsss commented on .eslintrc
> +    "react/react-in-jsx-scope": "off",
해당 규칙을 잘 적용해주셨네요. 
JSX를 사용할 때 React를 스코프에 명시적으로 가져와야 하는 규칙을 비활성화하는 규칙입니다. React 버전 17부터는 이 규칙을 해제할 수 있기 때문에, 현재 18 버전을 사용하시므로 잘 적용해주셨어요.

2024-01-01 17:37 UTC, wonsss commented on .eslintrc
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
jsx 문법을 사용한 파일의 확장자를 jsx 뿐만 아니라 js 도 사용할 수 있도록 추가로 린트 설정하셨군요.
기본값 그대로 둬도 괜찮을 것 같은데, 혹시 이유가 있으실까요?

2024-01-01 17:37 UTC, wonsss commented on .eslintrc
> +    "react/function-component-definition": [2, { "namedComponents": ["arrow-function", "function-declaration"] }],
좋은 설정인 것 같습니다. 👍 
해당 설정을 하신 이유를 설명해주실 수 있으실까요 ?

2024-01-01 17:37 UTC, wonsss commented on package.json
> +}
end of line이 들어가 있지 않네요.

prettier 설정을 보니 end of line 이 자동으로 들어가도록 설정은 되어 있던데, 다시 한번 확인 부탁드려요.

대부분의 css 파일들에 end of line 경고가 뜨고 있는 것을 보니, 
기존 코드를 그대로 복사해서 가져온 후 저장을 하지 않아서, 현재 prettier 설정대로 format on save가 적용되지 않은 것 같습니다.

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +            <a href={link.url} className="link" key={link.id}>
컴포넌트 리스트 항목에 link의 id라는 적절한 key 값을 넣어주셨네요 👍 
map() 호출 내부의 JSX 엘리먼트에는 항상 key가 필요합니다!
만약에 배열의 index나 랜덤한 값을 key로 넣어서는 안됩니다. 그 이유는 다음과 같고 자세한 내용은 공식문서를 참고하세요. 중요한 내용입니다. 😄 

> 각 배열 항목에 다른 항목 중에서 고유하게 식별할 수 있는 문자열 또는 숫자를 key로 지정해야 합니다.
Key는 각 컴포넌트가 어떤 배열 항목에 해당하는지 React에 알려주어 나중에 일치시킬 수 있도록 합니다. 이는 배열 항목이 정렬 등으로 인해 이동하거나 삽입되거나 삭제될 수 있는 경우 중요해집니다. key를 잘 선택하면 React가 정확히 무슨 일이 일어났는지 추론하고 DOM 트리에 올바르게 업데이트 하는데 도움이 됩니다.
https://ko.react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.css
React 프로젝트 구조 설계를 자주 함께 변경되는 파일들을 같이 보관하셨군요.  “코로케이션(colocation)“을 잘하신 것 같아요 👍 

React는 컴포넌트 기반 라이브러리로서, 프로젝트 구조를 컴포넌트에 중점을 두고 설계하는 것이 좋습니다. 각각의 기능 또는 화면은 독립적인 컴포넌트로 나누어져야 합니다. 이는 각 컴포넌트의 재사용성을 높입니다.

정답은 없고 협업, 확장성, 유지보수성 측면에서 어떤 방식이 좋을지 생각해보시면 좋을 것 같아요.

관련해서 리액트 공식 문서 내용을 참고해보세요. :) 
https://ko.legacy.reactjs.org/docs/faq-structure.html

2024-01-01 17:37 UTC, wonsss commented on src/App.js
현재 라우팅을 하지 않으셨네요. 아마 미션 요구사항에 포함되지 않은 걸까요? 🤔 

react에서 싱글 페이지 애플리케이션 구현 시, `react-router-dom` 라이브러리를 설치하여 라우팅을 쉽게 구현하실 수 있습니다.

클라이언트 사이드 라우팅이라고도 하며 사용자가 요청한 URL에 따라서 이에 맞는 컴포넌트를 렌더링 해주는 것을 의미합니다. 서버에게 별다른 요청을 보내지 않고 클라이언트의 브라우저 단에서만 페이지를 이동하는 기능입니다.

예를 들어,  사용자가 `/folder` 경로의 url로 접속했을 때, 현재 구현하신 페이지를 렌더링하고 싶다면 이전처럼 `folder.html` 파일을 서버에 요청하여 다운로드 후 브라우저에서 새로고침하여 렌더링하는 것이 아니라 라우팅 설정한 코드에 의해 페이지 새로고침 없이 클라이언트의 브라우저 단에서만 페이지를 이동시킬 수 있씁니다.

예를 들어 아래와 같은 Router.jsx 파일을 작성하여 앱 전체의 라우팅을 관리하는 것입니다.

```jsx
// Router.jsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import FolderPage from "./pages/FolderPage";

export default function Router() {
	return (
		<BrowserRouter>
			<Routes>
				<Route path='/folder' element={<FolderPage />} />
			</Routes>
		</BrowserRouter>
	);
}
```


react-router-dom 버전6 사용법은 아래 블로그나 공식문서를 참고하여 시작해보세요 😄 
https://velog.io/@soryeongk/ReactRouterDomV6
https://github.com/remix-run/react-router?tab=readme-ov-file

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +  };
조건을 깔끔히 잘 작성하신 것 같습니다. 👍

다만, else if, else 문이 불필요하게 있는 것 같아요.  
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else나 else-if문을 사용하지 않아도 됩니다.

early return 패턴은 아래 참고 링크 등에서 참고해보세요.  
[https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90](https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90)

```js
  if (passedYear >= 1) {
    return `${Math.floor(passedYear)} years ago`;
  }

  if (passedMonth >= 1) {
    return `${Math.floor(passedMonth)} months ago`;
  }

  if (passedDay >= 1) {
    return `${Math.floor(passedDay)} days ago`;
  }

  if (passedHours >= 1) {
    return `${Math.floor(passedHours)} hours ago`;
  }

  if (passedMinutes >= 1) {
    return `${Math.floor(passedMinutes)} minutes ago`;
  }

  return '1 minute ago';
```

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +    if (passedYear >= 1) `${Math.floor(passedYear)} years ago`;
if (condition) doSomething()과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다. 
만약 if문 중괄호가 없는데 아래와 같이 실수로 줄바꿈이 되었다면 에러가 발생합니다.
```js
if (errorResult.status === 409)
return true; 
```
이처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋기 때문에 한줄이라도 중괄호를 쓰는 코딩 스타일을 일관성있게 유지하시길 바랍니다. 😄 

자세한 내용은 아래 링크 참고 바랍니다.
https://ko.javascript.info/coding-style

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +  const passedTimeCalculator = link => {
함수이름은 동사로 시작하는 것이 일반적입니다. 더 좋은 이름을 고민해보면 좋을 것 같아요.

그리고 함수의 매개변수로 link 객체를 받았는데, 함수 내부에서는 link.createdAt만 사용한다면, 매개변수의 타입을 더 좁혀서 createdAt이라는 문자열만 받도록 변경하는 것이 어떨까요?

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +  const returnUploadDate = link => {
함수이름으로 return보다는 get이나 format도 적절해보입니다.

해당 함수는 dateTimeString을 받아서 formattedDate를 반환하는 한 가지 간단한 역할을 하고 있습니다. 그러면 아래와 같이 함수 이름과 매개변수 이름을 변경하는 것도 괜찮을 것 같습니다. 기호님 생각은 어떠세요? 😄 
```js
const formatDate = dateTimeString => {
    const date = new Date(dateTimeString);
   // 중략
    return `${year}. ${month}. ${day}`;
}

2024-01-01 17:37 UTC, wonsss commented on src/assets/images/Search.svg
이러한 assets들은 public 폴더 하위로 옮기는 게 적절합니다.
public 폴더는 앱이 컴파일될 때 사용하지 않는 자원들을 모아둡니다. index.html, images, fonts 와 같은 정적파일들이 담깁니다.
아래 문서 내용을 참고해보세요 😄 
https://create-react-app.dev/docs/using-the-public-folder/#when-to-use-the-public-folder

2024-01-01 17:37 UTC, wonsss commented on src/components/Header/Header.js
> +          <button className="header__btn-login">
button 태그에 type을 항상 명시해주시면 좋을 것 같아요.
button 태그의 type 속성의 기본값은 submit입니다. 양식 제출용 버튼이 아니라면 type 특성을 button으로 지정하는걸 잊지 마세요. 기본값에서는 버튼을 눌렀을 때 양식 데이터를 제출하고, (존재하지 않는) 응답을 불러오려고 시도하는 과정에서 문서의 현재 상태가 사라질 수 있습니다.

>  button 태그의 type 속성: 버튼의 행동 방식. 가능한 값은 다음과 같습니다.
-submit: 버튼이 서버로 양식 데이터를 제출합니다. 지정하지 않은 경우 기본값이며, 유효하지 않은 값일 때도 사용합니다.
-reset: <input type="reset">처럼, 모든 컨트롤을 초깃값으로 되돌립니다.
-button: 기본 행동이 없으며 클릭했을 때 아무것도 하지 않습니다. 클라이언트측 스크립트와 연결할 수 있습니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/button

2024-01-01 17:37 UTC, wonsss commented on src/components/Footer/Footer.js
> +          <a href="https://www.facebook.com" target="_blank">
a 태그에 target="_blank" 속성을 사용할 때는 rel="noopener noreferrer" 특성을 지정하여 window.opener 참조 설정을 방지하는 것이 좋습니다. 이를 통해 생성된 창의 opener 속성에 접근해도 null을 반환합니다.  하이퍼링크를 신뢰할 수 없을 때, 브라우저의 보안 리스크를 방지할 수 있습니다.

관련해서 참고하실 수 있는 링크 전달드립니다.
https://mathiasbynens.github.io/rel-noopener/#recommendations
[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

2024-01-01 17:37 UTC, wonsss commented on public/index.html
> +    </body>
브라우저가 스크립트를 비활성화한 경우(chrome://settings/content/javascript) 에는 리액트 싱글페이지애플리케이션이 정상동작하지 않을 것이기 때문에, 이런 경우에 표시될 대체 메세지를 정의해두는 것도 좋습니다. 이를 위해 noscript 요소를 추가하면 됩니다.

```js
	<body>
		<noscript>You need to enable JavaScript to run this app.</noscript>
		<div id="root"></div>
	</body>
```

> HTML `<noscript>` 요소는 페이지의 스크립트 유형을 지원하지 않거나, 브라우저가 스크립트를 비활성화한 경우 보여줄 HTML 구획을 정의합니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/noscript

<img width="1294" alt="스크린샷 2024-01-01 오후 5 59 02" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/26f409d6-bd96-49c3-be25-1b635fce8bfa">

2024-01-01 17:37 UTC, wonsss commented on src/App.js
> +  };
응답 데이터을 얻기 위해서 response.json()을 매번 호출하거나, 데이터를 보낼 때, HTTP 요청 헤더에 "Content-Type": "application/json"로 설정해주는 부분 및 response.ok가 아닌 경우 에러를 던지는 등의 코드가 반복되고 있습니다.
반복되는 get fetch 요청을 함수로 분리한다면, 아래와 같이 사용할 수 있습니다.

```js
async function get(host, path, body, headers = {}) {
	const url = `https://${host}/${path}`;
	const options = {
		method: "GET",
		headers: {
			"Content-Type": "application/json",
			...headers,
		},
		body: JSON.stringify(body),
	};
	const res = await fetch(url, options);
	const data = await res.json();
	if (res.ok) {
		return data;
	} else {
		throw Error(data);
	}
}
```

```js
// 사용
const getFolderInfo = async () => {
  try {
    const res = await get(
      "bootcamp-api.codeit.kr",
      "api/sample/folder"
    );
    setFolder(res.folder);
  } catch (error) {
    console.log(error);
  }
};
```

2024-01-01 17:37 UTC, wonsss commented on src/App.js
> +  };
더 나은 사용자경험을 위해 fetch 시 fetch의 loading과 error 상태를 관리하는 것도 좋습니다. 만드신 페이지의 새로고침을 해보시면, 네트워크 요청을 하는 잠깐 동안 fetch가 완료되지 않아서 state의 기본값이 적용되어 화면의 UI 레이아웃이 전제적으로 깨지고 있습니다. 아주 잠깐이라서 괜찮지만, 만약 네트워크 환경이 안 좋은 사용자라면 그런 문제가 더 크게 느껴질 것입니다.  
fetch 하는 동안 어떤 컴포넌트(예를 들어, 로딩스피너)를 대체하여 보여줄지 고민해보시고 적용해보시는 것도 좋습니다. 
그리고 fetch 결과 에러가 발생했을 때에도, UI에 어떻게 보여줄지도 error 상태를 관리함으로써 하실 수 있습니다.

즉, fetch의 완료 성공 상태뿐만 아니라 로딩이나 에러 상태도 고려하여 UI를 대응하는 것이 좋습니다. 나중에 react-query 라이브러리를 사용하면 이런 것들이 추상화되어 편리하게 하실 수 있으니 참고바랍니다. 😄 


```js
// 사용
const [folder, setFolder] = useState();
const [error, setError] = useState('');
const [isLoading, setIsLoading] = useState(true);

const getFolderInfo = async () => {
  try {
    const res = await get(
      "bootcamp-api.codeit.kr",
      "api/sample/folder"
    );
    setFolder(res.folder);
  } catch (error) {
    console.log(error);
    setError(error.message); // 에러
  } finally {
    setIsLoading(false); // 로딩 끝
  }
};
```

그리고 인터넷 검색해보니 fetch 의 loading, error 적용하는 것을 단계적으로 설명해둔 블로그가 있어 전달드립니다.
https://week-book.tistory.com/entry/React-fetch-%EC%82%AC%EC%9A%A9%EB%B2%95-LoadingErrorGETPOST

2024-01-01 17:37 UTC, wonsss commented on src/App.js
> +      />
Header 컴포넌트는 login, userData 이라는 prop만 받도록 정의되어 있는데, 이 컴폰넌트 호출 부분에서는 prop으로 불필요하게 setLogin, setUserData, loadUserData 를 전달해주고 있는 것 같습니다.

2024-01-01 17:37 UTC, wonsss commented on src/components/CardList/Search/Search.js
> +            <input placeholder="링크를 검색해 보세요."></input>
검색인풋이므로 input type 속성에 "search"를 적용해주시는 것이 좋습니다.
그리고 해당 input은 self close 가능하므로 아래처럼 해주시는 게 좋아요.
```jsx
      <input type="search" placeholder="링크를 검색해 보세요." />
```

참고
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

2024-01-01 17:37 UTC, wonsss commented on src/components/Folder/Folder.js
> +        <img src={linkData.owner?.profileImageSource} alt="코드잇 마크" />
전체적으로 img들에 alt 속성 값을 잘 적용해주셨네요 👍 👍 

참고로 img 태그의 alt 속성에는 다음과 같은 이유로 해당 이미지를 설명하는 의미 있는 텍스트를 적어주시는 것이 좋습니다. 😄 
<img width="1213" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/70fe2c82-da3e-4a51-9209-372e5ebc7be1">
https://ko.wikipedia.org/wiki/Alt_%EC%86%8D%EC%84%B1

2024-01-03 10:50 UTC, GihoKo commented on src/components/CardList/Card/Card.js
넵 jsx로 파일로 적용하겠습니다!

2024-01-03 10:58 UTC, GihoKo commented on .eslintrc
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
원래는 jsx로 작성한 파일을 js확장자로 썼어서 자꾸 오류가 나서 설정을 했습니다.
이제는 해당 파일들을 jsx로 확장자로 다 변경시켜서 해당 린트는 제거할 예정입니다!

2024-01-03 11:07 UTC, GihoKo commented on .eslintrc
> +    "react/function-component-definition": [2, { "namedComponents": ["arrow-function", "function-declaration"] }],
화살표 함수의 경우에는 자주 쓰는 형태라서 설정을 했습니다.
그런데 함수 선언식의 경우에는 원래 표현식으로 할려했었는데 실수를 해버렸네요.
함수 표현식의 경우에 호이스팅에 영향을 받지 않기 때문에
항상 함수 선언을 코드 위쪽에, 호출을 아래쪽에 두면서 일관적으로 코드를 짜게 해줘서 
항상 이용하려고 하고 있습니다.
이 부분은 "function-declaration"를 "function-expression"로 변경할 예정입니다.

2024-01-03 11:13 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +            <a href={link.url} className="link" key={link.id}>
관련자료 꼼꼼히 읽어보겠습니다!

2024-01-03 11:13 UTC, GihoKo commented on src/components/CardList/Card/Card.css
넵 꼼꼼히 읽어보겠습니다!

2024-01-03 11:15 UTC, GihoKo commented on src/App.js
리액트 라우팅의 경우에는 이번주에 진도가 시작해서 저번주 과제에는 적용을 못했습니다 ㅠㅠ
이번주 과제를 시작하면 적용하겠습니다!

2024-01-03 11:19 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +  const passedTimeCalculator = link => {
passedTimeCalculator의 경우 calculatePassedTime로 바꿔보겠습니다.

해당부분 createdAt으로 적용해보겠습니다!

2024-01-03 11:20 UTC, GihoKo commented on .eslintrc
> +    "react/react-in-jsx-scope": "off",
감사합니다 ㅎㅎ

2024-01-03 11:22 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +  };
원래 이런식으로 했었는데 그게 맞았군요 ㅎㅎ
early return 패턴으로 수정하겠습니다 ㅎㅎ

2024-01-03 11:29 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +    if (passedYear >= 1) `${Math.floor(passedYear)} years ago`;
return과 중괄호를 생략할때마다 짧은게 좋은지 명시적으로 나타내지는게 좋은지 고민을 했었는데
다음부터는 명시적으로 해야겠습니다 ㅎㅎ

2024-01-03 11:34 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +  const returnUploadDate = link => {
오 저는 get이랑 format 둘다 좋습니다!
개인적으로 getFormattedDate도 좋아보여서 이걸로 해보겠습니다 ㅎㅎ

2024-01-03 11:37 UTC, GihoKo commented on src/assets/images/Search.svg
이미지 파일들이 많아지면 관리하기가 힘들어져서 public 폴더로 옮기는 것이 좋군요.
반영하겠습니다!

2024-01-03 11:45 UTC, GihoKo commented on src/components/Header/Header.js
> +          <button className="header__btn-login">
문서 확인하고 반영하겠습니다!

2024-01-03 11:49 UTC, GihoKo commented on src/components/Footer/Footer.js
> +          <a href="https://www.facebook.com" target="_blank">
관련 링크 참고해서 반영하겠습니다!

2024-01-03 11:52 UTC, GihoKo commented on public/index.html
> +    </body>
필요하지 않은 태그라고 생각했는데 이런 태그였군요.
잘 모르는 것을 변경할 때는 좀 더 신중해지겠습니다.
해당 부분 반영하겠습니다!

2024-01-03 11:53 UTC, GihoKo commented on src/App.js
> +      />
해당 부분 반영하겠습니다!

2024-01-03 11:55 UTC, GihoKo commented on src/components/CardList/Search/Search.js
> +            <input placeholder="링크를 검색해 보세요."></input>
오... input의 type에 search가 있는 건 처음 알았습니다...
문서 참고해보니 제가 모르는 타입도 꽤 있어서 한번씩 읽어보겠습니다!
해당 부분도 반영하겠습니다.

2024-01-03 11:56 UTC, GihoKo commented on src/components/Folder/Folder.js
> +        <img src={linkData.owner?.profileImageSource} alt="코드잇 마크" />
넵 알겠습니다!

2024-01-03 12:34 UTC, GihoKo commented on .eslintrc
> +  "parser": "babel-eslint",
https://velog.io/@c-jeongyyun/React-Eslint-%EA%B4%80%EB%A0%A8-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0
해당부분은 여기서 해결을 했습니다.

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/44d26f85-6f29-489c-8701-4464700fcda1)
이 폴더를 넣어야 하군요

2024-01-03 13:32 UTC, GihoKo commented on package.json
> +}
분명 end of line이 auto적용 돼있고 format on save도 적용돼있음에도
문서 서식 작업을 해도 적용이 안됐는데
.json이랑 .css 파일의 기본 서식이 prettier로 설정이 안돼있었습니다...
설정이 바꾸니 해결이 됐습니다

2024-01-03 13:53 UTC, GihoKo commented on .eslintrc
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
해당 부분 수정한 링크입니다!
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/.eslintrc#L13

2024-01-03 13:53 UTC, GihoKo commented on .eslintrc
> +    "react/function-component-definition": [2, { "namedComponents": ["arrow-function", "function-declaration"] }],
해당 부분 수정한 링크 입니다
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/.eslintrc#L15

2024-01-03 13:55 UTC, GihoKo commented on package.json
> +}
해당 부분 수정한 링크입니다.
// .json 파일
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/package.json#L49
// .css 파일
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/App.css#L18

2024-01-03 13:56 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +  };
해당 부분 수정한 링크입니다.
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/CardList/Card/Card.jsx#L12

2024-01-03 13:57 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +    if (passedYear >= 1) `${Math.floor(passedYear)} years ago`;
바로 윗 부분과 동일한 부분인데
해당 멘토링 반영한 부분입니다.
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/CardList/Card/Card.jsx#L12

2024-01-03 13:58 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +  const passedTimeCalculator = link => {
수정한 부분 링크입니다.
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/CardList/Card/Card.jsx#L2

2024-01-03 13:59 UTC, GihoKo commented on src/components/CardList/Card/Card.js
> +  const returnUploadDate = link => {
수정한 부분 링크입니다.
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/CardList/Card/Card.jsx#L30

2024-01-03 14:01 UTC, GihoKo commented on src/assets/images/Search.svg
수정된 부분 링크입니다.
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/CardList/Card/Card.jsx#L49C37-L49C37

그런데 public 폴더의 경우 링크 길이가 길어지는 문제가 발생하는데
멘토님께서 public 폴더에서 파일을 가져올때 어떤 방법을 사용하시나요?

2024-01-03 14:02 UTC, GihoKo commented on src/components/Header/Header.js
> +          <button className="header__btn-login">
수정한 부분 링크입니다!
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/Header/Header.jsx#L14

2024-01-03 14:03 UTC, GihoKo commented on src/components/Footer/Footer.js
> +          <a href="https://www.facebook.com" target="_blank">
수정한 부분 링크입니다!
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/Footer/Footer.jsx#L15

2024-01-03 14:06 UTC, GihoKo commented on public/index.html
> +    </body>
수정한 부분 링크입니다!
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/public/index.html#L16

2024-01-03 14:07 UTC, GihoKo commented on src/App.js
> +  };
꽤 긴 내용이라 이번주 과제하면서 리팩토링 해보겠습니다!

2024-01-03 14:07 UTC, GihoKo commented on src/App.js
> +      />
수정한 부분 링크입니다!
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/App.jsx#L54

2024-01-03 14:08 UTC, GihoKo commented on src/components/CardList/Search/Search.js
> +            <input placeholder="링크를 검색해 보세요."></input>
수정한 부분 링크입니다!
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/src/components/CardList/Search/Search.jsx#L5

2024-01-03 14:12 UTC, GihoKo commented on .eslintrc
> +  "parser": "babel-eslint",
수정한 부분 링크입니다.
https://github.com/GihoKo/3-Weekly-Mission/blob/bee6aa9415b015265782ce0353785c22686da9cf/.eslintrc#L3

2024-01-03 16:03 UTC, wonsss commented on .eslintrc
> +    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
네.  그렇다면   "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }], 라인을 제거해도 될 것 같아요.

2024-01-03 16:04 UTC, wonsss commented on .eslintrc
> +    "react/function-component-definition": [2, { "namedComponents": ["arrow-function", "function-declaration"] }],
기명함수(namedComponents) 사용 강제한 룰 같은데, 이는 번거롭긴 하지만 디버깅 시 유용하기도 합니다.
저는 그런데 유연하게 하고 싶어서 해당 룰 설정을 하는 편은 아니에요 ㅎㅎ

2024-01-03 16:05 UTC, wonsss commented on src/App.js
네 다음 미션에서 하시면 될 것 같아요!

2024-01-03 16:05 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +  };
네 코드 가독성이 좋아졌네요 👍

2024-01-03 16:06 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +    if (passedYear >= 1) `${Math.floor(passedYear)} years ago`;
작성하는 사람이 편한 것보다 나중에 읽는 사람이 읽는 데 편한 코드를 작성하는 것이 좋아요! 👍

2024-01-03 16:06 UTC, wonsss commented on src/components/CardList/Card/Card.js
> +  const returnUploadDate = link => {
좋은 이름 같네요!

2024-01-03 16:10 UTC, wonsss commented on src/assets/images/Search.svg
이 경우는 정정하여 조금 더 명확하게 설명해드릴게요. ㅎㅎ
- public은 앱 컴파일 시 사용되지 않는 asset을 넣어둡니다.
- src는 앱이 컴파일될 때 사용되는 모든 것들을 넣어둡니다. 
컴포넌트 내부에서 사용하는 이미지라면, src 폴더 내부에 assets 폴더를 만들어서 넣고 사용하는 것이 적절하겠네요.
반면, index.html 내부에서 사용하는 favicon 등은 public 폴더 내부에 함께 있는 것이 적절합니다.

2024-01-03 16:11 UTC, wonsss commented on src/App.js
> +  };
화이팅입니다~!

2024-01-03 16:15 UTC, wonsss approved these changes
기호님 수고 많으셨습니다.
다만, 리뷰 반영 시 커밋을 1개 안에 모두 넣으셨네요.
커밋은 각각 맥락에 맞게 작은 적절한 단위로 쪼개어 해주시는 것이 좋습니다.  댓글 남길 때도 해당 커밋만 링크만 복사해서 올려주시면 더 편하시기도 하구요. ㅎㅎ

꼼꼼하게 잘 반영해주셔서 PR 어프로브하겠습니다. 다음 미션에서 뵈어요 😄

2024-01-03 16:15 UTC, merged