[이시열] Week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #170
Opened 2023-12-30 15:03 UTC by siyeol97

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?

- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?

- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?

- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?

- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?

- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?

- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [ ] 커스텀 hook을 만들어 활용했나요?

## Netlify URL
https://siyeol-codeit-linkbrary.netlify.app

## 스크린샷

### pc
<img width="1457" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/c28f13a3-a943-4532-a65e-14c5d3df2563">
<img width="1458" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/ab0f0f17-4e5e-46ec-974d-f072bcb57c21">
<img width="1456" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/491b067f-168c-4f1b-813e-e3104c9173af">
<img width="1457" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/79096c7a-4a54-40f1-aaa9-feb6fedc184f">

### tablet

<img width="903" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/f6ac64d0-6a87-4d6b-a6c5-7983831478e0">

### mobile

<img width="505" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/3108d4f3-4e02-4dd6-b786-63456efb410b">

## 멘토에게

- 커스텀 훅에 대해서 더 공부해서 적용하도록 하겠습니다.
- 어느 단위로 컴포넌트로 만들지 감이 아직 안잡히는 것 같습니다.

2024-01-01 14:16 UTC, wonsss requested changes
안녕하세요. 시열님! 첫 리액트 미션을 잘 해주셨네요. 수고 많으셨습니다. 👍 
리뷰 확인 후, 각각 리뷰에 의견이나 반영 여부 등에 대한 댓글을 남겨주시길 부탁드려요. 관련하여 수정하셨으면 댓글에 해당 커밋 링크 첨부도 부탁드립니다.

그리고 PR 내용에 해당 프로젝트의 설치 및 실행 방법 에 대해 추가적으로 적어주시면 좋습니다. 😄

2024-01-01 14:16 UTC, wonsss commented on src/components/FolderInfo.jsx
> +    };
응답 데이터을 얻기 위해서 response.json()을 매번 호출하거나, 데이터를 보낼 때, HTTP 요청 헤더에 "Content-Type": "application/json"로 설정해주는 부분 및 response.ok가 아닌 경우 에러를 던지는 등의 코드가 반복되고 있습니다.
반복되는 get fetch 요청을 함수로 분리한다면, 아래와 같이 사용할 수 있습니다.

```js
async function get(host, path, body, headers = {}) {
	const url = `https://${host}/${path}`;
	const options = {
		method: "GET",
		headers: {
			"Content-Type": "application/json",
			...headers,
		},
		body: JSON.stringify(body),
	};
	const res = await fetch(url, options);
	const data = await res.json();
	if (res.ok) {
		return data;
	} else {
		throw Error(data);
	}
}
```

```js
// 사용
const getFolderInfo = async () => {
  try {
    const res = await get(
      "bootcamp-api.codeit.kr",
      "api/sample/folder"
    );
    setFolder(res.folder);
  } catch (error) {
    console.log(error);
  }
};
```

2024-01-01 14:16 UTC, wonsss commented on src/App.jsx
> +      <GlobalStyle />
GlobalStyle을 적용해주셨군요 👍

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
조건을 깔끔히 잘 작성하신 것 같습니다. 👍

다만, else if, else 문이 불필요하게 있는 것 같아요.  
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else나 else-if문을 사용하지 않아도 됩니다.

early return 패턴은 아래 참고 링크 등에서 참고해보세요.  
[https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90](https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90)

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
carculateTime 함수 이름에 오타가 있네요. (->calculateTime)

오타를 내지 않는 것도 매우 중요합니다.
VSCode 익스텐션의 도움을 받아보실 것을 추천드려요.

이름: Code Spell Checker
ID: streetsidesoftware.code-spell-checker
설명: Spelling checker for source code
버전: 3.0.1
게시자: Street Side Software
VS Marketplace 링크: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
해당 함수를 별도의 유틸 파일로 분리하시는 것도 좋을 것 같습니다.
함수의 매개변수와 리턴값이 명확하면 파일 분리가 쉽습니다.

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +      else setElapsedTime(`${timeDifferenceYears} years ago`);
함수 내에 정의된 것이 아닌 외부에서 가져온 setElapsedTime() 을 사용하여 side effect를 발생시키지 마시고, 함수가 해당 값을 return하도록 하면 어떨까요?
그리고 해당 함수를 호출하여 리턴된 값을 한번만 setElapsedTime(함수리턴값) 으로 해주면 좋을 것 같습니다.
이렇게 하면 해당 calculateTime 함수가 순수한 역할을 할 수 있게 되어 함수를 외부 파일에 분리할 수 있습니다.

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +      setFormattedCreatedAt(`${year}. ${month}. ${day}`);
이 코드는 calculateTime 함수에서 분리하여 별도의 함수로 만드는 것이 좋을 것 같아요.

2024-01-01 14:16 UTC, wonsss commented on src/css/Card.css
> +.card-container {
React 프로젝트 구조 설계를 파일의 유형에 따라 분류하신 것 같네요. 이렇게 설계하시는 것도 좋습니다. 
일반적으로, 자주 함께 변경되는 파일들을 같이 보관하는 것이 좋은 방법이에요. 이러한 원칙을 “코로케이션(colocation)“이라고 불러요.

예를 들어, Card.js와 Card.css를 Card 라는 폴더 안에 같이 두는 것도 이런 면에서 좋을 수 있을 것 같습니다. 
React는 컴포넌트 기반 라이브러리로서, 프로젝트 구조를 컴포넌트에 중점을 두고 설계하는 것이 좋습니다. 각각의 기능 또는 화면은 독립적인 컴포넌트로 나누어져야 합니다. 이는 각 컴포넌트의 재사용성을 높입니다.

협업, 확장성, 유지보수성 측면에서 어떤 방식이 좋을지 생각해보시면 좋을 것 같아요.
관련해서 리액트 공식 문서 내용을 참고해보세요. :) 
https://ko.legacy.reactjs.org/docs/faq-structure.html

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +import "../css/Card.css";
CSS 작성 방법으로 현재 `css`를 사용하셨네요.
리액트 프로그래밍을 할 때는 `컴포넌트`를 중심으로 생각하는 게 좋습니다. UI는 컴포넌트의 조합으로 표현되며, 컴포넌트 하나를 잘 만들어서 여러 곳에 재사용하는 게 좋습니다. 그렇게 하기 위해서 각 컴포넌트는 서로 간의 의존성을 최소화하면서 내부적으로는 `응집도`를 높여야 합니다.
`응집도`가 높은 컴포넌트를 작성하기 위해 `CSS 코드`도 `컴포넌트 내부`에서 관리하는 게 좋습니다.

컴포넌트 내부에서 CSS 코드를 관리하는 방법으로 `css-module`, `css-in-js` 등이 있습니다.

css-module을 사용하면 일반적인 css 파일에서 클래스명이 충돌할 수 있는 단점을 극복할 수 있습니다. 컴포넌트 단위로 스타일을 적용할 때 좋습니다.
CRA에서는 css 파일 이름을 다음과 같이 작성하면 css module이 됩니다. `{이름}.module.css`
css-module은 클래스명 정보를 담고 있는 객체를 내보내며, css 파일에서 정의한 클래스명은 style 객체의 속성 이름으로 존재합니다. 각 클래스명에 고유한 해시값이 들어 있어서 클래스 이름이 겹치지 않도록 방지합니다.
CSS Module을 적용한 아래 예시 코드를 참고해보세요.
```jsx
// CardList/CardList.module.css
.card {
   background-color: red;
}

// CardList/CardList.jsx
import styles from "./CardList.module.css";

export default function CardList({ itemList }) {
	return (
		<div className={styles.card}>
      생략
		</ul>
	);
}
```

CSS Module에 대해서는 아래 링크들을 더 참고해보시기 바랍니다.

[Adding a CSS Modules Stylesheet](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet)
[What are CSS Modules and why do we need them?](https://css-tricks.com/css-modules-part-1-need/)

이외의 CSS 작성 방법으로 css-in-js 방식은 css-module 방식을 경험해본 후 다음에 해보시길 바랍니다.

2024-01-01 14:16 UTC, wonsss commented on public/index.html
>    </body>
브라우저가 스크립트를 비활성화한 경우(chrome://settings/content/javascript) 에는 리액트 싱글페이지애플리케이션이 정상동작하지 않을 것이기 때문에, 이런 경우에 표시될 대체 메세지를 정의해두는 것도 좋습니다. 이를 위해 noscript 요소를 추가하면 됩니다.

```js
	<body>
		<noscript>You need to enable JavaScript to run this app.</noscript>
		<div id="root"></div>
	</body>
```

> HTML `<noscript>` 요소는 페이지의 스크립트 유형을 지원하지 않거나, 브라우저가 스크립트를 비활성화한 경우 보여줄 HTML 구획을 정의합니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/noscript

<img width="1294" alt="스크린샷 2024-01-01 오후 5 59 02" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/26f409d6-bd96-49c3-be25-1b635fce8bfa">

2024-01-01 14:16 UTC, wonsss commented on src/App.jsx
> +import { createGlobalStyle } from "styled-components";
styled-components 라이브러리를 설치하셨다면, 전체적인 CSS 작성 방법으로
css-in-js 방식을 사용해보시는 것도 고민해보세요 :)

2024-01-01 14:16 UTC, wonsss commented on package.json
>    "dependencies": {
사용하지 않는 라이브러리와 스크립트를 정리하셨네요. 이런 습관 너무 좋습니다. 👍

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
해당 함수 매개변수명으로 `createdAt` 을 하셨군요!
이 이름도 좋은 이름 같아요.
인자로 넘겨지는 값이 "2022-11-27T12:24:09Z" 와 같은[ ISO8601 표준](https://ko.wikipedia.org/wiki/ISO_8601) 형식의 문자열이네요.

조금 더 명시적으로 짓기 위해, 날짜만 있는 경우와 날짜와 시간까지 함께 있는 경우를 구분하고 string 타입 여부까지 구분한다면, `dateTimeString` 이라는 이름도 적합할 수 있을 것 같습니다.  그리고 해당 함수 내부 맥락에서는 created라는 이름은 불필요할 것 같아요. 

실무에서 ISO8601 표준 형식의 dateTimeString 을 자주 사용하니, 무엇인지 이해하고 계시는 것도 좋습니다.

https://262.ecma-international.org/11.0/#sec-date-time-string-format

2024-01-01 14:16 UTC, wonsss commented on src/App.jsx
> +export default function App() {
현재 라우팅을 하지 않으셨네요. 아마 미션 요구사항에 포함되지 않은 걸까요? 🤔 

react에서 싱글 페이지 애플리케이션 구현 시, `react-router-dom` 라이브러리를 설치하여 라우팅을 쉽게 구현하실 수 있습니다.

클라이언트 사이드 라우팅이라고도 하며 사용자가 요청한 URL에 따라서 이에 맞는 컴포넌트를 렌더링 해주는 것을 의미합니다. 서버에게 별다른 요청을 보내지 않고 클라이언트의 브라우저 단에서만 페이지를 이동하는 기능입니다.

예를 들어,  사용자가 `/folder` 경로의 url로 접속했을 때, 현재 구현하신 페이지를 렌더링하고 싶다면 이전처럼 `folder.html` 파일을 서버에 요청하여 다운로드 후 브라우저에서 새로고침하여 렌더링하는 것이 아니라 라우팅 설정한 코드에 의해 페이지 새로고침 없이 클라이언트의 브라우저 단에서만 페이지를 이동시킬 수 있씁니다.

예를 들어 아래와 같은 Router.jsx 파일을 작성하여 앱 전체의 라우팅을 관리하는 것입니다.

```jsx
// Router.jsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import FolderPage from "./pages/FolderPage";

export default function Router() {
	return (
		<BrowserRouter>
			<Routes>
				<Route path='/folder' element={<FolderPage />} />
			</Routes>
		</BrowserRouter>
	);
}
```


react-router-dom 버전6 사용법은 아래 블로그나 공식문서를 참고하여 시작해보세요 😄 
https://velog.io/@soryeongk/ReactRouterDomV6
https://github.com/remix-run/react-router?tab=readme-ov-file

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +      onClick={handleCardClick}
handleCardClick 함수는 매개변수로 link를 받는다고 정의하고 있지만, 실제 사용 시 인자를 전달받지 못하고 있습니다. 
또한 함수 내에서 매개변수 link를 사용하고 있지 않고, 함수 밖에 있는 linkUrl 변수를 참조하여 사용하고 있습니다. 
함수 수정이 필요할 것 같아요.

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +      onClick={handleCardClick}
그리고 클릭 이벤트 핸들러 역할이 새 페이지를 여는 것뿐이라면, 클릭 이벤트 핸들러를 넣을 필요 없고, div 태그를 a 태그(앵커태그)로 변경하고 href 속성에 linkUrl을 넣는 것이 시맨틱 태그로서 더 좋습니다. 😄

2024-01-01 14:16 UTC, wonsss commented on src/components/Card.jsx
> +          alt="noimg"
img 태그의 alt 속성에는 다음과 같은 이유로 해당 이미지를 설명하는 의미 있는 텍스트를 적어주시는 것이 좋습니다. 😄 
<img width="1213" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/70fe2c82-da3e-4a51-9209-372e5ebc7be1">
https://ko.wikipedia.org/wiki/Alt_%EC%86%8D%EC%84%B1

2024-01-01 14:16 UTC, wonsss commented on src/components/FolderArea.jsx
> +                key={link.id}
컴포넌트 리스트 항목에 link의 id라는 적절한 key 값을 넣어주셨네요 👍 
map() 호출 내부의 JSX 엘리먼트에는 항상 key가 필요합니다!
만약에 배열의 index나 랜덤한 값을 key로 넣어서는 안됩니다. 그 이유는 다음과 같고 자세한 내용은 공식문서를 참고하세요. 중요한 내용입니다. 😄 

> 각 배열 항목에 다른 항목 중에서 고유하게 식별할 수 있는 문자열 또는 숫자를 key로 지정해야 합니다.
Key는 각 컴포넌트가 어떤 배열 항목에 해당하는지 React에 알려주어 나중에 일치시킬 수 있도록 합니다. 이는 배열 항목이 정렬 등으로 인해 이동하거나 삽입되거나 삭제될 수 있는 경우 중요해집니다. key를 잘 선택하면 React가 정확히 무슨 일이 일어났는지 추론하고 DOM 트리에 올바르게 업데이트 하는데 도움이 됩니다.
https://ko.react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key

2024-01-01 14:16 UTC, wonsss commented on src/components/Footer.jsx
> +                rel="noreferrer"
a 태그의 rel에 noreferrer를 지정하셨군요. 👍 
하이퍼링크를 신뢰할 수 없을 때, rel에 필요한 속성을 지정하곤 합니다. 관련해서 참고하실 수 있는 링크 공유드립니다.
[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

2024-01-01 14:16 UTC, wonsss commented on package.json
> +    "@types/styled-components": "^5.1.34"
아직 타입스크립트를 사용하진 않으셔서 devDependencies에 @types/styled-components 는 제거하셔도 될 것 같아요.

2024-01-01 14:16 UTC, wonsss commented on src/components/FolderInfo.jsx
> +    };
더 나은 사용자경험을 위해 fetch 시 fetch의 loading과 error 상태를 관리하는 것도 좋습니다. 만드신 페이지의 새로고침을 해보시면, 네트워크 요청을 하는 잠깐 동안 fetch가 완료되지 않아서 state의 기본값이 적용되어 화면의 UI 레이아웃이 전제적으로 깨지고 있습니다. 아주 잠깐이라서 괜찮지만, 만약 네트워크 환경이 안 좋은 사용자라면 그런 문제가 더 크게 느껴질 것입니다.  
fetch 하는 동안 어떤 컴포넌트(예를 들어, 로딩스피너)를 대체하여 보여줄지 고민해보시고 적용해보시는 것도 좋습니다. 
그리고 fetch 결과 에러가 발생했을 때에도, UI에 어떻게 보여줄지도 error 상태를 관리함으로써 하실 수 있습니다.

즉, fetch의 완료 성공 상태뿐만 아니라 로딩이나 에러 상태도 고려하여 UI를 대응하는 것이 좋습니다. 나중에 react-query 라이브러리를 사용하면 이런 것들이 추상화되어 편리하게 하실 수 있으니 참고바랍니다. 😄 


```js
// 사용
const [folder, setFolder] = useState();
const [error, setError] = useState('');
const [isLoading, setIsLoading] = useState(true);

const getFolderInfo = async () => {
  try {
    const res = await get(
      "bootcamp-api.codeit.kr",
      "api/sample/folder"
    );
    setFolder(res.folder);
  } catch (error) {
    console.log(error);
    setError(error.message); // 에러
  } finally {
    setIsLoading(false); // 로딩 끝
  }
};
```

그리고 인터넷 검색해보니 fetch 의 loading, error 적용하는 것을 단계적으로 설명해둔 블로그가 있어 전달드립니다.
https://week-book.tistory.com/entry/React-fetch-%EC%82%AC%EC%9A%A9%EB%B2%95-LoadingErrorGETPOST

2024-01-01 14:16 UTC, wonsss commented on src/components/Navbar.jsx
> +        } else throw new Error("fetch error");
`else throw new Error("fetch error");` 에서 중괄호를 생략하셨군요.

if (condition) doSomething() 등과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다. 
만약 if문 중괄호가 없는데 아래와 같이 실수로 줄바꿈이 되었다면 에러가 발생합니다.
```js
if (errorResult.status === 409)
return true; 
```
이처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋기 때문에 한줄이라도 중괄호를 쓰는 코딩 스타일을 일관성있게 유지하시길 바랍니다. 😄 

추가적인 코딩스타일은 아래 문서 참고 바랍니다.
[코딩스타일](https://ko.javascript.info/coding-style)

2024-01-03 16:04 UTC, siyeol97 commented on src/components/FolderInfo.jsx
> +    };
[fix: 반복되는 fetch 함수 분리](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/283ac80039cc90a84052c03be59b37f38815d6d3)
코드를 참고하여 함수를 분리 후 적용해보았습니다.
loading과 error 상태관리는 7주차 과제에 적용해보겠습니다!

2024-01-03 16:05 UTC, siyeol97 commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
[fix: calculateTime 함수 오타 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/2f74082c53430e747ad009acc510a22526c63007)
Code Spell Checker 익스텐션을 사용해보았습니다! 편리하네요

2024-01-03 16:08 UTC, siyeol97 commented on src/components/Card.jsx
> +          alt="noimg"
[fix: card default image 파일 이름, 설명 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/d53e6af6630e3f9f03e66b7c96e0ff2ad5fb0ee2)
설명과 파일이름, 변수명을 더 명확하게 수정하였습니다!

2024-01-03 16:10 UTC, siyeol97 commented on src/components/Card.jsx
> +      setFormattedCreatedAt(`${year}. ${month}. ${day}`);
[fix: 생성일을 나타내는 함수 분리](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/f99b8867356adca554526632ebed36a802eb1d16)
별도의 함수로 분리했습니다.

2024-01-03 16:12 UTC, siyeol97 commented on src/components/Card.jsx
> +      else setElapsedTime(`${timeDifferenceYears} years ago`);
[fix: calculateTime 함수 외부 파일에 분리, 리팩터링](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/19ac654dc4035c28739faf54b9d9fc23118643fa)
calculateTime 함수를 외부 파일에 분리하고 Early Return 기법을 적용해 리팩터링 해보았습니다.
Early Return을 이런 식으로 하는게 맞나요?

2024-01-03 16:14 UTC, siyeol97 commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
[fix: createdAt, createdTime -> dateTimeString, formattedDateTime 변수 이…](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/8148cfaf13f59066038752483e7ebb725958064a)
함수 내부 맥락에 맞게 변수 이름을 수정해보았습니다.

2024-01-03 16:16 UTC, siyeol97 commented on src/css/Card.css
> +.card-container {
[chore: 프로젝트 파일 구조 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/304dc43b311c409ba8ce82ff3ce4b46910fc84d5)
참고해서 파일 구조를 변경해 보았습니다.
파일이 많아질수록 더 편리해지는것 같습니다.

2024-01-03 16:18 UTC, siyeol97 commented on public/index.html
>    </body>
[chore: noscript 요소 추가](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/79ff6a1949729324d85ad17aac329ffa3f8a5c06)
뭔지도 모르고 그냥 삭제했었네요.. 
더 신중하게 해야겠습니당

2024-01-03 16:22 UTC, siyeol97 commented on src/components/Card.jsx
> +      onClick={handleCardClick}
[fix: handleCardClick 함수 삭제, div -> a 태그로 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/ebce75b4780eca992b4da6ff6959a90617cf64ea)
필요없는 함수 삭제하고 a 태그로 바꿔서 반영했습니다!

2024-01-03 16:25 UTC, siyeol97 commented on src/components/Navbar.jsx
> +        } else throw new Error("fetch error");
무조건 생략하는게 더 좋은줄 알았는데 명시적으로 나타내는게 더 가독성이 좋군요! 참고하겠습니당!

2024-01-03 16:48 UTC, siyeol97 commented on src/components/Card.jsx
> +import "../css/Card.css";
7주차 과제에 반영해보겠습니다!

2024-01-03 16:50 UTC, siyeol97 commented on src/App.jsx
> +export default function App() {
7주차 과제에 참고하여 반영해 보겠습니다!

2024-01-03 17:31 UTC, siyeol97 commented on package.json
> +    "@types/styled-components": "^5.1.34"
[chore: prettier, eslint 설정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/170/commits/e043db71fff5b2c4c94e25f67bb657145cafc25c)
사용하지 않는것 제거하고 prettier, eslint 설정을 해봤습니다.

2024-01-03 17:33 UTC, siyeol97 commented on src/components/Footer.jsx
> +                rel="noreferrer"
참고하겠습니다!😁

2024-01-03 17:50 UTC, siyeol97 commented on src/components/FolderArea.jsx
> +                key={link.id}
넵! 참고하겠습니다!

2024-01-04 11:06 UTC, wonsss commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
문명의 혜택 좋습니다 😄

2024-01-04 11:06 UTC, wonsss commented on src/components/Card.jsx
> +      else setElapsedTime(`${timeDifferenceYears} years ago`);
네! 맞습니다. 가독성이 좋아졌네요

2024-01-04 11:07 UTC, wonsss commented on package.json
> +    "@types/styled-components": "^5.1.34"
오류도 사랑해주세요

2024-01-04 11:07 UTC, wonsss commented on src/components/Navbar.jsx
> +        } else throw new Error("fetch error");
작성하는 사람이 조금 더 고생하면, 나중에 읽는 사람이 편해집니다!

2024-01-04 11:09 UTC, wonsss commented on src/css/Card.css
> +.card-container {
좋습니다!

2024-01-04 11:10 UTC, wonsss commented on src/components/Card.jsx
> +      onClick={handleCardClick}
넵! 그리고 이제 라우터를 배우시니 참고로 말씀드릴게요.
리액트의 싱글 페이지 애플리케이션을 구현하신다면, 앵커 태그(`<a>`) 대신에 react-router-dom 라이브러리의 `<Link>` 컴포넌트를 사용하시는 것이 좋습니다.

Link는 html의 앵커 태그와 역할은 같습니다. 
하지만, 앵커 태그는 페이지를 새로고침 시키기 때문에, 싱글페이지 애플리케이션에서는 앱 내 페이지 이동할 때는 이 대신 Link 컴포넌트를 사용합니다. 

주의사항으로는 Link 컴포넌트는 Router안에서만 동작합니다.

공식문서나 관련 블로그 내용을 참고해보세요.
https://reactrouter.com/en/main/components/link

https://www.daleseo.com/react-router-basic/

2024-01-04 11:11 UTC, wonsss commented on src/components/Card.jsx
> +      setFormattedCreatedAt(`${year}. ${month}. ${day}`);
깔끔하네요

2024-01-04 11:11 UTC, wonsss commented on src/components/Card.jsx
> +    const carculateTime = (createdAt) => {
수고하셨습니다!

2024-01-04 11:11 UTC, wonsss approved these changes
LGTM

2024-01-04 11:11 UTC, merged