[박준용] Week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #172
Opened 2023-12-30 17:45 UTC by mocking-tiger

## 요구사항

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?

- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?

- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?

- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?

- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?

- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?

- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

- [ ] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

- 리액트 활용해서 페이지 구현
- api호출로 받아온 데이터 활용

## 스크린샷

배포: https://weekly-mission-part2.vercel.app/

## 멘토에게

- 어떻게든 온몸 비틀어서 하긴 했는데 이번주 과제는 솔직히 좀 버거웠습니다.
- 멘토님은 개발 공부하다가 벽 느꼈을때 어떻게 극복하셨는지 선배개발자로서의 조언을 좀 구하고 싶습니다.

2024-01-01 14:50 UTC, goldfrosch requested changes
고생하셨습니다!

전체적인 칭찬(?)이라면 폴더구조가 많이 깔끔하다고 느꼈습니다!

Footer, Header, 등 역할에 맞게 css와 js파일을 넣어 좀 깔끔하다는 인상을 받았습니다.

다만 이거는 작은 프로젝트에만 통용될 수 있겠네요...

```
src/
  components/
    Footer/
    Header/
    Section/
    Main/
    Card/
 utils/
   TimeDiffChecker/
   TodayIs/
```

정도로면 괜찮을 것 같고,
woff와 woff2는 폴더구분 없이 assets/fonts에 한번에 넣어도 문제 없어보이네요~

고생하셨고 PR 확인 부탁드립니다~

2024-01-01 14:50 UTC, goldfrosch commented on public/index.html
> +<html lang="en">
[중요도: 높음] lang ko로 바꿔주세요~

2024-01-01 14:50 UTC, goldfrosch commented on src/App.js
> +    </div>
[중요도: 중간]
불필요한 div는 제거해도 괜찮습니다.
```suggestion
    <>
      <Header />
      <Main />
      <Section />
      <Footer />
    </>
```
<></>는 Fragment로 React에서 하나의 컴포넌트 return할 때 하나의 큰 element로 return해야하는데 준용님 코드처럼 한번에 하나의 큰 element를 return하지 못할 때 이 Fragment로 묶어 return하게 해줄 수 있습니다.

Fragment는 실제 html에 보여줄 때 해당 태그를 제거해줍니다.

2024-01-01 14:50 UTC, goldfrosch commented on src/Footer/Footer.css
> +footer > div > div {
[중요도: 높음] 원래 개인적으로 css는 리뷰를 잘 안하지만 이런 경우는 위험할 수 있어 PR을 남깁니다.
이런 element 종속되는 element의 style은 element의 구조가 변경될 때 매우 까다롭게 될 수 있습니다. (실제로 매우 까다롭게 처리했던 기억이 많이 나네요 ㅎㅎ;)

보통 스프린터분들이 귀찮아서 이렇게 element 종속되게 처리를 많이 하시는데 귀찮으시더라도 className을 지정해주는게 도움이 됩니다. 현업에서는 이렇게 작업하시면 매우 위험한 코드가 될 수 있어요

2024-01-01 14:50 UTC, goldfrosch commented on src/Header/Header.js
> +        "https://bootcamp-api.codeit.kr/api/sample/user"
이런 API 고유 주소의 경우는 상수화 해서 한 곳에 보관해 import를 받아 사용하는 것을 추천드립니다.
상수화의 주요 목적은 휴먼 에러(오타) 방지를 위함입니다~
```suggestion
    const API_BASE_URL = 'https://bootcamp-api.codeit.kr'; // 이건 상수 파일로 따로 뺏다고 가정

        `${API_BASE_URL}/api/sample/user`
```

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Card/Card.js
> +const defalutValue = {
[중요도: 중간] 이런 변하지 않는 상수의 경우는 UPPER_SNAKE_CASE로 해주세요. 이름도 조금 구체적으로 적으면 좋겠군요
```suggestion
const DEFAULT_CARD_VALUE = {
```

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Card/Card.js
> +  uploadDate = defalutValue.uploadDate,
기본값 설정 매우 좋습니다. 공부 열심히 하셨군요!

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Card/Card.js
> +          className={isHover ? "growImg" : ""}
[중요도: 중간] 이런 삼항 연산자로 불필요한 ""를 적는 것을 방지하기 위해 classNames라는 라이브러리가 존재하니 시간이 남으신다면 찾아보시면 좋겠군요!

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Card/Card.js
> +        <h6>{uploadDate}</h6>
시멘틱 마크업 챙기는 것 좋습니다

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Section.js
> +  };
[중요도: 높음] 여기서 Promise를 사용한 이유가 뭘까요? Promise의 정확한 역할이 무엇일까요?

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Section.js
> +      let timeDiff = today - linkedDay;
[중요도: 중간] 이런 선언하고 변하지 않는 값이라면 let보다는 const가 좋아보이네요

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/Section.js
> +        </a>
[중요도: 높음]이렇게 API를 통해서 전달해준 데이터를 전부 뿌려주려면 Array.map이라는 함수를 사용하셔야 합니다.

```suggestion
       {cardInfo.map((cardData, index) => (
         <a rel="noreferrer" href={cardData.url} target={"_blank"} key={index}>
            <Card
              style={cardData.imageSource !== undefined ? style : logoStyle}
              image={cardData.imageSource}
              createdAt={timeDiffChecker(timeDiffs[index])}
              description={cardData.description}
              uploadDate={todayIs()}
            />
        </a>
       )}
```
형식으로 쓰면 좋습니다.

map을 사용할 때 가장 상위 element에 key를 사용하는 이유와 key의 값에는 단순히 숫자(index)가 들어가면 안좋습니다. 그 이유를 찾아보시면 더 도움이 될 것 같습니다!
제가 index를 쓴건 데이터가 정확하게 어떻게 오는지 몰라서 우선 이렇게 사용했습니다 ㅎㅎ

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/TimeDiffChecker/TimeDiffChecker.js
> +  const mon = day * 30;
[중요도: 중간]이거는 바로 윗 scope로 올리고 UPPER_SNAKE_CASE로 바꾸면 좋겠군요.
```suggestion

const SECOND = 1; // s는 뺐습니다. 복수가 아니니까요!
const MINUTE = SECOND * 60;
const HOUR = MINUTE * 60;
const DAY = HOUR * 24;
const MONTH = DAY * 30; // 정확하게 이름을 적으면 좋습니다, 그리고 월은 30일, 31일, 28일이 있긴 하나 이 부분은 현재 계산하기 어려워서 이렇게 처리했다라고 인지하고 있겠습니다 ㅎㅎ
function timeDiffChecker(num) {
```

2024-01-01 14:50 UTC, goldfrosch commented on src/Section/TodayIs/TodayIs.js
> +}
[중요도: 높음] let today를 밖으로 꺼내서 사용하면 이미 한번 선언되었기 때문에 today의 값이 계속해서 갱신이 안됩니다.

const test1 = () => {
    let today =new Date();
    return today;
}

test1(); // 시간이 지날 때 마다 새로 호출하면 그 시간에 맞춘 값을 return 해줌.

let today = new Date();
function todayIs() {
  return today.toLocaleDateString();
}

todayIs() => 월, 일, 년만 나오지만 실제로 시, 분, 초까지 체크하게 되면 값이 바뀌지 않게됨.

2024-01-02 03:06 UTC, mocking-tiger commented on src/Section/Section.js
> +  };
> [중요도: 높음] 여기서 Promise를 사용한 이유가 뭘까요? Promise의 정확한 역할이 무엇일까요?

제가 이번 과제 하면서 제일 힘들었던 부분인데,
각 링크의 createdAt 값을 받아오는 함수가 비동기라 저 데이터들을 담는 배열(timeDiffs)에 담기는 값이 새로고침할때마다 오락가락하길래 fetch함수가 끝까지 실행될때까지 기다렸다가 배열에 담으라고 사용해봤습니다!
혹시 더 권장되는 방법이 있다면 가르쳐주시면 적용해보겠습니다!

2024-01-02 04:51 UTC, mocking-tiger commented on src/Section/Section.js
> +  };
혹시나 하고 async/await, Promise.allSettled 지우고 해봤는데 배열에 제대로 담기네요 ,,
코드 수정했습니다.
그런데 과제 할때는 console.log(timeDiffs)했을때 배열에 담기는 값이 뒤죽박죽이길래 비동기실행이 끝나기전에
for문이 실행돼서 그런가보다 하고 저 함수에도 async를 썼던건데 왜 오늘 지워도 정상적으로 되는지는 모르겠습니다 ㅠ

2024-01-02 11:26 UTC, goldfrosch requested changes
추가 comment 확인 부탁드립니다.

2024-01-02 11:26 UTC, goldfrosch commented on src/Section/Section.js
> +  let [cardInfo, setCardInfo] = useState();
[중요도: 높음] 이거는 지금 봤네요;; state를 let으로 선언한 이유가 뭘까요?

2024-01-02 11:26 UTC, goldfrosch commented on src/Section/Section.js
> +  };
음... 이 부분은 멘토링 시간 때 더 다루면 좋을 것 같네요. 설명하기는 좀 길겠네요;
일단 제가 comments를 남긴 이유는 여기서 Promise가 필요하지 않아서 남긴 부분이라 이거는 추후 자세히 살펴보죠.

2024-01-03 02:33 UTC, mocking-tiger commented on src/Section/Section.js
> +  let [cardInfo, setCardInfo] = useState();
> [중요도: 높음] 이거는 지금 봤네요;; state를 let으로 선언한 이유가 뭘까요?

useState에서  setter가 변수를 재할당 한다고 생각해서 let을 사용했는데 검색해보니까 const로 쓰는게 맞다고 해서 수정했습니다! 검색한 글에서 클로저에 대해 설명하던데 제가 아직 잘 모르는 개념이라 더 공부하겠습니다!

2024-01-03 03:12 UTC, goldfrosch commented on src/Section/Section.js
> +  let [cardInfo, setCardInfo] = useState();
좋습니다. useState는 클로저라는 개념을 사용해 setState를 이용해서만 값을 변경하고 리렌더링이 되게 설정되어있습니다.

객체지향 언어들에서도 값을 직접 변하지 않게 하기 위한 "캡슐화"라는 개념이 존재합니다. 직접 변경을 막는 방법이죠. 그 개념이랑 같이 알아본다면 더 도움이 될 것 같습니다 :)

2024-01-03 03:26 UTC, goldfrosch approved these changes
고생하셨습니다. approve and merge 진행합니다

2024-01-03 03:26 UTC, merged