[백진영] Week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #181
Opened 2023-12-31 16:42 UTC by jinyoung1018

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [x] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

-
-

## 스크린샷

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-03 03:31 UTC, goldfrosch requested changes
고생했습니다.
밑의 comments들을 확인 부탁드립니다~
전체적인 피드백이라면...
폴더구조에 대해 신경쓰는 것도 괜찮아 보입니다.

현재는 /api, /CardList, /Folder...으로 되어있는데 
기능단위인
src/
  api/
  component/
     CardList/
     Folder/
     
등의 형식으로 해보는 것도 방법이죠.

2024-01-03 03:31 UTC, goldfrosch commented on package.json
> +    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
[중요도: 중간] babel을 사용하셨군요. 바벨과 이 라이브러리를 도입한 이유가 궁금합니다!

2024-01-03 03:31 UTC, goldfrosch commented on src/App.js
> +      <Footer></Footer>
```suggestion
      <Header /r>
      <Folder />
      <ContentsArea />
      <Footer />
```

[중요도: 중간] Header, Footer의 경우도 children 영역에 아무것도 들어가지 않는다면 바로 닫아도 문제 없어보입니다.

2024-01-03 03:31 UTC, goldfrosch commented on src/CardList/CardList.js
> +  console.log(cardList);
[중요도: 높음] console.log는 개발환경 전용이라면 빼주세요.
console.log는 실제 환경에 배포했을 때 단점이라면
- 특정 데이터를 유저한테도 노출시켜 버림 (단순 API라면 문제없지만 보안 데이터가 들어있는 곳이라면 문제가 될 수 있음.)
- 메모리를 잡아먹습니다. 놀랍게도 console.log도 메모리를 잡아먹는데 일조합니다.

2024-01-03 03:31 UTC, goldfrosch commented on src/CardList/CardList.js
> +      {cardList.map((it) => (
[중요도: 중간] map에서 사용하는 lambda함수 인자의 it은 이름을 변경하는게 좋아보입니다.
뭐든지 변수명은 항상 가독성있게 짤 필요가 있어요

2024-01-03 03:31 UTC, goldfrosch commented on src/CardList/CardList.js
> +              <h1 className="createdDate">{createDate(it.createdAt)}</h1>
[중요도: 높음] 시멘틱 마크업 기준으로는 맞지 않는 규약의 element같네요. h1는 가장 큰 주제, h2는 부가 주제에 해당된답니다.
전부 P태그로 하는게 더 좋아보이네요. 설명관련이니

2024-01-03 03:31 UTC, goldfrosch commented on src/ContentsArea/CardContainer.js
> +    console.log(card.folder.links[0].createdAt);
[중요도: 높음] console.log 빼주세요... 테스트를 위함인 것은 이해하나 실제 PR에 console.log를 올리는 것은 위험하다고 봅니다.

2024-01-03 03:31 UTC, goldfrosch commented on src/ContentsArea/ContentsArea.js
> +import CardContainer from "./CardContainer.js";
[중요도: 높음] 본인이 지정한 폴더 컨벤션에 맞는 행동은 아닌 것 같네요...
하나의 디렉토리에 하나의 기능 파일이 들어가는 것이라면 그렇게 맞추는게 더 좋아보입니다.
```suggestion
import CardContainer from "../CardContainer/CardContainer.js";
```

2024-01-03 03:31 UTC, goldfrosch commented on src/Footer/Footer.js
> +            <img src={process.env.PUBLIC_URL + `/assets/icons_instagram.png`} />
[중요도: 높음] env의 사용을 시도해보셨군요...! env는 무엇이며 env를 여기서 사용한 이유는 뭘까요?

2024-01-03 03:31 UTC, goldfrosch commented on src/api/api.js
> +// };
[중요도: 중간] 주석 제거해주세요

2024-01-03 03:31 UTC, goldfrosch commented on src/api/api.js
> +  const res = await fetch("https://bootcamp-api.codeit.kr/api/sample/user");
```suggestion
const API_BASE_URL = 'https://bootcamp-api.codeit.kr' // 최상단에 선언하기
  const res = await fetch(`${API_BASE_URL }/api/sample/user`);
```

같은 식으로 baseUrl을 미리 선언해주는게 오타 방지 및 재사용에도 도움이 될겁니다 참고 부탁드려요~

2024-01-03 03:31 UTC, goldfrosch commented on src/SearchArea/SearchArea.js
> +        src={process.env.PUBLIC_URL + `/assets/Search.png`}
[중요도: 중간] img 태그에 alt attribute 넣어주세요!

2024-01-03 03:31 UTC, goldfrosch commented on src/CardList/CardList.js
> +  };
[중요도: 중간] 이런것들은 util 함수 즉 별도의 파일로 뺴면 좋겠네요.
[중요도: 중간] https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188#discussion_r1439413423 해당 PR로 코드 개선건 제안드립니다.

2024-01-04 05:13 UTC, jinyoung1018 commented on package.json
> +    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
제가 따로 설치한건 아니지만 babel은 최신 버전의 자바스크립트를 구형 버전의 자바스크립트로 변환시켜주는 것으로 알고있습니다!

2024-01-04 05:13 UTC, jinyoung1018 commented on src/App.js
> +      <Footer></Footer>
1a14c7ddfb00854fb586e81305ed21b0da07aa30 넵! 수정하였습니다!

2024-01-04 05:15 UTC, jinyoung1018 commented on src/CardList/CardList.js
> +  console.log(cardList);
4812229cc57630c4da80e93c40967895b76e571e 데스트용으로 작성한건데 제거하는걸 깜빡했네요ㅠㅠ 다음부터 더 주의하도록 하겠습니다!  console.log를 실제 환경에 배포했을 때 단점에 대해서도 알게되었습니다. 감사합니다!

2024-01-04 05:15 UTC, jinyoung1018 commented on src/CardList/CardList.js
> +      {cardList.map((it) => (
f2df8b0736e06f6f214e0aa6233a036a467fc3c2 변경하였습니다!

2024-01-04 05:16 UTC, jinyoung1018 commented on src/CardList/CardList.js
> +              <h1 className="createdDate">{createDate(it.createdAt)}</h1>
a2780eb76e72abfa9db1ef6e7ba64cff0c02ce4a 이 부분도  더 주의하도록 하겠습니다! 변경 완료하였습니다!

2024-01-04 05:17 UTC, jinyoung1018 commented on src/ContentsArea/CardContainer.js
> +    console.log(card.folder.links[0].createdAt);
d12fbcaa749fad5ca229309a741be2ec1b05a15a 넵! 제거하였습니다!

2024-01-04 05:18 UTC, jinyoung1018 commented on src/ContentsArea/ContentsArea.js
> +import CardContainer from "./CardContainer.js";
d879a4c982c85a8f2a4c6c7160e9e91f25232f50 폴더 구조 변경하였습니다!

2024-01-04 05:22 UTC, jinyoung1018 commented on src/Footer/Footer.js
> +            <img src={process.env.PUBLIC_URL + `/assets/icons_instagram.png`} />
src 경로를 지정할 때, public 내의 절대 경로를 이용해야 나중에 사이트를 배포할 때 오류가 나지 않기 때문에 process.env.PUBLIC_URL 를 사용하는 것으로 알고있습니다!

2024-01-04 05:23 UTC, jinyoung1018 commented on src/api/api.js
> +// };
441bd6a58078e836e6e04702abb77f7d26f52c5e 제거하였습니다!

2024-01-04 05:24 UTC, jinyoung1018 commented on src/api/api.js
> +  const res = await fetch("https://bootcamp-api.codeit.kr/api/sample/user");
009eaf98bd9f2f0cd09c1ccf587efa7e843e48f7 수정하였습니다! 오타도 방지되고 재사용하기 편리해서 좋은 것 같습니다!

2024-01-04 05:25 UTC, jinyoung1018 commented on src/SearchArea/SearchArea.js
> +        src={process.env.PUBLIC_URL + `/assets/Search.png`}
2e0ba6312b9e65bf0fab55987eda4877918c4085 alt속성을 사용해야 하는 이유를 한번 더 복습하고 수정하였습니다!

2024-01-04 05:26 UTC, jinyoung1018 commented on src/CardList/CardList.js
> +  };
fe0b7c74538a2eb32859c76598b1f8baf8559151 알려주신 코드 참고하여 수정하고 따로 분리하였습니다!

2024-01-04 13:39 UTC, goldfrosch commented on package.json
> +    "@babel/plugin-proposal-private-property-in-object": "^7.21.11"
왜 구형버전으로 변환을 해줘야하는지 알아보시면 좋을 것 같아요!

2024-01-04 13:40 UTC, goldfrosch commented on src/Footer/Footer.js
> +            <img src={process.env.PUBLIC_URL + `/assets/icons_instagram.png`} />
조금 얘기가 다를 것 같네요.
만약 절대경로로 설정을 한다고 하더라도 상수를 하나 선언 후 import해서 사용해도 무방할 것 같아보입니다.

.env의 존재 이유에 대해 알아보심 도움이 될 것 같으니 참고해주세요

2024-01-04 13:41 UTC, goldfrosch approved these changes
고생하셨습니다. 우선 approve and merge 진행하겠습니다.

.env에 대해 조금 더 알아봐주세요!

2024-01-04 13:41 UTC, merged