Part2 박지용 week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #185
Opened 2024-01-01 06:53 UTC by jiyong0106

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?

- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?

- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?

- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?

- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?

- [ ] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?

- [ ] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [ ] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

- 반응형 못만들었습니다..죄송합니다.  조금씩 추가해보겠습니다. 
- useEffect를 async  함수 선언 전에 사용하는 코드랑 선언 후 함수 호출하기 직전에 사용하는 것 차이가 일단 렌더링이 2번 /  1번 되는 것 같은데 성능 및 개발자의 취향에 따라 사용하는 방법이 다른건가요? 
- 전체적으로 뭔가 미흡하지만 일단pr올려보겠습니다 ㅠㅠ
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-03 14:41 UTC, goldfrosch requested changes
고생 많으셨습니다. 늦어서 우선 죄송합니다. 처리해야할 것들도 많았고.. 어쩌다보니 밀렸네요 (변명이 됬네요...) 추가 확인 comments를 남겨드리니 확인 부탁드립니다!

2024-01-03 14:41 UTC, goldfrosch commented on src/Api.js
> +export{UserFolderData, UserIdData}
[중요도: 중간] 
```suggestion
export async function UserFolderData() {
  const response = await fetch("https://bootcamp-api.codeit.kr/api/sample/folder" );
  const data = await response.json();
  return data;
}

export async function UserIdData() {
  const response = await fetch("https://bootcamp-api.codeit.kr/api/sample/user");
  const data = await response.json();
  return data;
}

```
굳이 마지막에 export를 적을 필요는 없습니다. 이 안의 코드들이 많아지면 많아질 수록 함수 하나 만들고 밑에 적기 귀찮기도 하구요... 함수에 직접 export하는 방법도 괜찮으니 추천드립니다.

2024-01-03 14:41 UTC, goldfrosch commented on src/Api.js
> +  const response = await fetch("https://bootcamp-api.codeit.kr/api/sample/folder" );
```suggestion
  const API_BASE_URL = 'https://bootcamp-api.codeit.kr'; // 함수밖으로 꺼내 사용하세요.
  const response = await fetch(`${API_BASE_URL}/api/sample/folder` );
```
[중요도: 중간] 이런 형식으로 쓰면 API 선언할 때 오타를 최소화하면서도 불필요하게 적을 것들이 적어질겁니다 ㅎㅎ

2024-01-03 14:41 UTC, goldfrosch commented on src/Api.js
> +import React from 'react'
[중요도: 높음] 이곳에 React를 import한 이유가 뭘까요?

2024-01-03 14:41 UTC, goldfrosch commented on src/Footer/Footer.js
> +        <li>
ul, li 사용 좋습니다 :) 시멘틱 마크업의 올바른 사용법 중 하나죠

2024-01-03 14:41 UTC, goldfrosch commented on src/Header/Bookmark.js
> +    {folderData && folderData.owner && ( // folderData가 있고, folderData 안에 owner가 있으면
[중요도: 중간]
```suggestion
    {folderData?.owner &&
```
주석을 적어주셔서 더 빠르게 파악이 됬네요.
optionalChaining이라는 것을 사용한다면 굳이 folderData가 있는지 그리고 folderData의 owner가 있는지를 축약해서 사용할 수 있습니다!

2024-01-03 14:41 UTC, goldfrosch commented on src/shared.js
> +};
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188#discussion_r1439413423
[중요도: 중간] 설명은 다른분의 PR로 대체합니다...!

2024-01-03 14:42 UTC, goldfrosch commented
Q. useEffect를 async 함수 선언 전에 사용하는 코드랑 선언 후 함수 호출하기 직전에 사용하는 것 차이가 일단 렌더링이 2번 / 1번 되는 것 같은데 성능 및 개발자의 취향에 따라 사용하는 방법이 다른건가요?

A. 아마 그것은 React 18 그리고 StrictMode를 사용해서 그럴겁니다. React 18 디버깅 환경에서 더 정확한 테스트를 위해 useEffect를 두번 실행시키는 이슈가 있으니 그 부분을 확인하면 될 것 같습니다!

2024-01-04 07:53 UTC, jiyong0106 commented on src/Api.js
> +export{UserFolderData, UserIdData}
공부하면서 함수를 한번에 모아서 export 하는 방법이 깔끔하다 생각했는데 멘토님 말씀대로 코드가 많아지면 번거로울 수 있다고 생각을 못했습니다.
수정했습니다!
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/185/commits/d02f98406d5fd3078bd1d85afa5a74a77c1c332d

2024-01-04 08:05 UTC, jiyong0106 commented on src/Api.js
> +  const response = await fetch("https://bootcamp-api.codeit.kr/api/sample/folder" );
url 공통적인 부분을 따로 상수로 만들어 사용하면  가독성도 좋은 것 같고 오타를 줄일 수 있어 좋은 것 같습니다. 
감사합니다!
수정했습니다 https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/185/commits/9be977f00b48bf2d8b022cbe74baed059fe1e33b

const folderData = "https://bootcamp-api.codeit.kr/api/sample/folder"
export async function UserFolderData() {
  const response = await fetch(folderData());
  const data = await response.json();
  return data;
}
이런식으로 url전체를 함수 밖에서 변수로 선언해서 사용하는 것은 괜찮을까요?

2024-01-04 08:17 UTC, jiyong0106 commented on src/Api.js
> +import React from 'react'
컴포넌트 만들 때마다 함수형 컴포넌트 단축키 rfc를  무지성으로 사용하다보니 신경을 안썼습니다.. 멘토님 리뷰를 보고 찾아보니 react로 작성한 코드를 브라우저가 읽을 수 있도록 변환해주는 건데  react 17버전부터는  JSX transformer가 JSX를 React 요소로 변환하는 작업을 거치기 때문에 모든 컴포넌트에 작성하지 않아도 된다고 하네요... 공부하고 사용하겠습니다!

2024-01-04 08:29 UTC, jiyong0106 commented on src/Header/Bookmark.js
> +    {folderData && folderData.owner && ( // folderData가 있고, folderData 안에 owner가 있으면
optionalChaining... 리마인드 감사합니다!!https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/185/commits/12de3aa04b5f4b42a8ef6a6f39d73781c0d142bb

2024-01-04 13:44 UTC, goldfrosch commented on src/Api.js
> +  const response = await fetch("https://bootcamp-api.codeit.kr/api/sample/folder" );
저는 권장하지 않습니다! 그러면 API 하나당 하나의 상수를 선언해서 사용해야하는데 재사용하지 않을 상수를 굳이 선언하는 이유는 없을 것 같아요.

2024-01-04 13:44 UTC, goldfrosch commented on src/Api.js
> +import React from 'react'
공부 열심히 하셨군요 좋습니다

2024-01-04 13:44 UTC, goldfrosch approved these changes
고생하셨습니다. approve and merge 진행하겠습니다.

2024-01-04 13:45 UTC, merged