6주차과제
codeit-bootcamp-frontend/3-Weekly-Mission pull request #186
Opened 2024-01-01 11:17 UTC by yunsunglee2

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?

- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?

- [ ] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?

- [ ] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?

- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?

- [ ] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?

- [ ] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [ ]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

- 함수안에 있는 fetch를 통해 받아온 결과값을 반환값으로 받아와 setState의 인자로 전달해주고 싶은데 잘 안되네여.. 그래서 fetch가 들어있는 함수에 setState를 해주었는데 좋은 방법인지 모르겠습니다. 
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-02 12:57 UTC, goldfrosch requested changes
고생하셨습니다.

React를 익히는 과정이 매우 어렵고... 힘들죠... 이해합니다.
comment가 적은 이유는 미완성이기에 최대한 코어한 부분 위주로 적었습니다.

미완성이라 추가 개발을 하실지는 모르겠지만 중요도: 매우 높음은 필히 필히 수정 부탁드립니다.
고생하셨습니다!

2024-01-02 12:57 UTC, goldfrosch commented on src/header/Account.js
> +        <Button text={login} onClick={login==='로그인' ? handleLogin : handleLogout}/>
```suggestion
  const [isLogin, setIsLogin] = useState(false);

  const handleLogin = () => {
    fetch(url)
    .then((response) => response.json())
    .then((result) => {
      setInfo(result['email']);
    })
      setImgsrc(imgSrc);
      setIsLogin(true);
  }
  const handleLogout = () => {
      setInfo('');
      setImgsrc('');
      setIsLogin(false);
  }
  return (
    <div className="Account">
        <AccountImage value={imgsrc} /> 
        <AccountEmail content={info}/>
        <Button text={isLogin ? '로그인' : '로그아웃'} onClick={isLogin ? handleLogin : handleLogout}/>
```
[중요도: 높음] 개인적으로는 login의 title string 보다는 isLogin(boolean)을 써서 로그인 여부를 검증하고 그 값을 밑에 활용하는게 더 좋아보이네요. 타이틀이 아주 만약에 로그인말고 login으로 바꿔주세요 할 때 관련 코드를 다 바꿔야할 수 있으니까요. 무엇보다 로그인이 된건지 안된건지 더 확실하게 보이니까요

검증은 boolean으로 state로 저장하고, 타이틀은 view에서만 쓰는게 좋아보입니다.

2024-01-02 12:57 UTC, goldfrosch commented on src/header/Header.js
> +const url = 'https://bootcamp-api.codeit.kr/api/sample/folder';
[중요도: 중간] 상수는 UPPER_SNAKE_CASE를 사용하는게 가독성이 좋습니다. (무엇보다 개발자 사이의 국룰이기도 하죠...)
[중요도: 높음] 변수의 이름은 최대한 구체적으로 적는게 좋습니다.
url -> API_BASE_URL

2024-01-02 12:57 UTC, goldfrosch commented on src/main/MainFileTimeAgo.js
> +  }
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188#discussion_r1439413423

다 적기는 힘들어... 여기로 대체하겠습니다.

2024-01-02 12:57 UTC, goldfrosch commented on src/main/Main.js
> +          <MainFile value="image9" onClick={handleClick} i={8}/>
[중요도: 매우높음]
이거는 구조에 문제가 있어 수정이 필요합니다.
밑의 MainFile에도 추가로 적을 예정입니다만..

1. 배열의 값을 임의로 갯수를 정해 뿌린다. (API 의존이 있는 경우에 이렇게 처리하는 것은 매우 안좋은 패턴입니다)
- API를 Main.js로 호출하고 Array.map함수를 이용해 배열로 뿌려주는게 좋겠네요.
2. i의 의미는 아마 컴포넌트마다 호출할 때의 번호이겠지만... i라는 변수명은 좋은 변수명은 아닌 것 같네요.

2024-01-02 12:57 UTC, goldfrosch commented on src/main/MainFile.js
> +  getInfo(i);
[중요도: 매우높음] 위의 Main.js의 PR에서 이어가보겠습니다.
이렇게 사용하게 되면 API가 MainFile컴포넌트의 갯수만큼 호출됩니다. 매우 불필요한 호출 수죠...
페이지에서 호출하고 props로 response의 값을 가져와 사용하셔야합니다.

이부분은 필히 수정 부탁드립니다.

2024-01-02 13:02 UTC, goldfrosch commented
Q. 함수안에 있는 fetch를 통해 받아온 결과값을 반환값으로 받아와 setState의 인자로 전달해주고 싶은데 잘 안되네여.. 그래서 fetch가 들어있는 함수에 setState를 해주었는데 좋은 방법인지 모르겠습니다.

A. 사실 뭐... 방법이 있지는 않죠. 순수 React를 쓰시는 분들의 고민이긴합니다. 아마 setState인자로 줬을 때 안되는 것은 setState의 값에 객체, 배열을 넣었을 때 발생할 수 도 있는 이슈입니다. 이 부분은 멘토링 시간에 조금 더 구체적으로 설명드릴 수 있겠네요 (멘토링 전에 사전 질문으로 꼭 적어주세요 ㅎㅎ...)
state안에 server response의 값을 저장하는 경우는 피치못하긴 합니다. 하지만 불편하죠...보기도? 그래서 현업에서는 react-query를 사용해 server state(server response) 를 쉽게 관리하곤 합니다. 참고부탁드립니다.

2024-01-05 04:42 UTC, yunsunglee2 commented on src/header/Account.js
> +        <Button text={login} onClick={login==='로그인' ? handleLogin : handleLogout}/>
수정했습다. 1cea9f27c1448a60713dca83efc26e671a7cf417

2024-01-05 04:43 UTC, yunsunglee2 commented on src/header/Header.js
> +const url = 'https://bootcamp-api.codeit.kr/api/sample/folder';
수정했습니다.
a19d3199d2ca2b258c444514445f3769c08fa394

2024-01-05 04:43 UTC, yunsunglee2 commented on src/main/MainFileTimeAgo.js
> +  }
수정했습니다.
92394fa01a45b563a0942dc83a9f409d2a2d72d9

2024-01-05 04:44 UTC, yunsunglee2 commented on src/main/Main.js
> +          <MainFile value="image9" onClick={handleClick} i={8}/>
수정했습니다. 
8a31d888c2f6c274cd5dbf50f3e75bb6c27ac116

2024-01-05 04:45 UTC, yunsunglee2 commented on src/main/MainFile.js
> +  getInfo(i);
수정했습니다! 위 커밋과 동일합니다.

2024-01-05 09:50 UTC, goldfrosch approved these changes
고생하셨습니다! approve and merge 진행하겠습니다.

2024-01-05 09:50 UTC, merged