[윤해용] Week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #188
Opened 2024-01-01 20:00 UTC by haeyong9701

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [ ] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

- PC, Tablet, Mobile 디자인에 해당하는 링크 공유 페이지 생성

## 스크린샷

![스크린샷 2024-01-02 오전 4 53 15](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/72595163/84b9cdd3-4275-4ac1-a4d4-4ad666d46715)

## 멘토에게

-

2024-01-02 12:40 UTC, goldfrosch requested changes
고생하셨습니다.
전체적인 피드백 드립니다.
1. 글로벌 스타일 관련들을 styles 디렉토리에 뺀 부분은 잘하셨습니다.
2. 그 외의 폴더구조 관리도 괜찮네요.

추가 필요 피드백은 comment로 남기니 확인 부탁드립니다.

2024-01-02 12:40 UTC, goldfrosch commented on src/components/FolderLinks/index.js
> +};
[중요도: 높음] 이 함수는 FolderLinks안에 종속된 것 처럼 보이는데 컴포넌트 밖으로 뺀 이유가 있을까요?

2024-01-02 12:40 UTC, goldfrosch commented on src/components/FolderLinks/index.js
> +      </div>
[중요도: 중간] <></>가 없어도 되는 것 같아보이네요.
불필요한 fragment는 없애는게 좋아보입니다.

2024-01-02 12:40 UTC, goldfrosch commented on src/index.js
> -  <React.StrictMode>
[중요도: 중간] StrictMode는 뭐고 없앤 이유는 뭔가요?

2024-01-02 12:40 UTC, goldfrosch commented on src/api.js
> +const api = "https://bootcamp-api.codeit.kr/api";
[중요도: 낮음] 상수화의 시도는 매우 좋습니다!
다만 상수의 경우는 UPPER_SNAKE_CASE를 적는게 좋습니다.
const API_BASE_URL = ~~로하면 더 좋겠죠~
(_BASE_URL)은 제가 추가한 이름으로 상수명은 최대한 구체적인게 더 좋습니다~

2024-01-02 12:40 UTC, goldfrosch commented on src/App.js
> +      setFolderObj(folderBody);
```suggestion
    try {
      setLoadingError(null);
      const userBody = await getSampleUser();
      const folderBody = await getSampleFolder();
      setUser(userBody);
      setFolderObj(folderBody);
```
가 더 좋아보이네요. 굳이 let으로 위에 선언하고 값을 변경할 필요는 없어 보입니다.

2024-01-02 12:40 UTC, goldfrosch commented on public/index.html
>  <html lang="en">
[중요도: 중간] lang 바꿔주세요~ ko로

2024-01-02 12:40 UTC, goldfrosch commented on src/utils.js
> +  }
```suggestion
  const SECOND = 1000;
  const MINUTE = SECOND * 60;
  const HOUR = MINUTE * 60;
  const DAY = HOUR * 24;
  const MONTH = DAY * 30 // 사실 2월은 28일까지 있고, 31일까지 있는 월도 있지만... 임의이실 것 같으니 30으로 고정하겠습니다.
  const YEAR = 365 * DAY:
  
  const diffMin = Math.floor(diff / (60 * 1000));
  const diffHour = Math.floor(diff / (60 * 60 * 1000));
  const diffDate = Math.floor(diff / (24 * 60 * 60 * 1000));
  const diffMonth = Math.floor(diff / (30 * 24 * 60 * 60 * 1000));
  const diffYear = Math.floor(diff / (365 * 24 * 60 * 60 * 1000));
 
 // seconds도 있음 좋겠어 보여 임의로 추가했습니다. 참고만 하세요.
  if (diff < MINUTE) {
    return `${diffMin} second${diff <SECOND * 2 ? '' : 's'} ago`;
  }
  if (diff < HOUR) {
    return `${diffMin} minute${diff < MINUTE * 2 ? '' : 's'} ago`;
  }
  if (diff < DAY) {
    return `${diffHour} hour${diff < HOUR * 2 ? '' : 's'} ago`;
  }
  if (diff < MONTH) {
    return `${diffDate} day${diff < DAY * 2 ? '' : 's'} ago`;
  }
  if (diff < YEAR) {
    return `${diffMonth} month${diff < 2 * MONTH ? '' : 's' } ago`;
  }
  return `${diffYear} year${diff < YEAR * 2 ? '' : 's'} ago`;
```

를 제안드립니다.
이렇게 사용하면 if문들도 훨씬 간결해지고 비교는 diff만 이용해서 하니 부담도 적으며 무엇보다 상수화를 통해 해당 if문을 조금 더 편하게 이해하는데 도움이 될겁니다.

2024-01-02 13:00 UTC, goldfrosch commented
Q. className prop을 부모 컴포넌트에서 받고, style 코드를 작성할 때 부모의 style.css 파일에 작성하는게 맞는지 자식의 style.css 파일에 작성하는게 맞는지 아직 헷갈립니다.

A. 사실 둘은 분리되어서 처리되어야하는 것이 맞습니다. 둘에 종속성이 생기게 된다면 사실 컴포넌트를 분리하는 의미는 없습니다.
이 부분을 고려하시면서 개발하시면 될 것 같습니다 :)

2024-01-02 13:39 UTC, haeyong9701 commented on src/components/FolderLinks/index.js
> +};
다른 곳에서 쓰일까봐 밖에 놔두긴 했는데 FolderLinks 컴포넌트 밖에 놔둔건 잘못됐네요. 재사용 가능성이 있어서 utils.js에 넣었습니다. https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188/commits/98b323a2e1fe542b632cc4caf3db334d7967bf09

2024-01-02 13:41 UTC, haeyong9701 commented on src/components/FolderLinks/index.js
> +      </div>
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188/commits/98b323a2e1fe542b632cc4caf3db334d7967bf09 수정했습니다.

2024-01-02 14:10 UTC, haeyong9701 commented on src/index.js
> -  <React.StrictMode>
Strict Mode는 개발 중에 컴포넌트에서 발생하는 오류를 발견할 수 있게 해줍니다.
- 개발 환경에서 불완전한 렌더링으로 인한 버그를 찾기 위해 한 번 더 렌더링합니다.
- 개발 환경에서 Effect를 재실행하여 버그를 찾을 수 있습니다.
- 컴포넌트가 더 이상 지원되지 않는 API중 하나를 사용하는 경우 경고를 표시합니다.

강의에서 StrcitMode도 지워버려서 당연히 중요한게 아니라고 생각하고 저도 지워버렸습니다. Strict Mode로 버그를 찾을 수 있다고 하니 다시 추가했습니다!

2024-01-02 14:38 UTC, haeyong9701 commented on src/api.js
> +const api = "https://bootcamp-api.codeit.kr/api";
습관이 되어버려서 소문자로 적었네요. 수정했습니다.

2024-01-02 14:42 UTC, haeyong9701 commented on src/App.js
> +      setFolderObj(folderBody);
처음에는 let이 필요했었는데 코드를 수정하다보니 필요가 없어졌네요. const로 수정했습니다!

2024-01-02 14:56 UTC, haeyong9701 commented on public/index.html
>  <html lang="en">
lang 신경안썼는데 스크린 리더와 관련있었네요. 수정했습니다!

2024-01-02 15:54 UTC, haeyong9701 commented on src/utils.js
> +  }
상수화가 중요하군요.. 코드 가독성이 더 좋아졌네요. 감사합니다. diffSec 변수가 없어서 따로 추가해서 조건문에 넣었습니다! https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188/commits/016012b598819c7d8c2efc4b5f971f9500e42620

2024-01-03 02:24 UTC, haeyong9701 commented on src/components/FolderLinks/index.js
> +};
다시 코드를 보니까 이해가 잘 안됩니다. set 함수를 쓰지를 않았는데 왜 종속되어 있는지 잘 모르겠습니다..

2024-01-03 03:13 UTC, goldfrosch commented
+ 이 내용은 피드백으로 드릴겸 여쭤보려 했는데 아에 잊고있었군요?
[중요도: 중간] 컴포넌트 파일 이름을 index.js로 준 이유랑 사용했을 때 장점에 대해 알려주세요~

2024-01-03 03:15 UTC, goldfrosch commented on src/index.js
> -  <React.StrictMode>
언제나 어떤 것을 할 때 이유가 가장 중요하다고 생각합니다!
이부분에 대해 잘 인지하고 있으니 편하신대로 사용하면 좋습니다.

다만 프로젝트를 진행할 때는 strict모드를 불편하겠지만 키고 하는 것을 추천드립니다.

한번 끄면 누군가 실수하는 것도 묻히고... 그게 쌓이다보면 다시 킬 때 문제가 커지니까요

2024-01-03 03:25 UTC, goldfrosch commented on src/components/FolderLinks/index.js
> +};
종속의 의미를 잘못 전달드린 것 같네요. 제가 말씀드린 종속은 FolderLink 컴포넌트에만 사용하는 util함수로 보여 말씀드렸습니다 :)

2024-01-03 03:25 UTC, goldfrosch commented on src/components/FolderLinks/index.js
> +};
보통 state나 ref에 종속되어 있지 않는 함수들(함수의 리렌더링이 필요하지 않은 경우)들에 한해서는 컴포넌트 밖에 빼 불필요한 리렌더링을 방지하기 위함으로 자주 사용합니다.

여기서 제가 종속이라는 말씀을 드리며 PR을 드린 이유를 조금 더 설명드리면

(주의: 개인적인 의견에 가까우니 참고만 해주시면 좋을듯 합니다.)
컴포넌트 파일에 단순 리렌더링을 방지하기 위해 밖으로 함수를 빼는게 정말 파일 가독성에 좋은것인가? 라는 의문이 조금 있습니다. 개인적으로는 컴포넌트 파일 하나에는 하나의 컴포넌트만 있는게 좋다라고 생각하고 있기 때문입니다. 

물론 이렇게하면 성능의 약간을 포기해야 하겠죠... 불필요한 리렌더링을 발생시키니까요. 하지만 저정도의 리렌더링 때문에 앱의 성능이 눈에 띌 정도로 낮아질까는 조금의 의문이 있습니다.

어찌됬든 이런 부분은 보통 사바사(회사마다 다르다) 즉 규칙에 따라 달라지는 부분이니 참고만 해주세요 :)

중요한 것은 저렇게 뺐을 때 어떤 효과가 있는지니까요~

2024-01-03 11:38 UTC, haeyong9701 commented
> * 이 내용은 피드백으로 드릴겸 여쭤보려 했는데 아에 잊고있었군요?
>   [중요도: 중간] 컴포넌트 파일 이름을 index.js로 준 이유랑 사용했을 때 장점에 대해 알려주세요~

다른 파일에서 컴포넌트를 import 할 때, 경로에서 index.js을 생략 할 수 있어서 사용했습니다. 컴포넌트 파일 이름이 생략되어 있으니 보기 좋은게 장점입니다.

2024-01-03 12:41 UTC, haeyong9701 commented on src/components/FolderLinks/index.js
> +};
event 객체와 url을 handleLinkClick 함수에서 사용하기 때문에 FolderLinksCard 컴포넌트 안에 넣어 가독성을 좋게 만들어 주었습니다. 
그리고 오늘 회의 시간에 알려주신대로 div 태그는 시맨틱 태그인 a 태그로 변경했습니다. https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/188/commits/8256e0b170ce55fedd349bcd0f252d580921c498

2024-01-04 13:45 UTC, goldfrosch commented
잘 이해하고 사용하셨군요 좋습니다!

2024-01-04 13:46 UTC, goldfrosch approved these changes
고생하셨습니다. approve and merge 진행하겠습니다!

2024-01-04 13:46 UTC, merged