Part2 송상훈 week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #190
Opened 2024-01-02 04:30 UTC by Song-Sang

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)

- [x]상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?

- [x]상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?

- [x]폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?

- [x]Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?

- [x]Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?

- [x]카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?

- [x]Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?

- [x]Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- []커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

-피그마 요구사항에 명시된 header,footer,mian page 구현 했습니다.
-프로필 영역과 header 영역에 api 데이터 활용 필요한 부분 적용 했습니다.
-카드 컴포넌트 부분 호버 기능 구현했습니다.
-반응형 구현 했습니다.

## 스크린샷

![스크린샷 2024-01-02 오후 1 23 53](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152246452/22332eaf-5311-4e50-92cf-4ef81b31d257)
![스크린샷 2024-01-02 오후 1 24 09](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152246452/0f8d9353-2a74-4036-bae0-0ae5d09d6c1e)
![스크린샷 2024-01-02 오후 1 24 13](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152246452/edf1a057-c2f1-43ea-b69e-e11778d352d5)

## 멘토에게

- 진도를 따라가는데 어려움을 느끼고 있어서 과제 진행이 쉽지 않았습니다 ㅠㅠ..
- 이곳 저곳 많이 참고하고 물어봐서 구현은 했지만 확실히 이해하지 못하고 작성한 곳이 많아 js와 react에 대한 개인적인 학습 시간이 많이 필요하다고 생각중이고, 진행중입니다.

2024-01-02 18:21 UTC, wonsss requested changes
안녕하세요. 상훈님! 첫 리액트 미션을 잘 해주셨네요. 수고 많으셨습니다. 👍
리뷰 확인 후, 각각 리뷰에 의견이나 반영 여부 등에 대한 댓글을 남겨주시길 부탁드려요. 관련하여 수정하셨으면 댓글에 해당 커밋 링크 첨부도 부탁드립니다.

그리고 PR 내용에 해당 프로젝트의 설치 및 실행 방법 에 대해 추가적으로 적어주시면 좋습니다. 😄

2024-01-02 18:21 UTC, wonsss commented on src/Section/Card/Card.js
> +      </div>
createdAt 이 두 번 렌더링되고 있어요. 디자인 요구사항이랑 다른 부분인 것 같습니다. 확인 부탁드려요 😄 
<img width="329" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/1ea48836-87b7-4218-91b2-0038ef89c44f">

2024-01-02 18:21 UTC, wonsss commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +function timeDiffChecker(num) {
유틸 함수를 나누셨군요! 하나의 기능을 하는 함수 분리 좋습니다 👍 

그런데 함수 이름은 일반적으로 동작과 관련된 동사로 시작합니다.
예를 들어, 이 함수의 이름은 무언가를 반환하니 get으로 시작하는 것도 가능할 것 같습니다.  그리고 Diff 처럼 축약어를 사용하기보다는 실제 단어를 사용하는 것이 협업을 위해 더 권장됩니다.

함수 이름짓기 관련하여 아래 문서를 참고해보세요 😄 

https://ko.javascript.info/function-basics#function-naming

<img width="826" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/4fc2c032-dccd-4a05-b4a0-16f2c8f829f6">

2024-01-02 18:21 UTC, wonsss commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +function timeDiffChecker(num) {
그리고 함수의 매개변수로 num 보다는 더 구체적인 맥락의 이름을 짓는 게 좋을 것 같습니다.
함수 정의를 보니 num을 시간과 비교하고 있던데 그러면 time은 어떨까요?

2024-01-02 18:21 UTC, wonsss commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +  const mon = day * 30;
매직넘버를 별도의 변수로 만들어 이름을 붙여준 것 너무 좋습니다.

매직 넘버(Magic number)나 매직 리터럴(Magic Literal)은 코드에서 하드 코딩된 일정한 값을 의미하는 숫자나 문자열을 의미합니다. 
예를 들어 '2', 나 '60*24' 등의 숫자는 코드 내에서 여러 곳에서 사용되고 있지만, 이 값의 의미나 목적은 현재 코드에서 명확하게 알려져 있지 않습니다.

매직넘버나 매직리터럴은 가독성이 떨어지고 유지보수를 어렵게 만들며, 예상치 못한 버그를 발생시키는 원인이 될 수 있습니다.

따라서 이들을 상수로 분리하고 해당 매직넘버의 역할을 정확한 이름으로 붙여서 사용하시는 것이 좋습니다. 그리고 상수로 분리해두면 값을 변경할 때 일괄적으로 변경할 수 있으므로 코드의 유지보수성과 가독성이 향상됩니다.

참고로 자바스크립트에서 상수를 선언하는 컨벤션은
`MINUTE` 처럼 모두 영어 대문자에 띄어쓰는 부분은 언더바를 적습니다.

```
const MINUTE = 1;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;
const MONTH = 30 * DAY;
const YEAR = 12 * MONTH;
```

2024-01-02 18:21 UTC, wonsss commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +  }
조건을 깔끔히 잘 작성하신 것 같습니다. 👍

다만, else if, else 문이 불필요하게 있는 것 같아요.  
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else나 else-if문을 사용하지 않아도 됩니다.

early return 패턴은 아래 참고 링크 등에서 참고해보세요.  
[https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90](https://velog.io/@jangws/9.-Else-if%EC%99%80-Else%EB%A5%BC-%ED%94%BC%ED%95%98%EA%B3%A0-Early-Return%ED%95%98%EC%9E%90)

2024-01-02 18:21 UTC, wonsss commented on src/index.js
> +root.render(<App />);
그리고 `<React.StrictMode>` 로 App을 감싸면, 개발 중에 컴포넌트에서 일반적인 버그를 빠르게 찾을 수 있습니다. 
아마 CRA로 프로젝트 시작하셨으면, 기본으로 있었을텐데 수정하신 것 같네요. 
이유가 있으셨을 것 같은데, 이유가 궁금합니다. 
그리고 자세한 내용은 문서 참고해보세요 😄 
https://ko.react.dev/reference/react/StrictMode

2024-01-02 18:21 UTC, wonsss commented on public/index.html
>    </body>
브라우저가 스크립트를 비활성화한 경우(chrome://settings/content/javascript) 에는 리액트 싱글페이지애플리케이션이 정상동작하지 않을 것이기 때문에, 이런 경우에 표시될 대체 메세지를 정의해두는 것도 좋습니다. 이를 위해 noscript 요소를 추가하면 됩니다. 참고로 알아두세요~

```js
	<body>
		<noscript>You need to enable JavaScript to run this app.</noscript>
		<div id="root"></div>
	</body>
```

> HTML `<noscript>` 요소는 페이지의 스크립트 유형을 지원하지 않거나, 브라우저가 스크립트를 비활성화한 경우 보여줄 HTML 구획을 정의합니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/noscript

<img width="1294" alt="스크린샷 2024-01-01 오후 5 59 02" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/26f409d6-bd96-49c3-be25-1b635fce8bfa">

2024-01-02 18:21 UTC, wonsss commented on src/App.js
> +import Section from "./Section/Section.js";
Header, Footer, Main, Section은 모두 component들입니다.
src 폴더 하위에 바로 이러한 컴포넌트 폴더를 두는 것보다, 
이 컴포넌트 폴더들을 src/components 폴더 하위에 모아두면 어떨까요?

현재 개발된 상황에서 대략 아래와 같은 폴더 구조도 가능할 것 같습니다.
```
src
   components
       Header
       Footer
       Main
       Section
   utils
   assets
```

일반적으로, 자주 함께 변경되는 파일들을 같이 보관하는 것이 좋은 방법이에요. 이러한 원칙을 “코로케이션(colocation)“이라고 불러요.

React는 컴포넌트 기반 라이브러리로서, 프로젝트 구조를 컴포넌트에 중점을 두고 설계하는 것이 좋습니다. 각각의 기능 또는 화면은 독립적인 컴포넌트로 나누어져야 합니다. 이는 각 컴포넌트의 재사용성을 높입니다.

협업, 확장성, 유지보수성 측면에서 어떤 방식이 좋을지 생각해보시면 좋을 것 같아요.
관련해서 리액트 공식 문서 내용을 꼭 읽어보세요 😄 
https://ko.legacy.reactjs.org/docs/faq-structure.html

2024-01-02 18:21 UTC, wonsss commented on src/Footer/Footer.js
> +            <a rel="noreferrer" href="https://twitter.com/?lang=ko" target="_blank">
a 태그에 target="_blank" 속성을 사용할 때는 rel="noopener noreferrer" 특성을 지정하여 window.opener 참조 설정을 방지하는 것이 좋습니다. 이를 통해 생성된 창의 opener 속성에 접근해도 null을 반환합니다.  하이퍼링크를 신뢰할 수 없을 때, 브라우저의 보안 리스크를 방지할 수 있습니다.

관련해서 참고하실 수 있는 링크 전달드립니다.
참고로 알아두시면 좋아요.
https://mathiasbynens.github.io/rel-noopener/#recommendations
[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

2024-01-02 18:21 UTC, wonsss commented on src/Footer/Footer.js
> +              <img src={instagramImg} alt="insta" />
img 태그에 alt 속성을 넣어주셨군요 👍 

참고로 img 태그의 alt 속성에는 다음과 같은 이유로 해당 이미지를 설명하는 의미 있는 텍스트를 적어주시는 것이 좋습니다. 😄 
<img width="1213" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/70fe2c82-da3e-4a51-9209-372e5ebc7be1">
https://ko.wikipedia.org/wiki/Alt_%EC%86%8D%EC%84%B1

2024-01-02 18:21 UTC, wonsss commented on src/Header/Header.js
> +        </div>
조건부렌더링을 하기 위해, style 속성을 이용하셨군요. 

리액트에서 조건부 렌더링은 JSX 자체에 삼항조건연산자를 적용하여 하시는 것이 일반적이고 더 간단합니다.
```suggestion
    {userInfo ? (
      <div className='user-info'>
        <img
          src={userInfo["profileImageSource"]}
          alt='profile'
        />
        <h6>{userInfo["email"]}</h6>
      </div>
    ) : (
      <a href='./signin/signin.html'>로그인</a>
    )}
```

react 공식문서의 조건부 렌더링 페이지를 읽어보실 것은 추천드립니다.
https://ko.react.dev/learn/conditional-rendering

2024-01-02 18:21 UTC, wonsss commented on src/Header/Header.js
> +        </div>
그리고 
객체의 프로퍼티 접근 방법으로서
괄호표기법인 `userInfo["profileImageSource"]` 대신에, 
점 표기법인 `userInfo.profileImageSource` 를 사용해보세요. 

점 표기법이 더 간편해서 일반적으로 쓰입니다.

다만, 키 값이 변수이거나 숫자로 시작하거나 공백이 있는 경우는 괄호표기법만 가능하므로 그런 경우에 한하여 괄호표기법을 사용하실 수 있습니다.

객체 프로퍼티 접근 방법에 대해 자세한 내용은 아래 링크 참고해보세요. 
https://ko.javascript.info/object#ref-271

2024-01-02 18:21 UTC, wonsss commented on src/Header/Header.js
> +  console.log(userInfo.id);
PR 제출 시 사용하지 않고 개발용으로만 사용하셨던 콘솔로그나 주석 등은 제거 부탁드려요 😄

2024-01-02 18:21 UTC, wonsss commented on src/Header/Header.js
> +  }
userInfo 가 없으면 null 을 반환하는 조건부 렌더링을 적용하셨군요.
만약 로그인을 하지 않은 경우라면, userInfo가 없어서 여기서 null을 return하여 이 함수형 컴포넌트가 종료됩니다.

그러면 헤더 자체가 안 보이게되어 로그인 여부와 무관한 로고도 보이지 않게 됩니다.
따라서 이 부분에 이 조건부 렌더링은 제거하는 게 맞을 것 같아요.
대신에 아래에서 로그인 여부에 따라 로그인버튼 혹은 로그인한 이메일주소를 보여주는 조건부렌더링을 해주시면 될 것 같아요.

2024-01-02 18:21 UTC, wonsss commented on src/Header/Header.js
> +        <a href="./signin/signin.html" style={userInfo.id !== 1 ? visible : invisible}>
userInfo.id 가 1인지 여부에 따라 로그인 여부를 판단하신 것 같아요.
그런데 userInfo.id는 2나 3 등등이 될 수 있고 로그인을 했기에 사용자의 id인 해당 값이 올 수 있는 것이라서 이를 기준으로 로그인 여부를 판단할 수 없습니다.
대신 userInfo 객체 자체가 존재하는지 여부를 갖고는 로그인 여부를 판단할 수 있을 것 같아요.

2024-01-02 18:21 UTC, wonsss commented on src/Section/Card/Card.js
> +function Card({ image = logo, createdAt = DEFAULT_CARD_VALUE.createdAt, description = DEFAULT_CARD_VALUE.description, uploadDate = DEFAULT_CARD_VALUE.uploadDate, style }) {
컴포넌트 prop에 기본값을 다 적용해두셨군요.
기본값을 적용하신 이유가 궁금합니다.

2024-01-02 18:21 UTC, wonsss commented on src/Section/Card/Card.js
> +  };
이벤트 핸들러 함수의 이름은 관습적으로 `handle` 이라는 접두어로 시작합니다.
이 경우에도 해당 함수들의 이름이 `handleCardMouseOver` `handleCardMouseOut` 이라면 함수의 역할이 더 쉽게 이해될 것 같습니다. 일반적인 네이밍 컨벤션에 익숙해지면 이름 짓는 게 더 쉬워집니다. 😄 

React component의 prop 이름을 짓는 규칙 관련하여 아래 링크 참고바랍니다.
https://wonsss.github.io/React/react-component-props-naming/

2024-01-02 18:21 UTC, wonsss commented on src/Section/Card/Card.js
> +        <img src={image} alt="cardImage" style={style} onMouseOver={mouseOver} onMouseOut={mouseOut} className={isHover ? "growImg" : ""} />
이미지 hover 시 이미지 확대하는 기능은 이러한 이벤트 핸들러 등록 방법을 쓰지 않고, 아래와 같은 단순한 css 만으로 구현 가능합니다.
css로 구현 가능한 기능은 자바스크립트가 아닌 css로 구현하는 것이 더 직관적이고 성능에도 좋습니다.

```css
.image-box img:hover {
	transform: scale(1.3);
}
```

2024-01-02 18:21 UTC, wonsss commented on src/Section/Search/Search.js
> +        <input type="text" placeholder="링크를 검색해 보세요." className="search-bar" />
검색인풋이므로 input type 속성에 "search"를 적용해주시는 것이 좋습니다.
```jsx
      <input type="search" placeholder="링크를 검색해 보세요." className="search-bar" />
```

참고
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

2024-01-02 18:21 UTC, wonsss commented on src/Section/Section.js
> +  }
이건 함수로 만들지 않아도 될 것 같아요.

2024-01-02 18:21 UTC, wonsss commented on src/Section/Section.js
> +            uploadDate={todayIs()}
0부터 9까지 모든 Card 컴포넌트를 다 작성하셨군요.
이처럼 여러개의 컴포넌트 렌더링을 해야 하는 경우가 자주 있습니다.
리액트에서는 자바스크립트 배열의 메서드인 filter()와 map()을 사용해 데이터 배열을 컴포넌트 배열로 변환할 수 있습니다.
이 방법으로 꼭 리팩터링해보시기 바랍니다. 

그리고 map() 호출 내부의 JSX 엘리먼트에는 항상 key가 필요한데, key 속성이 왜 필요하고 어떤 값을 넘기는 것이 좋은지 확인해보시기 바랍니다.

아래의 공식 문서에 자세히 작성되어 있으니 참고 바랍니다. 😄 
https://ko.react.dev/learn/rendering-lists

2024-01-02 18:21 UTC, wonsss commented on src/Section/Section.js
> +            style={cardInfo[0].imageSource !== undefined ? style : logoStyle}
이 style이 컴포넌트에 어떤 영향을 미치고 있나요? 혹시 불필요하진 않나요?

2024-01-02 18:21 UTC, wonsss commented on src/Section/Section.js
> +  dateCalculator();
함수는 가능한 순수함수로 만들 것을 추천드립니다. 
위 함수는 함수 밖에 있는 배열의 값을 변경시키는 로직을 갖고 있어서 순수하지 않은 함수입니다.

순수함수란 동일한 인수가 전달되면 언제나 동일한 값을 반환하는 함수이며 부수 효과(Side Effect)가 없어야 합니다.

순수함수로 작성하면, 다음과 같은 장점이 있어요.
- 동일한 입력에 대해 항상 동일한 결과를 반환합니다. 이는 예측 가능성을 높이고 디버깅 및 테스트를 용이하게 합니다. 
- 순수 함수는 다른 함수와 조합하여 더 복잡한 로직을 만들 수 있습니다. 이는 모듈화와 코드 재사용성을 높여줍니다.
- 함수가 외부 상태를 변경하지 않고, 함수 외부의 상태에 영향을 주지 않습니다. 이로써 코드의 복잡성이 감소하고 예상치 못한 동작이 발생할 확률이 낮아집니다.

순수함수가 무엇인지 다음 링크에서 조금 더 참고해보세요.
https://maxkim-j.github.io/posts/js-pure-function/

2024-01-02 18:21 UTC, wonsss commented on src/Header/Header.js
> +          <img src={userInfo["profileImageSource"]} alt="prifile" />
prifile -> profile 
오타가 있네요.
오타를 내지 않는 것도 매우 중요합니다.  
VSCode 익스텐션의 도움을 받아보실 것을 추천드려요.

 Code Spell Checker  
VS Marketplace 링크: [https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

2024-01-02 18:21 UTC, wonsss commented on src/Section/Section.js
> +  }, []);
fetch 시 에러가 발생하는 경우 처리 로직도 추가하면 좋습니다.

예시 코드 참고해보세요.
아래 예시 코드에서 get 함수는 get 메서드로 fetch 요청할 때, 응답 데이터을 얻기 위해서 response.json()을 매번 호출하거나, 데이터를 보낼 때, HTTP 요청 헤더에 "Content-Type": "application/json"로 설정해주는 부분 및 response.ok가 아닌 경우 에러를 던지는 등의 코드의 반복을 줄이기 위해 함수로 분리한 것입니다.

```js
async function get(host, path, body, headers = {}) {
	const url = `https://${host}/${path}`;
	const options = {
		method: "GET",
		headers: {
			"Content-Type": "application/json",
			...headers,
		},
		body: JSON.stringify(body),
	};
	const res = await fetch(url, options);
	const data = await res.json();
	if (res.ok) {
		return data;
	} else {
		throw Error(data);
	}
}
```

```js
// 사용
const getFolderInfo = async () => {
  try {
    const res = await get(
      "bootcamp-api.codeit.kr",
      "api/sample/folder"
    );
    setFolder(res.folder);
  } catch (error) {
    console.log(error); // 에러 발생시 어떻게 처리할지 
  }
};
```

2024-01-04 09:37 UTC, Song-Sang commented on src/index.js
> +root.render(<App />);
아! 특별한 이유가 있지는 않았고, 강의 내용을 생각없이 따라가면서 작업하다보니 필요 없겠거니 하고, 강의랑 똑같이 삭제 한것 같습니다 ㅎㅎ,,, 어떤 기능인지 궁금하긴 했는데 첨부 문서 참고해서 학습해보겠습니다!

2024-01-04 09:53 UTC, Song-Sang commented on src/Section/Card/Card.js
> +      </div>
실수입니다! 수정 완료했습니다. 
[f692b41](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/190/commits/f692b416579e8c8ca363972ef6ad741fae1780cb)

2024-01-04 09:55 UTC, Song-Sang commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +function timeDiffChecker(num) {
함수이름 getTimeDifference로 변경 했고, 동일 함수의 매개변수 num 이름 time으로 수정 했습니다!
[512b7bc](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/190/commits/512b7bcb4c0a373f8b280ed5ba6725f9cb021b12)

2024-01-04 09:59 UTC, Song-Sang commented on src/Section/Section.js
> +            uploadDate={todayIs()}
아.. 맞아요 여기 작성할 때 반복 사용 되는 부분이라고 알고있었는데, filter와 map을 사용해서 추상화 할 생각을 못했습니다. 
말씀해주신 대로 리팩토링 해보았습니다.
[f8d096c](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/190/commits/f8d096c851a2d3830c18aed9317b45729488199b)

2024-01-04 10:00 UTC, Song-Sang commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +  const mon = day * 30;
대문자로 변경완료했습니다! 간단한 변경이라 커밋 코드는 첨부하지않았습니다!

2024-01-04 10:01 UTC, Song-Sang commented on src/Section/TimeDiffChecker/TImeDiffChecker.js
> +  }
early return에 관한 장점을 이전 팀 멘토링에서 들었는데 적용할 생각을 못했네요! 이 부분은 첨부링크 다시 한번 확인하고 추후에 리팩토링 하도록하겠습니다!

2024-01-04 10:12 UTC, Song-Sang commented on src/Section/Section.js
> +  }, []);
try catch 문을 이용해서 말씀하신대로 에러 로직 추가 해봤습니다!

[de6cd7a](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/190/commits/de6cd7ae570f3a83fcc16ef1c61a5d43525e5d68)

2024-01-04 10:14 UTC, Song-Sang commented on src/Section/Section.js
> +  dateCalculator();
이 리뷰에 대한 리팩토링은 학습을 좀 더 이해한 후에 해봐야할듯 합니다!

2024-01-04 11:14 UTC, wonsss approved these changes
상훈님 중간에 Load More 버튼 클릭하면, 제가 남기 리뷰 13개 더 보실 수 있어요. 해당 리뷰들에는 댓글이 안달려있는 것을 보니 이 버튼 때문에 확인 못하신 것 같아요.
다음 미션 진행을 위해 본 PR은 merge할게요. 반영 못한 리뷰는 다음 미션 PR에서 이어서 반영 부탁드려요. 😄 
<img width="998" alt="스크린샷 2024-01-04 오후 8 12 42" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/86544097-e713-4810-af95-4663f9a7eb26">

2024-01-04 11:16 UTC, wonsss commented on src/Section/Section.js
> +            uploadDate={todayIs()}
key에는 index를 넣으셨군요.
<img width="619" alt="스크린샷 2024-01-04 오후 8 15 29" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/87bb9707-b171-488e-a4ef-dc1cdb4a17e8">

key에는 index를 넣어서는 안됩니다.  그 이유가 공식문서에 자세히 설명되어 있으니 꼭 확인해주세요. 중요한 내용입니다
https://ko.react.dev/learn/rendering-lists#rules-of-keys
<img width="929" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/f0238031-279c-46aa-9a62-4c40a89ca3fa">

2024-01-04 11:17 UTC, merged