[조현진] Week 7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #194
Opened 2024-01-05 06:55 UTC by ahrrrl

![01_모코코콘1_27_뜨겁다](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/126558640/8ed6bbb6-9a4e-45cb-b81d-4dccee58cbe2)

### 기본

- [ ] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정했나요?

- [x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용했나요?

- [x] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이나요?

- [x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용했나요?

- [x] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 “/api/users/1/links?folderId={해당 폴더 ID}”를 활용했나요?

- [ ] Mobile에서 “폴더 추가” 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들었나요?

## 만드는 중입니다!

## 멘토에게

- 많은 일들이 일어나고 있습니다

2024-01-09 13:36 UTC, goldfrosch requested changes
고생많으셨습니다. 진도를 열심히 따라오면서 퀄리티 높은 과제를 주시니 저도 기분이 좋네요 :)

몇개의 요청을 PR comments로 남겨드리니 확인 한번 부탁드립니다!

2024-01-09 13:36 UTC, goldfrosch commented on src/components/FolderContentCard.js
> +        })
```suggestion
        items.map(({ created_at, url, id, description, image_source }) => (
        <li className="card" onClick={() => openNewWindow(url)} key={id}>
              <div className="card-img-div">
                <img
                  className="card-img"
                  src={
                    image_source ||
                    "/imgs/01_모코코콘1_16_백색모코코_물음표.png"
                  }
                  alt="카드사진"
                />
                <img
                  className="star-img"
                  src="/imgs/star.png"
                  alt="즐겨찾기 등록"
                />
              </div>
              <div className="card-contents">
                <div className="card-time-ago-box">
                  <p className="card-time-ago">{getTimeDifference(created_at)}</p>
                  <img src="/imgs/kebab.png" alt="파일수정" />
                </div>
                <p className="card-description">{description}</p>
                <p className="card-createdat">{formatCreatedAt(created_at)}</p>
              </div>
            </li>
        ))
```
[중요도: 낮음] 이렇게도 괜찮을 것 같습니다. 사실 이정도 간단하게 모듈화가 되어있으면 중괄호를 쓸 필요가 굳이굳이 있을까라는 생각은 조금 있습니다. (지극히 개인적인 견해)

이미지가 없으면 기본 이미지가 나오게 한 것은 좋네요 :)
map함수에서 1번째 인자를 구조분해 할당으로 처리한 것도 정말 좋습니다!

2024-01-09 13:36 UTC, goldfrosch commented on src/components/LinkSearchInput.js
> +        <img src="/imgs/link.png" className="link-img" alt="링크추가기" />
[중요도: 낮음] alt 태그 오타같네요?

2024-01-09 13:36 UTC, goldfrosch commented on src/components/FolderList.js
> +                selectedFolder.id === folder.id ? "folderSelected" : ""
[중요도: 중간] 이런 조건부에 따라 className을 지정해야한다면 classnames라는 라이브러를 써보는 것을 추천드립니다. 정말 편해요!

2024-01-09 13:36 UTC, goldfrosch commented on src/components/FolderName.js
> +        {selectedFolder ? selectedFolder.name : "전체"}
```suggestion
        {selectedFolder?.name ?? "전체"}
```
[중요도: 중간] 이런 식으로 optional chaining과 ?? 연산자를 섞어서 쓰면 더 간단하게 사용할 수 있어보이네요~

2024-01-09 13:36 UTC, goldfrosch commented on src/components/Nav.js
> +  }, [prevScrollPos]);
[중요도: 낮음]
당장은 아니지만... 추후 intersection observer라는 개념을 익히고 쓰신다면 스크롤 할 때마다 연산하는 것을 줄일 수 있을 것 같아요.

시간이 되신다면 조사해보세요~

2024-01-09 13:36 UTC, goldfrosch commented on src/components/FolderSection.js
> +  const [selectedFolder, setSelectedFolder] = useState("$1");
[중요도: 높음] $1가 정확하게 의미하는 바가 뭘까요?

2024-01-11 07:39 UTC, ahrrrl commented on src/components/FolderSection.js
> +  const [selectedFolder, setSelectedFolder] = useState("$1");
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/194/commits/a657bdb0e7aa9cc2a8682525f8299ddb17188275

다른  폴더들은 ID 값으로 서로 식별이 가능한데 '전체'는 서버에서 가져오는 방법도 다르고 달리 식별할 방법이 생각이 안나서 임의로 아이디값을 $1로 줬었습니다! 
다른 방법도 있겠지만 일단 '전체'로 바꿔서 사용 용도의 의미를 그나마 넣어봤습니다

2024-01-11 07:40 UTC, ahrrrl commented on src/components/FolderName.js
> +        {selectedFolder ? selectedFolder.name : "전체"}
오 더 간단하게 될 수 있군요!

2024-01-11 07:40 UTC, ahrrrl commented on src/components/FolderList.js
> +                selectedFolder.id === folder.id ? "folderSelected" : ""
classnames 공부하며 써보겠습니다!

2024-01-11 07:41 UTC, ahrrrl commented on src/components/LinkSearchInput.js
> +        <img src="/imgs/link.png" className="link-img" alt="링크추가기" />
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/194/commits/a657bdb0e7aa9cc2a8682525f8299ddb17188275

예리하시군요 수정했습니다!

2024-01-11 07:42 UTC, ahrrrl commented on src/components/FolderContentCard.js
> +        })
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/194/commits/aa98dcf4a0b04aaacacb7a5ef14db355267e976f

return문 안에 깔끔하게 변수로 넣을 생각에 쓸데없이 변수 선언을 한번 더 해버렸군요! 다음부터는 그대로 넣도록하겠습니다!

2024-01-13 03:39 UTC, ahrrrl commented on src/components/FolderSection.js
> +  const [selectedFolder, setSelectedFolder] = useState("$1");
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/194/commits/00287c0474fc0cd9b401861aa71a7b6bd596fe16

2024-01-13 08:19 UTC, merged