[고기호] Week7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #198
Opened 2024-01-06 09:13 UTC by GihoKo

## 요구사항

### 기본

- [x] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정했나요?

- [x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요?

- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용했나 
        요?

- [x] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이 
        나요?

- [x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용했나요?

- [x] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 
       “/api/users/1/links?folderId={해당 폴더 ID}”를 활용했나요?

- [] Mobile에서 “폴더 추가” 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들었나요?

### 심화

## 주요 변경사항

- /shared와 /folder 페이지 react router를 이용해서 라우팅 구현
- /folder 페이지 전체 반응형 디자인 구현
- 리액트 라우터로 존재하지 않은 페이지에 접근할 때 Not Found 페이지 보여주기 구현
- folder button 클릭시 해당 폴더에 존재하는 Card만을 보여주게 구현
- folderCard의 케밥 버튼을 누를시 모달창 구현
- css파일 전체 Styled Component로 변경 

## 스크린샷
![1](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/98e6c538-b5dd-4847-a99d-a950b0c5c85d)
![2](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282
![3](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/868eff6a-d6bf-49b2-bb09-adf2c45529fb)
547/633d8e5b-a2a7-49fb-a9db-35c060acac2d)
![4](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/bef059e0-0d29-4d87-9a15-48741723d00d)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-08 15:38 UTC, wonsss requested changes
수고 많으셨습니다. 기호님! 
PR 메세지도 상세히 적어주시고 커밋도 의미있게 나누려고 노력해주셨네요 👍 
리뷰 남겼습니다. 반영 후 목요일 전까지 재리뷰 요청주시면 좋을 것 같아요. 😄

2024-01-08 15:38 UTC, wonsss commented on .eslintrc
> +    "react/jsx-filename-extension": "off"
airbnb 린트 룰에 기본 포함되어 있는  "react/jsx-filename-extension": "on" 는 유용하다고 생각합니다. `.js` 확장자 파일 내에 JSX 문법을 사용할 경우 `.jsx` 확장자로 변경하는 것이 좋다고 아래와 같이 알려줄 수 있죠. 기호님께서는 해당 룰을 끄신 이유가 궁금합니다. :) 
<img width="857" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/4fa9a8ba-5f2b-4ea0-a7af-e98d9e11aae5">

2024-01-08 15:38 UTC, wonsss commented on .eslintrc
eslint의 parser 설정이 잘못되어 있는 것 같습니다.
기호님 프로젝트 그대로 설치했을 때, 계속 아래와 같은 parser 에러가 프로젝트 전체에서 나네요
<img width="785" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/4e25cc02-926b-4535-81b0-35e3116e604a">

아래와 같이 .eslintrc 파일의 parserOptions 설정을 추가해보세요. eslint는 기본적으로 parser를 쓰고 있는데, 
`@babel/eslint-parser` 커스텀 파서로 쓰겠다고 정의하셨습니다. (`  "parser": "@babel/eslint-parser",`)
해당 설정 때문에 현재 에러가 나는 것 같네요.
문제는 파싱할 때 사용할 babel 설정을 하지 않았다는 것입니다. 그래서 직접 바벨설정 파일을 넣지 않는다는 설정과 대신 간편하게 "@babel/preset-react" 프리셋을 사용한다는 설정을 해주셔야 합니다.

<img width="1021" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/c40630bb-0470-49cb-b8d6-0fe6f3ee0a57">

그리고 package.json을 보니 이미 사용중인 "@babel/eslint-parser" 도 설치가 되어 있지 않네요. 이거랑 "@babel/preset-react" 도 devDepndencies에 설치해주세요.
```bash
npm i -D @babel/eslint-parser @babel/preset-react
```

2024-01-08 15:38 UTC, wonsss commented on .eslintrc
참고: https://www.npmjs.com/package/@babel/eslint-parser#additional-parser-configuration

2024-01-08 15:38 UTC, wonsss commented on package.json
> +    "styled-components": "^6.1.6"
"^6.1.6" 이런 버전 방식을 Semantic Versioning이라고 합니다.
왜 중요하고 어떻게 사용하는 걸까요?

2024-01-08 15:38 UTC, wonsss commented on src/App.jsx
> +import getFetch from './utils/getFetch';
파일을 import 할 때, 실제 파일명의 대문자,소문자와 달리 import를 하시면 정확하지 않으므로, ESLint는 이것을 허용하지 않아요.
이 부분에서 파일명은 `GetFetch` 인데 import하는 경로가 `getFetch`네요.  그래서 여기서 에러가 나고 있습니다. 
<img width="1368" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/8ade5e14-96fd-4ec5-a853-95befa5c188b">

2024-01-08 15:38 UTC, wonsss commented on src/App.jsx
> +                  HandleFolderCardData={HandleFolderCardData}
핸들러 함수의 이름과 prop의 이름을 대문자로 시작하게 만드신 이유가 궁금합니다.
함수명은 소문자로 시작하는 것이 보편적입니다.

2024-01-08 15:38 UTC, wonsss commented on src/App.jsx
> +                  HandleFolderCardData={HandleFolderCardData}
이름이 대문자로 시작하는 경우는 클래스 이름, 생성자 함수 이름, 컴포넌트 이름 정도일 것 같네요. 
일반적인 변수나 함수의 이름은 소문자로 시작해요.

2024-01-08 15:38 UTC, wonsss commented on src/App.jsx
> +  const [folderCardData, setFolderCardData] = useState([]);
이러한 상태들이 모두 이 페이지 파일에 있네요. 이 때문에 이 페이지 코드가 많이 길어졌네요.
해당 상태를 필요로 하는 컴포넌트 가까이에 두는 것이 응집성에 더 좋지 않을까요?
그리고 해당 상태와 관련된 로직들도 함께 옮기구요. 😄

2024-01-08 15:38 UTC, wonsss commented on src/utils/getFormattingCardData.jsx
> +  return formattedData;
객체의 불변성 유지를 위해 forEach 와 delete 는 사용하지 않는 것이 좋을 것 같습니다.
map 메서드를 사용해서 새로운 객체를 생성하여 필요한 속성만 유지하고 나머지는 제외시키는 방식을 사용할 수 있습니다.

> forEach: forEach 메서드는 반환값이 없다 ➡️ 작업을 수행하고 원본 배열을 직접 수정하는 데 주로 사용
map: map 메서드는 새로운 배열을 반환.각 요소에 대해 작업을 수행한 결과를 새로운 배열로 만들어 반환한다 ➡️ 원본 배열은 변경X

2024-01-08 15:38 UTC, wonsss commented on src/utils/getFormattingCardData.jsx
> +const getFormattingCardData = (data) => {
함수 이름을 getFormattedCardData로 하는 것은 어떨까요?
만드신 다른 함수 이름 중에 getFormattedDate도 있더라구요. formatting 대신 formatted루요.
이름도 일관성 있게 만들면 좋습니다.

2024-01-08 15:38 UTC, wonsss commented on src/utils/getFormattingCardData.jsx
직접 유틸함수를 만드는 것도 연습에는 좋으나, 나중에 에러가 날 가능성도 큽니다.
이런 경우에는 이전에 말씀드린 camelcase-keys 라이브러리를 사용하는 것도 권장드립니다. 
https://www.npmjs.com/package/camelcase-keys
해당 라이브러리 설치하시고 아래와 같이 사용해보세요. 라이브러리 설명을 보니 객체가 중첩되어 있으므로 재귀적으로 중첩되어 있는 key들을 모두 카멜케이스로 변경하려면 deep: true 옵션도 넣어주셔야 하네요.
```
import camelcaseKeys from 'camelcase-keys';

 const formattedData = camelcaseKeys(data, { deep: true });

```

2024-01-08 15:38 UTC, wonsss commented on src/App.jsx
> +                  HandleFolderCardData={HandleFolderCardData}
App 파일 안에 라우팅 관련 파일을 함께 두는 것보다
Router 파일을 따로 만들어서 분리하는 것도 좋을 것 같습니다.

2024-01-08 15:38 UTC, wonsss commented on src/utils/getFormattedDate.jsx
이 파일에는 jsx 가 없는데 확장자명으로 jsx를 사용하셨네요. js로 수정해주세요.
jsx가 없으면 확장자로 js를 사용해주셔야 확장자만으로도 이 파일의 역할을 예측하기 쉬워요.

2024-01-08 15:38 UTC, wonsss commented on src/utils/calculatePassedTime.jsx
확장자를 js로 수정해주세요.

2024-01-08 15:38 UTC, wonsss commented on src/utils/GetFetch.jsx
파일명을 getFetch.js 로 수정해주세요.

2024-01-08 15:38 UTC, wonsss commented on src/components/Folder/Folder.jsx
> +  }
컴포넌트 파일 내부에서 스타일드컴포넌트들을 제일 위에 작성하고, 그 아래에 컴포넌트 함수를 작성하셨네요.
스타일드컴포넌트와 컴포넌트 함수의 위치를 뒤바꿔보는 것을 추천드립니다.
컴포넌트 파일을 읽을 때 위에서 아래로 순서대로 읽는데, 이 컴포넌트가 어떤 로직을 가져와서 쓰는지 그리고 어떻게 생겼는지 알 수 있는 해당 컴포넌트가 제일 아래에 있으니 가독성이 떨어질 수 있습니다.

2024-01-08 15:38 UTC, wonsss commented on src/components/CardList/Card/CardImg/CardImg.jsx
> +        <img src={`${process.env.PUBLIC_URL}/images/star.svg`} alt="즐겨찾기 별 이미지" className="link__img--star" />
public 에서 image 가져오는 경우에 대해 이전 PR 코멘트에서 추가 설명드렸었는데, 확인 부탁드려요. 
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/169#discussion_r1440631947

2024-01-08 15:38 UTC, wonsss commented on src/components/CardList/Card/CardContent/CardContent.jsx
> +            className="link__content--More-Btn"
불필요한 클래스네임인 것 같은데 지워도 될 것 같습니다.

2024-01-08 15:44 UTC, wonsss commented
> 막상 styled component로 css를 전부 변경했는데, jsx파일의 윗 부분이 styled component로 도배되버려서
이걸 또 jsx파일로 분리해야하나 고민 중입니다.

스타일드 컴포넌트만 분리한 파일을 만드실 수도 있습니다.
또는 컴포넌트 하나의 파일 안에 스타일드 컴포넌트도 함께 유지하는데, 스타일드 컴포넌트들을 제일 아래로 옮기는 것이 가독성에 좋습니다.

> CardList.jsx와 Hero.jsx 부분이흡사하게 생겨서 재활용을 해보려고 시도했는데
아무리 생각해봐도 두 컴포넌트 내부에 children prop을 주고
이런식으로 구현하는 방법밖에 떠오르지 않는데...
차라리 이렇게 하는 것보다 그냥 share, folder 컴포넌트를 따로 파고 내부 컴포넌트도 따로 파는게 더 가독성이 좋을 것
같습니다... 멘토님께서 보시기엔 어떻게 생각하시나요

저는 지금도 괜찮은 것 같습니다.

2024-01-08 15:46 UTC, wonsss commented
아 그리고 pages 폴더를 따로 만들고 그 안에 NotFoundPage.jsx 옮기시고, 지금 라우팅된 컴포넌트들도 `000page.jsx` 같은 형식으로 분리해서 파일로 만들어주세요. 
파일구조를 처음 봤을 때, 만드신 folder나 shared 페이지가 존재하는지 몰랐습니다. 그런데 이렇게 pages 폴더를 나누면 페이지 단위로 인식하고 유지보수하기 쉽습니다.

2024-01-10 10:20 UTC, GihoKo commented on .eslintrc
> +    "react/jsx-filename-extension": "off"
아 해당 부분은 제가 실수를 한 것 같습니다.
"react/jsx-filename-extension": [2, { "extensions": [".jsx"] }]
이 부분이 있어야 .jsx 확장자에서만 jsx를 사용할 수 있게 해주니
이 부분은 다시 넣어주는 것이 맞다고 생각합니다.

2024-01-10 10:37 UTC, GihoKo commented on src/components/CardList/Card/CardContent/CardContent.jsx
> +            className="link__content--More-Btn"
수정완료했습니다.

2024-01-10 10:37 UTC, GihoKo commented on src/utils/GetFetch.jsx
수정완료했습니다.

2024-01-10 10:37 UTC, GihoKo commented on src/utils/calculatePassedTime.jsx
수정완료했습니다.

2024-01-10 10:37 UTC, GihoKo commented on src/utils/getFormattedDate.jsx
수정완료했습니다.

2024-01-10 10:48 UTC, GihoKo commented on src/App.jsx
> +import getFetch from './utils/getFetch';
cb6afbd4d4ad2d70ca66ef807c52dfac9f571de1 수정완료했습니다.

2024-01-10 10:58 UTC, GihoKo commented on src/App.jsx
> +                  HandleFolderCardData={HandleFolderCardData}
원래 핸들어 함수 이름을 소문자로 시작하게 짓는데
제가 실수를 한 것 같습니다.
ec49cf0596d48b2dab36d526bec6eee9c2aec3de 수정했습니다!

2024-01-10 10:59 UTC, GihoKo commented on src/utils/getFormattingCardData.jsx
> +const getFormattingCardData = (data) => {
네이밍 영어에 좀 익숙해져야 할 것 같습니다 ㅎㅎ;
ec49cf0596d48b2dab36d526bec6eee9c2aec3de 수정했습니다!

2024-01-10 11:24 UTC, GihoKo commented on src/components/CardList/Card/CardImg/CardImg.jsx
> +        <img src={`${process.env.PUBLIC_URL}/images/star.svg`} alt="즐겨찾기 별 이미지" className="link__img--star" />
알람이 안떠서 못봤었네요 ㅠ
cdd8623c820085bac893ee00347c7e2fdd5d29f7 해당 부분 수정했습니다!

2024-01-10 11:25 UTC, GihoKo commented on src/components/Folder/Folder.jsx
> +  }
6eed5b8b2ccd81f7a5cf7b103f35e04f6439ac59 해당 부분 수정했습니다!

2024-01-10 11:42 UTC, GihoKo commented on .eslintrc
뭔가 babel 부분을 좀 공부해야 할 것 같습니다.
공식문서를 보니 해당 부분 기초 지식이 너무 없는 것 같습니다.
bad9063a1208dc732929bd0be7fddf88be4eb002 일단은 수정했습니다!

2024-01-10 12:07 UTC, GihoKo commented on package.json
> +    "styled-components": "^6.1.6"
많은 사람이 어떠한 패키지를 이용하다가 
해당 패키지의 작동법이나 호환성 등의 큰 업데이트가 있으면 혼란이 생길 수 있으므로
패키지의 변화를 구분하기 위해서 사용하는 것이 Semantic Versioning입니다.

왼쪽의 숫자는 하위 호환성이 깨질 정도의 큰 변경사항이 있을 때 증가가 되고,
가운데 숫자는 하위 호환성이 지켜지면서 기능이 추가될 때 증가가 되고,
오른쪽의 숫자는 하위 호환성이 지켜지면서 버그가 수정됐을 때 증가가 됩니다.
어떠한 숫자가 증가되면 해당 숫자의 오른쪽에 있는 모든 숫자는 0으로 초기화 됩니다.

2024-01-10 13:32 UTC, GihoKo commented on src/App.jsx
> +                  HandleFolderCardData={HandleFolderCardData}
a8cb666a65db0eef47819d080643a99151894a23 변경 완료했습니다.
뭔가 ... 저번 과제에서 썼던 코드에 대한 불신의 50프로가 날라간 느낌이였습니다.

2024-01-10 14:34 UTC, GihoKo commented on src/utils/getFormattingCardData.jsx
> +  return formattedData;
20dc09cf6da0657e488b256dc0f29952d5d44159
해당부분 카멜케이스 라이브러리로 변경하긴 했는데
비슷한 상황이 오면 객체의 불변성을 위해서 forEach와 delete 대신
map과 구조분해할당으로 필요한 속성만을 유지하는 방법으로 해보겠습니다.

2024-01-10 14:34 UTC, GihoKo commented on src/utils/getFormattingCardData.jsx
20dc09cf6da0657e488b256dc0f29952d5d44159
카멜케이스 라이브러리로 적용했습니다.

2024-01-10 14:36 UTC, GihoKo commented on src/App.jsx
> +  const [folderCardData, setFolderCardData] = useState([]);
a8cb666a65db0eef47819d080643a99151894a23
일단 최대한 구조를 바꿔봤는데
계속해서 리팩토링해나가겠습니다!

2024-01-10 15:07 UTC, GihoKo commented
> 아 그리고 pages 폴더를 따로 만들고 그 안에 NotFoundPage.jsx 옮기시고, 지금 라우팅된 컴포넌트들도 `000page.jsx` 같은 형식으로 분리해서 파일로 만들어주세요. 파일구조를 처음 봤을 때, 만드신 folder나 shared 페이지가 존재하는지 몰랐습니다. 그런데 이렇게 pages 폴더를 나누면 페이지 단위로 인식하고 유지보수하기 쉽습니다.

1db0c0a3172c6a96e7f40bff9dae44df76fe0467
a8cb666a65db0eef47819d080643a99151894a23
수정 완료했습니다!

2024-01-11 01:07 UTC, wonsss commented on package.json
> +    "styled-components": "^6.1.6"
caret(^)에 대해서도 알아보세요!

npm에서 기본 설치시 모든 버전은 캐럿(caret)을 붙인 상태가 기본이다.

캐럿이란 ^1.2.3 와 같이 Semver 앞에 붙은 ^ 특수문자를 가리킨다.

캐럿이 붙은 라이브러리는 버전 업데이트를 했을 때, 최신 minor 버전까지만 업데이트되고 해당 major 버전을 초과하여 업데이트되진 않도록 한다. 즉, 하위 호환성을 유지한다.

^1.2.3 : 1.2.3보다 크거나 같고 2.0.0보다 작은 버전까지만 업데이트한다.

2024-01-11 01:09 UTC, wonsss approved these changes

2024-01-11 01:09 UTC, merged