[박준용] Week7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #199
Opened 2024-01-06 19:19 UTC by mocking-tiger

## 요구사항

-[x] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정했나요?

-[x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요?

-[x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용했나요?

-[x] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이나요?

-[x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용했나요?

-[x] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 “/api/users/1/links?folderId={해당 폴더 ID}”를 활용했나요?

-[x] Mobile에서 “폴더 추가” 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들었나요?

## 주요 변경사항

- folder페이지 제작
- 리액트 라우터 활용

## 스크린샷

배포: https://weekly-mission-part2.vercel.app/

## 멘토에게

- 항상 세심하게 봐주셔서 감사합니다
- 좀 늦었지만 새해 복 많이 받으세요

2024-01-09 13:28 UTC, goldfrosch requested changes
고생하셨습니다! 이전보다 많은 성장이 보여서 리뷰하는 입장에서도 기분이 좋네요 :)
early return이나 styled-components의 활용 .map 함수의 활용 등 피드백이 잘 반영된 모습이 보입니다.

밑에 PR에 대한 changed 요청을 드리니 확인 부탁드립니다~

2024-01-09 13:28 UTC, goldfrosch commented on src/components/AddLink/AddLink.js
> +    <>
[중요도: 낮음] 불필요한 <>(fragment)인 것 같으니 제거하셔도 될 것 같아요

2024-01-09 13:28 UTC, goldfrosch commented on src/components/AddLink/AddLink.js
> +          <label>
[중요도: 중간] 현재 label이 하는 역할이 무엇인지 확인이 필요해보입니다

2024-01-09 13:28 UTC, goldfrosch commented on src/components/FloatingActionButton/FloatingActionButton.js
> +  ) : null;
```suggestion
 if (!showFab) {
   return null;
 }

  return  (
    <>
      <button className="fab" onClick={onClick}>
        폴더 추가
      </button>
      <img src={add} className="floating-add-button" alt="add" />
    </>
  )
```
[중요도: 높음] 만약 특정 조건이 만족하지 못할 때 아무것도 노출시켜주지 않게 하려면 early return 패턴을 이용하시는 것을 추천드립니다. 조금 더 가독성이 좋아집니다.

[중요도: 높음] return null로 아무것도 없는 컴포넌트를 처리하는 이유가 뭘까요? 다른 방식은 없을까요?

2024-01-09 13:28 UTC, goldfrosch commented on src/components/Header/Header.js
> +import { CODEIT_API } from "../../assets/url";
상수화 좋습니다 :)

2024-01-09 13:28 UTC, goldfrosch commented on src/components/Header/Header.js
> +`;
[중요도: 중간] 이거는 컨벤션의 영역이긴 한데요... styled-component를 통해 만들어지는 것은 컴포넌트입니다. 그러니 PascalCase로 이름을 지정하는게 더 좋지 않나라는 생각이 드네요. 동적 스타일 컴포넌트 만드신 것은 좋습니다 :)

2024-01-09 13:28 UTC, goldfrosch commented on src/components/Section/Section.js
> +  const timeDiffs = cardInfo.map((item) => {
map 함수 잘쓰셨네요 고생하셨어요 :)

2024-01-09 13:28 UTC, goldfrosch commented on src/components/UserSection/UserSection.js
> +  });
[중요도: 높음] 해당 값(함수)들은 early return 밑에 작성이 되었네요. 이렇게 썼을 때 어떤 효과가 있었나요?

2024-01-09 13:28 UTC, goldfrosch commented on src/components/UserSection/UserSection.js
> +            <a href="#!">
[중요도: 중간] a 태그의 href attribute 값에 #!가 들어갔는데 이것을 넣은 이유가 뭘까요?

2024-01-09 13:28 UTC, goldfrosch commented on src/index.js
> +root.render(<Main />);
[중요도: 낮음] App의 이름을 바꾼 이유가 있을까요?

2024-01-09 13:28 UTC, goldfrosch commented on src/components/Header/Header.js
> +    <STYLED_HEADER $notFixed={notFixed}>
[중요도: 중간] styled-components의 props의 인자 앞에 $가 붙었네요. 이렇게 사용하는 이유는 뭘까요?

2024-01-09 14:06 UTC, mocking-tiger commented on src/components/UserSection/UserSection.js
> +            <a href="#!">
href에 #만 넣고 실행시 화면 출력에는 이상이 없는데 터미널에 Line 106:13:  The href attribute requires a valid value to be accessible. 라는 경고메시지가 떠서 구글링 해보니까 #!나 {() => false}를 넣어주면 사라진다고 해서 썼습니다!
https://chlolisher.tistory.com/124

2024-01-09 14:08 UTC, mocking-tiger commented on src/index.js
> +root.render(<Main />);
코드잇 강의에서 라우팅 하는 파일을 main.js라고 해놨길래 덜 헷갈리려고 따라했습니다,,

2024-01-09 14:10 UTC, mocking-tiger commented on src/components/Header/Header.js
> +    <STYLED_HEADER $notFixed={notFixed}>
이것도 위에 a태그 경우처럼 출력은 정상적으로 되는데 이번에는 크롬 콘솔에서 자꾸 경고메시지가 떠서 구글링해서 저렇게 하면 없앨 수 있다길래 했습니다!
https://velog.io/@mintmin0320/styled-components-it-looks-like-an-unknown-prop-%EB%AC%B8%EC%A0%9C%EA%B0%80-%EB%90%98%EB%8A%94-props-is-being-sent-through-to-the-DOM-which-will-likely-trigger-a-React-console-error.-%EA%B2%BD%EA%B3%A0-%ED%95%B4%EA%B2%B0%EB%B2%95

2024-01-09 14:15 UTC, mocking-tiger commented on src/components/UserSection/UserSection.js
> +  });
if (!buttonInfo && !cardInfo) {
    return null;
  }

buttonInfo랑 cardInfo는 api에서 받아온 데이터를 할당한 변수인데 데이터가 없을시 렌더링을 방지할 목적으로 사용했습니다

2024-01-10 00:18 UTC, goldfrosch commented on src/components/UserSection/UserSection.js
> +  });
잘 알고 사용하셨군요 좋습니다!

2024-01-10 00:19 UTC, goldfrosch commented on src/components/UserSection/UserSection.js
> +            <a href="#!">
좋습니다. href에 #!를 넣은 이유 자체는 원래는 이동해야하는 링크지만 당장 url이 없어 처리해둔 것으로 인지하겠습니다!

2024-01-10 00:19 UTC, goldfrosch commented on src/index.js
> +root.render(<Main />);
확인했습니다~ 중요한 것은 아니고 이름을 바꿨길래 확인차 여쭤봤습니다!

2024-01-10 00:22 UTC, goldfrosch commented on src/components/Header/Header.js
> +    <STYLED_HEADER $notFixed={notFixed}>
좋습니다 고생하셨어요!

2024-01-13 08:19 UTC, merged