[박지용]week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #20
Opened 2023-12-02 06:10 UTC by jiyong0106

## 요구사항

### 기본

- [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [x] [기본] Netlify에 파일 배포가 아닌 포크한 Github 레포지토리로 연결했나요?
- [x] [랜딩 페이지] 아래로 스크롤 해도 “Linkbrary” 로고와 “로그인” 버튼이 있는 상단 네비게이션 바(Global Navigation Bar)영역이 최상단에 고정되게 했나요?
- [x] [로그인 페이지, 회원가입 페이지 공통] Linkbrary 로고 클릭시 루트 페이지(“/”)로 이동하나요?
- [ ] [로그인 페이지, 회원가입 페이지 공통] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일한가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus in 일 때, 테두리 색상이 파랑색인가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus out 일 때, 테두리 색상이 회색인가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] SNS 아이콘들은 클릭시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동하나요?
- [x] [로그인 페이지] “회원 가입하기”는 클릭시 “/signup” 페이지로 이동하나요?
- [x] [회원가입 페이지] “로그인 하기”는 클릭시 “/signin” 페이지로 이동하나요?

### 심화

- [ ] [심화] palette에 있는 color값들을 css 변수로 등록하고 사용했나요?
- [x] [심화] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가했나요?

## 주요 변경사항

- 로그인/ 회원가입 페이지 추가
- 각 페이지 링크 참조하여 연결

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-02 15:46 UTC, airman5573 requested changes
위클리 미션 1,2 주차 수행하시느라 수고 많으셨습니다.

다만, 종종 왜 작성했는지 알기 어려운 코드들이 보입니다.
때로는 피그마에서 그대로 복붙한것 같은 느낌도 들어요.

브라우저는 피그마랑 다르게 모니터 크기가 다양하기 때문에, 그대로 가져다 쓰는것 보다는
요소의 내부 크기만 지정해 주고 가로/세로는 자연스럽게 정해지도록 하는 방식이 좋습니다.

유튜브에서 HTML&CSS 관련 예제들을 찾아보시는걸 추천드립니다.
https://www.youtube.com/watch?v=QRrPE9aj3wI 이 영상도 괜찮아 보여요.

전반적으로 수정 부탁드립니다! 감사합니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +  display: flex;
들여쓰기에 일관성이 필요합니다. 4 space 혹은 2 space로 통일해주세요.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    width: 100%;
`width: 100%`는 없어도 되는 스타일링 같습니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +  height: 1020px;
header에는 nav만 넣고, "세상의 모든 정보를 쉽게 저장하고 관리해보세요" 이 부분은 따로 분리하는게 좋을것 같아요. (꼭 그런건 아니지만, 경험상 분리된 경우가 많았습니다)

참고
- https://live.lge.co.kr/
- https://developer.mozilla.org/ko/docs/Web/HTML/Element/header

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +  overflow: hidden;
overflow: hidden은 왜 작성해 주셨나요?
없어도 되는 스타일링 같아서 여쭈어 봅니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +  align-items: center;
flex를 잘 사용하셨네요 👍

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +  position: fixed;
html 구조가 달라져야 하지만,
sticky 라는 속성도 있으니 참고 바랍니다.
참고: https://coding-factory.tistory.com/951

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    background: var(--gra-purpleblue-to-skyblue, linear-gradient(91deg, #6D6AFE 0.12%, #6AE3FE 101.84%));
css variable 사용이 좋네요 👍

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    width: 128px;
일반적으로 가로길이를 딱 정해주지는 않고, 패딩으로 길이를 조절합니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    display: flex;
flex는 안하셔도 될것 같습니다.
flex는 주로 자식들을 정렬할때 사용하는데 .login 은 자식이 없기 때문입니다.
width가 필요하시다면, block을 추천드립니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    gap: 10px;
flex를 사용하셔도 자식요소가 없기 때문에 gap도 불필요합니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +.title{
각 css 속성들의 필요성을 다시 검토해 보시기 바랍니다.
제가 테스트 해보았을때 width, padding은 없어도 동일하게 보이네요.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    height: 160px;
일반적으로 가로길이, 높이까지 다 지정할 필요는 없습니다.
font-size와 line-height만 지정하시고 높이나 가로길이는 자연스럽게 변할 수 있도록 해주세요.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    padding: 120px 461px 50px 461px;
max-width로 가로길이를 잡고, 위아래만 패딩으로 간격 조절해주세요.
<img width="1144" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/f61141df-b9ca-4d42-8666-77f356072152">

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +  .icorn {
오타인것 같아요.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    height: 2rem;
px로 단위를 통일해주세요.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.html
> +           <span class="link_save_color"> 원하는 링크를 </span><br>
`원하는 링크를` 양 옆으로 빈 스페이스바를 제거해주세요. 실제 브라우저에 이 스페이스바가 표현되서 종종 원하는 디자인과 다른 결과가 나오는 경우가 있습니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.html
> +<html lang="en">
한글 위주이기 때문에 lang="ko"가 더 어울리는것 같습니다.
주로 검색 엔진에게 "이 페이지는 한글 문서야" 라고 알려주는 용도로 사용됩니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly1_mission/weekly1.html
> +        <div class="icorn">
리스트라서 div보다는 ul가 더 어울립니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/FAQ.html
> +    <title>FAQ</title>
타이틀 설정 좋습니다 👍

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2.css
> +    box-sizing: border-box;
👍

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2.css
> +    margin: 0 auto;
margin: 0 대신 auto까지 넣으신 이유가 있나요?
0으로 충분해 보여 여쭈어 봅니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2.css
> +    font-style: normal;
font-style을 normal로 지정한 이유가 있으신가요?

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2.css
> +
가독성을 위해 빈줄을 지워주세요.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2.css
> +    position: absolute;
부모가 flex 이기 때문에, absolute까지는 쓰지 않으셔도 될것 같습니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2_signin.html
> +            <div gap_box>
class가 빠졌습니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2_signin.html
> +                <img src="/3-Weekly-Mission/weekly1_mission/logo.svg" class="logo">
src에 `/3-Weekly-Mission/` 부분이 반복적으로 보이는데요, 제가 파일을 받았을때는 이미지가 안나옵니다.
혹시 잘못 넣으신걸까요?

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2_signin.html
> +                <label for="emai;">이메일</label>
오타가 있습니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2_singup.html
> +                <div class="pass">
password로 수정이 필요해 보입니다.

2023-12-02 15:46 UTC, airman5573 commented on weekly2_mission/weekly2_singup.html
> +                    <input id="password_check" name="password_checck" type="password">
`password_checck` 오타가 있습니다.

2023-12-04 11:40 UTC, jiyong0106 commented on weekly1_mission/weekly1.css
> +    height: 160px;
화면을 줄이면 줄바꿈이 되는 것을 해결하고 싶은데 이럴 경우에 white-space: nowrap을 사용하면 될까요?

2023-12-04 12:29 UTC, airman5573 commented on weekly1_mission/weekly1.css
> +    height: 160px;
좋은 질문 해주셔서 감사해요.
<img width="857" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/a0fcaa2e-3d1a-4a51-b177-bc393689db72">

저도 잘 몰랐는데, 이렇게 뚫고 나오네요.

참고: https://www.daleseo.com/css-white-space/#google_vignette

2023-12-06 05:45 UTC, merged