[이윤성] Week7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #201
Opened 2024-01-07 03:45 UTC by yunsunglee2

## 요구사항

### 기본
- [] PC, Tablet, Mobile 디자인에 해당하는 폴더 페이지를 만들어 주세요.
- [ x ] 폴더 페이지에서 저장된 링크가 없는 경우의 디자인도 만들어 주세요.
- [ x ] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정해 주세요.
- [ x ] 카드 컴포넌트에 별모양 버튼, 케밥 버튼도 추가해 주세요. 다만, 버튼의 기능은 추후 만듭니다.
- [ x ] 링크 추가하기, 폴더 추가, 공유, 이름 변경, 삭제 버튼들의 기능은 추후 만듭니다.
- [ x ] Github에 위클리 미션 PR을 만들어 주세요.
- [ x ] React를 사용해 진행합니다.

### 심화

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게
1. Header에서 로그인 버튼을 클릭하면 상위 컴포넌트의 state를 변경해 조건부 렌더링을 통해 유저 아바타를 화면에 출력 하고 싶음 + 버튼이 안보이다가 버튼이 생기게 하기 

2. Main에서 즐겨찾기 이외에 다른 버튼을 클릭하면 id를 검색해 다른 파일들을 불러오게 구현 

등등.. 이번주 과제하면서 어떻게 구현하면 되겠다! 하는 것들이 많았지만 막상 만들어놓은 구조를 깨버리고 다시 수정하기가 쉽지 않더군요.. 
뭔가 망설여 지기도 하고 여러 컴포넌들이 상태를 공유해서 상태마다 다른 값들을 화면에서 보여주고 싶었는데 아쉽습니다.. 
아직 리액트 공부를 많이 못해서 미완성인 상태로 제출합니다.. 

- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-09 13:14 UTC, goldfrosch requested changes
고생하셨습니다! 이전보다 많이 실력이 늘어난 것이 조금씩 보이는군요!
밑에 Request-Changes 요청 드리니 확인 부탁드립니다.

2024-01-09 13:14 UTC, goldfrosch commented on src/header/Header.css
> +.Header .box01 .item01 {
👍

2024-01-09 13:14 UTC, goldfrosch commented on src/header/AddInput.js
> +          <button><div className="text">추가하기</div></button>
```suggestion
          <button><span className="text">추가하기</span></button>
```
[중요도: 중간] 개인적으로 텍스트 관련에 스타일을 먹일 때는 span, p같은 것을 사용하는 것을 추천드립니다~

2024-01-09 13:14 UTC, goldfrosch commented on src/header/Header.js
> +            <Account loginState={setUserState}/>
[중요도: 높음] loginState의 정확한 역할과 왜 여기에 setState 액션을 넣었는지가 궁금합니다.

2024-01-09 13:14 UTC, goldfrosch commented on src/main/Main.js
> +    data.length === 0 ? setLoad(1) : setLoad(2);
[중요도: 높음] load에 1, 2가 들어가는 이유가 뭘까요?

2024-01-09 13:14 UTC, goldfrosch commented on src/main/Main.js
> +    }
[중요도: 높음] 이것도 어떻게 보면 하드코딩 같네요.
getMyInfo에 들어가는 정보들에 id를 서버에서 가져올수는 없었을까요?

2024-01-09 13:14 UTC, goldfrosch commented on src/main/api/allApi.js
> +  return datas;
```suggestion
  return await response.json();
```
[중요도: 중간] 굳이 상수를 선언해서 return할 필요는 없어보입니다.

2024-01-09 13:14 UTC, goldfrosch commented on src/main/api/allApi.js
> +const API_BASE_URL_FOLDER_ALL = 'https://bootcamp-api.codeit.kr/api/users/1/links';
```suggestion
const API_BASE_URL = 'https://bootcamp-api.codeit.kr' //외부에 선언하고  import하는 형식
const API_FOLDER_ALL = `${API_BASE_URL }/api/users/1/links`;
```

[중요도: 중간] API_BASE_URL을 포함한 정보를 한번에 선언하는 거라면 의미가 크게 있어 보이지는 않습니다.
[중요도: 높음] 혹시 /api/users/1/links에 있는 숫자 1은 직접 주입하신 걸까요? 아니면 본인이 넣은걸까요? 만약 본인이 넣은거라면 수정이 필요해보입니다. 서버에서 가져온 정보면 아마 localStorage 혹은 저장된 유저 정보를 import해서 쓰는게 좋아보입니다. (어찌보면 상태관리의 개념으로 넘어갈수도...)

밑에도 내용은 비슷해 밑 파일의 내용들은 생략하겠습니다.

2024-01-09 13:14 UTC, goldfrosch commented on src/main/fnc.js
> +      <img src="" alt="" />
[중요도: 높음] 빈 이미지 태그의 의미는 무엇인가요?

2024-01-09 13:14 UTC, goldfrosch commented on src/header/Logo.js
> +    window.location.href = '/folder'
[중요도: 높음] React-Router를 쓰지 않은 이유가 뭘까요?
React-router을 통해 페이지를 이동하는 것과 location.href를 통해 이동하는 것의 차이는 뭘까요?

2024-01-09 13:14 UTC, goldfrosch commented on src/header/Account.js
>      })
[중요도: 중간] then을 2번 사용하셨네요. 여기는 왜 2번 사용하셨나요? 어떤 효과가 있었을까요?

2024-01-14 07:59 UTC, yunsunglee2 commented on src/header/Header.js
> +            <Account loginState={setUserState}/>
과제 의도와 다르게 개인적으로 
로그인 버튼 클릭 -> 로그인 상태로 변경 -> 로그인 상태 시 화면 변경
로그아웃 상태: 인풋창 출력
로그인 상태: 유저 이름, 목록이름 화면 출력 
이렇게 변경해주고 싶어서 고민하다가 수정하지 못한채 풀리퀘스트 드렸습니다.

2024-01-14 08:04 UTC, yunsunglee2 commented on src/main/Main.js
> +    data.length === 0 ? setLoad(1) : setLoad(2);
1. 페이지에 처음 들어왔을 때 
2. 파일에 목록이 없을 때  
3. 파일에 목록이 있을 때 
세가지 경우로 나눠서 화면을 출력하고 싶은 마음에 좋지 않은 방법으로 코딩을 했습니다. 지금은 삼항 연산자로 수정하였습니다.

2024-01-14 08:08 UTC, yunsunglee2 commented on src/main/Main.js
> +    }
id 값을 가져와서 상태값을 변경해 줬습니다!

2024-01-14 08:12 UTC, yunsunglee2 commented on src/main/api/allApi.js
> +  return datas;
오호... 이렇게 해도 되네요 감사합니다!

2024-01-14 08:24 UTC, yunsunglee2 commented on src/main/api/allApi.js
> +const API_BASE_URL_FOLDER_ALL = 'https://bootcamp-api.codeit.kr/api/users/1/links';
수정 후 파일을 하나로 통합했습니다!

2024-01-14 08:25 UTC, yunsunglee2 commented on src/main/fnc.js
> +      <img src="" alt="" />
앗... 이미지로 넣어줄 생각으로 미리 만들어 놓았다가 수정하지 못하고 그대로 올렷네요

2024-01-14 08:27 UTC, yunsunglee2 commented on src/header/AddInput.js
> +          <button><div className="text">추가하기</div></button>
88cf1e9acb5fa37f76130100f71dd2c23aa78440 
넵 참고하겠습니다 수정 완료했습니다

2024-01-14 09:15 UTC, yunsunglee2 commented on src/header/Account.js
>      })
fetch함수와 json()함수가 모두 비동기 방식이기 때문입니다.
첫번째 then에서는 자바스크립트를 json으로 바꿔주고 완료되면 
두번째 then에서 실행돼야하기 때문입니다!

2024-01-14 09:20 UTC, yunsunglee2 commented on src/header/Logo.js
> +    window.location.href = '/folder'
React-router는 애플리케이션 상태를 유지하며 페이지 새로고침을 하지 않고 HTTP요청을 보내지 않습니다.
window.location.href는 HTTP요청과 페이지 새로고침을 새롭게 하며 애플리케이션의 상태를 변경합니다. 페이지 이동시 필요에 따라 골라서 사용하면 될것같습니다. 
저는 단순히 로고를 클릭하면 페이지 이동하기 위한 목적으로 사용했으므로 React-routr로 이동하는 방법으로 수정 했습니다!
105efa9462375c119a629aef78e7bd8350ab7b87

2024-01-16 06:39 UTC, goldfrosch commented
질문에 대한 답변이 늦었네요 ;-; 정리하고 있다가 미처 놓쳐 지금이라도 전달드립니다.

Q. Header에서 로그인 버튼을 클릭하면 상위 컴포넌트의 state를 변경해 조건부 렌더링을 통해 유저 아바타를 화면에 출력 하고 싶음 + 버튼이 안보이다가 버튼이 생기게 하기

A. 말씀하신 부분을 완벽하게 이해한 것은 아니나, state의 관리를 상위 컴포넌트에서 관리를 하고 싶다라고 이해했습니다.
보통 이런 경우는 useState의 인자 (state, setState)를 props으로 넣어서 해결합니다. 이렇게 되면 deps가 깊어 문제가 될 수 있는데 이런 deps가 깊어지는 이슈를 방지하기 위해 보통 상태관리(contextAPI, redux 등...)를 활용하곤 합니다.

Q. Main에서 즐겨찾기 이외에 다른 버튼을 클릭하면 id를 검색해 다른 파일들을 불러오게 구현

A. 두개의 예상 질문 케이스로 보입니다. 두개에 대해 답변 드립니다.
  1.  방법 자체에 대한 질문?
    보통 이렇게 하는 경우는 Main쪽에서 폴더를 클릭 시 그 id를 state로 저장하고 API에서 가져온 폴더 데이터 리스트 or 폴더 개별 데이터 를 노출시키게 합니다!
  2. 이벤트 전파 관련 질문?
    즐겨찾기 이외에 버튼을 눌러도 즐겨찾기만 동작되거나 하는 것 때문에 요청 주신 것으로도 보입니다. 코드만 봐서는 정확하게 이해가 어려워 이해한대로 답변을 드리자면...
    즐겨찾기의 element의 위치에 따라 달라질 수는 있지만 이런 경우는 보통 이벤트 버블링을 방지하는 것으로 시작합니다.
    이벤트 버블링: 이벤트가 상위 엘리먼트로 전파하는 것을 의미하는데 이것을 방지하려면 버튼이나 a태그 같은 곳에서 onClick, onChange 등 앞에 on이 붙는 attributes의 고유한 parameter인 event객체 안의 stopPropagation()를 사용하시면 됩니다!
    
말씀하신게 이 두가지가 아니라면 다시 말씀해주세요 감사합니다!

2024-01-17 00:36 UTC, goldfrosch commented on src/header/Header.js
> +            <Account loginState={setUserState}/>
보통 이런 처리의 props명은
onChangeLoginState: (loginState: boolean) => void; // 로그인, 로그아웃 시 의 처리
저라면 로그인 상태가 변할때라는 뜻으로 on~~~식으로 쓸 것 같습니다.

2024-01-17 00:37 UTC, goldfrosch commented on src/main/api/allApi.js
> +  return datas;
네 좋습니다! 사실 .json() 함수가 비동기가 아닌지라 await을 빼도 되고, 굳이굳이 재선언할 필요는 없는거니까요~

2024-01-17 00:45 UTC, goldfrosch commented on src/header/Account.js
>      })
.json이 비동기 인것을 몰랐었네요... ;-; 저는 동기적으로 처리라고 알고 있었는데 확인해보니 스트림 바이트 처리 때문에 비동기로 처리는 한다라고 적혀있어 저도 배우고 갑니다 확인했습니다!

2024-01-18 00:02 UTC, goldfrosch approved these changes
Approve and merge 진행하겠습니다!

2024-01-18 00:02 UTC, merged