[노진석] week7 수정중..
codeit-bootcamp-frontend/3-Weekly-Mission pull request #202
Opened 2024-01-07 08:07 UTC by SiWooJinSeok

## 요구사항

### 기본

- [x] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정했나요?
- [x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용했나요?
- [x] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이나요?
- [x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용했나요?
- [x] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 “/api/users/1/links?folderId={해당 폴더 ID}”를 활용했나요?
- [x] Mobile에서 “폴더 추가” 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들었나요?

## 주요 변경사항

- test, express, web-vitals 라이브러리 제거
- "react-router-dom": "^6.21.1" 라이브러리 설치
- "camelcase": "^8.0.0" 라이브러리 설치
- folderPage 추가 
- a 태그 Link 태그로 변경
- module css 사용
- useFetchData 커스텀 Hook 생성 
- 케밥 버튼 hover시 버튼 2개 생김 (스샷을 찍지 못하겠음)

##설치 및 실행 방법!

1. 아래 사진을 참고하셔서 클릭 후 이동해주세요!
설치 방법 1

2. 밑에 사진 방법으로 다운 받아 주세요!
설치 방법 2

3. 압축 해제 후 폴더로 이동해주세요!
4. VScode를 실행 시켜 터미널을 열어 주세요!
5. npm install react-scripts 를 다운로드 해주세요!
6. 다운이 완료 되었으면 npm run start 명령어를 이용해서 실행 시켜주세요!

## 스크린샷
![캡처 1](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/8bbc395e-c414-4372-8e7a-460859a76c20)
![캡처 2](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/9fe54e0d-53d3-44dc-a003-d8d2a8c958b9)
![캡처 3](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/096b5933-d691-45ae-825d-b9dfb06a1e15)
![캡처 4](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/410f3069-25cd-4de8-af0d-e69dc95b2595)
![캡처 5](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/3c5284e2-9a53-4951-a5d3-45a123865cbc)
![캡처 6](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/815d47c8-9523-44cf-a6f9-3126d36facdd)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-08 17:54 UTC, wonsss requested changes
수고 많으셨습니다. 진석님! 
코드를 가독성 좋게 잘 작성해주셨네요. 👍 
리뷰 남겼습니다. 반영 후 목요일 전까지 재리뷰 요청주시면 좋을 것 같아요. 😄

2024-01-08 17:54 UTC, wonsss commented on package.json
> +    "camelcase": "^8.0.0",
카멜케이스 라이브러리를 사용하셨군요. 
외부 라이브러리를 적절하게 잘 쓰는 것도 좋은 방법이에요.
왜 선택하셨고 어떤 점이 좋으셨는지 설명해주실 수 있으실까요?

2024-01-08 17:54 UTC, wonsss commented on package.json
> +    "react-router-dom": "^6.21.1",
"^6.1.6" 이런 버전 방식을 Semantic Versioning이라고 합니다.  
왜 중요하고 어떻게 사용하는 걸까요?

2024-01-08 17:54 UTC, wonsss commented on package.json
>      ]
사용하지 않는 설정을 지워주셨네요 👍

2024-01-08 17:54 UTC, wonsss commented on src/App.js
> +          <Route path="folder" element={<FolderPage />} />
page 컴포넌트 이름을 다른 컴포넌트와 구분되도록 `000Page` 처럼 지으신 것 좋네요

2024-01-08 17:54 UTC, wonsss commented on src/apis/api.js
> +const BASE_URL = "https://bootcamp-api.codeit.kr/api/";
상수 분리 좋습니다!

2024-01-08 17:54 UTC, wonsss commented on src/apis/api.js
> +}
가독성이 좋네요.

2024-01-08 17:54 UTC, wonsss commented on src/components/CtaButton/CtaButton.jsx
CtaButton 이름 좋네요. 왜 이 이름을 사용하셨는지 궁금합니다.

2024-01-08 17:54 UTC, wonsss commented on src/pages/FolderPage.jsx
> +import styled from "./FolderPage.module.css";
module css 를 사용해보셨군요.  👍 
장단점을 설명해주실 수 있으실까요?

2024-01-08 17:54 UTC, wonsss commented on src/pages/FolderPage.jsx
> +  );
이것도 컴포넌트 분리하는 것은 어떨까요?

2024-01-08 17:54 UTC, wonsss commented on src/hooks/useFetchData.js
> +      if (!result) throw new Error("없습니다!");
if (condition) doSomething()과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다.

2024-01-08 17:54 UTC, wonsss commented on src/pages/FolderPage.jsx
> +    useFetchData(getLinkList);
배열이 아니라 객체로 커스텀훅 반환 받을 수 있습니다. 반환값이 3개 이상이면 객체 반환이 더 직관적이에요.

 const {cardListItem, handleEntireData, handleIdData} =
    useFetchData(getLinkList);

2024-01-08 17:54 UTC, wonsss commented on src/hooks/useFetchData.js
> +  };
이 함수에서는 async await가 필요없을 것 같아요.

2024-01-08 17:54 UTC, wonsss commented on src/hooks/useFetchData.js
> +  const [data, setData] = useState(null);
커스텀훅을 잘 만드셨고, 여기에 필요한 상태를 잘 두셨네요! 👍

2024-01-08 17:54 UTC, wonsss commented on src/hooks/useFetchData.js
> +  };
그리고 그냥 fetchData를 훅에서 반환해줘도 될 것 같아요.

2024-01-08 17:54 UTC, wonsss commented on src/hooks/useFetchData.js
> +export default function useFetchData(apiFunction) {
이 훅의 매개변수로 apiFunction을 받을 필요가 있을까요?

이 훅의 내부 함수로 fetchData 하나만 두고, 그 함수의 매개변수로 apiFunction을 받도록 하면 될 것 같아요.

2024-01-08 17:54 UTC, wonsss commented on src/hooks/useFetchData.js
> +      const result = await apiFunc(id);
fetchData와 거의 동일한 역할인데, 다만 매개변수로 apiFunction 외에 id를 하나 더 받는다는 점이 다르네요. 그러면 매개변수를 apiFunction 하나만 받도록 하고, 해당 매개변수에 전달하는 인자를 `() => apiFunction(id)`  처럼 id가 전달된 익명함수로 넘겨주는 것은 어떨까요?

그리고 이렇게 하게 되면 위에 있는 fetchData 함수와 차이가 없어지니 fetchData 함수 하나로 통일시키면 될 것 같네요.

2024-01-08 17:54 UTC, wonsss commented on src/utils/imageData.js
> +export default imageData;
이렇게 하신 이유가 궁금해요! 😄

2024-01-08 17:54 UTC, wonsss commented on src/components/FolderListButton/FolderListButton.jsx
> +            key={item.id}
key를 잘 넣어주셨네요.

2024-01-08 17:54 UTC, wonsss commented on src/components/Card/Card.jsx
> +  const imgSource = imageSource ? imageSource : imageData.defaultImg;
`const imgSource = imageSource ?? imageData.defaultImg;`
  이렇게 해도 같은 효과일 것 같네요. 
  null  병합 연산자에 대해 확인해보세요~
https://ko.javascript.info/nullish-coalescing-operator

2024-01-08 17:54 UTC, wonsss commented on src/components/Card/Card.jsx
> +      <Link to={url} rel="noreferrer noopener" target="_blank">
리액트라우터돔의 Link 컴포넌트를 잘 사용해주셨네요!

2024-01-08 17:57 UTC, wonsss commented
>아직은 props drilling이 심하지 않은 것 같고 컴포넌트가 많이 있지 않아서 불편하지는 않지만, 혹시 여기서 context를 사용할려면 어떤 것을 context로 만들면 좋을 지 고민입니다! 아직 context를 이용하는 방식이 잘 이해되지 않은 것 같습니다!

네 말씀대로 props drilling이 심하지 않으면 context api 같은 것을 사용하실 필요가 없습니다. 지금처럼 state 끌어올리기 방법으로 컴포넌트 간 상태 관리하는 방법이 일반적이고 더 가독성에 좋습니다. 
context는 props drilling이 2depth나 3depth 이상으로 심하거나 의도하는 리액트 컴포넌트 패턴(ex, 컴파운드 컴포넌트)이 있다면 사용하곤 합니다. 심하다는 props drilling의 기준은 사람이나 상황마다 다를 수는 있습니다.

> 여기서 더 리펙토링 하려면 어떤식으로 해야할지 모르겠습니다..! 지금은 이게 최선인 것 같습니다. 수정해야 할 부분이나 추가할 부분이 있으면 알려주세용..! 미리 감사합니다!

이번 미션에서 구현해야 할 부분, 그리고 이전리뷰에서 제가 말씀드렸던 부분을 잘 반영해주셔서 감사합니다. 
리뷰 드린 내용 확인해주시고, 반영해주세요~
css-module 방식 잘 사용해주셨고, 나중에 css-in-js 방식으로 리팩터링도 고민해보세요!
현업에서는 css-in-js를 더 많이 사용합니다.

2024-01-08 18:33 UTC, wonsss commented on src/utils/camelCaseUtil.js
> +}
직접 유틸을 만드셨군요. 👍 

직접 유틸함수를 만드는 것도 연습에는 좋으나, 나중에 에러가 날 가능성도 큽니다.
이런 경우에는 이전에 말씀드린 camelcase-keys 라이브러리를 사용하는 것도 권장드립니다. 
https://www.npmjs.com/package/camelcase-keys
해당 라이브러리 설치하시고 아래와 같이 사용해보세요. 라이브러리 설명을 보니 객체가 중첩되어 있으므로 재귀적으로 중첩되어 있는 key들을 모두 카멜케이스로 변경하려면 deep: true 옵션도 넣어주셔야 하네요.

```
import camelcaseKeys from 'camelcase-keys';

 const formattedData = camelcaseKeys(data, { deep: true });

```

2024-01-10 06:54 UTC, SiWooJinSeok commented on package.json
> +    "camelcase": "^8.0.0",
api요청시 create_at createdAt처럼 페이지마다 다르게 전달되기에 통일 시킬 수 있는 방법이 없을까 하여 적용 시켜보았습니다!

2024-01-10 07:06 UTC, SiWooJinSeok commented on package.json
> +    "react-router-dom": "^6.21.1",
잘 몰라서 찾아봤습니다! ^6.1.6 으로 가정하면 처음 6은 주 버전이고 1은 호환성이 유지되는 기능추가된 버전이고, 마지막 6은 버그같은 것을 수정한 버전으로 알게되었습니다. 협업시 버전 호환성 때문에 중요한 것 같습니다. 제가 잘 알고 있는 것인지는 잘 모르겠습니다. 부족한 부분이 있다면 추가 설명 부탁드립니다!

2024-01-10 07:07 UTC, SiWooJinSeok commented on package.json
>      ]
넵! 지금은 사용할 일이 없을 것 같아서 지웠습니다!

2024-01-10 07:07 UTC, SiWooJinSeok commented on src/App.js
> +          <Route path="folder" element={<FolderPage />} />
감사합니다!

2024-01-10 07:08 UTC, SiWooJinSeok commented on src/apis/api.js
> +const BASE_URL = "https://bootcamp-api.codeit.kr/api/";
코드잇 강의 보다가 상수 분리하는 부분이 있기에 저도 한번 시도해봤습니다!

2024-01-10 07:08 UTC, SiWooJinSeok commented on src/apis/api.js
> +}
감사합니다!

2024-01-10 07:09 UTC, SiWooJinSeok commented on src/components/CtaButton/CtaButton.jsx
사실 버튼 디자인이 어딘가에 쓰일 것 같아서 이름을 고민하다가 피그마에 CTA라고 써져있기에 검색해봤는데 나쁘지 않은 것 같아서 CtaButton이라고 지어봤습니다!

2024-01-10 07:14 UTC, SiWooJinSeok commented on src/pages/FolderPage.jsx
> +import styled from "./FolderPage.module.css";
개인적으로 장점으로는 클레스 이름같은 거 지을 때 과감하게 지을 수 있어서 편했습니다. 클래스이름에 대한 고민을 적게 해준 것이 좋았습니다. 단점으로는 아무래도 파일이 많아진다는 것이였습니다.

2024-01-10 07:30 UTC, SiWooJinSeok commented on src/pages/FolderPage.jsx
> +  );
[refactor: NoLinkBlock.jsx로 컴포넌트화](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/0a47c2c0c12d08af9d45670bb3214b52d6f59af5) 여기서 수정했습니다!
처음 만들 때 이것도 컴포넌트로 분리해도 되나 싶었는데 모범답안에서도 분리가 되어 있더라구요!

2024-01-10 08:55 UTC, SiWooJinSeok commented on src/pages/FolderPage.jsx
> +    useFetchData(getLinkList);
[refactor: useFetchData.js 수정 및 useEffectOnce.js 생성](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/bb040954dd942c7e1c4cc2264f11b2bed2df0e63) 여기서 같이 수정했습니다!

2024-01-10 08:55 UTC, SiWooJinSeok commented on src/hooks/useFetchData.js
> +  };
[refactor: useFetchData.js 수정 및 useEffectOnce.js 생성](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/bb040954dd942c7e1c4cc2264f11b2bed2df0e63) 여기서 같이 수정했습니다!

2024-01-10 08:56 UTC, SiWooJinSeok commented on src/hooks/useFetchData.js
> +  const [data, setData] = useState(null);
[refactor: useFetchData.js 수정 및 useEffectOnce.js 생성](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/bb040954dd942c7e1c4cc2264f11b2bed2df0e63)
감사합니다! 여기서 멘토링때 들었던  error와 isLoading도 넣어봤습니다!

2024-01-10 08:58 UTC, SiWooJinSeok commented on src/hooks/useFetchData.js
> +export default function useFetchData(apiFunction) {
[refactor: useFetchData.js 수정 및 useEffectOnce.js 생성](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/bb040954dd942c7e1c4cc2264f11b2bed2df0e63) 일단 이렇게 수정했습니다. 이것 저것 시도해봤는데 순수한 커스텀 훅으로 만들기가 쉽지 않네요 ㅠㅠ 일단 folder페이지 전용 커스텀훅으로 생각해야할 것 같습니다!

2024-01-10 08:59 UTC, SiWooJinSeok commented on src/hooks/useFetchData.js
> +      const result = await apiFunc(id);
[refactor: useFetchData.js 수정 및 useEffectOnce.js 생성](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/bb040954dd942c7e1c4cc2264f11b2bed2df0e63) 여기서 같이 수정했습니다! 
익명함수로 데이터를 넣어서 보내는 방식은 생각지도 못했네용! 하나 더 배워갑니다!

2024-01-10 09:02 UTC, SiWooJinSeok commented on src/utils/imageData.js
> +export default imageData;
개인적인 니즈가 있었습니다! 폴더구조를 바꿀 때나 이미지를 수정할 때 등 이미지를 사용하는 모든 컴포넌트를 수정해야하는 점이 귀찮았던 것도 있었고 import문이 늘어나면서 한곳에서 관리하면 좋을 것 같다는 생각에 이미지들을 한곳에 모아봤습니다!

2024-01-10 09:03 UTC, SiWooJinSeok commented on src/components/FolderListButton/FolderListButton.jsx
> +            key={item.id}
넵! 감사합니다!

2024-01-10 09:07 UTC, SiWooJinSeok commented on src/components/Card/Card.jsx
> +  const imgSource = imageSource ? imageSource : imageData.defaultImg;
[chore: card컴포넌트 null병합 연산자로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/6eac283f9220d86b1432c2bfaa4e40a60d916c80) 여기서 수정했습니다!
좋은 정보 감사합니다!

2024-01-10 09:09 UTC, SiWooJinSeok commented on src/components/Card/Card.jsx
> +      <Link to={url} rel="noreferrer noopener" target="_blank">
넵! 어렵지 않게 적용했습니다!

2024-01-10 09:18 UTC, SiWooJinSeok commented on src/utils/camelCaseUtil.js
> +}
[feat: camelcase라이브러리 제거 및 camelcase-key라이브러리 설치](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/55921f94816f502e845d0ac5ece3f7da0532cbbf) 여기서 기존라이브러리 삭제 후 추가했습니다. 라이브러리가 따로 있는줄 몰랐었네용.. ㅎㅎ 좋은 정보 감사합니다!

2024-01-10 09:27 UTC, SiWooJinSeok commented on src/hooks/useFetchData.js
> +      if (!result) throw new Error("없습니다!");
[refactor: useFetchData.js 수정 및 useEffectOnce.js 생성](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/202/commits/bb040954dd942c7e1c4cc2264f11b2bed2df0e63) 여기서 같이 수정했습니다!

2024-01-11 00:54 UTC, wonsss commented on package.json
> +    "react-router-dom": "^6.21.1",
넵 맞습니다! 추가로 caret(^)의 역할에 대해 알아보세요😊

npm에서 기본 설치시 모든 버전은 캐럿(caret)을 붙인 상태가 기본이다.

캐럿이란 ^1.2.3 와 같이 Semver 앞에 붙은 ^ 특수문자를 가리킨다.

캐럿이 붙은 라이브러리는 버전 업데이트를 했을 때, 최신 minor 버전까지만 업데이트되고 해당 major 버전을 초과하여 업데이트되진 않도록 한다. 즉, 하위 호환성을 유지한다.

^1.2.3 : 1.2.3보다 크거나 같고 2.0.0보다 작은 버전까지만 업데이트한다.

2024-01-11 00:55 UTC, wonsss commented on src/components/CtaButton/CtaButton.jsx
네 cta 용어 뜻에 대해 한번 검색해보세요! 👍

2024-01-11 01:02 UTC, wonsss commented on src/utils/imageData.js
> +export default imageData;
그러면 해당 파일의 위치를 이미지 파일이 있는 폴더 내에 함께 두는 것은 어떨까요?

2024-01-11 01:03 UTC, wonsss approved these changes

2024-01-11 01:04 UTC, merged

2024-01-11 02:20 UTC, SiWooJinSeok commented on package.json
> +    "react-router-dom": "^6.21.1",
감사합니다! ㅎㅎ