[이시열] Week7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #203
Opened 2024-01-07 09:12 UTC by siyeol97

## 요구사항

### 기본

- [x] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정했나요?
- [x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용했나요?
- [x] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이나요?
- [x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용했나요?
- [x] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 “/api/users/1/links?folderId={해당 폴더 ID}”를 활용했나요?
- [x] Mobile에서 “폴더 추가” 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들었나요?
## 주요 변경사항
- css 파일 삭제, styled-components 로 변경
- Router 추가
- 커스텀 훅 추가
## 설치 및 실행 방법
```
git clone --branch part2-이시열-week7 https://github.com/siyeol97/3-Weekly-Mission.git
```
```
npm i
```
```
npm run start
```
## Netlify URL
https://siyeol-codeit-linkbrary.netlify.app/
## 스크린샷
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/6e333852-246c-4235-acfc-6908610210d1)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/0dfb8ea8-06f6-4ba8-b685-ff02b784c8f6)
## 멘토에게
- state와 props 제어를 너무 복잡하게 한 것 같아요. 이럴 때 Zustand나 redux를 사용하는 건가요?

2024-01-08 18:34 UTC, wonsss requested changes
수고 많으셨습니다. 시열님! 
PR 메세지에 설치 방법 등 해당 프로젝트에 잘 모르는 분이 보더라도 이해할 수 있도록 잘 작성해주셨네요. 코드도 깔끔하네요  👍 
리뷰 남겼습니다. 반영 후 목요일 전까지 재리뷰 요청주시면 좋을 것 같아요. 😄

2024-01-08 18:34 UTC, wonsss commented on netlify.toml
> +  status = 200
netlify 배포를 위해 관련 설정을 잘 넣어주셨네요👍 
이게 왜 필요하고 어떤 효과를 내는지 설명해주실 수 있으실까요?

2024-01-08 18:34 UTC, wonsss commented on .eslintrc.json
> +    "operator-linebreak": "off"
해당 규칙을 설정한 이유가 궁금해요.

2024-01-08 18:34 UTC, wonsss commented on package.json
> +    "camelcase": "^8.0.0",
카멜케이스 라이브러리르 사용하셨군요. 👍 
왜 사용하셨고 어떤 점이 좋으셨나요?

2024-01-08 18:34 UTC, wonsss commented on package.json
> +    "react-router-dom": "^6.21.1",
"^6.1.6" 이런 버전 방식을 Semantic Versioning이라고 합니다.  
왜 중요하고 어떻게 사용하는 걸까요?

2024-01-08 18:34 UTC, wonsss commented on src/App.jsx
> +]);
라우터를 깔끔하게 잘 짜셨네요. 가독성이 좋아요.

2024-01-08 18:34 UTC, wonsss commented on src/Hooks/useFolderLinks.js
> +const useFolderLinks = (host, path, folderId = 0) => {
해당 훅의 인자로 host를 받아야 할까요?
관련된 값을 import해서 이 훅 안에서 바로 사용해도 될 것 같아요.
훅 자체가 공용적이진 않고 도메인이 많이 묻어있어서요.

2024-01-08 18:34 UTC, wonsss commented on src/Hooks/useFolderLinks.js
> +      }
early return 패턴으로 리팩터링하면 어떨까요?
그리고 hook의 인자로 apiPath를 바로 받을 수는 없을까요?

2024-01-08 18:34 UTC, wonsss commented on src/Hooks/useFolderLinks.js
> +const useFolderLinks = (host, path, folderId = 0) => {
url의 path를 인자로 받고 있는데,  나중에 해당 훅을 사용하는 곳의 라우팅이 변경될 수도 있으니 url path에 의존하기보다는 직접적인 apiPath를 인자로 받는 게 더 적절할 것 같아요.

2024-01-08 18:34 UTC, wonsss commented on src/components/AddLink/AddLink.jsx
> +        <IconInputWrapper>
컴포넌트 함수를 제일 위로 올리고, 그 밑에 styled components를 두세요. 순서를 바꿈으로써 컴포넌트 파일의 가독성 올라갑니다

2024-01-08 18:34 UTC, wonsss commented on src/components/Card/Card.jsx
> +          onError={handleImageError}
[img 태그에 onError 처리](https://developer.mozilla.org/ko/docs/Web/HTML/Element/img#%EC%9D%B4%EB%AF%B8%EC%A7%80%EB%A5%BC_%EA%B0%80%EC%A0%B8%EC%98%AC_%EC%88%98_%EC%97%86%EC%9D%84_%EB%95%8C)를 해주셨네요. 
센스가 너무 좋으십니다 👍

2024-01-08 18:34 UTC, wonsss commented on src/components/Card/Card.jsx
> +        <CardInfoBody>{link.description || '설명이 없습니다.'}</CardInfoBody>
잘 처리해주셨네요.

`||` 와 `??` 의 차이를 설명해주실 수 있으실까요?

2024-01-08 18:34 UTC, wonsss commented on src/components/Folder/FolderBody.jsx
> +  const [folderName, setFolderName] = useState('전체');
useState의 기본값을 설정해주셨군요 👍

2024-01-08 18:34 UTC, wonsss commented on src/components/Folder/FolderBody.jsx
> +      {links.length === 0 && folderList.length !== 0 && <NoLinkCard />}
참고로 jsx 조건부 렌더링에서 && 연산자 대신 삼항조건연산자를 사용하는 것이 버그 방지를 위해 좋은 방법이라고 합니다

https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

2024-01-08 18:34 UTC, wonsss commented on src/components/Folder/FolderTitle.jsx
> +    <FolderItem $isSelected={isSelected} onClick={handleClick}>
props 이름으로 $isSelected 처럼 `$` 를 붙이신 이유가 궁금합니다.
일관성에 맞지 않는다면 `$`는 제거하는 게 좋을 것 같아요

2024-01-08 18:34 UTC, wonsss commented on src/components/Shared/SharedBody.jsx
> +      }
객체의 속성에 접근하는 방식으로 조건부렌더링을 하셨군요.

아래 예시처럼 조건을 포함한 jsx 방식으로 조건부 렌더링하는 것은 어떠신가요?
그리고 condition에 예상치 못한 값이 오는 경우도 대비하면 좋겠습니다. 조건을 포함한 jsx 방식으로 하면 대비가 될 것 같아요.

```jsx
if (loading) {
  return <Loading/ >;
}
if (error) {
  return <Error />
}

return <Contents/>
```

2024-01-08 18:34 UTC, wonsss commented on src/utils/convertToCamelCase.js
> +export default convertKeyToCamelCase;
직접 유틸을 만드셨군요. 

직접 유틸함수를 만드는 것도 연습에는 좋으나, 나중에 에러가 날 가능성도 있습니다.
이런 경우에는 이전에 말씀드린 camelcase-keys 라이브러리를 사용하는 것도 권장드립니다. 
https://www.npmjs.com/package/camelcase-keys
해당 라이브러리 설치하시고 아래와 같이 사용해보세요. 라이브러리 설명을 보니 객체가 중첩되어 있으므로 재귀적으로 중첩되어 있는 key들을 모두 카멜케이스로 변경하려면 deep: true 옵션도 넣어주셔야 하네요.
```
import camelcaseKeys from 'camelcase-keys';

 const formattedData = camelcaseKeys(data, { deep: true });

```

2024-01-09 07:57 UTC, siyeol97 commented on netlify.toml
> +  status = 200
React는 SPA라서 하나의 index.html을 가지고 있습니다. "/" 경로가 아닌 다른 경로에서 새로고침을 하면 해당 경로의 리소스를 찾으려고 하기 때문에 404 에러가 발생합니다. 그래서 모든 경로에 대해서 루트로의 리다이렉션을 정의해 어떤 경로로 들어오더라도 index.html을 제공하는 것 처럼 보이게 하는 효과입니다!

2024-01-09 08:25 UTC, siyeol97 commented on .eslintrc.json
> +    "operator-linebreak": "off"
*import/no-extraneous-dependencies* 규칙은
```
error 'react-router-dom' should be listed in the project's dependencies. Run 'npm i -S react-router-dom' to add it 
```
에러가 나와서 구글링을 해본 결과 규칙을 추가하면 해결된다는 글을 보고 설정했습니다.
나머지 3개의 규칙은 styled-components 에서 동적으로 스타일을 변경할 때
```jsx
${(props) =>
    props.isFolderPage &&
    css`
      position: relative;
    `}
```
이렇게 코드를 짰는데, 
```
Expected no linebreak before this expression.
'&&' should be placed at the beginning of the line.
```
오류가 나와서 규칙을 설정했습니다.

2024-01-09 08:29 UTC, siyeol97 commented on package.json
> +    "camelcase": "^8.0.0",
api 응답으로 온 데이터의 프로퍼티 네임이 카멜케이스와  스네이크 케이스가 혼용되어 있어서 카멜케이스로 변환하려고 사용했습니다!
문자열 변환에 있어서 복잡한 로직을 직접 구현하지 않아도 돼서 편했습니다!

2024-01-09 08:58 UTC, siyeol97 commented on package.json
> +    "react-router-dom": "^6.21.1",
시멘틱 버저닝은 3자리 숫자로 버전을 표현합니다.
```json
"react-router-dom": "^6.21.1"
```
### 첫번째 숫자 (major digit)
- 이전 버전들과의 호환성을 나타냅니다. 업데이트 시 이전 버전과 호환되지 않는 변화가 있으면 첫번째 숫자를 올립니다.
### 두번째 숫자 (minor digit)
- 새로운 기능이 추가가 됐지만, 이전 버전과 호환이 되면 두번째 숫자를 올립니다.
### 세번째 숫자 (patch digit)
- 업데이트에 간단한 버그 패치가 있었을 경우 세번째 숫자를 올립니다.
### 버전 앞에 붙이는 접두사 `^`, `~`
버전 앞에  `^`, `~` 기호가 없고 버전만 명시되어 있다면 정확하게 일치하는 버전의 의존성을 사용합니다.
- `^`
  - minor digit 기준으로 호환 가능한 최신 패키지를 사용합니다.
  - `^6.21.1` 버전을 기준으로 `6.*.*` 의 버전을 가져올 수 있고 `5`로 시작하는 버전을 가져오는 것은 불가능 합니다
- `~`
  - patch digit 기준으로 최신 패키지를 사용합니다.
  - `^6.21.1` 기준으로 `6.21.*`의 버전을 가져올 수 있습니다.

명확한 정의와 버전 번호 관리로 종속성을 관리하고 사용자의 호환성 문제를 최소화 하는데에 있어서 중요한 것 같습니다!

2024-01-09 12:56 UTC, siyeol97 commented on src/components/Folder/FolderTitle.jsx
> +    <FolderItem $isSelected={isSelected} onClick={handleClick}>
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/331a469c-af14-4f09-9dae-0c4ca1cdc853)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/0be5252a-4074-41ba-9930-9b8131228844)
styled-component로 prop을 전달할 때 위의 오류가 발생해서 찾아보니 해결 방법이
1. @emotion/is-prop-valid 패키지를 설치하고 StyleSheetManager를 사용
2. DOM으로 전달되지 않게 transient props(prefix `$` 키워드)를 사용해서 해당 prop을 필터링

이렇게 있었습니다. 그래서 2번 방법 대로 `$`기호를 붙여서 해결했습니다!

2024-01-10 08:12 UTC, siyeol97 commented on src/Hooks/useFolderLinks.js
> +const useFolderLinks = (host, path, folderId = 0) => {
[fix: useFolderLinks Hook 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/203/commits/39289e24f23bdabc3fc530cc5bf36f7041e0475c)
수정해보았습니다.

2024-01-10 08:20 UTC, siyeol97 commented on src/components/AddLink/AddLink.jsx
> +        <IconInputWrapper>
[chore: styled-components 하단으로 이동, import문 정렬](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/203/commits/109a2b68e0d04ffdfbd4ddaf8a98f4302cc4ae73)
수정했습니다!

2024-01-10 08:26 UTC, siyeol97 commented on src/components/Card/Card.jsx
> +        <CardInfoBody>{link.description || '설명이 없습니다.'}</CardInfoBody>
### `||`
`A || B` => A가 Truthy 값이면 A, falsy 값이면 B를 리턴합니다.
### `??`
`A ?? B` => A가 `null` 혹은 `undefined` 이면 B를 리턴합니다.
여기서는 link.description이 없으면 null값 이어서 `??`으로 수정했습니다.
그리고 eslint 설정에 `"parser": "babel-parser"` 설정을 추가했습니다.

2024-01-10 08:34 UTC, siyeol97 commented on src/components/Folder/FolderBody.jsx
> +      {links.length === 0 && folderList.length !== 0 && <NoLinkCard />}
[fix: && 연산자 -> 삼항 조건 연산자로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/203/commits/610f52d63fd85f254a66f9574f4dadfb436c013d)
수정했습니다. 참고하겠습니다!

2024-01-10 10:24 UTC, siyeol97 commented on src/components/Shared/SharedBody.jsx
> +      }
[fix: jsx 방식 조건부 렌더링으로 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/203/commits/17f2171d73d7298c57b734f9cb4fc3f9533385be)
이렇게 하는게 맞는지 모르겠습니다..

2024-01-10 10:57 UTC, siyeol97 commented on src/utils/convertToCamelCase.js
> +export default convertKeyToCamelCase;
[fix: camelcase-keys 라이브러리로 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/203/commits/fe9047eaa85af68fe2502456306d3b961eee181e)
변경했습니다!

2024-01-11 01:15 UTC, wonsss commented on src/components/Shared/SharedBody.jsx
> +      }
기호님과 비슷한 상황이신 것 같네요.
기호님께 드렸던 멘션 내용 참고해보세요😊
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/198#discussion_r1444744884

2024-01-11 01:15 UTC, wonsss approved these changes

2024-01-11 01:16 UTC, merged