[백진영] week7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #215
Opened 2024-01-09 14:34 UTC by jinyoung1018

## 요구사항

### 기본

- [x] PC, Tablet, Mobile 디자인에 해당하는 폴더 페이지를 만들어 주세요.
- [x] 폴더 페이지에서 저장된 링크가 없는 경우의 디자인도 만들어 주세요.
- [x] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정해 주세요.
- [x] 카드 컴포넌트에 별모양 버튼, 케밥 버튼도 추가해 주세요. 다만, 버튼의 기능은 추후 만듭니다.
- [x] 링크 추가하기, 폴더 추가, 공유, 이름 변경, 삭제 버튼들의 기능은 추후 만듭니다.
- [x] Github에 위클리 미션 PR을 만들어 주세요.
- [x] React를 사용해 진행합니다.  

### 심화

## 주요 변경사항

-
-

## 스크린샷

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-10 01:08 UTC, goldfrosch requested changes
고생하셨습니다. 부상투혼임에도 최대한 깔끔하고 잘 짜려고 노력한 모습이 보여 보기 좋습니다!

밑의 PR들 확인 부탁드립니다~

2024-01-10 01:08 UTC, goldfrosch commented on src/api/api.js
> +};
```suggestion
export const getFolderList = async () => {
  const res = await fetch(`${API_BASE_URL}/api/users/1/folders`);
  return res.json();
};

export const getAllCardData = async () => {
  const res = await fetch(`${API_BASE_URL}/api/users/1/links`);
  return res.json();
};

export const getCardDataById = async (id) => {
  const res = await fetch(`${API_BASE_URL}/api/users/1/links?folderId=${id}`);
  return res.json();
};

```
[중요도: 중간] export의 경우 꼭 최하단에 몰아서 적는 것 보다 함수 바로 옆에 적는 것을 추천드립니다.
함수가 여러개면 매번마다 밑에까지 가서 적기 귀찮으실거거든요... (지금은 괜찮아도 몇십개까지 가게 되면 적기 귀찮고 협업시에 conflict나기도 좋으니까요 ;-;)
[중요도: 중간] 
```
  const result = await res.json();
  return result;
```
에서 result를 선언하고 return하는 것은 불필요해보이네요~ 바로 res.json을 return해보는 것도 방법입니다.
[중요도: 높음] ~~result는 await res.json()으로 가져왔는데 res.json()은 비동기 처리가 아닌지라 await이 필요없습니다 ㅎㅎ~~ 이거 제 미스입니다. 비동기 맞습니다.

2024-01-10 01:08 UTC, goldfrosch commented on src/components/AddLinkArea/AddLinkArea.js
> +      <AddLinkInput />{" "}
[중요도: 중간] {" "}가 있네요...? 정확한 역할이 뭐였을까요? 오타인지 일부러 띄어쓰려고 사용한 건지 확인 부탁드립니다.
일부러라면 margin값으로 설정해주는 게 훨씬 좋습니다

2024-01-10 01:08 UTC, goldfrosch commented on src/components/AddLinkInput/AddLinkInput.js
> +        src={process.env.PUBLIC_URL + `/assets/link.png`}
[중요도: 높음] 이거는 전 PR에 남겨뒀는데 process.env에 대해 설명을 조금 해드리자면...
process.env의 경우는 암호화가 필요한 값들을 주로 저장하는 공간입니다. (ex. 간편 로그인에 필요한 key를 저장하는 용도 - 외부에 노출되지 않게)
그래서 PUBLIC_URL 즉 이미지 관련 url은 env가 아니라 별도의 상수로 빼는게 더 나아보입니다.
그리고 CRA라서 REACT_APP_~~~형식으로 env를 사용해야 정상적으로 작동하는걸로 아는데 이거는 최근에 CRA가 바뀌었었나 보군요 휴휴...

2024-01-10 01:08 UTC, goldfrosch commented on src/components/CardContainer/CardContainer.js
> +  } else {
[중요도: 중간] else빼도 될 것 같습니다 :)

2024-01-10 01:08 UTC, goldfrosch commented on src/components/CardContainer/CardContainer.js
> +  console.log({ cardData });
[중요도: 높음] 언제나 위험한 CDD(console driven developement...)
저도 애용해서 자주 실수하지만 실제로 프로덕트 나갈 때 console.log가 남으면 위험하니 이 부분은 꼭 제거해주세요.
(나중에 빌드 설정을 통해 안나오게 할 수는 있지만 처음부터 제거하는 습관을 들인다면 더 편하겠죠?)

정 props에 대한 값을 확인하는 방법을 알고싶으시면 Chorme Extension인 React Devtools에 익숙해지는게 훨씬 더 좋은 개발자가 될 수 있습니다!

2024-01-10 01:08 UTC, goldfrosch commented on src/components/FolderList/FolderList.js
> +// export default FolderList;
[중요도: 높음] 불필요한 주석 파일은 제거해주세요~

2024-01-10 01:08 UTC, goldfrosch commented on src/components/ContentsArea/ContentsArea.js
> +};
[중요도: 높음] 이런 경로(location.pathname)에 따라 다른 컴포넌트를 보여주는게 react-router의 역할이죠? 그것을 사용하는게 훨씬 좋아보입니다.

2024-01-10 01:08 UTC, goldfrosch commented on src/context/FolderNameContext.js
> +};
context API를 최대한 쓰기 위해 많은 노력을 하셨군요 좋습니다. 고생하셨어요!

2024-01-10 14:54 UTC, jinyoung1018 commented on src/api/api.js
> +};
74185f5e56e241c6030057c22ac22823c591bdd2 몰아서 적는 것보다 하나씩 export해주는게 더 좋군요! 수정했습니다!
47701993897b477ebeb979fb60bb1d19e8a5bf1c 이 부분도 수정했습니다!

2024-01-10 14:55 UTC, jinyoung1018 commented on src/components/AddLinkArea/AddLinkArea.js
> +      <AddLinkInput />{" "}
45bba783dde779a398d8129e5f77754f8fd03b8f 오타가 났네요ㅠㅠ 제거했습니다!

2024-01-10 14:56 UTC, jinyoung1018 commented on src/components/AddLinkInput/AddLinkInput.js
> +        src={process.env.PUBLIC_URL + `/assets/link.png`}
75c3acc11895948b5967edbb8c74593099e6e24f 제가 잘 이해한건지 모르겠습니다ㅠㅠ 이렇게 별도로 빼는게 맞나용??

2024-01-10 14:57 UTC, jinyoung1018 commented on src/components/CardContainer/CardContainer.js
> +  } else {
9d82859d148fb6482e37e23e28c12b5c92491d26 제거했습니다!

2024-01-10 14:57 UTC, jinyoung1018 commented on src/components/CardContainer/CardContainer.js
> +  console.log({ cardData });
820e7ae5351724b3198bc52b08cb6c02e9558a37 넵! 더 주의하겠습니다!!

2024-01-10 14:58 UTC, jinyoung1018 commented on src/components/FolderList/FolderList.js
> +// export default FolderList;
549347d5781e071532eac9ead44139fa511d2293 제거한다는걸 깜빡했습니다ㅠㅠ 파일 삭제했습니다!

2024-01-10 14:59 UTC, jinyoung1018 commented on src/components/ContentsArea/ContentsArea.js
> +};
0c6eb3ac7f22d9d41f9aa962dccf0ed10e308922 제가 불필요한 작업을 더 했네용! 수정했습니다!!

2024-01-10 14:59 UTC, jinyoung1018 commented on src/context/FolderNameContext.js
> +};
감사합니다!

2024-01-11 08:23 UTC, goldfrosch commented on src/components/AddLinkInput/AddLinkInput.js
> +        src={process.env.PUBLIC_URL + `/assets/link.png`}
네네 제가 말씀드린 부분은 올리신 PR이 맞습니다.

dotenv에 대해서는 설명이 조금 부족했던 것 같은데 정확하게는 외부에 공개되면 안되는 보안 값들을 저장하는 공간입니다.
https://www.daleseo.com/js-dotenv/
위의 포스팅을 참고해보시면 도움이 되지 않을까 싶네요~

2024-01-11 08:27 UTC, goldfrosch commented on src/components/ContentsArea/ContentsArea.js
> +};
https://github.com/remix-run/react-router/blob/dev/examples/custom-link/src/App.tsx
제가 말씀드린 부분은 이런 방식을 써보는 겁니다!
switch-case 로 쓰는 것도 어찌보면 맞을수는 있으나 react-router 라이브러리에서 잘 정리해서 사용할 수 있으니 위 링크를 확인해보세요.

2024-01-13 05:31 UTC, jinyoung1018 commented on src/components/AddLinkInput/AddLinkInput.js
> +        src={process.env.PUBLIC_URL + `/assets/link.png`}
넵 참고해보겠습니다! 감사합니다!

2024-01-13 05:31 UTC, jinyoung1018 commented on src/components/ContentsArea/ContentsArea.js
> +};
아아 그렇군요! 알려주셔서 감사합니다!

2024-01-13 05:37 UTC, merged