[윤해용] week7
codeit-bootcamp-frontend/3-Weekly-Mission pull request #217
Opened 2024-01-12 04:17 UTC by haeyong9701

## 요구사항

### 기본

- [x] 링크 공유 페이지 url path는 ‘/shared’, 폴더 페이지 url path는 ‘/folder’가 되도록 설정했나요?
- [x] 폴더 페이지에서 상단 네비게이션 바는 스크롤 시 상단에 고정하지 않고 가려지도록 했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/users/1”을 활용했나요?
- [x] “전체” 폴더를 선택한 경우 “공유”, “이름 변경”, “삭제” 버튼들이 보이지 않지만, 다른 폴더를 선택한 경우에는 버튼들이 보이나요?
- [x] 폴더 목록에 필요한 데이터는 “/api/users/1/folders”를 활용했나요?
- [x] “전체” 폴더에 필요한 링크들 데이터는 “/api/users/1/links”를 활용하고, 이외의 폴더에 필요한 링크들 데이터는 “/api/users/1/links?folderId={해당 폴더 ID}”를 활용했나요?
- [x] Mobile에서 “폴더 추가” 버튼은 최하단에서 101px 떨어져있는 Floating Action Button으로 만들었나요?

## 주요 변경사항

- 링크 공유 페이지를 리액트 라우터를 이용해서 만들었습니다.
- 링크 공유 페이지 모바일 구현

## 스크린샷
![스크린샷 2024-01-12 오후 1 10 06](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/72595163/da7c022f-bfbc-4316-b0ad-49d9fe71bbf1)

## 멘토에게
-

2024-01-16 07:06 UTC, goldfrosch requested changes
고생하셨습니다!
개인적으로 index패턴을 좋아하기도 하다보니 해당 코드가 더 깔끔하게 느껴지고 개발 폼도 점점 올라오는 것이 느껴집니다!

밑의 PR 확인 부탁드립니다~

2024-01-16 07:06 UTC, goldfrosch commented on src/Main.js
> +      return;
[중요도: 낮음] 굳이 return이 필요해보이지는 않네요~

2024-01-16 07:06 UTC, goldfrosch commented on src/api.js
> +    throw new Error("데이터를 불러오는데 실패했습니다");
new Error를 사용하시는 것 정말 좋습니다 ㅎㅎ

2024-01-16 07:06 UTC, goldfrosch commented on src/api.js
>    return body;
```suggestion
  return response.json();
```
[중요도: 중간] 으로 하셔도 됩니다~ .json() 이 비동기도 아니기도 하고, 굳이 새로 변수 선언해서 return할 필요도 따로 없어요~

2024-01-16 07:06 UTC, goldfrosch commented on src/components/FolderItem/index.js
> +  const { created_at, url, title, description, image_source = noImage } = link;
구조분해 할당 좋네요 ㅎㅎ

2024-01-16 07:06 UTC, goldfrosch commented on src/pages/FolderListPage/index.js
> +    }
```suggestion
    if (links.data) {
      setLinks(links.data);
    }
```
[중요도: 높음] 가 더 맞는 표현으로 보입니다!
만약 links.data가 배열이 아닐 경우에는 에러가 발생할 수 있는 요소로 보입니다.

2024-01-16 11:42 UTC, haeyong9701 commented on src/Main.js
> +      return;
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/217/commits/ffe7cc6d1a88a76bb37c0bea8a2f9e4c9e1badd9 함수 마지막 부분이라서 return을 시킬 필요가 없었네요. 수정했습니다!

2024-01-16 11:48 UTC, haeyong9701 commented on src/api.js
>    return body;
수정했습니다. [ceabed4](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/217/commits/ceabed46da6f5b3026ce4b14fc7ddece383ac82a)

2024-01-16 11:58 UTC, haeyong9701 commented on src/pages/FolderListPage/index.js
> +    }
피드백 감사합니다! https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/217/commits/207e5e8dbf37752118c32e9ceffa08e517dbfda0

2024-01-18 00:03 UTC, goldfrosch approved these changes
Approve and merge 진행하겠습니다!

2024-01-18 05:31 UTC, haeyong9701 commented
오류를 확인하고 싶은데 접근 권한이 없어서 확인 할 수가 없네요...
피드백에 대한 커밋을 보내기 전에 로컬 레포지토리에서 8주차 브랜치를 생성하고 잠깐 작업을 하다가 삭제하고 커밋을 보냈었습니다. 아마 이부분 때문에 오류가 생긴 것 같은데... 잘 모르겠습니다.

2024-01-18 05:31 UTC, haeyong9701 commented
> Approve는 해뒀습니다! Vercel에서 뭔가 막힌게 있는 것 같아 이 부분의 확인을 부탁드립니다! 강제 merge는 가능하니 해결 불가능하거나 known issue라면 알려주세요~

오류를 확인하고 싶은데 접근 권한이 없어서 확인 할 수가 없네요...
피드백에 대한 커밋을 보내기 전에 로컬 레포지토리에서 8주차 브랜치를 생성하고 잠깐 작업을 하다가 삭제하고 커밋을 보냈었습니다. 아마 이부분 때문에 오류가 생긴 것 같은데... 잘 모르겠습니다.

2024-01-18 09:24 UTC, goldfrosch commented
일단 merge 진행하겠습니다~

2024-01-18 09:25 UTC, merged