[고기호] Week8
codeit-bootcamp-frontend/3-Weekly-Mission pull request #218
Opened 2024-01-12 07:14 UTC by GihoKo

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-16 16:36 UTC, wonsss requested changes
수고하셨습니다. 기호님. 
고민을 많이 하신 흔적이 느껴지네요. 👍 
코드도 매번 더 좋아지시네요.
리뷰 남겨드렸으니 참고하여 반영 부탁드립니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/CardList/CardDescription/CardDescription.jsx
> +      <CardContentTimePassedBox>
명시적인 이름 좋습니다.
다만 해당 컴포넌트 내부에서 이미 맥락이 있으니 스타일드 컴포넌트 이름을 Wrapper, ContentBox  처럼 조금 단순화하는 것도 가능합니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/CardList/CardImg/CardImg.jsx
> +      <CardStarButton>
button 태그의 type 속성의 기본값은 submit입니다. 양식 제출용 버튼이 아니라면 type 특성을 button으로 지정하는걸 잊지 마세요. 기본값에서는 버튼을 눌렀을 때 양식 데이터를 제출하고, (존재하지 않는) 응답을 불러오려고 시도하는 과정에서 문서의 현재 상태가 사라질 수 있습니다.

>  button 태그의 type 속성: 버튼의 행동 방식. 가능한 값은 다음과 같습니다.
-submit: 버튼이 서버로 양식 데이터를 제출합니다. 지정하지 않은 경우 기본값이며, 유효하지 않은 값일 때도 사용합니다.
-reset: <input type="reset">처럼, 모든 컨트롤을 초깃값으로 되돌립니다.
-button: 기본 행동이 없으며 클릭했을 때 아무것도 하지 않습니다. 클라이언트측 스크립트와 연결할 수 있습니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/button

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/CardList/CardDescription/CardDescription.jsx
> +              }}
e.preventDefault(); 를 추가하신 이유가 궁금합니다.
만약 button submit 때문이라면,  button 에 type="button" 속성을 명시해주시면 이러한 submit 동작이 일어나지 않을 것이고 preventDefault 도 할 필요가 없지 않을까요?

다른 코멘트에서 관련한 내용 적어두었습니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/CardList/CardList.jsx
> +              <CardContent link={link} handleModal={handleModal} />
컴포넌트 props이름으로 일반적인 네이밍 컨벤션은 접두사가 handle이 아닌 on이 옵니다.
그리고 살펴보니, 내부적으로 삭제 버튼 클릭하는 핸들러에 전달되는 prop이네요. 그렇다면 prop 이름을 onDeleteButtonClick 으로 하는 게, 이 사용하는 쪽에서 봤을 때 가독성이 좋을 것 같습니다. 또한 여기에 전달하는 handleModal 이라는 이벤트 핸들러 함수명도 명시적인 이름으로 수정하면 좋겠습니다. 😄

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +                    console.log(sharingUrl);
콘솔로그는 제거해주세요

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +  const [sharingUrl, setSharingUrl] = useState('');
sharingUrl은 state로 관리할 필요가 없어보입니다. 
state는 필요한 것만 만드는 게 좋습니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +                    handleFolderCardData(folder.id);
`handle` + `대상` 이런식으로 함수 이름을 주로 지으시는 것 같아요.
handle은  이벤트 핸들러 함수인 경우에만 이름에 접두사로 주로 사용합니다.
그리고 이벤트 핸들러 함수는 아래처럼 뒤에 "이벤트 이름" 까지 붙여주시는 게 명시적입니다.
`handle` + `이벤트 발생하는 요소` + `이벤트 이름` 
이러한 방식으로 이벤트핸들러 이름을 일관되게 지으시는 것을 제안드려요.

일관된 네이밍 컨벤션을 정해두면, 어떤 함수의 이름만 보더라도 이벤트핸들러이며 어떤 요소의 무슨 이벤트가 발생했을 때 쓴다는 것을 알 수 있습니다.

[관련 링크](https://blog.sonim1.com/220#google_vignette)를 공유드려요.

2024-01-16 16:36 UTC, wonsss commented on src/data.js
> +export const modalInit = { name: '', data: {} };
상수는 `MODAL_INIT` 처럼 이름을 대문자와 언더바의 조합으로 지어주세요.
그리고 역할을 살펴보니 `DEFAULT_MODAL_VALUE` 같은 이름도 가능할 것 같아요.

2024-01-16 16:36 UTC, wonsss commented on src/pages/SharedPage.jsx
>    }, []);
커스텀 훅으로 분리해보시면 어떨까요?

그리고 이 로직들을 하나의 커스텀 훅으로 통채로 분리하진 마시고, 연관된 로직끼리 적절하게 나누어 여러 커스텀 훅으로 분리해서 사용하실 수 있을 것 같습니다.

참고 링크입니다.
https://engineering.linecorp.com/ko/blog/line-securities-frontend-3

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +    window.open(`http://www.facebook.com/sharer/sharer.php?u=${sharedLink}`);
shareFacebook 같은 유틸함수로 분리하면 어떨까요?
재사용성을 고려하여 유틸함수 분리를 제안드립니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +    }
copyToClipboard 같은 유틸함수로 분리하면 어떨까요?
재사용성을 고려하여 유틸함수 분리를 제안드립니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +  }, []);
이 컴포넌트 내부에서만 카카오 SDK script를 호출하도록 하셨군요. 이 방법도 좋은 방법인 것 같습니다. 👍 

이 부분도 커스텀 훅으로 분리한다면, 다른 페이지에서 동일한 로직을 쉽게 재활용할 수 있겠네요.

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +    }
shareKakao 같은 유틸함수로 분리하면 어떨까요?
재사용성을 고려하여 유틸함수 분리를 제안드립니다.

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +        kakao.init('e5f079e205ef1816dd9189a0388e190b'); // 카카오에서 제공받은 javascript key를 넣어줌
이러한 시크릿 key는 외부에 노출되면 안되므로, `.env` 같은 환경변수 파일을 만들고 여기서 가져와서 사용해주세요.
그리고 해당 `.env`파일이 깃허브에 함께 푸시되면 안되므로, `.gitignore`에서 `.env`를 목록에 추가해주세요.

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +  background: ${(props) => props.bgColor};
passed props 기능을 활용하셨네요 👍

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +    window.open(`http://www.facebook.com/sharer/sharer.php?u=${sharedLink}`);
window.open 메서드를 사용하셨군요. 
일단 그냥 open보다는 popup 으로 여는 게 공유하기 시 일반적인 사용자 경험일 것 같습니다.
그리고 외부 하이퍼링크로 이동할 때는 보안 리스크를 방지하기 위해 nopener와 noreferrer 같은 속성 추가를 고민하시면 좋습니다.
[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

popup이나 보안 리스크 방지 기능 등은 open 메서드의 세번째 매개변수인 windowFeautres에 정해진 속성 값을 넘겨줌으로써 가능합니다. [[MDN window.open 참고]](https://developer.mozilla.org/en-US/docs/Web/API/Window/open)
 그리고 새 탭을 여는 것이니 두 번째 매개변수인 target에 "_blank"를 넘겨주세요. [[MDN a 요소 target 설명 참고]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target)

2024-01-16 16:36 UTC, wonsss commented on src/components/Modal/ModalContent/ModalCloseButton.jsx
> +  };
handleModlaClose보다는 closeModal이라는 이름이 적절할 것 같습니다. 
그리고 이 컴포넌트에서 props 로 setModal 대신 closeModal을 전달받도록 하면 여기서 modalInit을 import할 필요가 없습니다.

2024-01-16 16:36 UTC, wonsss commented on src/pages/FolderPage.jsx
> +  };
handleModal 이라는 이름은 포괄적이고 모호하게 느껴집니다.
역할을 살펴보니, 표시하고자 하는 모달의 값을 인자로 받아서 상태를 변경해주는 함수인 것 같네요.
그렇다면 handleModla보다는 showModal이라는 이름이 해당 함수의 역할을 조금 더 명시적으로 알려주지 않을까요?

2024-01-16 16:36 UTC, wonsss commented on src/pages/FolderPage.jsx
> +        <LinkCreator handleModal={handleModal} />
컴포넌트가 받는 props이름은 handleModla이 아니라 그 LinkCreaor라는 컴포넌트의 입장에서 어떤 역할인지를 생각해서 이름을 지으시는 게 좋습니다. onButtonClick 도 가능한 이름 중 하나겠네요.

2024-01-16 16:36 UTC, wonsss commented on src/pages/FolderPage.jsx
> +      {modal.name ? <Modal modal={modal} setModal={setModal} /> : null}
효율적인 모달 관리를 위해서 Context API를 사용하는 방안도 고려해보세요.

참고할 수 있는 링크 전달드립니다.
[[React] 효율적인 모달 관리 (with Context API)
](https://velog.io/@eunnbi/%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9D%B8-%EB%AA%A8%EB%8B%AC-%EA%B4%80%EB%A6%AC)

2024-01-17 09:22 UTC, GihoKo commented on src/components/Contents/CardList/CardDescription/CardDescription.jsx
> +      <CardContentTimePassedBox>
052509341c179d1e94b22edc151051bb1a7da2b3
바꿀게 많아보여서 PR 반영하면서 천천히 수정해나가겠습니다.
그런데 다른 컴포넌트에서 사용되어야하는 스타일드 컴포넌트의 경우가 있는데
이 부분은 원래대로 명시적으로 해놨는데 다른 괜찮은 방법이 있을까요?

예를들어
  &:hover ${CardDescriptionWrapper} {
    background: var(--gray5);
  }
이런식으로 다른 컴포넌트에서 hover를 할 때 다른 파일의 스타일드 컴포넌트에
스타일을 주고 싶은 경우가 있습니다.

2024-01-17 09:24 UTC, GihoKo commented on src/components/Contents/CardList/CardImg/CardImg.jsx
> +      <CardStarButton>
052509341c179d1e94b22edc151051bb1a7da2b3
해당부분 수정 완료했습니다!

2024-01-17 09:43 UTC, GihoKo commented on src/components/Contents/CardList/CardList.jsx
> +              <CardContent link={link} handleModal={handleModal} />
26c263d01bea4a55e8cefe5401c9996c406fe8d0
해당 부분 수정했습니다!
근데 한 컴포넌트에 여러개의 버튼이 있어서 일단 onButtonClick으로 해두고
해당 버튼들은 나중에 따로 작은 컴포넌트로 빼놔서 다시 네이밍 할 예정입니다.

2024-01-17 09:43 UTC, GihoKo commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +                    console.log(sharingUrl);
26c263d01bea4a55e8cefe5401c9996c406fe8d0
수정 완료했습니다!

2024-01-17 10:10 UTC, GihoKo commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +  const [sharingUrl, setSharingUrl] = useState('');
f0e26028c99b73b19850f7345581f3531fa01365
해당 부분 수정 완료했습니다!

2024-01-17 10:14 UTC, GihoKo commented on src/data.js
> +export const modalInit = { name: '', data: {} };
dcc8ca51af9b288b40d7948e0b955a0529044928
해당부분 수정했습니다!

2024-01-17 10:28 UTC, GihoKo commented on src/components/Modal/ShareFolder.jsx
> +    }
95f986ba5b5e53d8d6215a6157e6c2a39a60102e
해당 부분 수정했습니다!

2024-01-17 10:28 UTC, GihoKo commented on src/components/Modal/ShareFolder.jsx
> +    window.open(`http://www.facebook.com/sharer/sharer.php?u=${sharedLink}`);
95f986ba5b5e53d8d6215a6157e6c2a39a60102e
해당부분 수정했습니다!

2024-01-17 10:28 UTC, GihoKo commented on src/components/Modal/ShareFolder.jsx
> +  background: ${(props) => props.bgColor};
감사합니다 ㅎㅎ

2024-01-17 10:35 UTC, GihoKo commented on src/components/Modal/ShareFolder.jsx
> +        kakao.init('e5f079e205ef1816dd9189a0388e190b'); // 카카오에서 제공받은 javascript key를 넣어줌
c5e50766b00b9f24ca549d90401bc97037502d2a
해당 부분 수정완료했습니다!

2024-01-17 10:49 UTC, GihoKo commented on src/components/Modal/ModalContent/ModalCloseButton.jsx
> +  };
ef7d58fdf36ce789f1afdc39237256b418493a18
해당부분 수정했습니다!

2024-01-17 10:53 UTC, GihoKo commented on src/pages/FolderPage.jsx
> +  };
26c263d01bea4a55e8cefe5401c9996c406fe8d0
해당부분 수정했습니다!

2024-01-17 10:58 UTC, GihoKo commented on src/pages/FolderPage.jsx
> +        <LinkCreator handleModal={handleModal} />
ef7d58fdf36ce789f1afdc39237256b418493a18
onUpdateButtonClick으로 수정하긴했는데 이것도 괜찮은 네이밍일까요?

2024-01-17 13:15 UTC, GihoKo commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +                    handleFolderCardData(folder.id);
7f5b530205db9250f2bf4a4649ff4b20354ec303
최대한 바꿔봤는데 뭔가... 어렵네요 ㅠ
너무 짧게 하면 명시성이 없어 보이고 명시성 있게 하려면 이름이 좀 길어지고...

2024-01-17 13:46 UTC, GihoKo commented on src/components/Modal/ShareFolder.jsx
> +  }, []);
3ec1d5f756bc310b644073b021b883432135655c
일단 만들어 보긴 했는데...
제가 짠 코드가 맞는 지 모르겠습니다.
어떤 상태를 빼야하는지 아직 감이 안잡혀서 그런 것 같습니다.
혹시 멘토님께서 커스텀 훅으로 분리하신다면 어떤 상태들을 빼내실건가요?

2024-01-17 14:00 UTC, GihoKo commented on src/components/Modal/ShareFolder.jsx
> +    }
c53f83a066dec3a10c6f51ff53b0c1120e4194f2
수정 완료했습니다! 재밌네요...

2024-01-17 14:18 UTC, GihoKo commented on src/components/Contents/CardList/CardDescription/CardDescription.jsx
> +              }}
이 부분은 뭔가 꼬인 것 같아서 천천히 분석하고 다시 말씀 드리겠습니다...

2024-01-17 16:42 UTC, GihoKo commented on src/pages/SharedPage.jsx
>    }, []);
a59b8f4316074d7146efa3f289faac8c9ef07fde
ce003b368bf75676b1f3ab713438b841e799c987
a5af3daa109450a1c3a127b9ffbe3e0cb30c5b6e
뭔가 어렵네요 ㅋㅋㅋ
근데 확실히 코드가 엄청 깨끗해졌습니다!

2024-01-18 15:33 UTC, wonsss commented on src/components/Contents/CardList/CardDescription/CardDescription.jsx
> +      <CardContentTimePassedBox>
CardDescriptionWrapper 를 export해서 다른 곳에서 사용하게 하셨네요. 
그렇다면 CardDescription.jsx 파일 안에 해당 CardDescriptionWrapper 스타일드컴포넌트를 두는 게 어색할 것 같아요.
이보다는 더 상위에 해당 스타일드컴포넌트를 빼 두어야 다른 곳에서 공유하여 사용할 때, 위계가 맞을 것 같아요.
어떻게 하든 구현은 되지만, 기준을 일관되게 잡고 가야 나중에 유지보수에 편리합니다.

2024-01-18 15:36 UTC, wonsss commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +  const [sharingUrl, setSharingUrl] = useState('');
ref로 바꾸셨군요. 이것도 괜찮습니다.
다만 제가 제안드린 의도는 createSharingUrl 함수가 사이드이펙트를 일으키기 보다는 sharingUrl을 return 하도록 순수하게 만들면 어떨까 했습니다. ㅎㅎ 참고해보세요.

2024-01-18 15:38 UTC, wonsss commented on src/components/Contents/FolderCollection/FolderCollection.jsx
> +                    handleFolderCardData(folder.id);
변경하신 handleOverviewCardButtonClick 이름 좋다고 생각합니다. 

이전에는 `Click` 같은 이벤트 이름이 없었는데 이제 어떤 이벤트를 핸들링하는 이벤트 핸들러 함수의 이름이 적절해진 것 같아요 👍

2024-01-18 15:48 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +  }, []);
const [KakaoSdk, setKakaoSdk] = useState(false);  이러한 KakaoSdk 상태 코드 필요 없을 것 같고 훅에서 KakaoSdk return 도 하지 않으셔도 될 것 같습니다.
그리고 아래와 같은 초기화 로직도 useGetKakaoSdkScript 훅으로 넣을 수 있지 않을까요?
```
    if (KakaoSdk) {
      // url이 id값에 따라 변경되기 때문에 route를 인자값으로 받아줌
      if (window.Kakao) {
        const kakao = window.Kakao;
        if (!kakao.isInitialized()) {
          kakao.init(`${process.env.REACT_APP_KAKAO_JS_KEY}`); // 카카오에서 제공받은 javascript key를 넣어줌
        }
```

2024-01-18 15:49 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +    }
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/9f8173cb-c03b-4969-ba4e-bd0ac15a1f86)

2024-01-18 16:01 UTC, wonsss approved these changes

2024-01-18 16:02 UTC, merged