[박준용] Week8
codeit-bootcamp-frontend/3-Weekly-Mission pull request #223
Opened 2024-01-12 17:51 UTC by mocking-tiger

## 요구사항

- [x] 링크를 입력하고 “추가하기” 버튼을 누르면 “폴더에 추가” 모달이 보이나요?

- [x] “폴더 추가” 버튼을 누르면 “폴더 추가” 모달이 보이나요?

- [x] “공유” 버튼을 누르면 “폴더 공유” 모달이 보이나요?

- [x] “이름 변경” 버튼을 누르면 “폴더 이름 변경” 모달이 보이나요?

- [x] “삭제” 버튼을 누르면 “폴더 삭제” 모달이 보이나요?

- [x] 케밥 버튼을 누르면 “삭제하기”, “폴더에 추가” 버튼이 있는 팝오버가 보이나요?

- [x] 팝오버에 있는 “삭제하기” 버튼을 누르면 “링크 삭제” 모달이 보이나요?

- [x] 팝오버에 있는 “폴더에 추가” 버튼을 누르면 “폴더에 추가” 모달이 보이나요?

- [x] “폴더 공유” 모달에서 “카카오톡 아이콘”을 클릭하면 카카오로 공유 폴더 페이지 링크 공유하기 가능한가요?

- [x] “폴더 공유” 모달에서 “페이스북 아이콘”을 클릭하면 페이스북으로 공유 폴더 페이지 링크 공유하기 가능한가요?

- [x] “폴더 공유” 모달에서 “링크 아이콘”을 클릭하면 클립보드에 공유 폴더 페이지 링크가 복사 되나요?

## 주요 변경사항

- 페어프로그래밍으로 모달 컴포넌트 구현
- SNS공유기능 구현

## 스크린샷

배포: https://weekly-mission-part2.vercel.app/

## 멘토에게

- 초반에는 강의로 안 다룬 부분은 심화요구사항으로 냈는데 이제는 자연스럽게 기본요구사항들도 안가르쳐준것들이라 처음부터 찾아보면서 하느라 코드가 많이 지저분한것 같습니다.
- 짧은시간이었지만 멘토링으로 도움이 많이 되었습니다 주강사 업무 하시면서도 늘 건승하시길 바라겠습니다.

2024-01-16 06:58 UTC, goldfrosch requested changes
고생 많으셨습니다! 날이가면 갈수록 발전하는 모습이 보여 저도 보기 좋네요 ㅎㅎ

밑의 PR 확인 부탁드립니다~

2024-01-16 06:58 UTC, goldfrosch commented on src/App.js
> +        </Route>
```suggestion
          <Route path="/" element={<HomePage />} />
          <Route path="/shared" element={<Shared />} />
          <Route path="/folder" element={<Folder />} />
          <Route path="/folder-empty" element={<FolderEmpty />} />
```
[중요도: 낮음] 이런식으로 하셔도 되었었을텐데... <Route path="/">로 묶은 이유가 특별히 있을까요?
[중요도: 높음] url pahtname의 경우는 웬만해선 kebab-case가 좋습니다. SEO관점에서도 좋고 가독성에서도 좋습니다.
https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Why-you-should-make-kebab-case-a-URL-naming-convention-best-practice
위의 게시글 참고해주세요~

2024-01-16 06:58 UTC, goldfrosch commented on src/assets/url.js
> +const CODEIT_API = "https://bootcamp-api.codeit.kr/api";
```suggestion
export const CODEIT_API = "https://bootcamp-api.codeit.kr/api";
export const SAPMLE_USER = `${CODEIT_API}/sample/user`;
export const SAMPLE_FOLDER = `${CODEIT_API}/sample/folder`;
```
[중요도: 중간] 상수화 좋습니다! 다만 상수화를 재활용하기 위해 이런 방식도 추천드립니다.
[중요도: 중간] export를 최하단에 몰아서 선언하는 것보다 바로 옆에 붙이는 것도 좋은 방법입니다. 최하단 선언의 단점은 50-60개가 넘어가게 되면(혹은 그 전에도 그럴 수 있음) 맨 밑에 찾아서 적기 귀찮고 여러명이 이 파일을 건드리게 되면 conflict이 날 가능성도 있습니다~

2024-01-16 06:58 UTC, goldfrosch commented on src/components/AddLink/AddLink.js
> +      setButtonInfo(folderData["data"]);
folderData["data"]로 단순히 .이 아닌 배열식으로 접근하는 것도 좋습니다!
[중요도: 낮음] 다만 이런 데이터가 정적으로 정해져있는 경우는 folderData.data도 좋습니다

2024-01-16 06:58 UTC, goldfrosch commented on src/components/Card/Card.js
> +  const [showAddLink, setShowAddLink] = useState(false);
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/228#discussion_r1452828379
[중요도: 중간] 이 PR과 같은 느낌일 것 같아 대체합니다~

2024-01-16 06:58 UTC, goldfrosch commented on src/components/FloatingActionButton/FloatingActionButton.js
> +  }
[중요도: 중간] 동적으로 JS에서 처리하는 것도 좋은 방법이긴 하지만. 개인적으로는 media-query안에서 768보다 width값이 낮다면 display:none옵션을 주는 것도 방법입니다!

2024-01-16 06:58 UTC, goldfrosch commented on src/components/Modal/ModalAddLink.js
> +            : alert("폴더정보는 8주차 과제(folder페이지)부터 제공됩니다.")}
```suggestion
  useEffect(() => {
    if (!buttonInfo) {
      alert("폴더정보는 8주차 과제(folder페이지)부터 제공됩니다.");
    }
  }, [])
  .
  .
  .

          {buttonInfo
            && buttonInfo.map((item) => (
                <div
                  key={item.id}
                  onClick={() => handleFolderSelected(item.id)}
                  className={
                    selectedFolders.includes(item.id) ? "selected" : undefined
                  }
                >
                  <h2>{item.name}</h2>
                  <h3>{item.link.count}개 링크</h3>
                  <img src={check} alt="check" />
                </div>
              ))
```
[중요도: 높음] 이런 형식을 추천드립니다.
props라서 당장에 문제가 되지는 않지만 원래 하던 방식으로 진행하게 된다면 리렌더링 될 때 마다 저 alert가 노출될 수 있습니다!

그래서 저는 컴포넌트 return문 부터에는 순수한 함수를 렌더하게 하는 것은 안쓰고 있으니 바꿔보시는 것도 좋아보입니다!

2024-01-16 06:58 UTC, goldfrosch commented on src/utils/Fetch/FetchFolderData.js
> +export default FetchFolderData;
[중요도: 중간] API 하나당 하나의 파일보다는 2deps의 카테고리 별로 구분 하는 것도 좋아보여요!
이 파일의 경우는 API/users~~ 로 가니까 UsersAPI.js 이런 식으로요~

2024-01-16 06:58 UTC, goldfrosch commented on src/utils/Kakao/ShareKaKaoLink.js
> +      kakao.init("39e36379232c0a9c4af7969a3d7593ea"); // 카카오에서 제공받은 javascript key를 넣어줌 -> .env파일에서 호출시킴
env를 말씀드리려고 했는데 주석으로 이미 적어두셨군요...! 추후 개선하면 좋을 것 같네요~

2024-01-17 12:32 UTC, mocking-tiger commented on src/App.js
> +        </Route>
코드잇 강의에서 저렇게 /를 위로 올리고 메인에다 index라고 해주면 
따로 경로설정을 안해줘도 된다고 해서 저렇게 했는데
멘토님이 말씀해주신 방법이 좀 더 간결하고 좋은것 같습니다 수정하겠습니다!

2024-01-17 12:45 UTC, mocking-tiger commented on src/components/FloatingActionButton/FloatingActionButton.js
> +  }
코드가 엄청 짧아졌습니다 감사합니다!

2024-01-17 13:17 UTC, mocking-tiger commented on src/utils/Kakao/ShareKaKaoLink.js
> +      kakao.init("39e36379232c0a9c4af7969a3d7593ea"); // 카카오에서 제공받은 javascript key를 넣어줌 -> .env파일에서 호출시킴
저거 저 양식 붙여넣기 할때 따라온 주석이라
혹시 해주실 말씀 있으시면 부탁드리겠습니다 ㅠ

2024-01-18 00:01 UTC, goldfrosch commented on src/utils/Kakao/ShareKaKaoLink.js
> +      kakao.init("39e36379232c0a9c4af7969a3d7593ea"); // 카카오에서 제공받은 javascript key를 넣어줌 -> .env파일에서 호출시킴
아...?
dotenv에 대해 조사해보시면 좋을 것 같아요 그러면!

2024-01-18 09:25 UTC, goldfrosch approved these changes
approve and merge 진행하겠습니다!

2024-01-18 09:25 UTC, merged