[노진석] week8 - 수정중
codeit-bootcamp-frontend/3-Weekly-Mission pull request #227
Opened 2024-01-13 13:38 UTC by SiWooJinSeok

## 요구사항

### 기본

- [x] 링크를 입력하고 “추가하기” 버튼을 누르면 “폴더에 추가” 모달이 보이나요?
- [x] “폴더 추가” 버튼을 누르면 “폴더 추가” 모달이 보이나요?
- [x] “공유” 버튼을 누르면 “폴더 공유” 모달이 보이나요?
- [x] “이름 변경” 버튼을 누르면 “폴더 이름 변경” 모달이 보이나요?
- [x] “삭제” 버튼을 누르면 “폴더 삭제” 모달이 보이나요?
- [x] 케밥 버튼을 누르면 “삭제하기”, “폴더에 추가” 버튼이 있는 팝오버가 보이나요?
- [x] 팝오버에 있는 “삭제하기” 버튼을 누르면 “링크 삭제” 모달이 보이나요?
- [x] 팝오버에 있는 “폴더에 추가” 버튼을 누르면 “폴더에 추가” 모달이 보이나요?
- [x] “폴더 공유” 모달에서 “카카오톡 아이콘”을 클릭하면 카카오로 공유 폴더 페이지 링크 공유하기 가능한가요?
- [x] “폴더 공유” 모달에서 “페이스북 아이콘”을 클릭하면 페이스북으로 공유 폴더 페이지 링크 공유하기 가능한가요?
- [x] “폴더 공유” 모달에서 “링크 아이콘”을 클릭하면 클립보드에 공유 폴더 페이지 링크가 복사 되나요?

## 주요 변경사항

- 모달 기능들 추가
- netlify 게시 주소 : https://superlative-raindrop-7cbd14.netlify.app/
- 링크 공유에서 카카오톡 링크 공유는 위에 주소에서만 가능! 로컬에서는 불가능
- "styled-components": "^6.1.8" 추가
- imageData.js assets폴더로 이동
- shared 페이지 받아오는 데이터 변경
- 케밥 호버에서 클릭으로 변경!

## 스크린샷
![1s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/1cb1853a-7833-4e9d-8069-9b7c02fcc490)

![2s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/1dd42d4a-3e0a-4386-a8ee-ab95f2c4fcaa)
![5s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/db971d99-b479-410e-9246-299a2b4f813f)
![8s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/b8e3bedb-154f-4fd5-af35-1ede4b0d29b8)
![3s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/11a43b93-a50c-4f9f-8969-e0f578a08727)
![6s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/24e0e38e-f1b7-4f4d-ade0-21249cbf9fda)
![9s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/45f7013e-1529-4d6a-a8c0-c621e6c6d0cf)
![10s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/392f5882-edd4-435c-88fe-d5ce6aa47ced)
![4s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/939945f7-5815-46b4-9bfb-de9d4f32c36d)
![7s](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/f140d519-5489-4d6d-a686-e6cfdf4914ac)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-01-16 14:32 UTC, wonsss commented on src/components/FolderNameLine/FolderNameLine.jsx
> +          </div>
### 버튼에 div를 사용하지 마세요. 버튼에는 button 요소를 사용해주세요. 

우리는 웹접근성이 좋은 페이지를 만들어야 합니다.
> “웹의 힘은 보편성에 있습니다. 장애에 관계없이 모든 사람이 접근할 수 있는 것이 필수적인 측면입니다.” — 팀 버너스 리

브라우저는 해당 요소가 클릭할 수 있는 button 요소인지 의미론적으로 해석할 수 있는 없습니다. 시각장애인에게 이를 알려주고 싶어도 div 요소로는 알 수가 없습니다.
그리고 페이지에서 사용자가 키보드의 Tab을 클릭하면, 페이지에 button들이 있다면 button 들 간에 다음 요소로 focus가 이동될 수 있고 Enter키를 통해 요소를 트리거할 수 있습니다. 하지만 div요소라면 이와 같이 focus가 될 수가 없습니다. 시각장애인, 노인 및 일반 사용자 중에서도 키보드 탐색에 의존하는 경우가 많습니다. 그런데 버튼에 div를 사용한다면, 이러한 접근성이 낮아집니다.

이외에도 button 요소는 기본적으로 hover 했을 때 cursor가 pointer 모양으로 변경되어 클릭 가능한 요소임을 알려주는 스타일을 갖고 있습니다. 
div 요소를 버튼으로 사용한다면, 별도로 해당 요소에 cursor: pointer 스타일을 지정했어야 하지만, button 요소는 그럴 필요가 없으므로 편리합니다.

그러나 button 요소는 기본적인 background, border, outline, box-shadow 등의 스타일을 내재하고 있습니다. 범용적으로 사용하려면 이러한 기본 스타일을 아래와 같은 reset css를 global에 적용하여 제거할 수 있습니다.

```css
button {
	background: none;
	border: none;
	outline: none;
	box-shadow: none;
}
```

2024-01-16 15:37 UTC, wonsss requested changes
진석님. 수고하셨습니다.
점점 코드가 좋아지네요! 👍 
리뷰 남겨드린 내용 참고하여 반영해보시면 좋겠습니다.

2024-01-16 15:37 UTC, wonsss commented on src/components/FolderNameLine/FolderNameLine.jsx
> +          </div>
## 버튼에 div를 사용하지 마세요. 버튼에는 button 요소를 사용해주세요. 

우리는 웹접근성이 좋은 페이지를 만들어야 합니다. 웹을 만든 팀 버너스 리는 접근성에 대해 강조했습니다.

> “웹의 힘은 보편성에 있습니다. 장애에 관계없이 모든 사람이 접근할 수 있는 것이 필수적인 측면입니다.” — 팀 버너스리

브라우저는 해당 요소가 클릭할 수 있는 button 요소인지 의미론적으로 해석할 수 있는 없습니다. 시각장애인에게 이를 알려주고 싶어도 div 요소로는 알 수가 없습니다.
그리고 페이지에서 사용자가 키보드의 Tab을 클릭하면, 페이지에 button들이 있다면 button 들 간에 다음 요소로 focus가 이동될 수 있고 Enter키를 통해 요소를 트리거할 수 있습니다. 하지만 div요소라면 이와 같이 focus가 될 수가 없습니다. 시각장애인, 노인 및 일반 사용자 중에서도 키보드 탐색에 의존하는 경우가 많습니다. 그런데 버튼에 div를 사용한다면, 이러한 접근성이 낮아집니다.

이외에도 button 요소는 기본적으로 hover 했을 때 cursor가 pointer 모양으로 변경되어 클릭 가능한 요소임을 알려주는 스타일을 갖고 있습니다. 
div 요소를 버튼으로 사용한다면, 별도로 해당 요소에 cursor: pointer 스타일을 지정했어야 하지만, button 요소는 그럴 필요가 없으므로 편리합니다.

참고로 button 요소는 기본적인 background, border, outline, box-shadow 등의 스타일을 내재하고 있습니다. 범용적으로 사용하려면 이러한 기본 스타일을 아래와 같은 reset css를 global에 적용하여 제거할 수 있습니다.

```css
button {
	background: none;
	border: none;
	outline: none;
	box-shadow: none;
}
```

2024-01-16 15:37 UTC, wonsss commented on src/components/Kebab/Kebab.jsx
> +          </button>
button 태그의 type 속성의 기본값은 submit입니다. 양식 제출용 버튼이 아니라면 type 특성을 button으로 지정하는걸 잊지 마세요. 기본값에서는 버튼을 눌렀을 때 양식 데이터를 제출하고, (존재하지 않는) 응답을 불러오려고 시도하는 과정에서 문서의 현재 상태가 사라질 수 있습니다.

>  button 태그의 type 속성: 버튼의 행동 방식. 가능한 값은 다음과 같습니다.
-submit: 버튼이 서버로 양식 데이터를 제출합니다. 지정하지 않은 경우 기본값이며, 유효하지 않은 값일 때도 사용합니다.
-reset: <input type="reset">처럼, 모든 컨트롤을 초깃값으로 되돌립니다.
-button: 기본 행동이 없으며 클릭했을 때 아무것도 하지 않습니다. 클라이언트측 스크립트와 연결할 수 있습니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/button

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/Modal.jsx
> +      <ModalContainer>
네이밍 시, wrapper와 container 를 구분하는 기준이 무엇이신가요?

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/Modal.jsx
> +        <ModalCloseButton
네이밍은 button인데 실제로 요소는 img네요. 
스타일드 컴포넌트의 이름은 오해가 없도록 만드는 게 좋습니다.
close하는 button 요소가 있고 내부에 img 요소가 있도록 만드는 게 좋을 것 같아요.

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/Modal.jsx
> +        {getModalContent({ modalId, folderName, modalUrl, itemList, user })}
Modal 컴포넌트가 props으로 children을 받도록 하고 이 코드를 {children} 자리로 대체하면 어떨까요?
그리고 해당 Modal 컴포넌트를 사용하는 곳에서 이 Modal 컴포넌트로 감싸고 그 사이에 `<ModalForm ~~중략~~ />` 처럼 그 곳에 해당하는 컴포넌트를 명시적으로 넣어주는 것도 방법일 것 같습니다. 현재 modalId를 props로 받아서 그 case에 따라 조건부렌더링을 이 안에서 다 해주고 있는데, modalId라는 관리 포인트를 늘릴 필요가 있을까 싶습니다.

또는 컴파운드 컴포넌트 패턴도 참고하여 고민해보세요. 😄

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/Modal.styled.jsx
Modal.styled.jsx 파일은 왜 분리해서 만드셨는지 궁금합니다.
사용하는 컴포넌트 파일에 같이 함께 위치하도록 넣어두는 게 더 가독성에 좋지 않을까요? 😄

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalAddLink/ModalAddLink.jsx
> +        {itemList &&
jsx 조건부 렌더링에서 && 연산자 대신 삼항조건연산자를 사용하는 것이 버그 방지를 위해 좋은 방법이라고 합니다

https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

2024-01-16 15:37 UTC, wonsss commented on src/components/CtaButton/CtaButton.jsx
> +export default function CtaButton({ CTAButtonStyle = CTAButton, children }) {
props 이름으로 CTAButtonStyle 은 해당 컴포넌트에 css를 전달해주는 느낌입니다.
그런데 현재 element 를 전달받고 있는 prop이므로, 더 좋은 이름을 고민해보면 좋겠습니다.

그리고 이 CtaButton이라는 컴포넌트는 Wrapper와 ButtonText 그리고 children 요소 3개로 이루어져있는데, 이 중에서 Wrapper와 children을 다 props로 받고 있네요. CTAButtonStyle prop 같은 Wrapper 요소를 prop으로 받기보다는, 컴포넌트 props으로 type 같은 것을 받아서 이에 따라 스타일드컴포넌트에 props를 전달하여 스타일을 동적으로 변경해주는 것도 고려해볼만 합니다.

스타일드컴포넌트의 passed props에 대해 공식문서 가이드를 참고해보세요.
https://styled-components.com/docs/basics#passed-props

<img width="1289" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/bf42f0ea-46a6-43e3-a2ed-f4c30f987592">

2024-01-16 15:37 UTC, wonsss commented on src/components/FolderListButton/FolderListButton.jsx
> +        id="addFolder"
img 요소에 추가하신 이 id는 어떤 역할을 하나요? 혹시 필요없는 속성은 아닌지 궁금합니다.

2024-01-16 15:37 UTC, wonsss commented on src/components/FolderListButton/FolderListButton.jsx
> +        onClick={ModalButtonClick}
핸들러 함수의 네이밍은 `handle` + `이벤트 발생하는 요소` + `이벤트 이름` 
이러한 방식으로 이벤트핸들러 이름을 일관되게 지으시는 것을 제안드려요.

특히 함수 이름을 대문자로 시작하게 지으셨는데 "ModalButtonClick", 일반적인 컨벤션에 어긋납니다. 함수는 반드시 소문자의 동사로 시작하도록 이름을 지어주세요.

[관련 링크](https://blog.sonim1.com/220#google_vignette)를 공유드려요.

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalShare/ModalShare.jsx
> +  const [curFolder] = itemList.filter((item) => item.name === folderName);
`const [curFolder] = itemList.filter((item) => item.name === folderName);` 는 itemList.filter((item) => item.name === folderName);를 해서 반환된 배열의 "첫번째 요소"를 curFolder라는 변수명으로 할당하는 것입니다.
이 코드를 읽는 개발자에게는 아마도 filter로 반환된 배열의 "첫번째 요소" 외에 "나머지 다른 요소"들의 존재가 신경쓰일 수 있어요. "만약 나머지 다른 요소들이 있다면 왜 다른 요소들은 사용하지 않고 첫번째 요소만 curFolder라는 이름을 붙여서 사용하는 것일까?" 같이요.

그래서 아래와 같이 배열의 find 메서드를 사용해서 리팩터링하면 어떨까요? 둘 다 결과적으로 같은 효과의 코드이지만, 의도가 더 명확하게 드러나는 코드는 어떤 것일지 고민하면 좋습니다~! 
```suggestion
  const curFolder = itemList.find((item) => item.name === folderName);
```

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalShare/ModalShare.jsx
> +  const [curFolder] = itemList.filter((item) => item.name === folderName);
그리고 curFolder라는 이름처럼 축약된 이름보다는 되도록 currentFolder 처럼 맞춤법에 맞는 네이밍을 하면 좋겠습니다. 

코드에서 축약어는 일반적으로 두 가지 위험을 초래합니다.
- 코드를 읽는 사람이 축약어를 이해하지 못할 수 있습니다.
- 다른 개발자가 같은 단어에 대해 여러 가지 다른 축약어를 사용해 쓸데없는 혼란을 초래할 수 있습니다.

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalShare/ModalShare.jsx
> +    window.open(`http://www.facebook.com/sharer/sharer.php?u=${sharedLink}`);
window.open 메서드를 사용하셨군요. 
일단 그냥 open보다는 popup 으로 여는 게 공유하기 시 일반적인 사용자 경험일 것 같습니다.
그리고 외부 하이퍼링크로 이동할 때는 보안 리스크를 방지하기 위해 nopener와 noreferrer 같은 속성 추가를 고민하시면 좋습니다.
[하이러링크를 신뢰할 수 없다면? noopener, noreferrer, nofollow](https://yozm.wishket.com/magazine/detail/1586/)

popup이나 보안 리스크 방지 기능 등은 open 메서드의 세번째 매개변수인 windowFeautres에 정해진 속성 값을 넘겨줌으로써 가능합니다. [[MDN window.open 참고]](https://developer.mozilla.org/en-US/docs/Web/API/Window/open)
 그리고 새 탭을 여는 것이니 두 번째 매개변수인 target에 "_blank"를 넘겨주세요. [[MDN a 요소 target 설명 참고]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target)

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalShare/ModalShare.jsx
> +    const sharedLink = encodeURIComponent(url);
uri 인코딩하셨군요 👍

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalShare/ModalShare.jsx
> +    shareKakao(url, folderName);
유틸함수로 분리하셨네요. 범용성이 있는 기능이라 잘 분리하셨습니다. 👍

2024-01-16 15:37 UTC, wonsss commented on src/components/Modal/ModalShare/ModalShare.jsx
> +  const handleShareToFacebook = () => {
페이스북 공유 기능도 범용적이므로 유틸함수로 분리하면 좋을 것 같습니다.

2024-01-16 15:37 UTC, wonsss commented on src/utils/util.js
> +export const handleCopyClipBoard = async (text) => {
이건 직접적인 이벤트 핸들러 함수가 아니므로 handleCopyClipBoard 라는 이름보다는 copyClipboard 같은 명시적인 이름은 어떠신가요?

2024-01-16 15:37 UTC, wonsss commented on public/index.html
> +      Kakao.init("32adc3f02c72c6c7bb61effc65a716ec"); // 사용하려는 앱의 JavaScript 키 입력
이러한 시크릿 key는 외부에 노출되면 안되므로, `.env` 같은 환경변수 파일을 만들고 여기서 가져와서 사용해주세요.
그리고 해당 `.env`파일이 깃허브에 함께 푸시되면 안되므로, `.gitignore`에서 `.env`를 목록에 추가해주세요.

2024-01-16 15:37 UTC, wonsss commented on src/utils/kakaoShare.js
> +  window.Kakao.Share.sendDefault({
카카오 공유하기 API를 잘 사용하셨네요 👍

2024-01-17 09:29 UTC, SiWooJinSeok commented on src/components/FolderNameLine/FolderNameLine.jsx
> +          </div>
[refactor: div를 button으로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/b8cf57e6616155bb0cdb523e94f1f8b12bf4ad4f)
여기서 수정했습니다!

2024-01-17 09:36 UTC, SiWooJinSeok commented on src/components/Kebab/Kebab.jsx
> +          </button>
[refactor: button태그 type button으로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/16b954ad31f9cac90e805c7a3fce371c4157a1f5)
여기서 수정했습니다!

2024-01-17 09:41 UTC, SiWooJinSeok commented on src/components/Modal/Modal.jsx
> +      <ModalContainer>
![dd](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/755ce5dd-c9c3-4011-abc6-248123871414)
이번 팀 프로젝트에서 이런 느낌으로 사용하기로 해서 프로젝트에 적용해봤습니다!

2024-01-17 09:44 UTC, SiWooJinSeok commented on src/components/Modal/Modal.jsx
> +        <ModalCloseButton
[refactor: closeButton img에서 button으로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/400d8552acb5001f1ac6300a1b5b299454032589)
여기서 수정했습니다!

2024-01-17 09:47 UTC, SiWooJinSeok commented on src/components/Modal/Modal.jsx
> +        {getModalContent({ modalId, folderName, modalUrl, itemList, user })}
감이 잡히지 않아서 아무래도 더 생각해보고 수정해야 할 것 같습니다! children까진 이해 했는데 그러면 밖에서 호출할 때 어떤 식으로 설계를 해야하는지 감이 안오네용.. 나중에 리펙토링 시간 남을 때 한번 더 고민해보겠습니다!

2024-01-17 09:54 UTC, SiWooJinSeok commented on src/components/Modal/Modal.styled.jsx
뭔가 중복되는 스타일들이 있기에 일일이 다 쓰는 것보다 중복되는 부분만 따로 빼고 싶어서 작성했었습니다! 
원래 ModalForm 이 아니라 Add, Edit 따로 있었는데 거기서 부터 빼서 작성하면서 중복될 것 같은 것들만 남겨뒀었습니다.

2024-01-17 09:56 UTC, SiWooJinSeok commented on src/components/Modal/ModalAddLink/ModalAddLink.jsx
> +        {itemList &&
[refactor: &&연산자에서 삼항연산자로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/62c384a8294354d36f55c17e338e20dcdd3fed1f)
여기서 수정했습니다!

2024-01-17 11:11 UTC, SiWooJinSeok commented on src/components/CtaButton/CtaButton.jsx
> +export default function CtaButton({ CTAButtonStyle = CTAButton, children }) {
StyledComponent.ts:142 styled-components: it looks like an unknown prop "styledType" is being sent through to the DOM, which will likely trigger a React console error. If you would like automatic filtering of unknown props, you can opt-into that behavior via `<StyleSheetManager shouldForwardProp={...}>` (connect an API like `@emotion/is-prop-valid`) or consider using transient props (`$` prefix for automatic filtering.)
(anonymous) @ StyledComponent.ts:142
O @ StyledComponent.ts:194
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
프레임 13개 더 표시
간단히 표시
react-dom.development.js:86 Warning: React does not recognize the `styledType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `styledtype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
  at button
  at O (http://localhost:3000/static/js/bundle.js:50643:6)
  at CtaButton (http://localhost:3000/static/js/bundle.js:1801:3)
  at form
  at LinkAddForm
  at section
  at main
  at FolderPage (http://localhost:3000/static/js/bundle.js:4320:3)
  at RenderedRoute (http://localhost:3000/static/js/bundle.js:44833:5)
  at RenderedRoute (http://localhost:3000/static/js/bundle.js:44833:5)
  at Routes (http://localhost:3000/static/js/bundle.js:45524:5)
  at Router (http://localhost:3000/static/js/bundle.js:45458:15)
  at BrowserRouter (http://localhost:3000/static/js/bundle.js:43438:5)
  at App (http://localhost:3000/static/js/bundle.js:1213:74)
  
  
![123](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59861974/1c7e3b14-b27a-4c84-89df-795546e18480)
이런 에러들이 떠서 리셋 시켰습니다.. ㅠㅠ 동작은 하는데 에러가 자꾸 보여서 그냥 리셋 시켰어요..!

2024-01-17 11:15 UTC, SiWooJinSeok commented on src/components/FolderListButton/FolderListButton.jsx
> +        id="addFolder"
[refactor: div를 button으로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/b8cf57e6616155bb0cdb523e94f1f8b12bf4ad4f) 여기서 같이 버튼으로 수정했습니다!
modalId 값을 받아와서 폴더 추가하기 모달이 뜹니다!

2024-01-17 11:23 UTC, SiWooJinSeok commented on src/components/FolderListButton/FolderListButton.jsx
> +        onClick={ModalButtonClick}
[chore: handleModalButtonClick으로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/9725025be4d29a4112f448f94897c94c1d91239e)
여기서 수정했습니다!

2024-01-17 11:29 UTC, SiWooJinSeok commented on src/components/Modal/ModalShare/ModalShare.jsx
> +  const [curFolder] = itemList.filter((item) => item.name === folderName);
[refactor : filter를 find로 변경 및 변수명 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/92bfa62f9ad6ad4f768a6cd8a585dbdd10d79b6c)
여기서 수정했습니다!

2024-01-17 11:46 UTC, SiWooJinSeok commented on src/components/Modal/ModalShare/ModalShare.jsx
> +    window.open(`http://www.facebook.com/sharer/sharer.php?u=${sharedLink}`);
[chore : _blank,popup,noopener,noreferrer 추가](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/c63aeb7a07c14ac99f977c2fdfc407af130e2e5f)
여기서 이렇게 추가하면 되는 것이 맞을까요?

2024-01-17 11:47 UTC, SiWooJinSeok commented on src/utils/kakaoShare.js
> +  window.Kakao.Share.sendDefault({
감사합니다!

2024-01-17 12:06 UTC, SiWooJinSeok commented on src/components/Modal/ModalShare/ModalShare.jsx
> +  const handleShareToFacebook = () => {
[chore : util함수 분리 및 함수 이름 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/48cc93861d6271e656610958bdfa9f6179115a14)
여기서 같이 수정했습니다!

2024-01-17 12:08 UTC, SiWooJinSeok commented on src/utils/util.js
> +export const handleCopyClipBoard = async (text) => {
여기서 같이 수정했습니다!

2024-01-17 12:26 UTC, SiWooJinSeok commented on public/index.html
> +      Kakao.init("32adc3f02c72c6c7bb61effc65a716ec"); // 사용하려는 앱의 JavaScript 키 입력
[chore : 키 값 숨기기](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/227/commits/6503370672bc99dfd71bfd656c671303944a52c9)
여기서 수정했습니다!

2024-01-17 12:28 UTC, SiWooJinSeok commented
이번주는 팀프로젝트도 있고 해서 정신이 없네용,, ㅎㅎ 급하게 수정한 부분도 많아서 팀 프로젝트 끝나고 시간적 여유 있을 때 좀 더 수정해야 할 것 같습니다...! 생각처럼 잘 안되니 힘드네요 ㅠㅠ

2024-01-17 12:29 UTC, SiWooJinSeok commented
> 진석님. 수고하셨습니다. 점점 코드가 좋아지네요! 👍 리뷰 남겨드린 내용 참고하여 반영해보시면 좋겠습니다.

이번주는 팀프로젝트도 있고 해서 정신이 없네용,, ㅎㅎ 급하게 수정한 부분도 많아서 팀 프로젝트 끝나고 시간적 여유 있을 때 좀 더 수정해야 할 것 같습니다...! 생각처럼 잘 안되니 힘드네요 ㅠㅠ

2024-01-18 15:27 UTC, wonsss commented on src/components/Modal/Modal.jsx
> +      <ModalContainer>
좋은 기준을 잡으셨네요!

2024-01-18 15:30 UTC, wonsss commented on src/components/CtaButton/CtaButton.jsx
> +export default function CtaButton({ CTAButtonStyle = CTAButton, children }) {
에러 내용은 button 요소 안에 buuton 을 넣었을 때 나오는 warning이네요. 🤔

2024-01-18 15:31 UTC, wonsss approved these changes
LGTM

2024-01-18 15:31 UTC, merged