[조성경] week8
codeit-bootcamp-frontend/3-Weekly-Mission pull request #231
Opened 2024-01-14 06:27 UTC by whtjdrud

## 멘토에게

- 모달 구현 중 title 이 정상적으로 출력되지 않아 해결하지 못하고 제출합니다.
- modal 컴포넌트 안에 title을 console.log로 출력하면 2번이 출력
- 정상 타이틀 출력 된 뒤 undefined 값이 출력되었습니다. 
- 왜 이전 커밋 내용들이 계속해서 남아있는지 원인도 확인 중입니다.

2024-01-17 00:20 UTC, goldfrosch requested changes
고생하셨습니다!
항상 열심히 하시고 잘해주셔서 너무 좋네요!

밑의 PR 확인 부탁드립니다!

2024-01-17 00:20 UTC, goldfrosch commented on assets/css/index.css
> +}
grid와 nth-child를 잘 활용해보셨군요 좋습니다~

2024-01-17 00:20 UTC, goldfrosch commented on src/components/folder/mainHeader.js
> +      {modalType === '수정' && (
타입 하나에 여러 enum(js, ts의 enum 개념 아니고...)을 넣어 그 타입에 따라 처리하는 방식 아주 좋습니다 ㅎㅎ

2024-01-17 00:20 UTC, goldfrosch commented on src/components/modals/modal.jsx
> +  console.log(title);
[중요도: 중간] console.log는 메모리를 잡아먹고 가끔씩은 위험한 데이터를 콘솔로 노출시켜 웬만해서 개발할 때는 빼는게 좋습니다. (물론 바벨 or 모듈 번들러 설정으로 없애는 것도 가능하나 굳이굳이 남길 이유는 없겠죠...?)
테스트는 console.log보다는 웹 Extension ReactDevTools를 쓰는데 더 익숙해져 보세요! 저도 요새는 그걸로 하려고 노력 중입니다.

2024-01-17 00:20 UTC, goldfrosch commented on src/components/modals/modal.jsx
> +    if (e.target === e.currentTarget) {
[중요도: 높음] e.target과 e.currentTarget의 차이는 뭘까요?

2024-01-17 00:20 UTC, goldfrosch commented on src/components/folder/mainHeader.js
> +          <FolderNameChange toggleModal={() => toggleModal()} folderName={activeFolderName} />
```suggestion
        <Modal toggleModal={toggleModal} title="폴더 이름 변경">
          <FolderNameChange toggleModal={toggleModal} folderName={activeFolderName} />
```
[중요도: 낮음] JS의 경우는 이렇게 써도 된답니다 ㅎㅎ

2024-01-17 00:20 UTC, goldfrosch commented on src/components/folder/mainHeader.js
> +          <MainTitle>{activeFolderName || '전체'}</MainTitle>
```suggestion
          <MainTitle>{activeFolderName ?? '전체'}</MainTitle>
```
[중요도: 중간] 위 방식을 더 권장 드립니다.
|| 연산자: falsy한 값을 탐색함(undefined, null, false, 0 등)
?? 연산자: nullish한 값을 탐색함(undefined, null)

현재 방식은 ||도 가능은 하나 최대한 ??를 사용하는게 괜한 사이드 이펙트 방지에 도움이 됩니다!

2024-01-17 00:28 UTC, goldfrosch commented
Q. 모달 구현 중 title 이 정상적으로 출력되지 않아 해결하지 못하고 제출합니다.
A. ㅠㅠ... 항상 이유는 생각보다 단순한 곳에 있으니 나중에 기회가 되면 꼭 찾아보세요!

Q. modal 컴포넌트 안에 title을 console.log로 출력하면 2번이 출력
A. console.log의 위치가 2번 이상이 충분히 발생할 수 있는 것으로 보입니다! 리렌더링과 다시 선언하는 것(reconciliation)은 다른 개념이라고 생각하시는게 좋습니다.

리렌더링: 화면이 변함.
reconciliation(한글로 적기 좀 민망해서 ㅎㅎ..): 화면이 할 수 있는지 비교하고 계산하는 과정

상위 컴포넌트가 리렌더링 된다면 하위컴포넌트는 Reconcilation 즉 계산하는 과정이 다시 발생하게 됩니다. 리렌더링이 되지 않더라도 충분히 발생할 수 있죠.

그러면 이게 console.log가 2번 찍힌 것이랑 무슨 상관이냐 하면, 컴포넌트 바로 내부 return문 전까지 선언한 것들은 재계산(reconciliation을 적기 편하게 재계산이라 정의할게요~)하게 될 때 함수, 변수(let, const, useState나 useRef말고)는 재 할당되게 됩니다. console.log도 마찬가지로 컴포넌트를 재계산하게 되면서 새로 선언이 되기 때문에 재호출되는 것이구요.

조금 난해하게 설명한 것 같지만 짧게 설명드리면 결국 계산하는 과정이 있었기 때문에 console.log가 두번 호출된 것입니다.
1번을 호출하게 하려면 useEffect에 넣어서 사용하시면 되구요, 2번 호출되는 근본적인 이유가 궁금하시다면 상위 컴포넌트로 올라가 그 컴포넌트가 리렌더링 되는 이유를 찾아보시는 게 좋을 듯 합니다!


Q. 정상 타이틀 출력 된 뒤 undefined 값이 출력되었습니다.
A. 어디선가 리렌더하면서 title을 없애는 로직이 있을 수도 있겠네요. Modal의 상위 컴포넌트들의 로직을 잘 살펴보죠. Context니까 관련된 곳들을 다 찾아봐야할 수 있겠에요.

Q. 왜 이전 커밋 내용들이 계속해서 남아있는지 원인도 확인 중입니다.
A. 깃은 늘 어려웡...

2024-01-17 00:47 UTC, whtjdrud commented on src/components/modals/modal.jsx
> +    if (e.target === e.currentTarget) {
e.target의 경우 이벤트가 발생한 태그
e.currentTarget은 이벤트 리스너가 달린 태그입니다.

이벤트 버블링 현상으로 인해서 제가 원치 않은 곳에서 이벤트를 발생하는 것을 막기 위해서 체크했씁니다.

2024-01-17 00:48 UTC, whtjdrud commented on assets/css/index.css
> +}
감사합니다

2024-01-17 00:49 UTC, whtjdrud commented on src/components/modals/modal.jsx
> +  console.log(title);
ReactDevTools에 대해서 찾아봤고 심지어 설치도 되어있긴 합니다.. ㅎ
설치는 했지만 불편하다고 생각해서 console.log로 찍었는데 저도 노력해보겠습니다.

2024-01-17 00:57 UTC, goldfrosch commented on src/components/modals/modal.jsx
> +  console.log(title);
저도 불편해도 그걸로 해보려 더욱 노력중입니다. 이전에 팀장님에게도 CDD(Console Driven Developement)했다가 놀림당했어요... ;-;

2024-01-17 00:57 UTC, whtjdrud commented on src/components/folder/mainHeader.js
> +          <MainTitle>{activeFolderName || '전체'}</MainTitle>
### 널 병합 할당
[널 병합 할당 (en-US)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment)

- ||는 첫 번째 truthy 값을 반환
- ??는 첫 번째 정의된(defined) 값을 반환

```javascript
let height = 0;

alert(height || 100); // 100
alert(height ?? 100); // 0
```
??의 경우 정확히 null이나 undefined인 경우에만 사용

좋은것 배웠습니다. 감사합니다.

2024-01-17 00:58 UTC, goldfrosch commented on src/components/modals/modal.jsx
> +    if (e.target === e.currentTarget) {
버블링 현상의 경우는
e.stopPropagation()으로 막을 수 있습니다! 혹시 이 메소드를 쓰지 않고 처리한 이유가 따로 있을까요~?

2024-01-17 00:59 UTC, goldfrosch commented on src/components/folder/mainHeader.js
> +          <MainTitle>{activeFolderName || '전체'}</MainTitle>
저보다 더 잘 정리해주셧군요 좋습니다 ㅎㅎ

2024-01-17 10:34 UTC, whtjdrud commented on src/components/modals/modal.jsx
> +    if (e.target === e.currentTarget) {
예전에 처음 이벤트 버블링을 배울때 방지하는 여러가지 방법중에 하나라고 했었습니다.
e.stopPropagation()은 폼이 자동으로 동작하지 않게만 사용 으로만 생각했었는데 앞으로 사용해보겠습니다.

2024-01-22 04:21 UTC, goldfrosch commented
기한이 지나 merge 처리해두겠습니다.

2024-01-22 04:21 UTC, merged