[이시열] Week8
codeit-bootcamp-frontend/3-Weekly-Mission pull request #232
Opened 2024-01-14 10:41 UTC by siyeol97

## 요구사항

### 기본
- [x] 링크를 입력하고 “추가하기” 버튼을 누르면 “폴더에 추가” 모달이 보이나요?
- [x] “폴더 추가” 버튼을 누르면 “폴더 추가” 모달이 보이나요?
- [x] “공유” 버튼을 누르면 “폴더 공유” 모달이 보이나요?
- [x] “이름 변경” 버튼을 누르면 “폴더 이름 변경” 모달이 보이나요?
- [x] “삭제” 버튼을 누르면 “폴더 삭제” 모달이 보이나요?
- [x] 케밥 버튼을 누르면 “삭제하기”, “폴더에 추가” 버튼이 있는 팝오버가 보이나요?
- [x] 팝오버에 있는 “삭제하기” 버튼을 누르면 “링크 삭제” 모달이 보이나요?
- [x] 팝오버에 있는 “폴더에 추가” 버튼을 누르면 “폴더에 추가” 모달이 보이나요?
- [x] “폴더 공유” 모달에서 “카카오톡 아이콘”을 클릭하면 카카오로 공유 폴더 페이지 링크 공유하기 가능한가요?
- [x] “폴더 공유” 모달에서 “페이스북 아이콘”을 클릭하면 페이스북으로 공유 폴더 페이지 링크 공유하기 가능한가요?
- [x] “폴더 공유” 모달에서 “링크 아이콘”을 클릭하면 클립보드에 공유 폴더 페이지 링크가 복사 되나요?
## 주요 변경사항
- 링크 추가, 폴더 추가, 공유, 이름 변경, 삭제 모달 컴포넌트 추가
- 카카오톡, 페이스북에 폴더 공유 기능, 링크 클립보드 복사 기능 추가
## 설치 및 실행 방법
```
git clone --branch part2-이시열-week8 https://github.com/siyeol97/3-Weekly-Mission.git
```
```
npm i
```
```
npm run start
```
## Netlify URL
https://siyeol-codeit-linkbrary.netlify.app/folder

## 스크린샷
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/5ce62c18-462f-4ded-88c3-c614ff56de1a)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/85405709/d93f6bf8-2eae-4832-9f13-d38148948358)
## 멘토에게

- eslint와 prettier 설정이 충돌이 나는건지 ```curly-newline``` 관련해서 자꾸 오류가 나서 일단 규칙을 꺼두었습니다..
오류가 날때 마다 규칙을 off 하고있는데 이게 맞는건지 잘 모르겠습니다

2024-01-16 17:21 UTC, wonsss requested changes
시열님 수고 많으셨습니다.
고민을 많이 하신 흔적이 느껴집니다!
코드도 매번 더 좋아지시네요. 👍 
리뷰 남겨드렸으니 참고하여 반영 부탁드립니다.

2024-01-16 17:21 UTC, wonsss commented on src/utils/shareKakao.js
> +  }
이 조건 때문에 카카오 공유하기 테스트를 할 수가 없네요.ㅠ

2024-01-16 17:21 UTC, wonsss commented on src/utils/shareKakao.js
> +    const newLink = camelcaseKeys(link);
camelcaseKeys 같이 api 응답값 포맷팅 로직은 fetcher 쪽 로직에서 다 처리해서 컴포넌트로 넘겨주면 좋을 것 같습니다.

2024-01-16 17:21 UTC, wonsss commented on src/utils/shareKakao.js
> +  }
공용 유틸인데, 이러한 도메인 로직이 함께 있을 필요가 있을까요?
요구사항이라고 하더라도, 이러한 예외 처리는 shareKakao 함수 내가 아닌 외부로 빼주는 게 맞을 것 같습니다.

2024-01-16 17:21 UTC, wonsss commented on src/utils/shareKakao.js
> +const shareKakao = (links, folderName, shareUrl) => {
공용 유틸 분리 좋습니다. 👍 
그런데 이 유틸함수를 다른 맥락의 다른 페이지에서 재사용한다고 했을 때, 현재 매개변수가 적절한지 고민해보면 좋겠습니다.
title, description, imageUrl, link 같이 카카오 API에서 필요로 하며 범용적인 이름을 매개변수로 정하는 게 어떨까요?

2024-01-16 17:21 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +const kakaoApiKey = process.env.REACT_APP_API_KEY;
api key를 env로 관리하셨군요 👍 

적용하신 것처럼 이러한 시크릿 key는 외부에 노출되면 안되므로, `.env` 같은 환경변수 파일을 만들고 여기서 가져와서 사용해야 합니다.

2024-01-16 17:21 UTC, wonsss commented on .gitignore
> +.env
해당 `.env`파일이 깃허브에 함께 푸시되면 안되므로, `.gitignore`에 `.env`를 잘 추가해주셨네요 👍

2024-01-16 17:21 UTC, wonsss commented on package.json
> +    "react-share": "^5.0.3",
react-share 라이브러리를 사용하셨군요.
외부 라이브러리 사용 이유가 궁금합니다.

2024-01-16 17:21 UTC, wonsss commented on src/App.jsx
> +      <GlobalStyle />
글로벌스타일 적용하셨군요 👍

2024-01-16 17:21 UTC, wonsss commented on src/components/AddLink/AddLink.jsx
> +        <AddButton id="addLinkButton" onClick={handleButtonClick}>
AddButton 이 어떤 요소인지 보니까 div로 지정하셨더라구요.

### 버튼에 div를 사용하지 마세요. 버튼에는 button 요소를 사용해주세요. 

우리는 웹접근성이 좋은 페이지를 만들어야 합니다. 웹을 만든 팀 버너스 리는 접근성에 대해 강조했습니다.

> “웹의 힘은 보편성에 있습니다. 장애에 관계없이 모든 사람이 접근할 수 있는 것이 필수적인 측면입니다.” — 팀 버너스리

브라우저는 해당 요소가 클릭할 수 있는 button 요소인지 의미론적으로 해석할 수 있는 없습니다. 시각장애인에게 이를 알려주고 싶어도 div 요소로는 알 수가 없습니다.
그리고 페이지에서 사용자가 키보드의 Tab을 클릭하면, 페이지에 button들이 있다면 button 들 간에 다음 요소로 focus가 이동될 수 있고 Enter키를 통해 요소를 트리거할 수 있습니다. 하지만 div요소라면 이와 같이 focus가 될 수가 없습니다. 시각장애인, 노인 및 일반 사용자 중에서도 키보드 탐색에 의존하는 경우가 많습니다. 그런데 버튼에 div를 사용한다면, 이러한 접근성이 낮아집니다.

이외에도 button 요소는 기본적으로 hover 했을 때 cursor가 pointer 모양으로 변경되어 클릭 가능한 요소임을 알려주는 스타일을 갖고 있습니다. 
div 요소를 버튼으로 사용한다면, 별도로 해당 요소에 cursor: pointer 스타일을 지정했어야 하지만, button 요소는 그럴 필요가 없으므로 편리합니다.

참고로 button 요소는 기본적인 background, border, outline, box-shadow 등의 스타일을 내재하고 있습니다. 범용적으로 사용하려면 이러한 기본 스타일을 아래와 같은 reset css를 global에 적용하여 제거할 수 있습니다.

```css
button {
	background: none;
	border: none;
	outline: none;
	box-shadow: none;
}
```

2024-01-16 17:21 UTC, wonsss commented on src/components/AddLink/AddLink.jsx
> +    e.preventDefault();
e.preventDefault()를 추가하신 이유가 무엇인가요?

2024-01-16 17:21 UTC, wonsss commented on src/components/AddLink/AddLink.jsx
> +      <Wrapper htmlFor="linkInput">
Wrapper라는 이름보다는 해당 요소의 이름을 사용해서 Label이라고 하는 게 더 읽기 좋을 것 같아요.

2024-01-16 17:21 UTC, wonsss commented on src/components/AddLink/AddLink.jsx
> +const Wrapper = styled.label`
시맨틱하게 form, label, input을 잘 사용해주셨네요 👍

2024-01-16 17:21 UTC, wonsss commented on src/components/Folder/Folder.jsx
> +    setIsModalClicked(!isModalClicked);
state를 직접적으로 사용하여 변경하기보다는,
setIsModalClicked(prev => !prev) 처럼 setState의 인자로 함수를 이용하는 것이 좋습니다.
자세한 내용은 리액트 공식문서 내용을 참고해보세요.
https://ko.legacy.reactjs.org/docs/hooks-reference.html#functional-updates

2024-01-16 17:21 UTC, wonsss commented on src/components/Folder/Folder.jsx
> +  const folderList = useFolderLinks(`users/${userId}/folders`);
커스텀훅을 만들어서 사용하셨군요. 👍

2024-01-16 17:21 UTC, wonsss commented on src/components/Modal/AddFolder.jsx
> +    </AddFolderWrapper>
AddFolder 컴포넌트 내부에서만 사용하는 스타일드컴포넌트들은
이름에 접두사로 AddFolder를 다 붙이셨는데, 오히려 AddFolder를 다 제거하더라도 AddFolder 내부라는 맥락이 있으므로
괜찮을 것 같습니다. 그리고 스타일드컴포넌트에서 AddFolder라는 접두사를 빼면 스타일드컴포넌트 이름이 더 잘 읽혀서 가독성에도 도움이 될 것 같습니다.

2024-01-16 17:21 UTC, wonsss commented on src/components/Modal/Modal.jsx
> +export default function Modal({
효율적인 모달 관리를 위해서 Context API를 사용하는 방안도 고려해보세요.

참고할 수 있는 링크 전달드립니다.
[[React] 효율적인 모달 관리 (with Context API)
](https://velog.io/@eunnbi/%ED%9A%A8%EC%9C%A8%EC%A0%81%EC%9D%B8-%EB%AA%A8%EB%8B%AC-%EA%B4%80%EB%A6%AC)

2024-01-16 17:21 UTC, wonsss commented on src/components/Folder/Folder.jsx
> +    document.documentElement.style.scrollbarGutter = 'stable';
scrollbarGutter 에 stable 속성을 지정하신 이유가 궁금합니다.
그리고 그걸 useEffect 내에서 하지 않아도 될 것 같습니다.

2024-01-16 17:21 UTC, wonsss commented on src/components/Folder/Folder.jsx
> +    };
useEffect 내에 이 스타일 속성 지정은 어떤 이유로 필요하셨는지 궁금합니다.
없어도 되지 않나요?

2024-01-16 17:21 UTC, wonsss commented on src/components/Modal/ShareFolder.jsx
> +  }, []);
커스텀훅으로 분리하면 어떨까요?

2024-01-16 17:21 UTC, wonsss commented on src/components/Folder/Folder.jsx
>  export default function Folder() {
페이지 역할을 하는 컴포넌트는 components 폴더가 아닌 별도의 pages 폴더에 분리하고 컴포넌트 이름도 FolderPage 처럼 page를 접미사로 붙여서 역할을 이름에서 명시적으로 드러내주면 가독성과 유지보수에 도움이 될 것 같습니다.

2024-01-18 04:36 UTC, siyeol97 commented on src/utils/shareKakao.js
> +  }
[fix: shareKaKao 함수 수정, 유저 id 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/e14bc78e414aabb8ba3324d3cb64e6a8599f8705)
예외처리를 외부로 빼고 테스트 할 수 있게끔 id를 변경해보았습니다.
아마 다른기수에서 원래 있던 링크들을 삭제한거같아요

2024-01-18 04:54 UTC, siyeol97 commented on src/utils/shareKakao.js
> +    const newLink = camelcaseKeys(link);
[fix: camelcaseKeys 처리 위치 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/4dc9ccfa9ea68c2e3b912837f41e107ac3c520ba)
수정해보았습니다.

2024-01-18 04:54 UTC, siyeol97 commented on package.json
> +    "react-share": "^5.0.3",
facebook에 공유하기 기능을 추가하는 방법중 가장 쉬운 방법이라고 해서 사용해보았습니다.

2024-01-18 05:04 UTC, siyeol97 commented on src/components/AddLink/AddLink.jsx
> +        <AddButton id="addLinkButton" onClick={handleButtonClick}>
[fix: 버튼 요소 div -> button으로 변경](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/0a8f6b0b4ab583080b9a8272ec9969c50242b7a9)
넵! 참고하겠습니다

2024-01-18 05:06 UTC, siyeol97 commented on src/components/AddLink/AddLink.jsx
> +    e.preventDefault();
e.preventDefault()를 추가하지 않으면 버튼을 누르면 모달창이 뜨지 않고 바로 submit이 되어버려서 기본 동작을 막기 위해 사용했습니다.

2024-01-18 05:13 UTC, siyeol97 commented on src/components/AddLink/AddLink.jsx
> +      <Wrapper htmlFor="linkInput">
[fix: Wrapper -> Label로 이름 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/20c231e7ab06834f4be1eb63bd779e14043aaafc)
수정했습니다!

2024-01-18 05:22 UTC, siyeol97 commented on src/components/Modal/AddFolder.jsx
> +    </AddFolderWrapper>
[fix: styled-components 이름 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/4adb4e3e65061ce4ab6b012cc07c954324ab8224)
앞으로도 참고하겠습니다!

2024-01-18 05:23 UTC, siyeol97 commented on src/components/Modal/Modal.jsx
> +export default function Modal({
감사합니다 참고하겠습니다

2024-01-18 05:34 UTC, siyeol97 commented on src/components/Folder/Folder.jsx
> +    };
모달창이 뜨면 body가 스크롤 되는걸 막고싶어서 지정했습니다! 저는 거슬리더라구요

2024-01-18 05:36 UTC, siyeol97 commented on src/components/Folder/Folder.jsx
> +    document.documentElement.style.scrollbarGutter = 'stable';
[fix: scrollbarGutter 지정 제거](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/a5f5fb6b73fbead40551030a44ce3b912f5b58c7)
스크롤바가 없어지고 생기면서 화면의 너비가 계속 바뀌어서 지정을 했었는데 지금 확인해보니까 안바뀌더라구요 그래서 제거했습니다!

2024-01-18 05:54 UTC, siyeol97 commented on src/components/Modal/ShareFolder.jsx
> +  }, []);
[fix: kakao 공유하기 init 부분 커스텀 훅으로 분리](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/8e807d5b2efc2254581a4048a0d7fa8d0f60cd19)
분리해보았습니다

2024-01-18 05:54 UTC, siyeol97 commented on src/components/Folder/Folder.jsx
>  export default function Folder() {
넵! 참고해서 앞으로 기초프로젝트, 과제에 반영해보겠습니다

2024-01-18 05:57 UTC, siyeol97 commented on src/components/Folder/Folder.jsx
> +    setIsModalClicked(!isModalClicked);
[fix: useState 인자를 콜백으로 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/3b852d353979d0c3660f6520c4a9c33feda657a6)
참고해서 수정했습니다!

2024-01-18 06:02 UTC, siyeol97 commented on src/utils/shareKakao.js
> +const shareKakao = (links, folderName, shareUrl) => {
[fix: 매개변수 이름 범용성 있게 수정](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/232/commits/4cf4036bc976a9047b5fa253f937187f6c32ba53)
수정해보았습니다

2024-01-18 16:06 UTC, wonsss commented on package.json
> +    "react-share": "^5.0.3",
라이브러리를 사용하지 않고도 가능한 방법도 한번 확인해보시면 좋아요.

사실 코드 한줄만으로 페이스북 공유하기가 가능할 수 있습니다. 해당 라이브러리는 이보다 더 좋은 많은 기능을 제공하겠지만, 용량을 그만큼 많이 차지하게 되는 것이라서 트레이드오프가 있습니다. 라이브러리를 사용했을 때 현재, 그리고 미래에 어떤 이익과 리스크가 있을지 예상해서 라이브러리를 사용해보시면 좋을 것 같습니다.

2024-01-18 16:08 UTC, wonsss commented on src/components/AddLink/AddLink.jsx
> +    e.preventDefault();
submit이 되는 이유가 button 요소에 type을 적용하지 않아서 기본값인 submit type이 적용되어서 그럴 거에요. 
button요소에 type="button"을 하셨다면, 해당 클릭 이벤트 핸들러에  e.preventDefault(); 메서드가 필요 없을 것 같아요. 😄

2024-01-18 16:09 UTC, wonsss approved these changes

2024-01-18 16:09 UTC, merged