[심은주] Week6
codeit-bootcamp-frontend/3-Weekly-Mission pull request #234
Opened 2024-01-14 16:22 UTC by nyaknya

## 요구사항

### 기본

- [x] 상단 네비게이션 바, 푸터가 랜딩 페이지와 동일한 스타일과 규칙으로 만들어졌나요? (week 1 ~ 3 요구사항 참고)
- [x] 상단 네비게이션 바에 프로필 영역의 데이터는 https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sample/user”를 활용했나요?
- [x] 상단 네비게이션 바에 프로필 영역의 데이터가 없는 경우 “로그인” 버튼이 보이도록 만들었나요?
- [x] 폴더 소유자, 폴더 이름 영역, 링크들에 대한 데이터는 “/api/sample/folder”를 활용했나요?
- [x] Static, no image, Hover 상태 디자인을 보여주는 카드 컴포넌트를 만들었나요?
- [x] Hover 상태에서 이미지가 기본 크기의 130%로 커지나요?
- [x] 카드 컴포넌트를 클릭하면 해당 링크로 새로운 창을 띄워서 이동하나요?
- [x] Tablet에서 카드 리스트가 화면의 너비 1124px를 기준으로 이상일 때는 3열로 작을 때는 2열로 배치되나요?
- [x] Tablet, Mobile에서 좌우 최소 여백은 32px 인가요?

### 심화

- [] [심화]커스텀 hook을 만들어 활용했나요?

## 주요 변경사항

- 즐겨찾기 화면 리액트 구현

## 멘토에게

- 안녕하세요, 멘토님. 아주 예전에 DM을 드린 것이 무색하고 과제가 너무나도 밀리고 말았네요... 그래도 올려놓는 것은 해야 할 것 같아 PR 드립니다. 물론, 규정상 시간이 지나면 리뷰를 받을 수 없기에 해당 요청은 필수로 피드백을 보내시지 않아도 됩니다! 멘토 시간 때 스스로가 적극적이지 못했던 것 같아 많이 아쉽습니다. 짧은 2~3주간 수고 많으셨습니다! 감사합니다.

2024-01-16 06:09 UTC, goldfrosch requested changes
늦었지만 그래도 고생하셨습니다.
어찌보면 그냥 넘기고 해도 됬었을텐데 끝까지 포기하지 않았군요.

밑의 PR 확인 부탁드립니다~

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Header/Header.jsx
> +        console.log(error);
[중요도: 낮음] console.error(error)로 괜찮을 것 같네요.

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Header/Header.jsx
> +  const [user, setUser] = useState(null);
[중요도: 중간] 정확하게 user state에는 email 정보가 들어가는 것 같네요.
개인적으로 변수명은 userEmail이 조금 더 적합해 보입니다.

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Main/Card/Card.jsx
> +    <li className="card">
[중요도: 중간] li라는 태그는 ul이랑 같이 쓰는 태그입니다. 공통화 중 아마... ul, li 가 필요해 li부분만 빼서 컴포넌트화가 된 것 처럼 보이는데 이렇게 되면 추후 ul랑 같이 써야하는 경우가 생깁니다.

제가 할 때는 ul > li태그 안에 컴포넌트를 집어넣는 방식으로 진행했었는데 이 방식도 참고 부탁드립니다.

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Main/Card/Card.jsx
> +          <img src={imageSource || defalutimg} alt={title} />
```suggestion
          <img src={imageSource ?? defalutimg} alt={title} />
```
[중요도: 중간] 위 방식을 권장 드립니다.

?? 연산자: nullish를 검증 (null or undefined)
|| 연산자: falsy value도 검증한다.

당장에 있어서는 ||도 되지만 명시적인 관점에서는 ??가 맞는 표현이니까요~

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Main/Cardlist/Cardlist.jsx
> +  const [url, setUrl] = useState("");
[중요도: 높음] 이 두 state는 안쓰는 것 처럼 보입니다...? 확인 한번 부탁드려요

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Main/Cardlist/Cardlist.jsx
> +        setCard(data.folder.links);
[중요도: 높음] 이것도 어찌보면 이름이 명시적이지는 않네요... ;-;
card대신 links가 더 나아보입니다.

2024-01-16 06:09 UTC, goldfrosch commented on src/components/Main/Cardlist/Cardlist.jsx
> +        })}
```suggestion
        {card.map((data) => (
          <Card key={data.id} data={data} />
        ))}
```
[중요도: 중간] 굳이 return문이 필요해보이지는 않네요.
key를 data값의 id로 선정해 identify를 유지한 것 좋습니다!

2024-01-16 06:09 UTC, goldfrosch commented on src/utils/calculateDate.js
> +};
[중요도: 중간] 상수는 UPPER_SNAKE_CASE를 권장 드립니다. (개발자 사이의 국룰이에요)
[중요도: 중간] 모든 상수 값들을 TIME_IN_MILLISECONDS로 묶어서 쓰는 이유가 뭘까요?

2024-01-17 09:21 UTC, nyaknya commented on src/utils/calculateDate.js
> +};
감사합니다. 수정했습니다! 단순하게는 선언된 변수가 개수가 많아서 묶어서 사용하면 편하겠다 싶어서 묶었는데요, 이유가 이것뿐이라면 그냥 사용하는 것이 더 좋을까요...?

2024-01-17 09:24 UTC, nyaknya commented on src/components/Main/Cardlist/Cardlist.jsx
> +        })}
감사합니다!
return을 없앴더니 map에서 만들어지는 값이 없어 Card 컴포넌트가 생성되지 않아 어쩔수없이 붙였습니다.. 🥹 혹시 더 좋은 방법이 있을까요?

2024-01-18 00:04 UTC, goldfrosch commented on src/components/Main/Cardlist/Cardlist.jsx
> +        })}
음... 현재로써는 더 좋은 방법이 생각나지는 않는군요 ㅎㅎ

2024-01-18 00:06 UTC, goldfrosch commented on src/utils/calculateDate.js
> +};
흐음... 사람마다 조금 다르게 생각할 수는 있습니다.
저렇게 했을 때의 장점은 이름을 길게 쓰지 않고 depth를 줌으로써 이름 중복 방지도 해결할 수 있으니까요...
꼭 저렇게 쓰는게 나쁘다는 아니라는 점 알고 계시면 될 것 같습니다. 다만 SECOND, MINUTE등은 이름이 중복 생성될 만한 것도 아닌지라 이 경우는 풀어서 쓰는게 더 좋아보이네요~

2024-01-18 09:27 UTC, goldfrosch approved these changes
Approve and merge 진행하겠습니다!

2024-01-18 09:27 UTC, merged