[최유정] Week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #25
Opened 2023-12-02 14:50 UTC by yoojungChoii

셀프 채점
다음 항목들이 제대로 구현되었는지 확인해 보세요!

[기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
 [기본] Netlify에 파일 배포가 아닌 포크한 Github 레포지토리로 연결했나요?
 [랜딩 페이지] 아래로 스크롤 해도 “Linkbrary” 로고와 “로그인” 버튼이 있는 상단 네비게이션 바(Global Navigation Bar)영역이 최상단에 고정되게 했나요?
 [로그인 페이지, 회원가입 페이지 공통] Linkbrary 로고 클릭시 루트 페이지(“/”)로 이동하나요?
 [로그인 페이지, 회원가입 페이지 공통] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일한가요?
 [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus in 일 때, 테두리 색상이 파랑색인가요?
 [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus out 일 때, 테두리 색상이 회색인가요?
 [로그인 페이지, 회원가입 페이지 공통] SNS 아이콘들은 클릭시 각각 “[https://www.google.com/”](https://www.google.com/%E2%80%9D), “[https://www.kakaocorp.com/page/”](https://www.kakaocorp.com/page/%E2%80%9D) 으로 이동하나요?
 [로그인 페이지] “회원 가입하기”는 클릭시 “/signup” 페이지로 이동하나요?
 [회원가입 페이지] “로그인 하기”는 클릭시 “/signin” 페이지로 이동하나요?
심화
 [심화] palette에 있는 color값들을 css 변수로 등록하고 사용했나요?
 [심화] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가했나요?

## 주요 변경사항

- 로그인 페이지 구현
- 회원가입 페이지 구현

## 스크린샷

![스크린샷 2023-12-02 234734](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151714134/3ac5f014-8150-4a4f-880e-72cfacdbb4b6)
![스크린샷 2023-12-02 234805](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151714134/046bc281-266e-4199-91bc-25a7b89f327a)

## 멘토에게

- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-03 07:39 UTC, goldfrosch requested changes
고생하셨습니다. 순한맛으로 요청하셨군요

전체적인 PR 드립니다.

1. element 종속 style 반영
- 최대한 지양하는 것을 권장 드립니다. 기본 element에 스타일을 지정하고 사용하는 경우도 없는 것은 아닙니다. (저희도 전역 설정에 있다면 있어요) 다만 지양을 추천하는 이유는 정말 전역적으로 설정하는 것이 필요할 수도 있으나, 웬만해서는 전역으로 설정하는 것보다 그 페이지의 element, 혹은 특정 컴포넌트의 element에만 필요한 css가 들어갈겁니다. 웬만해서 다 쓰겠지~ 했다가 다른 동일한 element에 다른 스타일을 줘야할 경우 어려워 질 수 있으니 지양하는걸 권장 드립니다 :)

2. 폴더 사용
- 현 프로젝트가 모든 파일이 one depth폴더로 되어있습니다. 이런 경우 파일이 많아지면 찾기 어려워 질겁니다 ;-;. FE의 경우는 특히 디렉토리에 대해 더 민감합니다. 많은 파일이 나오고, 많은 종류의 파일이 나와 정리가 중요하니까요 :). img, css등 별도의 폴더에 저장하는 것을 권장드립니다.

추천 구조
ㄴ img/
    ㄴ img0.png
    ㄴ img0.png
    ㄴ img0.png
ㄴ css/
    ㄴ style0.css
    ㄴ style1.css
    ㄴ style2.css
이런식으로요!    

3. 이름에 숫자 지양
- 비지니스 요구사항에 순서 변경되면 까다로워 집니다 ;-;. 최대한 이름을 명시적으로 지정해 순서 변경 or 가독성이 좋게 대응해주는 것이 좋습니다

몇개 쓰다보니 매운맛이 아닌가... 걱정은 되는데, 그래도 열심히 하신 모습도 좋고...! 기한내에 잘 제출해주셨습니다 :) 고생 많으셨고 확인 부탁드립니다!

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/29947636/ae073dc7-7532-4209-a673-9bf237d931cd)

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/index.html
> +<html lang="en">
[중요도: 높음] lang="en"로 설정한다면 chrome에서 번역가능하다고 나올겁니다.
이유는 페이지 언어 설정이 영어로 되어있어서 그럴텐데요 ko로 변경 시 안나오게 될겁니다.

+ 한국페이지라 인지해 SEO에도 좋습니다.

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/index.html
> +          <span id="save">원하는 링크를</span><br>저장하세요
[중요도: 높음] 이미지에 alt 속성에 설명을 넣는 것은 웹 접근성 + SEO에 유리합니다. 바쁜 일정에 SEO까지 소화하려면 이 내용을 적는게 습관화 되어야합니다. 적어주십쇼 (꾸벅)

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +      <button type="submit">로그인</button>
👍

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/index-style.css
> +  max-width: 1920px;
[중요도: 중간]: max-width 1920은 어떤 이유로 적게되었을까요? 확인 한번 부탁드립니다...!

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/index.html
> +      <div class="sns">>
[중요도: 중간] div element 뒤에 >가 하나 더 붙어있네요 이건 텍스트 일까요?

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +      </div>
[중요도: 중간] label밖에 div element를 넣은게 몇개 보입니다. login이라는 div element안에 div를 넣고 거기에 label을 넣었던데 이렇게 넣은 이유가 있을까요? label바로 밖의 div element는 빼도 괜찮은 것 처럼 보입니다. (이유가 있다면 말해주세요 :))

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/index-style.css
> +  margin: 20px 200px 20px 200px;
[중요도: 낮음] 이런 경우 margin: 20px 200px 로 해도 됩니다! margin 속성에 2개만 적는 경우는 세로 margin, 가로 margin의 값이 반영되거든요

2023-12-03 07:39 UTC, goldfrosch commented on 최유정_Week1/index-style.css
> +  -webkit-text-fill-color: transparent;
[중요도: 높음] id 기반으로 css를 설정해준게 좀 보입니다. 이건 좀 수정이 필요하겠군요...
id를 사용하면 안되는 이유
- className보다 더 우선적으로 css가 반영된다. (같은 속성이 들어갔을 때 id를 제거하거나 수정해야하는데, Js에서 element의 id속성 기반으로 동작하는게 있을 경우 문제가 됩니다)

에 대한 설명글을 준비했으니 읽어보세요 :)
https://dev.to/clairecodes/reasons-not-to-use-ids-in-css-4ni4

2023-12-03 07:42 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +  <div class="logo">
[중요도: 높음] signin페이지와 signup페이지는 시멘틱 마크업이 반영이 안되어있네요? 여기는 반영하지 않은 이유가 혹시 있을까요?

2023-12-03 09:42 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +      <input id="email" name="email" placeholder="이메일을 입력하세요.">
[중요도: 높음] label의 의미가 조금 퇴색되게 사용되고 있는 것 같네요 ;-; 이것도 확인 한번 부탁드립니다.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#try_it

2023-12-03 09:44 UTC, goldfrosch requested changes
[추가 확인 필요]: link로 이동하는 부분이 이동되지 않습니다 ;-; 확인 한번 부탁드려요~

2023-12-03 09:44 UTC, goldfrosch commented on 최유정_Week1/index.html
> +          <a class= "button-login" href= "/signin">로그인</a>
[중요도: 높음] 로그인, 회원가입 페이지로 접근이 되지 않군요... 확인 부탁드립니다

2023-12-03 09:47 UTC, goldfrosch commented on 최유정_Week1/signup-style.css
> +  padding: 18px, 15px, 18px, 15px;
[중요도: 높음] padding 설정 시 중간에 , 넣으면 반영 안됩니다~ 확인해주세요~

2023-12-03 09:47 UTC, goldfrosch commented on 최유정_Week1/index-style.css
> +  padding: 32px, 104px, 64px, 104px;
[중요도: 높음] 여기도 정상적으로 반영되지는 않을 것 같네요... 확인 부탁드립니다~

2023-12-04 08:33 UTC, yoojungChoii commented on 최유정_Week1/index.html
> +<html lang="en">
수정했습니다!

2023-12-04 08:48 UTC, yoojungChoii commented on 최유정_Week1/index.html
> +          <span id="save">원하는 링크를</span><br>저장하세요
alt속성에 내용을 적어보았습니다.

2023-12-04 08:49 UTC, yoojungChoii commented on 최유정_Week1/signin.html
> +      <button type="submit">로그인</button>
감사합니다!!!!!

2023-12-04 08:49 UTC, yoojungChoii commented on 최유정_Week1/index-style.css
> +  max-width: 1920px;
너비가 1920 이상일 때 더 넓어지지 않게 하라고 해서 넣었습니다.... 상관 없는 코드인가요?

2023-12-04 08:50 UTC, yoojungChoii commented on 최유정_Week1/index.html
> +      <div class="sns">>
오타입니다. 수정했습니다!_

2023-12-04 08:51 UTC, yoojungChoii commented on 최유정_Week1/signin.html
> +      </div>
한번 더 감싸서 쓸 일이 있을까봐 감싸두었습니다. 쓸모 없지 않나 하는 생각을 했으나... 역시 이유가 없는 코드는 지우는게 좋네요! 감사합니다. 삭제했습니다.

2023-12-04 08:57 UTC, yoojungChoii commented on 최유정_Week1/index-style.css
> +  margin: 20px 200px 20px 200px;
비슷하게 적은 것들도 전부 수정했습니다!

2023-12-04 09:57 UTC, yoojungChoii commented on 최유정_Week1/index-style.css
> +  -webkit-text-fill-color: transparent;
이해했습니다! 수정했습니다. 감사합니다!!

2023-12-04 12:00 UTC, goldfrosch commented on 최유정_Week1/index-style.css
> +  max-width: 1920px;
아뇨 이건 요구사항을 제가 다 체크 못해서 여쭤봤었습니다. 확인했습니다 :)

2023-12-04 12:03 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +      </div>
네 쓸일을 예측하고 하는 것은 좋은 패턴입니다. (저도 css 짤 때 UI 대충 어떻게 바뀌겠다 생각하고 짤때도 있어요)
다만 그렇게 해야하는 경우는 이미 지정된 스타일 및 element안에서 처리하는게 좋습니다~ 이 경우는 불필요한 element가 들어가는 경우라 지양하는 것을 권장드립니다

2023-12-04 13:07 UTC, yoojungChoii commented on 최유정_Week1/signin.html
> +  <div class="logo">
메인 페이지에만 반영하면 된다고 생각했습니다..! 수정완료했습니다.

2023-12-04 13:16 UTC, yoojungChoii commented on 최유정_Week1/signin.html
> +      <input id="email" name="email" placeholder="이메일을 입력하세요.">
라벨의 의미가 퇴색되게 사용되는 것이 어떤 것인지 페이지를 확인해보고 구글링을 해봤는데도 이해가 잘 되지 않습니다..

2023-12-04 13:19 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +  <div class="logo">
아뇨 굳이 반영하지 않아도 괜찮습니다. 호옥시 이유가 있어서 여쭤봤는데.... 이미 수정했을 줄이야... 제 질문은 진짜 질문으로 먼저 받아들여주시면 됩니다 ㅎㅎ;

로그인, 회원가입의 경우 보통 색인에 포함시키지 않아 사실 할 필요까지는 없습니다. (일단 제가 일을 했을 때는 그랬습니다)
그래도 하면 좋죠!

2023-12-04 13:21 UTC, goldfrosch commented on 최유정_Week1/signin.html
> +      <input id="email" name="email" placeholder="이메일을 입력하세요.">
이 경우에는 제가 조금 잘못본 것 도 있네요 ;-;

잘못본 내용: for 속성을 제가 미처 보지 못했었습니다. 이 부분은 제가 심심한 사과 드립니다... ;-; 사용 방식은 맞네요
확인 내용: div를 불필요하게 감싼 것 처럼 보입니다. 이 부분 확인 부탁드립니다.

2023-12-04 13:25 UTC, yoojungChoii commented on 최유정_Week1/index.html
> +          <a class= "button-login" href= "/signin">로그인</a>
네 확인 후 수정했습니다! 감사합니다

2023-12-04 13:26 UTC, yoojungChoii commented on 최유정_Week1/signup-style.css
> +  padding: 18px, 15px, 18px, 15px;
헉 이런 확인 후 수정했습니다!!!

2023-12-04 13:27 UTC, yoojungChoii commented on 최유정_Week1/index-style.css
> +  padding: 32px, 104px, 64px, 104px;
수정했습니다! 자잘한 실수가 많네요. 다음엔 더 신경쓰겠습니다.

2023-12-04 13:34 UTC, yoojungChoii commented on 최유정_Week1/signin.html
> +      </div>
지정된 스타일 및 엘레멘트 안에서! 숙지하겠습니다. 감사합니다!!

2023-12-04 13:35 UTC, yoojungChoii commented on 최유정_Week1/signin.html
> +  <div class="logo">
앗 그렇군요. 다음부턴 굳이 할 필요 없더라도 해두겠습니다 :D

2023-12-05 14:33 UTC, goldfrosch approved these changes
다음주에도 화이팅합시다!

2023-12-17 13:28 UTC, merged