[고기호] Week13
codeit-bootcamp-frontend/3-Weekly-Mission pull request #277
Opened 2024-02-18 09:22 UTC by GihoKo

## 요구사항

### 기본

- [x] TypeScript를 활용해 프로젝트에 타입 명시가 필요한 곳을 찾아 타입을 명시했나요?
- [x] ‘/folder’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?
- [x] ‘/shared’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?
- [x] 다른 페이지로 이동이 필요한 곳에 next/link의 Link를 적용했나요?
- [] Input 컴포넌트에 값이 없는 경우 회색의 placeholder값을 볼 수 있나요?
- [] Input 컴포넌트에 focus in 하면 파랑색 테두리를 볼 수 있나요?
- [] Input 컴포넌트에 눈 모양 아이콘을 누르면 비밀번호 가리기/보기 기능이 토글 되나요?
- [] Input 컴포넌트에 값이 에러케이스일 경우 빨강색 테두리와 에러 메세지를 볼 수 있나요?
- [] Input 컴포넌트에서 focus out 하면 실행할 함수를 설정할 수 있나요?

## 주요 변경사항

- 리액트 프로젝트 타입스크립트 + NextJS로 마이그레이션
- img 태그 Image 컴포넌트로 변경
- folderPage, SharedPage 라우팅 방식을 React-route-dom에서 Page routing으로 변경
- 배포 사이트 netlify에서 vercel로 변경

## 스크린샷
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/5759e387-b8b1-4872-9f50-793be11ac94f)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/13389607-dcc1-4f33-9b63-6240cf0780f0)

## 멘토에게
- 타입 지정에 실패한 부분은 any로 일단 두었습니다.
- 타입 지정을 할 때 맨처음에는 그냥 반복작업으로 느껴졌는데 패칭해서 받아온 데이터에 타입을 주고 나니
예전처럼 스웨거 가서 api 확인하는 시간이 줄어들어서 점점 편리함이 와닿는 것 같습니다.
- 정적 생성이나 서버 사이드 렌더링도 넣어보고 싶었는데 시간이 없어서 일단은 오류가 안나는 선에서 마이그레이션을 진행했습니다.
- 12주차, 13주차 PR 리뷰 피드백은 다음주 수요일까지 한번에 반영하겠습니다.
- 요즘 날씨가 많이 오락가락해서 몸살났는데 멘토님도 감기 조심하세용...

2024-02-20 13:56 UTC, wonsss requested changes
기호님~! 수고 많으셨습니다. 
타입스크립트 전환과 Next.js 전환 모두 다 해내시다니 👏 👏 👏  멋지십니다!
리뷰 남겨드린 내용 확인해주시고 리뷰 반영 및 댓글 달아주시면, 내일 오후에 approve 및 merge 처리하겠습니다.

2024-02-20 13:56 UTC, wonsss commented on package.json
> +        "next": "^14.1.0",
<img width="611" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/b6576245-2911-4d22-964d-1a4b3f998d38">

위 스크린샷처럼 협업하는 다른 개발자 컴퓨터의 node.js version이 다른 경우가 많습니다. 다양한 프로젝트 코드를 왔다갔다 하다보면, 각 프로젝트별 필요 node.js version이 상이하기 때문이에요. 
따라서, 새로운 프로젝트에서 터미널을 열 때마다 해당 프로젝트에서 필요로 하는 노드 버전을 감지하여 해당 노드 버전으로 변경하는 과정이 자동화되면 좋을 것입니다.
이러한 기능이 구현되어 있는 것이 `nvm` (노드 버전 매니저) 입니다.
- 프로젝트의 루트 디렉터리 내에 `.nvmrc` 파일을 생성하고 `18.17.0` 같은 필요 노드 버전을 명시해주세요.
- 그리고 이러한 `.nvmrc`를 인지하여 자동으로 노드 버전 변경되려면, 컴퓨터에 nvm을 설치하고 세팅하셔야 합니다.  설치 방법은 공식 문서 참고해보세요. https://github.com/nvm-sh/nvm?tab=readme-ov-file#install--update-script  또는 구글링하시면 관련 포스팅도 쉽게 찾으실 수 있을 것입니다.

2024-02-20 13:56 UTC, wonsss commented on tsconfig.json
> +        "jsx": "preserve",
참고로 "jsx" 설정은 tsx 파일 내부의 JSX를 어떻게 처리할지 설정합니다. `preserve` 는 JSX를 변환하지 않고 JSX 코드를 그대로 두는 것인데, Next.js에서는 swc가 JSX 또한 변환해주므로 이 옵션을 사용하는 것입니다. 잘 적용해주셨네요 👍

2024-02-20 13:56 UTC, wonsss commented on tsconfig.json
> +        "jsx": "preserve",
그리고 `SWC`는 Rust 언어로 작성된 고성능 JavaScript/ TypeScript 컴파일러입니다. SWC는 Babel과 유사한 기능을 제공하지만, 더 빠르고 효율적인 컴파일을 제공해요.
한국 개발자가 개발했는데, vercel에서 흡수하여 nextjs에서 사용되고 있습니다. 
https://swc.rs/

2024-02-20 13:56 UTC, wonsss commented on tsconfig.json
> +        },
절대경로를 잘 적용하셨네요!

2024-02-20 13:56 UTC, wonsss commented on next.config.js
>  const nextConfig = {
next.config.js 설정에 complier 옵션에서 styledComponents를 true로 켜시면, swc가 styled-components를 사용하는 코드를 더 빨리 변환하게 됩니다.
```js
	compiler: {
		styledComponents: true, // styled-components를 사용하기 위한 설정
	},
```

2024-02-20 13:56 UTC, wonsss commented on next.config.js
>  const nextConfig = {
https://github.com/vercel/next.js/blob/v14.1.0/packages/next/src/server/config-shared.ts 또는 https://nextjs.org/docs/app/api-reference/next-config-js 에서 사용 가능한 nextjs 설정 옵션을 참고해보세요. 
옵션이 많아서 필요에 따라 적절한 옵션을 찾아서 적용하는 것이 필요합니다.

2024-02-20 13:56 UTC, wonsss commented on .babelrc
<img width="968" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/2945f33d-85cb-4315-95d9-8d70227fd9fe">
nextjs에서는 컴파일러로 swc를 사용할 수 있기 때문에, babel을 사용할 필요가 없습니다. 기존에 babel 설정이 되어 있을 때, 실행한 결과 nextjs에서도 위와 같은 안내를 해주고 있는 것을 확인하실 수 있습니다. swc를 사용하도록 해당 바벨 설정은 제거해도 될 것 같네요.
nextjs에서 swc를 사용하면 좋은 이유는 다음 자료 참고해보세요~!

[Why You Should Replace Babel with SWC in Next.js](https://blog.bitsrc.io/why-you-should-replace-babel-with-swc-in-next-js-7d47510d0e0d)

2024-02-20 13:56 UTC, wonsss commented on components/Contents/FolderCollection/FolderCollection.tsx
> +interface FolderCollectionProps {
타입스크립트 type과 interface의 공통점과 차이점에 대해 이해해보시면 좋습니다. 아래 글 한번 읽어보세요~!
https://yceffort.kr/2021/03/typescript-interface-vs-type

2024-02-20 13:56 UTC, wonsss commented on components/Contents/FolderCollection/FolderCollection.tsx
> +    folderData: FolderDataInterface[] | undefined;
undefined 타입은 이렇게 유니언 타입으로 해줄 필요 없이, 아래처럼 타입이름 뒤에 `?` 옵셔널연산자를 붙여주시면 됩니다.

```ts
    folderData?: FolderDataInterface[];
```

2024-02-20 13:56 UTC, wonsss commented on types/index.ts
> +export type NoArgsNoReturnFunction = () => void;
별도의 함수호출시그니처로 만들어서 재사용하시는 이유가 궁금합니다.
개인적인 취향으로는 이는 구체적이지 않은 타입이라 그냥 매번 써도 될 것 같아요.

2024-02-20 13:56 UTC, wonsss commented on hooks/Shared.hook.tsx
> +    }, []);
각 상태의 초기값을 넣어주려는 것 같은데, user와 folder 모두 url query parameter에서 parsing하여 가져오는 값이므로, useState의 initialState에 바로 전달해주셔도 됩니다. 따라서, 각 상태의 초기값을 넣어주려는 용도라면 해당 useEffect는 불필요할 것으로 보이네요.

2024-02-20 13:56 UTC, wonsss commented on hooks/Shared.hook.tsx
> +    const { user, folder } = router.query;
router.query에서 파싱한 값을 가져오려고 하면, 타입이 `string | string[] | undefined` 라고 알려줄거예요. 그런데 실제로 우리는 사용자가 입력하는 url에서 user와 folder 쿼리파라미터가 들어올 것이고 각각의 타입은`string`이라는 것을 예측할 수 있어요.  따라서 이 경우에는 타입단언 (`as`)을 사용하여 타입스크립트에게 우리는 query가 어떤 타입의 객체인지 알고 있다고 알려주면 좋아요. 
그 방법으로는 아래처럼 querystring에서 ParsedUrlQuery 타입을 가져와서 해당 타입을 확장(`extends`)하여 query의 타입을 만들고 타입 단언(`as`) 해주시는 거예요. 

```tsx
import { ParsedUrlQuery } from "querystring";

interface SharedPageUrlQuery extends ParsedUrlQuery {
	user: string;
	folder: string;
}

export const useGetSharedPageIds = () => {
	const router = useRouter();
	const { user, folder } = router.query as SharedPageUrlQuery;
```

querystring은 node에서 제공되는 라이브러리라서 별도로 설치하실 필요는 없어요. https://nodejs.org/api/querystring.html

2024-02-20 13:56 UTC, wonsss commented on hooks/Shared.hook.tsx
> +        useState<SharedFolderIdType>(null);
초기값이 null이 되는 것보다, 초기값을 알고 있다면 정확한 초기값을 넣어주는 것이 좋습니다.
또는 아직 모르고 예를 들어 해당 상태의 타입이 string이라면 동일한 타입인 빈 문자열 `""` 을 넣어주시는 게 더 적절할 것 같네요!

2024-02-20 13:56 UTC, wonsss commented on hooks/Shared.hook.tsx
> +            setSharedPageInfoError(err);
타입스크립트에서 catch 블록의 error는 unknown 타입입니다. 에러는 무엇이든 될 수 있기 때문이에요.
그런데 그렇다고 해서 해당 에러를 unknown 타입으로 반환하시면, 사용하는 곳에서 말그대로 타입이 명확하지 않아 사용이 어렵습니다.

따라서 아래의 getErrorMessage 유틸함수를 사용할 것을 제안드립니다.  적절히 타입이 좁혀지도록 타입 가드를 사용한 함수예요.
위에서 말씀드렸다시피 error로 어떤 타입의 무엇이 던져질지 미리 알기 어렵습니다. 
그래서 `if(error instanceof Error)` 와 같은 타입가드를 사용하여 error가 내장된 Error 생성자함수의 인스턴스 객체에 해당하는지 확인 후 error 객체의 속성인 message에 안전하게 접근할 수 있습니다. 그리고 이외의 경우에는 error를 Stringify 하여 반환할 수 있을 것 같습니다.

```typescript
export const getErrorMessage = (error: unknown): string => {
	if (error instanceof Error) {
		return error.message;
	}
	return String(error);
};
```
위 유틸함수를 사용하여 string으로 좁혀진 상태를 업데이트하시고
`setSharedPageInfoError(getErrorMessage(err));` 
상태 초기값을 빈 문자열이나 적절한 string 타입의 값으로 바꾸시면 됩니다.
`    const [sharedPageInfoError, setSharedPageInfoError] = useState("");`

2024-02-20 13:56 UTC, wonsss commented on utils/shareToKakao.ts
> +}
js로 된 라이브러리를 사용하는데 해당 라이브러리에 타입선언파일이 없다면, 이처럼 global window에서 Kakao에 any 타입을 선언하여, 임시로 사용할 수도 있습니다.
(참고 [TypeScript 카카오 맵 React에서 kakao SDK 사용하기](https://velog.io/@ahsy92/TypeScript-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A7%B5-React%EC%97%90%EC%84%9C-kakao-SDK-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0))

하지만 이는 타입 선언 파일이 없기 때문에 임시방편에 불과했고 정확한 타입스크립트 사용은 아닙니다.  

관련한 @types 파일을 검색해보니, 아래와 같이 definitely typed에 kakao-js-sdk 라는 타입선언파일 라이브러리가 올라와 있습니다. 이를 설치하여 사용하시면 됩니다.
https://www.npmjs.com/package/@types/kakao-js-sdk

그런데 해당 @types 라이브러리는 카카오에서 공식적으로 만든 것이 아니라, 오픈소스로서 관리되고 있는 것입니다. 
카카오에서 Kakao.Link 대신 Kakao.Share 를 새로 만들었습니다. ([카카오공지](https://devtalk.kakao.com/t/notice-name-changed-kakao-link-kakao-talk-sharing/123149) 참고)
아마 해당 @types 라이브러리가 카카오 업데이트를 못 따라간 걸 수 있어요.  
그래서 이전 버전인 Kakao.Link도 하위호환성을 위해 유지되어 있으니,  
[![image](https://private-user-images.githubusercontent.com/59413128/304768651-f4339915-7817-490b-b3c4-3e4ebbd13ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg2NTEtZjQzMzk5MTUtNzgxNy00OTBiLWIzYzQtM2U0ZWJiZDEzZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZmNjMTBhZjcxZmZhZTU0NjYzMWY5MjliNTRjODhlMWI3OGViOThkZmUyMTdkNTQxZjcxYjcxZjY2NDlhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmHCF5CgDx8p7EuyUQF_j-NfJYJ_3aT0UjoZ_Nv9Pmg)](https://private-user-images.githubusercontent.com/59413128/304768651-f4339915-7817-490b-b3c4-3e4ebbd13ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg2NTEtZjQzMzk5MTUtNzgxNy00OTBiLWIzYzQtM2U0ZWJiZDEzZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZmNjMTBhZjcxZmZhZTU0NjYzMWY5MjliNTRjODhlMWI3OGViOThkZmUyMTdkNTQxZjcxYjcxZjY2NDlhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmHCF5CgDx8p7EuyUQF_j-NfJYJ_3aT0UjoZ_Nv9Pmg)  
이렇게 사용하셔도 가능할 거예요.  
[![image](https://private-user-images.githubusercontent.com/59413128/304768757-b2e1360d-1ecb-495e-8be3-839be535898d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg3NTctYjJlMTM2MGQtMWVjYi00OTVlLThiZTMtODM5YmU1MzU4OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OWExMDJhNzk1NjYxNjYxNGFhYWFmOGI0Y2JmYjY1MjU1YjU0OGJmOTdjM2U5ZDgyNDkwYWVjN2MxNzNiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLnaMtliFFSRFgx_geHaJUVwbyuiCbwwE7HrPyHF68M)](https://private-user-images.githubusercontent.com/59413128/304768757-b2e1360d-1ecb-495e-8be3-839be535898d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg3NTctYjJlMTM2MGQtMWVjYi00OTVlLThiZTMtODM5YmU1MzU4OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OWExMDJhNzk1NjYxNjYxNGFhYWFmOGI0Y2JmYjY1MjU1YjU0OGJmOTdjM2U5ZDgyNDkwYWVjN2MxNzNiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLnaMtliFFSRFgx_geHaJUVwbyuiCbwwE7HrPyHF68M)

그러나 신규 버전을 사용하는 게 당연히 권장사항일테니, Kakao.Share를 쓰는 게 적절할 수 있습니다. 그렇다면, 저 types 라이브러리가 업데이트되길 기대하거나, 직접 타입선언을 해주거나, 지금처럼 그냥 any를 쓰거나 입니다. ㅎㅎ any를 쓴다면, 타입스크립트 도움을 받지 못하니 카카오 인터페이스를 잘못 사용하지 않도록 설명서를 잘 보셔야 할 거예요~!

2024-02-20 13:56 UTC, wonsss commented on utils/shareToKakao.ts
> +            console.log(window.Kakao);
제출한 PR이 머지된 후 사용자에게 배포된다고 간주한다면, 프로젝트 전반적으로 console.log는 모두 제거되어야 합니다. 지금은 실제 사용자는 없지만, 실전이라 생각하여 PR 제출 시 습관적으로 불필요한 주석이나 콘솔로그를 제거하시면 좋을 것 같아요.

콘솔로그가 그대로 있는 상태로 사용자에게 배포되면, 콘솔로그로 인해 성능에도 영향을 미치고 사용자에게 노출되어선 안되는 정보도 노출될 수 있어 주의하셔야 합니다.

또는 nextjs에서 제공하는 컴파일 시 모든 콘솔 제거하는 설정을 켜서 사용하시는 것도 좋습니다.
```
// next.config.js
	compiler: {
		removeConsole: true,
	},
```
https://nextjs.org/docs/architecture/nextjs-compiler

2024-02-20 13:56 UTC, wonsss commented on components/Contents/CardList/CardList.tsx
> +    cardListData: CardInterface[] | undefined;
```suggestion
    cardListData?: CardInterface[];
```

2024-02-20 13:56 UTC, wonsss commented on components/Contents/CardList/CardList.tsx
> +    if (cardListData === undefined) {
```suggestion
    if (!cardListData) {
```

2024-02-20 13:56 UTC, wonsss commented on components/Contents/CardSearchBar/CardSearchBar.tsx
> +    onInputChange: (e: ChangeEvent<HTMLInputElement>) => void;
DOM 요소 이벤트 넣는 게 귀찮은데 잘하셨네요!

2024-02-20 13:56 UTC, wonsss commented on hooks/Folder.hook.tsx
> +    const linkCreatorDom = useRef<HTMLDivElement>(null);
ref 타입 잘 주셨네요!

2024-02-21 06:06 UTC, GihoKo commented on hooks/Shared.hook.tsx
> +        useState<SharedFolderIdType>(null);
fb259cf1e15586a5230e94add42dc21c8c9365a3
수정했습니다!

2024-02-21 06:27 UTC, GihoKo commented on next.config.js
>  const nextConfig = {
303ac797231adb9afcdfc9dd4746ac9410b00048
수정했습니다.
옵션들 한번 읽어보면서 정리해보겠습니다!

2024-02-21 06:30 UTC, GihoKo commented on components/Contents/FolderCollection/FolderCollection.tsx
> +    folderData: FolderDataInterface[] | undefined;
a0bb00ab6e073f48a6ddf6e93e93e22d2bf41ef5
수정했습니다~

2024-02-21 06:32 UTC, GihoKo commented on types/index.ts
> +export type NoArgsNoReturnFunction = () => void;
마이그레이션할 때 좀 강박적으로 재사용을 해야겠다 생각하고 해서 만들었습니다.
생각해보니 그냥 () => void 가 더 짧아서 안쓰는게 낫겠네요 ㅠ

2024-02-21 06:36 UTC, GihoKo commented on types/index.ts
> +export type NoArgsNoReturnFunction = () => void;
3977c2c352ac05056b4c0875b0fcdec4a65b8284
수정했습니다~

2024-02-21 06:43 UTC, GihoKo commented on hooks/Shared.hook.tsx
> +    }, []);
a1a0161c37a1c54766e3b2a2e5844c00aef35c99
수정 완료했습니다~

2024-02-21 06:53 UTC, GihoKo commented on hooks/Shared.hook.tsx
> +            setSharedPageInfoError(err);
727d8bbc6f17fb38fa2233b095100e6be53c1610
26792c459df1c15d395324ddff79ff8b62b3d4c0
수정완료했습니다~

2024-02-21 06:56 UTC, GihoKo commented on utils/shareToKakao.ts
> +            console.log(window.Kakao);
779e8e6239290e6e8a98258ec6299eeee25d6ca1
수정 완료했습니다.

2024-02-21 07:15 UTC, GihoKo commented on components/Contents/CardList/CardList.tsx
> +    cardListData: CardInterface[] | undefined;
f5e7d4e6fb96f4417d9db5248ee92eefa0373807
수정했습니다~

2024-02-21 07:15 UTC, GihoKo commented on components/Contents/CardList/CardList.tsx
> +    if (cardListData === undefined) {
f5e7d4e6fb96f4417d9db5248ee92eefa0373807
수정했습니다~

2024-02-21 08:07 UTC, GihoKo commented on package.json
> +        "next": "^14.1.0",
1a3ca685d37b6763ddafb0e1522cf96af4ca078d
nvm 최신버전 설치하고 .nvmrc 파일을 추가해봤는데 잘 안되네요 ㅠ
이전에는 nvm install은 되고 nvm use는 안됐는데(윈도우에서는 안될 확률이 있다고 합니다)
이제는 nvm install도 안되네요 뭐가 문젠지 모르겠어요...

2024-02-21 08:09 UTC, GihoKo commented on package.json
> +        "next": "^14.1.0",
버전을 쓴 다음에 한 줄 더 개행해야한다해서 해봤는데도 안되네요..

2024-02-21 08:13 UTC, GihoKo commented on package.json
> +        "next": "^14.1.0",
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/22f1ee74-8e4f-4f57-91f5-a6d880ff4fea)
에러 상황입니다.

2024-02-21 08:24 UTC, GihoKo commented on hooks/Shared.hook.tsx
> +    const { user, folder } = router.query;
9e7966ab5ae10c846ec2c3e72e4658875a889bbb
수정 완료했습니다~

2024-02-21 08:56 UTC, GihoKo commented on .babelrc
5794e1b30a7c1778bc80ace5617d5422202a913b
수정 완료했습니다.

2024-02-21 09:24 UTC, GihoKo commented on .babelrc
5794e1b30a7c1778bc80ace5617d5422202a913b
수정했습니다!

2024-02-21 09:34 UTC, GihoKo commented on utils/shareToKakao.ts
> +}
3ad8feaab20639a9d9ceb688f3b3ea8a1c0955c5
이미지가 깨져서 안보이네요 ㅠ
@types 라이브러리를 설치했는데
이전에 타입선언한걸 주석처리해도 에러는 안뜨고 있습니다.

2024-02-21 13:29 UTC, wonsss commented on package.json
> +        "next": "^14.1.0",
아래와 같이 install과 use 뒤에 이 명령어가 요구하는 인자인 버전을 적어주셔야 할 것 같네요. 😄 
```
- nvm install 버전
    - 버전을 설치한다
- nvm use 버전
    - 버전을 사용한다
```

2024-02-21 13:29 UTC, wonsss commented on .babelrc
수고하셨습니다.

2024-02-21 13:30 UTC, wonsss commented on types/index.ts
> +export type NoArgsNoReturnFunction = () => void;
그렇게 고민 많이 해보시면 좋아요! 좋은 시도였다고 생각해요! 👍

2024-02-21 13:30 UTC, wonsss commented on hooks/Shared.hook.tsx
> +    }, []);
좋아요~

2024-02-21 13:31 UTC, wonsss commented on hooks/Shared.hook.tsx
> +    const { user, folder } = router.query;
잘 적용해주셨네요!

2024-02-21 13:31 UTC, wonsss commented on hooks/Shared.hook.tsx
> +        useState<SharedFolderIdType>(null);
좋습니다~

2024-02-21 13:32 UTC, wonsss commented on hooks/Shared.hook.tsx
> +            setSharedPageInfoError(err);
잘 수정하셨네요~! 뿌듯합니다

2024-02-21 13:32 UTC, wonsss commented on utils/shareToKakao.ts
> +}
넵! 좋습니다

2024-02-21 13:33 UTC, wonsss approved these changes

2024-02-21 13:33 UTC, merged