[김민교] Week13
codeit-bootcamp-frontend/3-Weekly-Mission pull request #289
Opened 2024-02-19 13:35 UTC by INKmin9

## 요구사항

### 기본

- [0]  [기본] ‘/folder’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?
- [0]  [기본] ‘/shared’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?
- [0]  [기본] 다른 페이지로 이동이 필요한 곳에 next/link의 Link를 적용했나요?
- [0]  [기본] Input 컴포넌트에 값이 없는 경우 회색의 placeholder값을 볼 수 있나요?
- [0]  [기본] Input 컴포넌트에 focus in 하면 파랑색 테두리를 볼 수 있나요?
- [0]  [기본] Input 컴포넌트에 눈 모양 아이콘을 누르면 비밀번호 가리기/보기 기능이 토글 되나요?
- [0]  [기본] Input 컴포넌트에 값이 에러케이스일 경우 빨강색 테두리와 에러 메세지를 볼 수 있나요?
- [0]  [기본] Input 컴포넌트에서 focus out 하면 실행할 함수를 설정할 수 있나요?

### 심화

- [x]
- []

## 주요 변경사항

-

## 스크린샷

![image](이미지url)

## 멘토에게

- 코드 빨간줄은 모두 수정했지만 실행 시 컴파일 에러가 뜨면서 404페이지가 뜨네요..ㅠ
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-02-20 14:51 UTC, wonsss requested changes
수고하셨습니다! 민교님 👏 👏 👏 
타입스크립트 전환과 Next.js 전환 모두 잘 해주셨네요!
타입에러가 나서 컴파일이 안되던 부분은 리뷰 남겨드린 내용 보시면서 하나씩 해결하시면, 금방 해결되실거예요.
그리고 PR 내용을 조금 더 상세히 작성해주시면 좋을 것 같아요. 이것도 습관이라서 지금부터 해당 개발의 컨텍스트가 없는 동료나 미래의 자신을 위해, PR 내용을 상세히 작성하면 도움이 많이 됩니다. 추가하면 좋을 PR 내용에는 '배경', '작업내용', '테스트 방법(로컬에서 실행하는 방법)', '배포된 주소 진입점', '동작 스크린샷' 등이 있습니다.

리뷰 남겨드린 내용 확인해주시고 리뷰 반영 및 댓글 달아주시면, 내일 오후에 approve 및 merge 처리하겠습니다.

2024-02-20 14:51 UTC, wonsss commented on pages/_app.tsx
> +}
파일 마지막 줄에 개행이 되어 있지 않으면, 이와 같이 빨간색 경고 표시가 뜹니다.
<img width="109" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/211ac697-1b7a-4bb5-b7b0-01fc8cc50435">
아래 글 참고하시어 EOL 을 넣을 수 있도록 처리해주시면 좋을 것 같아요.
[EOL을 넣어야 하는 이유와 운영체제별 EOL(EndOfLine) 차이로 인한 Git 문제 해결](https://velog.io/@jangws/EOL%EC%9D%84-%EB%84%A3%EC%96%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0%EC%99%80-git%EC%97%90%EC%84%9C-CRLF-EOL-%EC%B0%A8%EC%9D%B4%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95)

2024-02-20 14:51 UTC, wonsss commented on pages/folder.tsx
> +import { getFoldersById, getLinksById } from '../3-weekly-mission/pages/api/api';
<img width="571" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0aab2a77-12be-4ec6-bd60-9ab5a6e32549">

정확하지 않은 경로에서 import 하고 있어서 타입 에러가 나고 있네요. 
아래처럼 수정하시면 해결됩니다. 

```suggestion
import { getFoldersById, getLinksById } from './api/hello';
```

2024-02-20 14:51 UTC, wonsss commented on src/components/footer/Sns/Sns.tsx
> +import LinkLogo from '../LinkLogo/LinkLogo';
여기서도 타입에러가 납니다. 
그런데 LinkLogo 파일을 보니, 파일은 있는데 내용이 텅 비어있어요. 
코드가 유실된 것 같은데, LinkLogo 파일 작성해주시면 해결되어요!

2024-02-20 14:51 UTC, wonsss commented on src/components/section/FolderList/FolderList.tsx
> +import { getFoldersById } from '@/pages/api/api';
<img width="894" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0555faa9-38e7-495f-89dd-de67628a3742">
타입 에러 나네요. 이 부분 아래와 같이 수정하셔야 할 것 같아요
```suggestion
import { getFoldersById } from '@/pages/api/hello';
```

2024-02-20 14:51 UTC, wonsss commented on src/components/section/Card/Card.tsx
> +import { SharedLink } from '@/pages/shared';
프로젝트에 SharedLink 라는 코드 자체가 없어요. 이 부분도 유실된 것 같은데, 정의하면 해결될 거예요.

2024-02-20 14:51 UTC, wonsss commented on src/components/header/Folder/Folder.tsx
> +import { getFolder } from '@/pages/api/api';
경로 문제로 인한 타입 에러 해결 필요합니다~!
```suggestion
import { getFolder } from '@/pages/api/hello';
```

2024-02-20 14:51 UTC, wonsss commented on src/components/header/Nav/Nav.tsx
> +import { getUser, getUserById } from '@/pages/api/api';
경로 문제로 인한 타입 해결 필요합니다~!
```suggestion
import { getUser, getUserById } from '@/pages/api/hello';
```

2024-02-20 14:51 UTC, wonsss commented on pages/folder.tsx
> +import 'intersection-observer';
```suggestion
```
intersection-observer 라는 라이브러리를 설치가 되어 있지도 않고, 사용하지도 않고 계신데, 이러한 import문이 있는 것을 보니 import가 실수로 잘못되어 있는 것 같네요. 잘못 imort했으니 여기서도 타입에러가 납니다. 이 코드 제거하면 타입 에러 해결됩니다!

2024-02-20 14:51 UTC, wonsss commented on pages/folder.tsx
> +import 'intersection-observer';
지금까지 리뷰 단 타입에러들을 모두 해결하니, 민교님 프로젝트가 아래와 같이 타입에러 없이 컴파일이 잘 되어 렌더링되는 것을 확인할 수 있었어요 👍 
<img width="1294" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/7a1d0e07-8206-4c4a-92be-d19fbc6a5bd5">

2024-02-20 14:51 UTC, wonsss commented on src/components/section/Card/Card.tsx
> +  page: LinkType | SharedLink;
또는 SharedLink 타입을 여기서 빼버려도 될 것 같은데용?

2024-02-20 14:51 UTC, wonsss commented on package.json
next.config.js 파일이 changed code로 확인되지 않아서, 관련 코멘트 여기에 남깁니다~

next.config.js 설정에 complier 옵션에서 styledComponents를 true로 켜시면, swc가 styled-components를 사용하는 코드를 더 빨리 변환하게 됩니다.
```js
	compiler: {
		styledComponents: true, // styled-components를 사용하기 위한 설정
	},
```

https://github.com/vercel/next.js/blob/v14.1.0/packages/next/src/server/config-shared.ts 또는 https://nextjs.org/docs/app/api-reference/next-config-js 에서 사용 가능한 nextjs 설정 옵션을 참고해보세요. 
옵션이 많아서 필요에 따라 적절한 옵션을 찾아서 적용하는 것이 필요합니다.

2024-02-20 14:51 UTC, wonsss commented on src/components/header/Nav/Nav.tsx
> +  id?: number | undefined;
undefined 타입이 포함되어 있는 경우 이렇게 유니언 타입으로 해줄 필요 없이, 아래처럼 타입이름 뒤에 `?` 옵셔널연산자를 붙여주시면 됩니다. 이외에도 이와 같은 부분들 있으면 모두 수정해주시면 좋을 것 같아요.

```suggestion
    id?: number;
```

2024-02-20 14:51 UTC, wonsss commented on src/components/header/Nav/Nav.tsx
> +  setUserId?: (value: number) => void;
이 컴포넌트에서 setUserId가 props에 전달되지 않을 수도 있나요?
그렇다면 이와 같이 옵셔널연산자(`?`)를 붙여주셔도 되지만, 필요하지 않은 곳에 넣어주는 것은 지양해야 합니닷

2024-02-20 14:51 UTC, wonsss commented on src/components/header/Nav/Nav.tsx
> +      setUser(nextUser.data[0]);
if (condition) doSomething()과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다. 
만약 if문 중괄호가 없는데 아래와 같이 실수로 줄바꿈이 되었다면 에러가 발생합니다.
```js
if (errorResult.status === 409)
return true; 
```
이처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋기 때문에 한줄이라도 중괄호를 쓰는 코딩 스타일을 일관성있게 유지하시길 바랍니다. 😄 

추가적인 코딩스타일은 아래 문서 참고 바랍니다.
[코딩스타일](https://ko.javascript.info/coding-style)

2024-02-20 14:51 UTC, wonsss commented on src/components/header/Nav/Nav.tsx
> +    else applyGetUser();
위 코멘트 내용처럼 이렇게 중괄호 넣는 코딩스타일이 실수 방지에 좋습니다.
```suggestion
    if (id) {
       apllyGetUserById(id);
    } else { 
       applyGetUser();
    }
```

2024-02-20 14:51 UTC, wonsss commented on pages/folder.tsx
> +export interface LinkType {
참고로 타입스크립트 type과 interface의 공통점과 차이점에 대해 이해해보시면 좋습니다.
https://yceffort.kr/2021/03/typescript-interface-vs-type

2024-02-20 14:51 UTC, wonsss commented on pages/_app.tsx
>  }
js로 된 라이브러리를 사용하는데 해당 라이브러리에 타입선언파일이 없다면, 이처럼 global window에서 Kakao에 any 타입을 선언하여, 임시로 사용할 수도 있습니다.
(참고 [TypeScript 카카오 맵 React에서 kakao SDK 사용하기](https://velog.io/@ahsy92/TypeScript-%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A7%B5-React%EC%97%90%EC%84%9C-kakao-SDK-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0))

하지만 이는 타입 선언 파일이 없기 때문에 임시방편에 불과했고 정확한 타입스크립트 사용은 아닙니다.  

관련한 @types 파일을 검색해보니, 아래와 같이 definitely typed에 kakao-js-sdk 라는 타입선언파일 라이브러리가 올라와 있습니다. 이를 설치하여 사용하시면 됩니다.
https://www.npmjs.com/package/@types/kakao-js-sdk

그런데 해당 @types 라이브러리는 카카오에서 공식적으로 만든 것이 아니라, 오픈소스로서 관리되고 있는 것입니다. 
카카오에서 Kakao.Link 대신 Kakao.Share 를 새로 만들었습니다. ([카카오공지](https://devtalk.kakao.com/t/notice-name-changed-kakao-link-kakao-talk-sharing/123149) 참고)
아마 해당 @types 라이브러리가 카카오 업데이트를 못 따라간 걸 수 있어요.  
그래서 이전 버전인 Kakao.Link도 하위호환성을 위해 유지되어 있으니,  
[![image](https://private-user-images.githubusercontent.com/59413128/304768651-f4339915-7817-490b-b3c4-3e4ebbd13ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg2NTEtZjQzMzk5MTUtNzgxNy00OTBiLWIzYzQtM2U0ZWJiZDEzZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZmNjMTBhZjcxZmZhZTU0NjYzMWY5MjliNTRjODhlMWI3OGViOThkZmUyMTdkNTQxZjcxYjcxZjY2NDlhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmHCF5CgDx8p7EuyUQF_j-NfJYJ_3aT0UjoZ_Nv9Pmg)](https://private-user-images.githubusercontent.com/59413128/304768651-f4339915-7817-490b-b3c4-3e4ebbd13ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg2NTEtZjQzMzk5MTUtNzgxNy00OTBiLWIzYzQtM2U0ZWJiZDEzZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZmNjMTBhZjcxZmZhZTU0NjYzMWY5MjliNTRjODhlMWI3OGViOThkZmUyMTdkNTQxZjcxYjcxZjY2NDlhODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XmHCF5CgDx8p7EuyUQF_j-NfJYJ_3aT0UjoZ_Nv9Pmg)  
이렇게 사용하셔도 가능할 거예요.  
[![image](https://private-user-images.githubusercontent.com/59413128/304768757-b2e1360d-1ecb-495e-8be3-839be535898d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg3NTctYjJlMTM2MGQtMWVjYi00OTVlLThiZTMtODM5YmU1MzU4OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OWExMDJhNzk1NjYxNjYxNGFhYWFmOGI0Y2JmYjY1MjU1YjU0OGJmOTdjM2U5ZDgyNDkwYWVjN2MxNzNiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLnaMtliFFSRFgx_geHaJUVwbyuiCbwwE7HrPyHF68M)](https://private-user-images.githubusercontent.com/59413128/304768757-b2e1360d-1ecb-495e-8be3-839be535898d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzY1MzYsIm5iZiI6MTcwODQzNjIzNiwicGF0aCI6Ii81OTQxMzEyOC8zMDQ3Njg3NTctYjJlMTM2MGQtMWVjYi00OTVlLThiZTMtODM5YmU1MzU4OThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEzMzcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OWExMDJhNzk1NjYxNjYxNGFhYWFmOGI0Y2JmYjY1MjU1YjU0OGJmOTdjM2U5ZDgyNDkwYWVjN2MxNzNiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XLnaMtliFFSRFgx_geHaJUVwbyuiCbwwE7HrPyHF68M)

그러나 신규 버전을 사용하는 게 당연히 권장사항일테니, Kakao.Share를 쓰는 게 적절할 수 있습니다. 그렇다면, 저 types 라이브러리가 업데이트되길 기대하거나, 직접 타입선언을 해주거나, 지금처럼 그냥 any를 쓰거나 입니다. ㅎㅎ any를 쓴다면, 타입스크립트 도움을 받지 못하니 카카오 인터페이스를 잘못 사용하지 않도록 설명서를 잘 보셔야 할 거예요~!

2024-02-20 14:51 UTC, wonsss commented on pages/folder.tsx
> +  const observer = useRef<IntersectionObserver>();
DOM element 의 타입을 ref에 잘 적용해주셨네요 👍

2024-02-20 14:51 UTC, wonsss commented on pages/folder.tsx
> +                })
이러한 비즈니스 로직은 UI를 담당하는 jsx 쪽에 포함시켜 작성하기보다는 jsx 위에서 변수나 함수로 따로 분리하여 두는 것이 가독성 및 나중에 유지보수에 유리할 것 같네요

2024-02-20 14:51 UTC, wonsss commented on src/components/section/BaseModal/BaseModal.tsx
> +export default function BaseModal({ closeModal, children }: Props) {
컴포넌트 props에 children이 있는 경우는 더 간단히 PropsWithChildren 유틸타입을 사용하셔도 됩니다.
```suggestion
interface Props {
  closeModal: () => void;
}

export default function BaseModal({ closeModal, children }: PropsWithChildren<Props>) {
```

2024-02-20 14:51 UTC, wonsss commented on package.json
>    }
scripts에 type-check하는 스크립트 추가하시고, 개발하시면서 타입에러 나는지 체크하시려면 해당 스크립트를 실행해서 터미널을 확인하면서 개발해보세요.
```
	"scripts": {
		"type-check": "tsc --noEmit --watch --skipLibCheck"
	},
```

2024-02-21 13:34 UTC, wonsss approved these changes
리뷰 반영은 다음주차 미션에서 이어서 부탁드려요!
수고 많으셨습니다. 다음 미션도 화이팅 👍

2024-02-21 13:34 UTC, merged

2024-02-22 08:00 UTC, INKmin9 commented on pages/folder.tsx
> +import 'intersection-observer';
와 정말이네요..! 뤼튼이나 구글 검색을 하다 보니 필요없는 부분들이 들어가는 것 같습니다. 참고 코드를 보고 코딩할땐 한번 더 생각하고 할 필요가 있겠네요ㅠㅜ

2024-02-22 08:06 UTC, INKmin9 commented on src/components/header/Nav/Nav.tsx
> +  setUserId?: (value: number) => void;
아직 어떤 부분이 명확히 전달되는지 파악이 힘들었던 것 같습니다..! 이것도 한번 더 생각해보고 작성해야겠군요

2024-02-22 08:08 UTC, INKmin9 commented on src/components/header/Nav/Nav.tsx
> +      setUser(nextUser.data[0]);
헉 알겠습니다..! 이번처럼 코드가 제가 모르는 사이에 소실되거나 수정된다면 큰일이겠군요