Part3 조형민 week13
codeit-bootcamp-frontend/3-Weekly-Mission pull request #290
Opened 2024-02-19 22:12 UTC by Vegatality

## 요구사항

### 기본

- [x] [기본] ‘/folder’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?

- [x] [기본] ‘/shared’ 페이지를 Next.js 프로젝트에 맞게 변경 및 이전 했나요?

- [x] [기본] 다른 페이지로 이동이 필요한 곳에 next/link의 Link를 적용했나요?

- [x] [기본] Input 컴포넌트에 값이 없는 경우 회색의 placeholder값을 볼 수 있나요?

- [x] [기본] Input 컴포넌트에 focus in 하면 파랑색 테두리를 볼 수 있나요?

- [x] [기본] Input 컴포넌트에 눈 모양 아이콘을 누르면 비밀번호 가리기/보기 기능이 토글 되나요?

- [x] [기본] Input 컴포넌트에 값이 에러케이스일 경우 빨강색 테두리와 에러 메세지를 볼 수 있나요?

- [x] [기본] Input 컴포넌트에서 focus out 하면 실행할 함수를 설정할 수 있나요?

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-02-20 18:32 UTC, wonsss requested changes
형민님 수고 많으셨습니다. 
고민을 많이 하신 부분들이 잘 느껴졌어요! 👏 👏 👏 
고민하신 만큼 타입스크립트나 Next.js에도 많이 익숙해지시고 잘 활용하시게 된 것 같으시네요!
리뷰 남겨드린 내용 참고하시어 반영 및 해당 리뷰에 댓글 남겨주시면 학습에 도움이 되실 것 같습니다.  👍

2024-02-20 18:32 UTC, wonsss commented on pages/_document.page.tsx
> +        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
Next.js에서는 뷰포트 메타 태그를 `_document` 파일이 아닌 `_app` 파일 내에 둘 것을 권장합니다.  따라서 해당 뷰포트 메타 태그 위치를 변경할 것을 제안드려요.
관련 상세 내용 확인을 위해 공식 문서 링크를 남겨둡니다.
https://nextjs.org/docs/messages/no-document-viewport-meta

2024-02-20 18:32 UTC, wonsss commented on assets/magnifier.svg
assets 폴더 내 넣어두신 svg를 사용하고 계신가요? 사용하지 않는다면 제거해도 될 것 같습니다.
혹시나 사용한다면, public 폴더로 이동시켜도 좋을 것 같네요.

2024-02-20 18:32 UTC, wonsss commented on style/font.css
> +/* @import url('/custom-font/pretendard/pretendard.css'); */ /* ? 절대 경로 왜 못찾지? */
일반적으로 CSS 파일에서는 직접적으로 절대 경로를 사용하는 것은 불가능합니다. CSS 파일 내에서는 JavaScript나 TypeScript와 같이 모듈 시스템이 없기 때문에 절대 경로를 해석할 수 있는 방법이 없습니다.

2024-02-20 18:32 UTC, wonsss commented on @types/styled-components.d.ts
> +}
React 모듈 타입 확장하셨네요. 
위의 코드에서는 모든 React 컴포넌트에 css 속성을 추가할 수 있도록 하는 것으로 보입니다. 이렇게 커스터마이징하시는 이유가 궁금합니다.

2024-02-20 18:32 UTC, wonsss commented on components/ui/molecules/bar/search-bar/common-search-bar/CommonSearchBar.tsx
> +              `}
JSX 컴포넌트에 인라인 방식으로 스타일을 설정하고 싶으시다면, CSS를 Object 형식으로 만들어서 직접 태그에 넣는 방식의 인라인 스타일 방식도 사용 가능합니다. 

<img width="1060" alt="스크린샷 2024-02-21 오전 1 44 44" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/5baa689d-6dca-476c-bf46-a34827988348">

2024-02-20 18:32 UTC, wonsss commented on pages/folder/comp/article/comp/search-bar/SearchBar.tsx
> +      `}
그리고 아마 jsx 컴포넌트에 css 속성을 이와 같이 그냥 주셨다면, 타입에러가 났을 겁니다. 그래서 @types/styled-components.d.ts 파일에서 css prop에 대한 타입 선언을 추가해주신 것 같구요. 
그런데 이보다는 공식문서에서 css prop 타입에러를 해결하기 위해 제안하는 방법은 `@types/styled-components` 라이브러리에서 다음과 같이 cssprop에 대해 import를 하는 것입니다. 공식문서를 따르는 것이 더 나을 것 같습니다.

```
import {} from 'styled-components/cssprop'
```
<img width="1072" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/744d3864-3c24-4bff-8ef3-c7f780624429">

참고: https://styled-components.com/docs/api#usage-with-typescript

2024-02-20 18:32 UTC, wonsss commented on pages/shared/comp/article/comp/search-bar/SearchBar.tsx
> +      <LinkSearchBar clearInput={clearInput} input={input} onChange={onChange} />
div 태그에 인라인으로 css 를 설정하셨는데, div도 다른 컴포넌트처럼 스타일드컴포넌트로 만들어 스타일을 지정해주시는 것은 어떠실까요?
일관성 및 가독성을 위해 저라면 그렇게 할 것 같습니다.

2024-02-20 18:32 UTC, wonsss commented on components/ui/molecules/bar/search-bar/common-search-bar/CommonSearchBar.tsx
> +          <StSearchBarCancelBtn type='reset' onClick={clearInput}>
참고로 jsx 조건부 렌더링에서 && 연산자 대신 삼항조건연산자를 사용하는 것이 버그 방지를 위해 좋은 방법이라고 합니다

관련 내용은 다음 글에 상세히 설명되어 있으니 참고 바랍니다.
https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

이 경우에 input이 string만 받도록 되어 있지만, 만약 numpad 같은 거라서 number 타입을 받을 수 있다면 어떨까요?
숫자 0이 input으로 입력되었을 때, 기대하는 것은 리셋버튼이 표시되는 것이겠지만, 실제로는 해당 자리에 숫자 0이 표시되는 버그가 발생하게 됩니다. 
물론, 이 경우는 string 타입만을 받도록 해두었으니 그런 문제가 없을 수 있지만, 저는 혹시나 모를 버그를 방지하기 위해 조건부렌더링 시에는 `&&` 대신 삼항조건연산자를 사용하는 것도 좋은 선택일 수 있다고 생각합니다.

2024-02-20 18:32 UTC, wonsss commented on components/ui/molecules/card/link-card/Description.tsx
> +type TDescriptionProps = {
type의 이름에 접두사 T를 붙인다거나 interface의 이름에 접두사 I를 붙이는 방식은 헝가리안 표기법이라고 부릅니다.

타입스크립트 개발팀은 이러한 헝가리안 표기법을 지양할 것을 권장하고 있습니다. 

이를 참고하시어, `T`나 `I` 같은 접두사를 타입 이름에 붙이지 마시고, 타입을 설명하는 적절한 이름을 붙이실 것을 제안드립니다.

2024-02-20 18:32 UTC, wonsss commented on components/ui/molecules/card/link-card/Description.tsx
> +const Description = ({ children, ...rest }: TDescriptionProps) => {
children이 있는 컴포넌트의 props 타입을 선언하실 때, `  children: React.ReactNode;` 대신
다음과 같이 PropsWithChildren 라는 리액트의 유틸리티 타입에 제네릭을 넣어서 사용하는 것으로 대체하실 수도 있습니다.
```ts
const Description = ({...rest}: PropsWithChildren<TDescriptionProps>) => {
```

2024-02-20 18:32 UTC, wonsss commented on components/ui/atoms/button/modal-btn/ModalCloseBtn.tsx
> +})`
스타일드 컴포넌트에서 요소 속성을 지정해주는 `attrs`라는 방법도 있군요.  여러 가지 찾아보시고 시도하시는 모습이 멋집니다. 👍 

저라면 요소의 기능적인 속성은 인라인에 두고, 스타일드컴포넌트에서는 기능적인 속성을 이처럼 두기보단 스타일만 지정하는 것에 초점을 둘 것 같습니다. 기준을 잡고 일관성 있게 코드를 작성하는 것이 가독성 및 유지보수에 좋은 클린코드를 지향하는 방향일 것 같아요.

물론, 이렇게 하더라도 컨벤션을 정하시고 의도를 갖고 일관성 있게 하신다면, 그것도 클린 코드일 수도 있습니다. 사람마다 견해는 다를 수 있으니까요. 😄

2024-02-20 18:32 UTC, wonsss commented on components/ui/atoms/input/common-input/CommonInput.tsx
> +  srcOnTextType?: ImgHTMLAttributes<HTMLImageElement>['src'];
타입스크립트에 대한 이해도가 많이 높아지신 것 같아요 👍

2024-02-20 18:32 UTC, wonsss commented on components/ui/atoms/input/common-input/CommonInput.tsx
> +      {initialType === 'password' && (
여기서 initialType이 아니라 inputType이 조건문에 들어가야 하는 것 아닌가요?
initialType은 상태 초기값으로만 사용하시려고 한 것 같아서요.

2024-02-20 18:32 UTC, wonsss commented on components/ui/atoms/select-menu/context/SelectMenuProvider.tsx
> +const SelectMenuProvider = ({ children, modalRef }: TSelectMenuProviderProps) => {
context api를 잘 사용하셨고, 이에 대한 타이핑도 잘 해주셨네요

2024-02-20 18:32 UTC, wonsss commented on package.json
> +    "next": "13.5.6",
<img width="611" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/b6576245-2911-4d22-964d-1a4b3f998d38">

위 스크린샷처럼 협업하는 다른 개발자 컴퓨터의 node.js version이 다른 경우가 많습니다. 다양한 프로젝트 코드를 왔다갔다 하다보면, 각 프로젝트별 필요 node.js version이 상이하기 때문이에요. 
따라서, 새로운 프로젝트에서 터미널을 열 때마다 해당 프로젝트에서 필요로 하는 노드 버전을 감지하여 해당 노드 버전으로 변경하는 과정이 자동화되면 좋을 것입니다.
이러한 기능이 구현되어 있는 것이 `nvm` (노드 버전 매니저) 입니다.
- 프로젝트의 루트 디렉터리 내에 `.nvmrc` 파일을 생성하고 `18.17.0` 같은 필요 노드 버전을 명시해주세요.
- 그리고 이러한 `.nvmrc`를 인지하여 자동으로 노드 버전 변경되려면, 컴퓨터에 nvm을 설치하고 세팅하셔야 합니다.  설치 방법은 공식 문서 참고해보세요. https://github.com/nvm-sh/nvm?tab=readme-ov-file#install--update-script  또는 구글링하시면 관련 포스팅도 쉽게 찾으실 수 있을 것입니다.

2024-02-20 18:32 UTC, wonsss commented on @types/kakao.d.ts
> +}
라이브러리에 대한 타입선언을 잘 확장해주셨네요 👍 
설치하신 카카오 라이브러리에 대한 @types/kakao-js-sdk 가 Kakao.Share 에 대한 타이핑까지는 지원하지 않고 있습니다. 
이런 경우 형민님께서 해주신 것처럼, 타입을 확장해주시면 좋습니다.

2024-02-20 18:32 UTC, wonsss commented on @types/environment.d.ts
> +}
사용하시는 환경변수에 대한 타입선언을 NodeJS의 ProcessEnv 에 확장하여 해주셨군요. 해당 환경변수가 ProcessEnv 객체에서 존재한다고 타입스크립트는 알게 되고,  undefined가 아닌 항상 string 타입으로 올 것이라고 알게 되어 더 편하게 사용할 수 있겠네요.  좋습니다. 👍

2024-02-20 18:32 UTC, wonsss commented on components/provider/modal/Modal.tsx
> +    typeof callback === 'function' && callback();
이처럼 And 연산자로 함수를 조건부로 호출하는 것보다는, 명시적으로 if 조건문을 사용하는 것이 더 나은 코딩스타일이라고 생각합니다.

이것은 견해 차이가 있을 수 있어요. 회사마다 컨벤션도 조금씩 다르고 사람마다 생각도 다르니까요.

제 의견은 파이선의 말을 빌려서 하고 싶습니다. https://wikidocs.net/7907
파이선의 선은 좋은 코드가 무엇인지 고민해볼 수 있는 경구 같은 건데요.
그 중에 "명확성이 함축된 것보다 낫다", "복잡함이 난해한 것보다 낫다", "가독성은 중요하다" 등의 원칙을 생각한다면, 굳이 명시적인 if 조건문 대신에 And 연산자의 평가를 통해 함수를 조건부로 호출해야 하는 것인지는 고민해볼 필요가 있을 것 같아요.

<img width="772" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/10cc0370-f0dd-4f4d-ac4d-c558258e8116">

2024-02-20 18:32 UTC, wonsss commented on components/provider/modal/ModalContext.ts
> +  if (dispatcher === undefined) throw new Error('useModalDispatch should be within ModalProvider');
if (condition) doSomething()과 같은 단 한 줄짜리 구문에서 중괄호를 생략할 수도 있습니다.
하지만, 추천드리는 코딩 스타일은 이런 경우에도 중괄호를 `명시적`으로 포함하는 것입니다. 
만약 if문 중괄호가 없는데 아래와 같이 실수로 줄바꿈이 되었다면 에러가 발생합니다.
```js
if (errorResult.status === 409)
return true; 
```
이처럼 코드 블록을 사용하는 방법이 가장 가독성이 좋기 때문에 한줄이라도 중괄호를 쓰는 코딩 스타일을 일관성있게 유지하시길 바랍니다. 😄 

추가적인 코딩스타일은 아래 문서 참고 바랍니다.
[코딩스타일](https://ko.javascript.info/coding-style)

2024-02-21 11:38 UTC, Vegatality commented on pages/folder/comp/article/comp/search-bar/SearchBar.tsx
> +      `}
음, 일단 제가 한 방식도 공식에서 권장하는 방식임을 알려드립니다.
이는 styled-components에서 제공하는 타입에 마우스를 호버해보면 바로 확인할 수 있는데요.

<img width="577" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/123563774/ef4ab1e6-45cd-4d9c-8b9b-541f96e1f73b">

Next.js같은 경우에는 `babel-plugin-styled-components`를 포팅해서 Next.js Compiler인 swr에서 처리하도록 해놓았습니다. 기본적으로 옵션을 키면 사용할 수 있는 것이죠.

Next.js가 아닌 경우 babel plugin을 설치하고, css prop을 inline에서 사용할 수 있었습니다.
그러나 이전 프로젝트에서는 `import type {} from 'styled-components/cssprop';`만으로는 css를 jsx element 요소에 자동으로 추천해주지 않는 문제가 있었습니다. 해당 이슈는  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245#issuecomment-484505773 에서도 찾아볼 수 있었습니다. `d.ts`라는 키워드로 검색해보면 이런 이슈를 겪는 사람이 많은 것을 알 수 있죠. 이를 해결하기 위해 찾아보니 위와 같은 방식이 있었고 해결이 되었습니다.

참고로 최신 방식에서는 `import {} from 'styled-components/cssprop'가 아니라 import type {} from 'styled-components/cssprop'으로 해야 제대로 추론이 이루어집니다.

2024-02-21 12:23 UTC, Vegatality commented on components/ui/molecules/bar/search-bar/common-search-bar/CommonSearchBar.tsx
> +          <StSearchBarCancelBtn type='reset' onClick={clearInput}>
글 흥미롭게 잘 읽었습니다.
이전에 알고 있었던 내용이라서 에러는 범한 적이 없지만, 미래에 일어날 에러를 방지할 수 있는 시야를 터득했습니다.
글에서 Boolean이나 !!연산자를 통해 해결하는 방법도 나오는데 저 역시 글의 저자와 마찬가지로 삼항 연산자가 논리합 연산자나 논리곱 연산자를 남용하는 측면보다는 더 낫다고 생각이 드네요.

2024-02-21 12:24 UTC, Vegatality commented on components/ui/molecules/bar/search-bar/common-search-bar/CommonSearchBar.tsx
> +          <StSearchBarCancelBtn type='reset' onClick={clearInput}>
글 흥미롭게 잘 읽었습니다.
이전에 알고 있었던 내용이라서 에러는 범한 적이 없지만, 미래에 일어날 에러를 방지할 수 있는 시야를 터득했습니다. 글에서 Boolean이나 !!연산자를 통해 해결하는 방법도 나오는데 저 역시 글의 저자와 마찬가지로 JSX 작성하는 곳에서 삼항 연산자가 논리합 연산자나 논리곱 연산자를 남용하는 측면보다는 더 분명해서 낫다고 생각이 드네요.
물론 중첩된 삼항 연산자는 피해야겠지요.

2024-02-21 12:26 UTC, Vegatality commented on components/ui/molecules/card/link-card/Description.tsx
> +type TDescriptionProps = {
다음번부터는 해당 표기법을 사용하지 않겠습니다.

2024-02-21 12:34 UTC, Vegatality commented on components/ui/molecules/bar/search-bar/common-search-bar/CommonSearchBar.tsx
> +              `}
인라인 스타일로 작성할 경우 우선순위가 높아져 버리고, 컴포넌트 리렌더링 때마다 매 번 스타일이 새롭게 생성된다고 알고 있습니다. 이 때문에 동적 스타일링이 아닌 이상 최대한 지양하고 있었습니다.

그래서 css prop을 사용했던 것인데 css 프롭도 결국에는 객체로서 할당이 되기 때문에 매번 새롭게 스타일이 생성된다고 합니다. 이에 대한 해결법은 css 를 컴포넌트 바깥으로 분리해서 불러오는 것이라고 합니다.

그래서 제가 내린 결정은 앞으로 스타일링은 동적 스타일을 할 때만 style 태그를 사용하고, 이외의 경우에는 className으로 하거나 컴포넌트 바깥에서 불러오려고 합니다.

[참고한 글 - styled components가 아니라 emotion이긴 합니다. ](https://velog.io/@parksil0/Emotion%EC%9D%98-css-Prop%EC%9D%84-%ED%9A%A8%EA%B3%BC%EC%A0%81%EC%9C%BC%EB%A1%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

2024-02-21 12:43 UTC, Vegatality commented on components/ui/atoms/input/common-input/CommonInput.tsx
> +      {initialType === 'password' && (
그렇지 않습니다.
`inputType`이 조건문으로 오면, type이 'text'로 변경됐을 때는 비밀번호 눈 아이콘이 아예 사라져버립니다.
미션에서 요구하는 사항은 눈을 없애는 것이 아니라 감은 눈, 뜬 눈을 보여주는 것이었습니다.
그래서 초깃값으로 고정된 값인 `initialType`을 사용해야 하는 것이 맞습니다. `initialType`이 passord가 아닌 이외의 경우에는 눈 아이콘을 아예 렌더링 하지 않기 위함입니다.
initialType이 password일 때만 우측의 `StInputIcon`이 렌더링 되는 것이고, src 삼항 연산자도 유효해지는 것이죠.

2024-02-21 12:44 UTC, Vegatality commented on components/provider/modal/Modal.tsx
> +    typeof callback === 'function' && callback();
참고하도록 하겠습니다.

2024-02-21 12:47 UTC, Vegatality commented on components/provider/modal/ModalContext.ts
> +  if (dispatcher === undefined) throw new Error('useModalDispatch should be within ModalProvider');
감사합니다. 코드가 짧다면 한 줄에 쓰고 있었는데, 에러 방지 측면에서는 중괄호를 명시적으로 적어주는 방식이 좋겠군요.

2024-02-21 13:17 UTC, wonsss commented on pages/folder/comp/article/comp/search-bar/SearchBar.tsx
> +      `}
그렇군요! 상세한 설명해주셔서 감사합니다 👍

2024-02-21 13:19 UTC, wonsss commented on components/ui/molecules/bar/search-bar/common-search-bar/CommonSearchBar.tsx
> +          <StSearchBarCancelBtn type='reset' onClick={clearInput}>
공감합니다 👍

2024-02-21 13:20 UTC, wonsss commented on components/ui/atoms/input/common-input/CommonInput.tsx
> +      {initialType === 'password' && (
그렇군요! 설명 감사합니다

2024-02-21 13:21 UTC, wonsss approved these changes

2024-02-21 13:21 UTC, merged