[고기호] week14
codeit-bootcamp-frontend/3-Weekly-Mission pull request #303
Opened 2024-02-24 11:32 UTC by GihoKo

## 요구사항

### 기본

- [x] [로그인 페이지] “회원 가입하기”를 클릭하면 ‘/signup’ 페이지로 이동하나요?
- [x] [로그인 페이지] 이메일 input에 placeholder는 “이메일을 입력해 주세요.”, 비밀번호 input에 placeholder는 “비밀번호를 입력해 주세요.”가 보이나요?
- [x] [로그인 페이지] 이메일 input에서 focus out 할 때, 값이 없을 경우 아래에 “이메일을 입력해주세요.” 에러 메세지가 보이나요?
- [x] [로그인 페이지] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 아래에 “올바른 이메일 주소가 아닙니다.” 에러 메세지가 보이나요?
- [x] [로그인 페이지] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?
- [x] [로그인 페이지] 로그인 실패하는 경우, 이메일 input 아래에 “이메일을 확인해주세요.”, 비밀번호 input 아래에 “비밀번호를 확인해주세요.” 에러 메세지가 보이나요?
- [x] [로그인 페이지] 로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행 되나요?
- [x] [로그인 페이지] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받으면 “/folder”로 이동하나요?
- [x] [회원가입 페이지] “회원 가입하기”를 클릭하면 ‘/signin’ 페이지로 이동하나요?
- [x] [회원가입 페이지] 이메일 input에 placeholder는 “이메일을 입력해 주세요.”, 비밀번호 input에 placeholder는 “영문, 숫자를 조합해 8자 이상 입력해 주세요. ”비밀번호 확인 input에 placeholder는 “비밀번호와 일치하는 값을 입력해 주세요.”가 보이나요?
- [x] [회원가입 페이지] 이메일 input에서 focus out 할 때, 값이 없을 경우 “이메일을 입력해주세요.” 에러 메세지가 보이나요?
- [x] [회원가입 페이지] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 “올바른 이메일 주소가 아닙니다.” 에러 메세지가 보이나요?
- [x] [회원가입 페이지] 비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 에러 메세지가 보이나요?
- [x] [회원가입 페이지] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input 아래에 “비밀번호가 일치하지 않아요.” 에러 메세지가 보이나요?
- [x] [회원가입 페이지] 회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 에러 메세지가 보이나요?
- [x] [회원가입 페이지] 회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 실행 되나요?
- [x] [회원가입 페이지] 이메일 중복 확인은 “/api/check-email” POST 요청해서 확인 할 수 있나요?
- [x] [회원가입 페이지] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요?
- [x] [로그인, 회원가입 페이지 공통] 눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지나요?
- [x] [로그인, 회원가입 페이지 공통] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?
- [x] [로그인, 회원가입 페이지 공통] 소셜 로그인에 구글 아이콘 클릭시 ‘https://www.google.com’, 카카오 아이콘 클릭시 ‘https://www.kakaocorp.com/page’로 이동하나요?
- [x] [로그인, 회원가입 페이지 공통] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장하나요?
- [x] [로그인, 회원가입 페이지 공통] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 ‘/folder’ 페이지로 이동하나요?

### 심화

- [x] [심화] 로그인, 회원가입 기능에 react-hook-form을 활용했나요?

## 주요 변경사항

- signin, signup page react-hook-form으로 구현

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/cee95241-8df4-41a1-9ad4-13ac2ad8d312)

## 멘토에게
- react-hook-form 없이 구현하고나서 마이그레이션하느라 진땀 뺐습니다..
- 회원가입 페이지에서 email focus-out시 fetch를 쏠 때 에러처리하는게 좀 어려웠습니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-02-27 12:51 UTC, wonsss requested changes
안녕하세요! 기호님 😸 
이번 미션도 잘 해주셨군요 👏 👏 👏 
react-hook-form 사용 처음이실텐데 깔끔히 잘 사용해주셨네요
코멘트 단 내용 보시고 반영 부탁드립니다!
반영 후 수요일까지 재리뷰 요청해주세요. 감사합니다!

2024-02-27 12:51 UTC, wonsss commented on package.json
> +    "next": "^14.1.0",
<img width="789" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/fabd6f50-4d34-47a6-b5a6-c9443689bd59">
.nvmrc 파일은 change로 안 걸려 있어서 여기에 코멘트 달아요.
nvmrc에 명시한 node version은 18.7.0인데, next 설치 및 실행을 위해서는
18.17.0 이상이 필요하다는 경고가 뜨네요.
이러한 의존성을 확인하여 nvmrc를 적어주시면 좋습니다!

2024-02-27 12:51 UTC, wonsss commented on package.json
> +    "styled-components": "^6.1.6",
styled-components와 관련된 _document.tsx 에 대한 피드백인데, _document 파일이 change에 안 걸려서 여기에 적어요.

현재 server-side 에서 css-in-js의 stylesheet가 적용되어 렌더링된 후 내려오고 있지 않습니다. 처음에 스타일이 적용되어 있지 않다가 호다닥 스타일 입혀지는 거 보이시나요? <아래 영상 참고>

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/ce998fee-92b4-4f64-a899-55439d1d2312

이러면 사용자 경험이 좋지 않겠죠.

아래 링크의 _document 파일 코드의 getInitialProps 비동기 함수 부분이 styled-components의 ServerStyleSheet 적용하는 코드입니다. 이 함수를 복사하여 _document.tsx 파일에 붙여 넣어주세요.
https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.tsx


그러면 아래와 같이 스타일도 SSR에서 잘 되어 내려오는 것을 보실 수 있습니다. 😄 

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/dcf7e36b-130e-47bd-945f-b891990c81ac

2024-02-27 12:51 UTC, wonsss commented on pages/signin/index.tsx
> +            <Form currentPath={currentPath} />
Header와 Form 컴포넌트에 currentPath 속성을 전달하여, 각 컴포넌트 내에서 'signin'용과 'signup'용 UI를 분기해주시는군요. 🤔 
이런 의도시라면, url pathname을 가져오고 state로 만들 필요가 없습니다.
여기는 signin 페이지라는 것은 명확하니까, 아래와 같이 currentPath 속성에 문자열을 바로 넣어주세요. 😄 

여기서 currentPath state는 불필요합니다.
```tsx
            <Header currentPath='signin' />
            <Form currentPath='signin' />
```

2024-02-27 12:51 UTC, wonsss commented on pages/signup/index.tsx
> +            <SnsLogin />
여기도 마찬가지입니다. 위 댓글내용대로 수정해주세요~!

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Header.tsx
> +export const Header = ({ currentPath }: { currentPath: string }) => {
currentPath의 타입을 string으로 하셨군요.
그런데 실제로 내부에서는 currentPath에 대하여 'signin'인 경우 'signup'경우 두 가지만 고려하고 계시므로, 가능한 타입을 좁게 만드시는 게 좋습니다.

리터럴 유니언 타입을 적용해주세요. 이와 같이 유니언 타입을 적용하면, Header 컴포넌트 사용처에서도 타입 도움을 받습니다! 😄 
```ts
currentPath: 'signin' | 'signup'
```

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +export const Form = ({ currentPath }: { currentPath: string }) => {
여기도 유니언 타입으로 해주세요~!

같은 타입을 여러 번 쓰게 되었으니, 타입을 공용으로 사용할 수 있도록 위치시키고 export해주셔도 좋겠네요.

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +                    localStorage.setItem("accessToken", result.accessToken);
로컬스토리지 key를 상수로 관리하시거나,
이 자체를 함수로 만들어서 사용하시는 것도 안전하게 사용하는 방법입니다.

2024-02-27 12:51 UTC, wonsss commented on pages/signin/index.tsx
> +    }, [router]);
useEffect의 dependency array에 router를 넣으셨군요.
여기서 하려는 것은 페이지 마운트 후 accseToken이 로컬스토리지에서 있으면, 페이지를 이동시키는 것입니다.
router의 변화 여부에 의존하여 useEffect 내부 콜백이 호출되도록 기대하는 것이 아니죠.

따라서 dependency array에서 router를 제거하고 비어두는 것이 이 경우 적절해보입니다.

그런데 그렇게 하면 eslint가 경고할 것입니다. 하지만, 저는 그런 경우 해당 라인 경고 룰을 끕니다 ㅎㅎ

물론 router 객체가 변하진 않아서 useEffect가 불필요하게 재호출되는 이슈는 없을 것입니다. 
하지만 코드에 의도를 담는 것이 중요하기에 위에서 설명드린대로 하는 것을 제안드립니다. 😄 

다른 분들이 이에 대해 논의한 내용도 있으니 참고해보세요~
https://github.com/vercel/next.js/discussions/29403

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +    } = useForm({ mode: "onBlur" });
진짜 넘 편하죠 🦖

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +            )}
컴포넌트 설계에 대한 의견입니다.
signin과 signup은 함께 둘만큼 비슷하다고 보기 어려울 수도 있을 것 같아요.
SigninForm과 SignupForm으로 각각 나눠서 로직을 분리하는 것은 어떠신가요?
이렇게 상이한 성격의 로직이 내부에서 분기되어 있으면, 가독성이 떨어지고 나중에 유지보수하기도 어려울 수 있습니다.

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +                    localStorage.setItem("accessToken", result.accessToken);
커스텀 훅으로 분리해보세요~
이를 통해 UI 컴포넌트에서 로직을 추출할 수 있습니다.
그리고 커스텀 훅을 통해 이름을 적절하게 지정하면 코드의 가독성이 더 좋아집니다.
그리고 컴포넌트와 커스텀 훅이 분리되면, 컴포넌트를 건드리지 않고도 훅을 통해 기능을 추가할 수 있습니다.

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +        e.preventDefault();
👍

2024-02-27 12:51 UTC, wonsss commented on components/Sign/Form.tsx
> +        (async () => {
async 키워드를 여기가 아니라 handleRegisterSubmit 함수에 두는 것이 나을 것 같아요.

2024-02-27 12:51 UTC, wonsss commented on components/Sign/PasswordInput.tsx
> +                        $isError={isPasswordError}
`$` 는 왜 포함된걸까요? 🤔

2024-02-28 23:25 UTC, GihoKo commented on package.json
> +    "next": "^14.1.0",
fcd872ea6c83ccf40ed0da4c22142f4e2fd9fee6
node버전은 수정했습니다!

그런데 사진처럼 node의 필요한 버전이 터미널에 뜨게 하라면 어떤 설정을 해야하나요?

2024-02-28 23:29 UTC, GihoKo commented on components/Sign/PasswordInput.tsx
> +                        $isError={isPasswordError}
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/109282547/ef95ec1a-adcd-4f47-ac4e-268f77af844f)
앞에 $접두사를 안붙이면 브라우저 콘솔창에서 이런 에러가 나와서 붙였습니다

2024-02-28 23:36 UTC, GihoKo commented on components/Sign/Form.tsx
> +        (async () => {
4c15df30f45d4244938c1b7203c0a23c72c4a4a8
수정완료했습니다!

2024-02-28 23:39 UTC, GihoKo commented on pages/signin/index.tsx
> +    }, [router]);
d52feb2cc771290345ba299c89f5738315036d18
수정완료했습니다!
참고해보겠습니다~

2024-02-28 23:53 UTC, GihoKo commented on components/Sign/Form.tsx
> +                    localStorage.setItem("accessToken", result.accessToken);
2c29d7231c06b8e79bb2dcf7af9d79a90c4cfab5
수정완료했습니다

2024-02-29 00:00 UTC, GihoKo commented on pages/signin/index.tsx
> +            <Form currentPath={currentPath} />
b21644035f76860ae77fdc2711ddaf8b9f9a22bc
수정완료했습니다

2024-02-29 00:02 UTC, GihoKo commented on components/Sign/Header.tsx
> +export const Header = ({ currentPath }: { currentPath: string }) => {
c25dd65db00ee3b925446fd891c85818d2209963
수정완료했습니다

2024-02-29 00:02 UTC, GihoKo commented on components/Sign/Form.tsx
> +export const Form = ({ currentPath }: { currentPath: string }) => {
c25dd65db00ee3b925446fd891c85818d2209963
수정완료했습니다

2024-02-29 00:03 UTC, GihoKo commented on pages/signup/index.tsx
> +            <SnsLogin />
b21644035f76860ae77fdc2711ddaf8b9f9a22bc
수정 완료했습니다~

2024-02-29 00:16 UTC, GihoKo commented on components/Sign/Form.tsx
> +                    localStorage.setItem("accessToken", result.accessToken);
91ab1e6bade370ad1776f08504d2b4333e4a5d97
완료했습니다

2024-02-29 00:17 UTC, GihoKo commented on components/Sign/Form.tsx
> +            )}
시간이 좀 걸릴 것 같아서 이번주 미션하면서 같이 수정하겠습니다!

2024-02-29 00:30 UTC, GihoKo commented on package.json
> +    "styled-components": "^6.1.6",
e9e7abadce8a4192c4f55ae80ed53a08483bd484
수정완료했습니다~

2024-02-29 01:24 UTC, wonsss commented on package.json
> +    "next": "^14.1.0",
nvmrc에 명시된 노드버전으로 자동 변경하게 하려면 전에 말씀드렸던 것처럼 컴퓨터에 nvm 설치하시면됩니다!
https://github.com/nvm-sh/nvm?tab=readme-ov-file#install--update-script

2024-02-29 01:27 UTC, wonsss approved these changes

2024-02-29 01:27 UTC, merged