Part3 조형민
codeit-bootcamp-frontend/3-Weekly-Mission pull request #314
Opened 2024-02-25 14:38 UTC by Vegatality

## 요구사항

### 기본

- [x] [로그인 페이지] “회원 가입하기”를 클릭하면 ‘/signup’ 페이지로 이동하나요?

- [x] [로그인 페이지] 이메일 input에 placeholder는 “이메일을 입력해 주세요.”, 비밀번호 input에 placeholder는 “비밀번호를 입력해 주세요.”가 보이나요? 

- [x] [로그인 페이지] 이메일 input에서 focus out 할 때, 값이 없을 경우 아래에 “이메일을 입력해주세요.” 에러 메세지가 보이나요? 

- [x] [로그인 페이지] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 아래에 “올바른 이메일 주소가 아닙니다.” 에러 메세지가 보이나요? 

- [x] [로그인 페이지] 비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요? 

- [x] [로그인 페이지] 로그인 실패하는 경우, 이메일 input 아래에 “이메일을 확인해주세요.”, 비밀번호 input 아래에 “비밀번호를 확인해주세요.” 에러 메세지가 보이나요? 

- [x] [로그인 페이지] 로그인 버튼 클릭 또는 Enter키 입력으로 로그인 실행 되나요? 

- [x] [로그인 페이지] https://bootcamp-api.codeit.kr/docs 에 명세된 “/api/sign-in”으로 { “email”: “test@codeit.com”, “password”: “sprint101” } POST 요청해서 성공 응답을 받으면 “/folder”로 이동하나요? 

- [x] [회원가입 페이지] “회원 가입하기”를 클릭하면 ~~‘/signin’~~ '/signup' 페이지로 이동하나요? 

- [x] [회원가입 페이지] 이메일 input에 placeholder는 “이메일을 입력해 주세요.”, 비밀번호 input에 placeholder는 “영문, 숫자를 조합해 8자 이상 입력해 주세요. ”비밀번호 확인 input에 placeholder는 “비밀번호와 일치하는 값을 입력해 주세요.”가 보이나요? 

- [x] [회원가입 페이지] 이메일 input에서 focus out 할 때, 값이 없을 경우 “이메일을 입력해주세요.” 에러 메세지가 보이나요? 

- [x] [회원가입 페이지] 이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 “올바른 이메일 주소가 아닙니다.” 에러 메세지가 보이나요? 

- [x] [회원가입 페이지] 비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 에러 메세지가 보이나요? 

- [x] [회원가입 페이지] 비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input 아래에 “비밀번호가 일치하지 않아요.” 에러 메세지가 보이나요? 

- [x] [회원가입 페이지] 회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 에러 메세지가 보이나요? 

- [x] [회원가입 페이지] 회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 실행 되나요? 

- [x] [회원가입 페이지] 이메일 중복 확인은 “/api/check-email” POST 요청해서 확인 할 수 있나요? 

- [x] [회원가입 페이지] 유효한 회원가입 형식의 경우 “/api/sign-up” POST 요청하고 성공 응답을 받으면 “/folder”로 이동하나요? 

- [x] [로그인, 회원가입 페이지 공통] 눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지나요? 

- [x] [로그인, 회원가입 페이지 공통] 비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요? 

- [x] [로그인, 회원가입 페이지 공통] 소셜 로그인에 구글 아이콘 클릭시 ‘https://www.google.com’, 카카오 아이콘 클릭시 ‘https://www.kakaocorp.com/page’로 이동하나요? 

- [x] [로그인, 회원가입 페이지 공통] 로그인/회원가입시 성공 응답으로 받은 accessToken을 로컬 스토리지에 저장하나요? 

- [x] [로그인, 회원가입 페이지 공통] 로그인/회원가입 페이지에 접근시 로컬 스토리지에 accessToken이 있는 경우 ‘/folder’ 페이지로 이동하나요? 

### 심화

- [x] [심화] 로그인, 회원가입 기능에 react-hook-form을 활용했나요? 

## 주요 변경사항

-
-

## 스크린샷

![](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/123563774/73aa11a4-6674-49a9-9eb5-75eade31a891)

## 멘토에게

- react-hook-form 사용하니까 엄청 편리하네요!
- 컴포넌트화 리팩토링 진행중입니다.
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2024-02-27 14:50 UTC, wonsss requested changes
안녕하세요. 형민님! 수고 많으셨습니다 😄 
react-hook-form 및 typescript 사용을 능숙하게 잘 하고 계시네요.
코드도 깔끔하십니다! 리뷰 남겨드린 내용 참고하여 도움 되시길 바랍니다.

질문하신 atomic design pattern에 대한 제 의견을 말씀 드릴게요.
1안은 큰 그림을 그려야 가능한 방법으로 생각됩니다. 크고 체계적인 설계를 할 수 있고 목표로 하는 디자인 시스템 라이브러리 같은 경우는 1안처럼 한다고 생각합니다. 디자인 시스템에서는 처음부터 청사진이 다 있고 모든 컴포넌트가 일원화된 규칙을 가져야 할테니까요.

그런데, 서비스를 만드는 회사에서는 현실적으로 1안처럼 하긴 어렵고 2안이 적절하다고 생각됩니다.
왜냐하면, 서비스 회사는 목적이 디자인 시스템의 창조가 아니라 급변하는 비즈니스 상황에서 마켓핏에 맞는 프로덕트를 빠르게 출시하는 것이 목적이니까요. 그래서 page마다 새롭게 생긴 컴포넌트도 있고 다른 페이지와 규칙이 달라진 컴포넌트들도 종종 생겨날 수밖에 없습니다. 
저는 확실히 공용 컴포넌트로 합의된 것은 별도의 상위 shared 디렉터리에 두어 1안처럼 합니다.
그리고 이외에 페이지마다 필요한 것은 페이지 디렉터리 내에 components 디렉터리 내에 둡니다(2안처럼 atoms, moleculse, organsims까지 다 분류하진 않아요, 바쁘고 이렇게 분류해야 할 정도로 가치가 있지 않은 경우가 많아서요). 이처럼 두 가지 방법을 혼용해서 쓸 수도 있습니다.

그런데 은빛탄환은 없다죠~ 매번 그 상황에 맞는 좋은 방법을 직접 느끼며 찾아나가시면 됩니다!
좋은 고민 감사합니다 👍

2024-02-27 14:50 UTC, wonsss commented on .eslintrc.cjs
> +    ],
접근성에 좋은 룰을 설정하셨네요! 👍

2024-02-27 14:50 UTC, wonsss commented on pages/signin/comp/signin-form/SigninForm.tsx
> +            autoComplete='email'
적절한 속성을 잘 넣어주셨네요 👍

2024-02-27 14:50 UTC, wonsss commented on pages/signin/comp/signin-form/SigninForm.tsx
> +      if (!(res instanceof Error) && typeof window !== 'undefined') {
submit 핸들러 함수 내에서 호출되는 로직에서는 클라이언트 사이드일테니,  typeof window !== 'undefined' 조건을 체크할 필요는 없어 보입니다.

2024-02-27 14:50 UTC, wonsss commented on pages/signin/comp/signin-form/SigninForm.tsx
> +      if (!(res instanceof Error) && typeof window !== 'undefined') {
그리고 signin API 호출 로직을 try catch로 감싸셨기에, 발생하는 API 에러는 catch문에서 잡힐 것 같습니다.
그래서 await signin() API 호출이 성공한 다음, 
실행되는 아래의 로직에 이와 같은 조건문을 할 필요가 있는건지 궁금해요.

2024-02-27 14:50 UTC, wonsss commented on pages/signin/comp/signin-form/SigninForm.tsx
> +        localStorage.setItem('accessToken', JSON.stringify(res.data.accessToken));
로컬스토리지 설정 key를 사용하는 곳은 setItem, getItem 쌍이며, 여러 곳에서 재사용할 수 있습니다.
그래서 key를 상수로 관리하시는 것이 좋습니다.
또는 accessToken 관리 방식이 로컬스토리지, 세션스토리지, 쿠키 등 방법은 달라질 수 있잖아요. 그렇다면, 호출 인터페이스는 동일하게 두고 해당 함수 구현부만 수정할 수 있도록 이 로직을 함수로 분리하시는 것도 추천드립니다.

2024-02-27 14:50 UTC, wonsss commented on constant/sign/sign.ts
> +export const SUBMIT_ERROR_MSG: SubmitErrorMsg[] = [
변수명에 타입 성격도 포함되면 가독성이 올라갑니다.
SUBMIT_ERROR_MSG는 그냥 문자열일수도 있겠다는 생각이 듭니다.
그런데 메세지의 리스트니 SUBMIT_ERROR_MSG_LIST 는 어떨까요?
변수명 잘 짓는 게 제일 어렵고 제일 중요하더라구요.

2024-02-27 14:50 UTC, wonsss commented on pages/folder/index.page.tsx
> +      folderCategoryList,
서버사이드에서 fetch하여 props로 전달을 잘 해주셨네요!

2024-02-27 14:50 UTC, wonsss commented on pages/folder/index.page.tsx
> +    const res = await getFolderCategory(userId as string);
아래처럼 querystring에서 ParsedUrlQuery 타입을 가져와서 해당 타입을 확장(`extends`)하여 query의 타입을 만들고 타입 단언(`as`) 하는 방법도 있습니다. 이렇게 한 후, FolderPageUrlQuery을 해당 페이지 내 컴포넌트에서도 import하여 router.query에 단언하여 예측 가능하게 사용할 수 있습니다.

```tsx
import { ParsedUrlQuery } from "querystring";

export interface FolderPageUrlQuery extends ParsedUrlQuery {
	userId: string;
}
  const { userId = '1' } = context.query as FolderPageUrlQuery
```

querystring은 node에서 제공되는 라이브러리라서 별도로 설치하실 필요는 없어요. https://nodejs.org/api/querystring.html

2024-02-27 14:50 UTC, wonsss commented on pages/folder/index.page.tsx
>  };
pages 내 파일들은 라우팅과 서버사이드 로직을 처리하는 데 역할을 두도록 하고,
페이지의 UI에 대한 로직(JSX)는 별도의 페이지 컴포넌트 디렉터리에 모으는 것도 방법입니다.
이렇게 함께 있으면, 약간 이질적인 느낌이 들어 파일 분리를 해주면 좋아요

2024-02-27 14:50 UTC, wonsss commented on pages/signin/comp/signin-form/SigninForm.tsx
> +  });
react-hook-form 잘 사용하셨네요

2024-02-27 14:50 UTC, wonsss commented on package.json
>      "styled-components": "^6.1.8"
styled-components와 관련된 _document.tsx 에 대한 피드백인데, _document 파일이 change에 안 걸려서 여기에 적어요.

현재 server-side 에서 css-in-js의 stylesheet가 적용되어 렌더링된 후 내려오고 있지 않습니다. 처음에 스타일이 적용되어 있지 않다가 호다닥 스타일 입혀지는 거 보이시나요? <아래 영상 참고>

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/ce998fee-92b4-4f64-a899-55439d1d2312

이러면 사용자 경험이 좋지 않겠죠.

아래 링크의 _document 파일 코드의 getInitialProps 비동기 함수 부분이 styled-components의 ServerStyleSheet 적용하는 코드입니다. 이 함수를 복사하여 _document.tsx 파일에 붙여 넣어주세요.
https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/pages/_document.tsx


그러면 아래와 같이 스타일도 SSR에서 잘 되어 내려오는 것을 보실 수 있습니다. 😄 

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/dcf7e36b-130e-47bd-945f-b891990c81ac

2024-02-27 14:50 UTC, wonsss commented on components/ui/molecules/form/sign-form/compound-kit/Form.module.css
module.css 파일이 조금 남아있네요.
styled-componets 방식으로 대부분 수정하신 것 같은데, 스타일도 일관성 있는 방법으로 해주시는 게 좋아요~

2024-02-27 14:50 UTC, wonsss commented on pages/signup/comp/signup-form/SignupForm.tsx
> +                  });
catch문에서 반환하는 error를 사용하지 않으셨네요.
try 문 내에서 어떤 에러가 발생하든 무조건 '이미 존재하는 이메일입니다.' 메세지를 표시하도록 설정하셨어요.

그런데 try 문 내의 checkEmailDuplication 에서 사실 어떤 에러가 발생할지는 모릅니다.  API에서 다른 에러 메세지를 줄 수도 있고, 클라이언트 내 타입에러가 발생할 수도 있어요. 
따라서, try 문 내 로직에서 적절히 에러를 던지도록 해두고, catch 문에서는 반환되는 error를 잡아서 이를 메세지에 표시해주도록 하는 것이 적절할 것 같아요.

2024-02-28 12:37 UTC, Vegatality commented on components/ui/molecules/form/sign-form/compound-kit/Form.module.css
예전에 했던 거 그대로 옮겨서 그렇습니다 ㅋㅋ. 시간이 나면... 하겠습니다.
프로젝트가 아닌 과제이기 떄문에 지금은 우선순위가 굉장히 낮은 것 같습니다.

2024-02-28 15:15 UTC, Vegatality commented on pages/signup/comp/signup-form/SignupForm.tsx
> +                  });
코드잇 리스폰스가 좀 꼼꼼히 안 되어 있습니다.
그럼에도 불구하고 대강 에러 분기처리 하도록 해두었습니다.

2024-02-28 15:16 UTC, Vegatality commented on pages/folder/index.page.tsx
>  };
좀 더 고민해보겠습니다.

2024-02-29 01:21 UTC, wonseokjang-29cm approved these changes

2024-02-29 01:23 UTC, wonsss approved these changes

2024-02-29 01:23 UTC, merged