[이치현] Week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #32
Opened 2023-12-03 04:11 UTC by DanteSnow

## 요구사항

### 기본

- [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [ ] - [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [ ] - [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [ ] - [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [ ] - [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

<img width="1509" alt="스크린샷 2023-12-03 오후 1 09 17" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/150772344/a4122058-7f25-4e36-adac-36110693ccb9">
<img width="1509" alt="스크린샷 2023-12-03 오후 1 09 24" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/150772344/6c63a574-2a22-44c6-8624-380e80ba6f47">

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-03 06:58 UTC, goldfrosch requested changes
고생 많으셨습니다! 중요도에 따라 PR 커멘트를 남겨놨으니 확인 부탁드립니다.

매우 맵게 준비하겠습니다.

그리고 commit 기능단위로 한거 매우 칭찬합니다! 다음에 하실때는 git commit 컨벤션을 찾고 해보시는 것을 추천드립니다!

[전체 피드백]
스타일이 너무 한 파일에 몰려있습니다. 단위별로 .css를 만드는 것을 추천드립니다.

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/29947636/eb6a1be6-ab38-4e3c-aad7-871b031efa02)

2023-12-03 06:58 UTC, goldfrosch commented on faq.html
> +<html>
[중요도: 중간] html에 lang을 쓰면 해당 페이지가 어떤 나라의 페이지인지 인지할 수 있어 ko로 작성할 시 국내 SEO에 페이지 색인에 유리해집니다. (+ 구글은 저걸로 언어 번역 여부도 검사합니다!)

2023-12-03 06:58 UTC, goldfrosch commented on index.html
> +    <article>
[중요도: 높음]<main> 태그는 안보이네요? 확인 한번 부탁드립니다~

2023-12-03 06:58 UTC, goldfrosch commented on signup.html
> +    </div>
[중요도: 중간] 폼의 내용물 마다 하나의 섹션당 div로 묶으시는 모습이 보입니다. 혹시 이렇게 묶는 이유가 있을까요?

2023-12-03 06:58 UTC, goldfrosch commented on src/reset.css
> +  text-decoration: none;
[중요도: 높음] reset.css는 왜 쓰는건가요? user agent stylesheet 초기화라는 주석이 있는데 user agent stylesheet에 대해 설명 가능할까요?

2023-12-03 06:58 UTC, goldfrosch commented on src/style.css
> +}
[중요도: 높음] css는 element에 종속시키면 좋지 않습니다. 물론 컴포넌트 or 페이지별 css가 만들어져 문제가 안생길수도 있겠지만 저 element를 재사용할 때 문제가 발생할 수 있습니다 :) 귀찮아도 항상 className을 선언하는 것을 권장합니다.

2023-12-03 07:03 UTC, goldfrosch commented on privacy.html
> +</html>
[중요도: 높음] 이 페이지는 왜 있는걸까요? 빈 페이지 처럼 보이는데...

2023-12-03 07:08 UTC, goldfrosch commented on signin.html
> +      <button>로그인</button>
[중요도: 높음] form 에 들어가는 버튼에 type="submit" 이라는 옵션을 추가로 넣을 경우에 form 정보 전체 입력 시 엔터를 눌러도 동작이 됩니다 :) 참고 해주세요

사실 안써도 동작은 되지만... 적어주는 게 좋습니다.

2023-12-03 07:49 UTC, goldfrosch commented on index.html
> +          <span class="title-2-gradient background-clip-text">관리</span>하세요
[중요도: 높음] 이거 지금 봤는데 class명과 이미지 명, 변수명 등에 숫자가 있음 좋지 않습니다.
비지니스 요청으로 순서 바꿀 때도 보기 어려워지고, 숫자나 a,b,c같은 값은 나중에 다른 개발자들을 혼란스럽게 하기 좋거든요 :)

2023-12-03 09:34 UTC, goldfrosch commented on signin.html
> +    </div>
[중요도: 높음] 지금 확인해보니 로그인 페이지에서 이미지들과 css는 반영되지 않은 것 같네요...? 확인 한번 부탁드립니다. 경로의 문제 처럼 보입니다.

저한테만 안보이는 문제거나 혹은 외부 사람이 받아서 쓰면 안보일 것 같네요~

2023-12-03 09:36 UTC, goldfrosch commented
[중요도: 높음]
 [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus in 일 때, 테두리 색상이 파랑색인가요?
 
 이 질문에 대한 사항이 누락된 것 처럼 보입니다. 이 부분도 확인이 필요해보여요~
 
 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/29947636/365228f9-d26f-4c4b-a1ca-f0906f026abc)

2023-12-03 09:49 UTC, goldfrosch requested changes
+ 추가 확인 요청 드립니다.
[중요도: 높음]
체크 박스에 되어있는 색깔에 대한 토큰화는 안되어있어 보입니다.

2023-12-04 09:22 UTC, DanteSnow commented on faq.html
> +<html>
피드백 감사드립니다! 다음부터 언어 설정도 신경쓰겠습니다!
(현재는 vs코드 시작하고 ! 누르고 tap 눌러서 DOCTYPE html 자동완성 기능을 그대로 사용했습니다. )

2023-12-04 09:24 UTC, DanteSnow commented on index.html
> +    <article>
2주차 제출 과제는 signin, signup 페이지를 만드는 것이라서,
index.html 은 템플릿으로 받아서 사용했습니다!

시맨틱 태그의 종류와 알맞은 사용 방법 다시 한 번 숙지하고 사용하겠습니다.
피드백 감사드립니다!

2023-12-04 09:26 UTC, DanteSnow commented on signup.html
> +    </div>
이메일, 비밀번호 부분을 세로로 정렬하기 위해서 div를 사용했습니다!

2023-12-04 09:26 UTC, DanteSnow commented on src/reset.css
> +  text-decoration: none;
index.html 은 템플릿으로 받아와서 사용했습니다.
이 부분의 기능은 제가 아직 숙지하지 못했습니다.

2023-12-04 09:28 UTC, DanteSnow commented on src/style.css
> +}
피드백 감사합니다! 되도록이면 모든 element에 className 선언해서 사용하겠습니다!

2023-12-04 09:29 UTC, DanteSnow commented on privacy.html
> +</html>
index.html은 제가 작성한 게 아니라 템플릿을 받아와서 사용했습니다.
제 생각에는 다음 과제에 대한 부분을 비워놓은 것 같습니다!!

2023-12-04 09:30 UTC, DanteSnow commented on signin.html
> +      <button>로그인</button>
네 숙지하겠습니다! 피드백 감사합니다! ^^

2023-12-04 09:31 UTC, DanteSnow commented on index.html
> +          <span class="title-2-gradient background-clip-text">관리</span>하세요
앞으로 class 명에는 숫자를 최대한 넣지 않고, 그 요소를 잘 나타내는 이름으로 사용하겠습니다.
피드백 감사합니다!

2023-12-04 09:32 UTC, DanteSnow commented on signin.html
> +    </div>
수정해서 다시 Push 완료했습니다. 확인 부탁드립니다!

2023-12-04 09:34 UTC, DanteSnow commented on signin.html
> +    </div>
바로 밑에있는 피드백들에는 코멘트가 달리지 않아서 여기에 작성하겠습니다!
테두리 색상 또한 css 경로가 잘못되어 있어서 적용이 안 됐던 것 같습니다!
지금 경로 재설정하고 확인해보니 정상적으로 보이네요!
확인 부탁드립니다!

2023-12-04 10:01 UTC, DanteSnow commented on signin.html
> +    </div>
css 색상 토큰화 진행한줄 알고있었는데 적용이 안 됐나보네요! ㅠㅠ 다시 수정해서 push 했습니다! 확인 부탁드립니다!!

2023-12-04 12:05 UTC, goldfrosch commented on signup.html
> +    </div>
스타일의 경우는 확인했습니다~ 다만 label에 대한 것을 잘못사용하고 있는 것 같아 확인이 필요해보여요~

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2023-12-04 12:06 UTC, goldfrosch commented on src/reset.css
> +  text-decoration: none;
네네 그러면 user agent stylesheet에 대해서 한번 조사해보세요~ 왜 reset.css라는게 생긴건지 알기 편하실겁니다.

2023-12-04 12:06 UTC, goldfrosch commented on signin.html
> +      <button>로그인</button>
넵 button의 type에 대해서 한번 연구해보세요~

2023-12-05 01:03 UTC, DanteSnow commented on signup.html
> +    </div>
숙지하고 사용하겠습니다! 피드백 감사합니다! ^^

2023-12-05 02:17 UTC, DanteSnow commented on src/reset.css
> +  text-decoration: none;
네, 피드백 감사드립니다! ^^

2023-12-05 02:18 UTC, DanteSnow commented on signin.html
> +      <button>로그인</button>
네 감사합니다! ^^

2023-12-05 14:33 UTC, goldfrosch commented
확인했습니다 approve합니다~

2023-12-05 14:33 UTC, goldfrosch approved these changes

2023-12-07 13:27 UTC, DanteSnow commented
감사합니다!!

2023-12-17 13:28 UTC, merged