[조형민]Week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #37
Opened 2023-12-03 09:20 UTC by Vegatality

## 요구사항

### 기본
- [x] [기본] Github에 1 ~ 2주차 위클리 미션 Pull Request를 만들었나요?
- [x] [기본] Netlify에 파일 배포가 아닌 포크한 Github 레포지토리로 연결했나요?
- [x] [랜딩 페이지] 아래로 스크롤 해도 “Linkbrary” 로고와 “로그인” 버튼이 있는 상단 네비게이션 바(Global Navigation Bar)영역이 최상단에 고정되게 했나요?
- [x] [로그인 페이지, 회원가입 페이지 공통] Linkbrary 로고 클릭시 루트 페이지(“/”)로 이동하나요?
- [x] [로그인 페이지, 회원가입 페이지 공통] 로그인 페이지, 회원가입 페이지 모두 로고 위 상단 여백이 동일한가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus in 일 때, 테두리 색상이 파랑색인가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] input 요소에 focus out 일 때, 테두리 색상이 회색인가요?
- [x] [로그인 페이지, 회원가입 페이지 공통] SNS 아이콘들은 클릭시 각각 “https://www.google.com/”, “https://www.kakaocorp.com/page/” 으로 이동하나요?
- [x] [로그인 페이지] “회원 가입하기”는 클릭시 “/signup” 페이지로 이동하나요?
- [x] [회원가입 페이지] “로그인 하기”는 클릭시 “/signin” 페이지로 이동하나요? 

### 심화

- [x] [심화] palette에 있는 color값들을 css 변수로 등록하고 사용했나요? 
- [x] [심화] 비밀번호 input 요소 위에 비밀번호를 확인할 수 있는 눈 모양 아이콘을 추가했나요? 

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-03 12:31 UTC, airman5573 requested changes
위클리 미션 하시느라 수고하셨습니다.

전반적으로 코드를 잘 작성하려고 노력하신 모습이 많이 보입니다.

다만 id나 class이름 짓는게 아직은 어색하신것 같아요.

쉽지 않지만, 좋은 예제들을 보면서 감 익히는걸 추천드립니다.
https://www.youtube.com/watch?v=wIx1O5Y5EB4&list=PLgCTlR71eB4-ZGpajuh01zexg8f9Qd98z

수고하셨습니다.

2023-12-03 12:31 UTC, airman5573 commented on auth/signin/index.html
> +<html lang="ko">
lang 설정 👍

2023-12-03 12:31 UTC, airman5573 commented on auth/signin/index.html
> +    <link rel="stylesheet" href="/global.css" />
global 을 따로 분리 하셨군요 👍

2023-12-03 12:31 UTC, airman5573 commented on auth/signin/index.html
> +      <div id="container">
container는 자주 쓰는 단어라서 보통 id 보다는 class에 많이 줍니다.
참고만 해주세요.

2023-12-03 12:31 UTC, airman5573 commented on auth/signin/index.html
> +                <div class="pw-input-box">
네이밍을 규칙에 맞게 하려는 노력이 보입니다 👍

2023-12-03 12:31 UTC, airman5573 commented on auth/signin/index.html
> +              <ul class="social-login-box">
ul을 사용하셨군요 👍

2023-12-03 12:31 UTC, airman5573 commented on auth/signin/index.html
> +                    <img alt="google_login" src="/public/images/icons/google.svg" />
alt를 넣어 주셨네요 👍

2023-12-03 12:31 UTC, airman5573 commented on auth/signup/index.html
> +    <title>Document</title>
title을 수정해주세요.

2023-12-03 12:31 UTC, airman5573 commented on auth/style.css
> +  display: flex;
스타일 속성이 너무 많은것 같아요.
<img width="827" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/43077862-bc6e-41ac-b7be-5cb74096e75e">

불필요한 속성이 있는지 확인해서 지워주세요.

2023-12-03 12:31 UTC, airman5573 commented on auth/style.css
> +.form-btn {
버튼이 너무 하얘요.
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/68623798/bb12014a-facb-4f1c-911b-2e2616aaa4a1)
수정해주세요.

2023-12-03 12:31 UTC, airman5573 commented on auth/style.css
> +  font-style: normal;
특별히 normal로 지정한 이유가 있으신가요?

2023-12-03 12:31 UTC, airman5573 commented on auth/style.css
> +  color: var(--grey-light, #f5f5f5);
css variable을 사용하셨네요 👍

2023-12-03 12:31 UTC, airman5573 commented on global.css
> +.blind {
blind 스타일은 어떤 이유로 작성하신건가요?

2023-12-03 12:31 UTC, airman5573 commented on index.html
> +      <main id="container" role="main">
role을 주셨군요 👍

2023-12-03 12:31 UTC, airman5573 commented on index.html
> +                <span><span class="gradient-text">원하는 링크</span>를</span><br />
`<span>`으로 한번 더 감싸지는 않아도 될것 같아요.

2023-12-03 12:31 UTC, airman5573 commented on style.css
> +  height: 10rem;
원래 피그마 디자인에서 height가 이정도 인가요?
너무 높아 보여서요.

2023-12-03 12:48 UTC, Vegatality commented on global.css
> +.blind {
icon같은 것들이 file reader기에 읽혔을 때 부가 정보를 읽을 수 있게 해주고 싶었는데 사용하지는 않았습니다.

2023-12-03 12:50 UTC, Vegatality commented on auth/style.css
> +  font-style: normal;
폰트는 피그마 시안에서 텍스트에서 그대로 추출해서 가져온 것입니다.
불필요한 것 같아서 빼도록 하겠습니다.

2023-12-04 03:23 UTC, airman5573 commented on global.css
> +.blind {
와, 꼼꼼하게 신경쓰셨군요 👍 
다만, 웹접근성은 조금 나중으로 미루셔도 됩니다. 당장은 HTML & CSS & JS익히는게 우선무라 alt만 작성해 주셔도 괜찮을것 같아요.

지금은 웹 접근성을 지켜야 하는 이유와 그 방법에 대해서 알고만 있으셔도 충분할것 같습니다.
참고
- https://velog.io/@sehyunny/basic-of-web-accessibility
- https://www.youtube.com/watch?v=yLZZi5E7NTU

2023-12-06 05:44 UTC, merged