[김선영] Week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #38
Opened 2023-12-03 12:11 UTC by kimsuns

### 기본
- [미완료]
랜딩 페이지의 url path는 루트(‘/’) 입니다.

화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 해주세요.
화면의 너비가 1920px 보다 작아질 때, “Linkbrary” 로고의 왼쪽 여백 200px “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소간 거리가 가까워져야 합니다

화면의 너비가 1920px 이상이면 내부에 있는 요소간 동일한 간격을 유지하며 가운데 정렬해야 합니다.
화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2023”의 왼쪽 여백 104px과 SNS 아이콘들의 오른쪽 여백 104px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.

- [완료]
 title은 Linkbrary로 설정해 주세요.
 “로그인”은 클릭 시 로그인 페이지(‘/signin’)로 이동 합니다.
 클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 cursor: pointer를 설정해 주세요.
 Linkbrary 아이콘은 클릭 시 루트 페이지(‘/’)로 이동 합니다.

 “링크 추가하기”는 클릭 시 회원가입(‘/signup’)로 이동 합니다. 
 “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동 합니다.

  페이스북, 트위터, 유튜브, 인스타그램 아이콘은 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동 합니다.

### 심화

- [미완료]
사용자의 브라우저 font-size가 크고 작아짐에 따라 페이지의 요소간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 보세요

- []

## 주요 변경사항
- 메인 화면 추가
- 로그인 / 회원가입 페이지 추가

## 스크린샷

![image](이미지url)
![1주-메인하단](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152264841/f601faa0-f960-432c-96f8-310fca0eda7e)
![1주-메인화면](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152264841/43c24223-356a-46ff-aebd-f9828b25b89a)
![2주-로그인화면](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152264841/1a2842f7-8ba1-467d-ac17-e5095b6fc248)
![2주-회원가입화면](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152264841/d352a5e0-5025-426a-abd2-437f6ddffb65)

## 멘토에게
- 화면 크기에 따라 글자가 작아지고 커지는 부분을 모르겠습니다.
- 마찬가지로 화면 크기에 따라 요소들의 크기가 변하는 부분을 잘 모르겠습니다.
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-04 13:17 UTC, goldfrosch requested changes
고생 많으셨습니다. 첫 과제라 많이 정신없고 힘들었을 거라고 생각해요~

전체적인 피드백 드립니다.
1. 폴더구조
- 현재 폴더구조가 굉장히 난잡해 보입니다. 이런 경우는 앞으로 서비스가 커졌을 때 관리하기 매우 어려워 보이네요 ;-;
FE는 파일량과 빠른 개발을 위해 폴더구조를 많이 고민하고 있기도 해서 잘 챙기는게 중요하다고 생각합니다~

추천 구조 (여러가지 구조가 있지만 당장의 경우는 간단하게 추천드립니다)
ㄴ images/
  ㄴ ~~~.svg
  ㄴ ~~~.png
ㄴ styles/
   ㄴ ~~~.css
ㄴ ~~~.html

이런식으로 해보는걸 추천드립니다. 지금은 너무 규칙이 없고 난잡하네요.

2. 파일 명
- 파일명에 한글 or 띄어쓰기 그리고 특수문자는 하지 않아야합니다.
  당장 문제가 되지는 않으나, 간혹가다 한글, 띄어쓰기 특수문자 등이 문제가 될 때 있습니다. (encoding시...) 굳이굳이 문제를 만들 필요는 없습니다.
  
3. css 이름
- 이름은 전반적으로 잘 지었다고 생각합니다. 웬만해서 어떤 css가 어떤 부모 element 밑에 있는지 알아보기 괜찮다는 생각이 있네요.


다음에는 과제 제시간에 제출해보도록 더 노력해봅시다!

이번에는 질문에 대한 대답입니다.
- Q. 화면 크기에 따라 글자가 작아지고 커지는 부분을 모르겠습니다.
- A. 화면 크기에 따라 글씨 크기를 정하는 것은 여러 경우가 있으나 저의 경우는 vw 단위를 사용합니다. vw는 view width라는 단위로 현재 여러분의 브라우저 너비 사이즈에 따라 값이 달라지는 건데 이 단위를 사용하거나 혹은 %를 사용할 수도 있죠. (원하시는 대답이 되길 바랍니다. 아니라면 말씀해주세요 :))

- Q. 화면 크기에 따라 요소들의 크기가 변하는 부분을 잘 모르겠습니다.
- A. 위와 동일한 답변입니다.

답변이 되길 바라며 모르시는게 있으시다면 언제든지 편하게 질문주세요 :)

2023-12-04 13:17 UTC, goldfrosch commented on singup.html
> +              <a class="kakao-login" href="https://www.kakaocorp.com/page/"><img src="/signin/icon/kakao.svg" alt="카카오톡 로그인" ></a>
[중요도: 낮음] 동작에는 문제 없으나 href에서 맨 뒤에 불필요한 /는 없애는 걸 권장드립니다.
[중요도: 높음] 이미지 제가 받아서 할 때는 안나옵니다. 절대경로 문제로 보입니다. 확인 부탁드립니다.

2023-12-04 13:17 UTC, goldfrosch commented on singup.html
> +            <input id="login-password" name="password" type="password">
[중요도: 높음] label에 대해서 다시한번 알아보시는걸 권장드립니다 :)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2023-12-04 13:17 UTC, goldfrosch commented on singup.html
> +<html>
[중요도: 높음] html에는 lang 설정이 있으면 좋습니다!
lang="ko" 로 해서 해당 페이지가 한국 페이지다라는 것을 인지시켜 SEO에도 색인할 때 유리한 점이 있습니다.

2023-12-04 13:17 UTC, goldfrosch commented on style-login.css
> +}
[중요도: 높음] 가급적으로 CSS는 element에 직접 주입하지 않는 것을 권장드립니다!
element에 전역적으로 필요할 때 사용하는 경우도 물론 있습니다.
다만 지금의 케이스에서는 그렇다기보다는 필요한 css를 지금은 다 같은걸 쓰니까 사용한 것 처럼 보이네요...

최대한 className을 만들어서 넣는 것을 권장드려요~

2023-12-04 13:17 UTC, goldfrosch commented on style-login.css
> +  background-image: url(/signin/icon/google.svg);
[중요도: 높음] 안에 img 태그를 넣어서 이미지를 보여주는데 background-image는 불필요한 정보로 보입니다. 확인 부탁드려요~

2023-12-04 13:17 UTC, goldfrosch commented on style-login.css
> +  background-image: url(/signin/icon/facebook.svg);
[중요도: 높음] 여기도 바로 위와 마찬가지겠네요. img 태그가 있는데 사용하는 것 처럼 보이고 background image도 카카오와 facebook 매칭되지 않네요 확인해주세요~

2023-12-04 13:17 UTC, goldfrosch commented on style.css
> +}
[중요도: 높음] 가급적 변수명이나 class 명에 숫자나 a,b,c같은 순서 명칭을 쓰지 않는 것을 권장합니다.
이런 케이스의 가장 큰 문제 중 하나는 순서가 바뀌었을 때 이름도 바꿔줘야할 필요가 있는게 문젭니다~

2023-12-04 13:17 UTC, goldfrosch commented on index.html
> +      <section class="main">
[중요도: 중간] main이라는 class는 조금 애매하네요...? 다른 이름을 고려해보세요. main은 main element에 더 적합해 보여요

2023-12-04 13:17 UTC, goldfrosch commented on index.html
> +          <a>쉽게 저장하고 관리해 보세요</a>
[중요도: 높음] a태그에 대해 이해가 아직 잘 안되신 것 처럼 보입니다~ a태그는 href(하이퍼링크)를 넣을 때 사용하는 겁니다. 물론 이대로도 동작하지만 올바른 html 사용법이라고 보기는 매우 어려워 보이네요

아마 span태그에 이름을 넣다보니 다른 element 쓸게 생각안나서 쓰지 않았나 생각이 듭니다.
element에 css를 주입하면 안되는 이유 중 하나일 것 같네요 :)

2023-12-05 07:33 UTC, kimsuns commented on singup.html
> +              <a class="kakao-login" href="https://www.kakaocorp.com/page/"><img src="/signin/icon/kakao.svg" alt="카카오톡 로그인" ></a>
23.12.05
href 수정하였습니다
이미지 문제는 좀 더 확인해보겠습니다

2023-12-05 07:35 UTC, kimsuns commented on singup.html
> +            <input id="login-password" name="password" type="password">
혹시 비밀번호와 비밀번호 확인 두 input의 id 값이 같아서 문제가 됐던거였을까요? 이거라 생각하고 id 명을 변경하였습니다.

2023-12-05 07:35 UTC, kimsuns commented on singup.html
> +<html>
설정 완료 하였습니다. (23.12.05)

2023-12-05 07:35 UTC, kimsuns commented on style-login.css
> +}
최대한 className으로 변경 할 수 있는 부분은 변경하였습니다. (23.12.05)

2023-12-05 07:36 UTC, kimsuns commented on style.css
> +}
변경 완료하였습니다. (23.12.05)

2023-12-05 07:36 UTC, kimsuns commented on index.html
> +      <section class="main">
변경 완료하였습니다. (23.12.05)

2023-12-05 07:37 UTC, kimsuns commented on index.html
> +          <a>쉽게 저장하고 관리해 보세요</a>
수정 완료하였습니다 (23.12.05)

2023-12-05 07:39 UTC, kimsuns commented on style-login.css
> +  background-image: url(/signin/icon/google.svg);
코드잇에서 제공된 로고(G)와 배경(흰색), 카카오 로고(대화창)와 배경(노란색)이 따로 되어있어서 배경을 깔고 각 로고를 배경 가운데에 위치 시켰습니다. 문제가 될시 수정하겠습니다!

2023-12-05 07:40 UTC, kimsuns commented on style-login.css
> +  background-image: url(/signin/icon/facebook.svg);
이미지명은 코드잇에서 가져온 그대로 사용하였는데 오해의 소지가 있어 이해하기 쉬운 이미지명으로 변경하였습니다.

2023-12-07 07:32 UTC, goldfrosch commented on singup.html
> +            <input id="login-password" name="password" type="password">
이거는 제가 잘못 봤습니다 죄송합니다. 제대로 하셨군요 고생하셨습니다 🙏

2023-12-17 13:28 UTC, closed without merging