[김선영] Week2
codeit-bootcamp-frontend/3-Weekly-Mission pull request #47
Opened 2023-12-06 06:37 UTC by kimsuns

### 기본

- [완료]
 title은 Linkbrary로 설정해 주세요.
 “로그인”은 클릭 시 로그인 페이지(‘/signin’)로 이동 합니다.
 클릭으로 기능이 동작해야 하는 경우, 사용자가 클릭할 수 있는 요소임을 알 수 있도록 cursor: pointer를 설정해 주세요.
 Linkbrary 아이콘은 클릭 시 루트 페이지(‘/’)로 이동 합니다.

 “링크 추가하기”는 클릭 시 회원가입(‘/signup’)로 이동 합니다. 
 “Privacy Policy”, “FAQ”는 클릭 시 각각 Privacy 페이지(‘/privacy’), FAQ 페이지(‘/faq’)로 이동 합니다.

  페이스북, 트위터, 유튜브, 인스타그램 아이콘은 클릭 시 각각의 홈페이지로 새로운 창이 열리면서 이동 합니다.

랜딩 페이지의 url path는 루트(‘/’) 입니다.

화면의 너비가 1920px 이상이면 하늘색 배경색은 너비를 꽉 채우도록 채워지고, 내부 요소들의 위치는 고정되고, 여백만 커지도록 해주세요.
화면의 너비가 1920px 보다 작아질 때, “Linkbrary” 로고의 왼쪽 여백 200px “로그인" 버튼의 오른쪽 여백 200px이 유지되고, 화면의 너비가 작아질수록 두 요소간 거리가 가까워져야 합니다

화면의 너비가 1920px 이상이면 내부에 있는 요소간 동일한 간격을 유지하며 가운데 정렬해야 합니다.
화면의 너비가 1920px 보다 작아질 때, 최하단에 있는 “codeit-2023”의 왼쪽 여백 104px과 SNS 아이콘들의 오른쪽 여백 104px을 유지하면서 가운데 있는 “Privacy Policy”, “FAQ” 요소와 각각 동일한 간격을 유지하며 가까워져야 합니다.

### 심화

- [미완료]
사용자의 브라우저 font-size가 크고 작아짐에 따라 페이지의 요소간 간격, 요소의 크기, font-size 등 모든 크기와 관련된 값이 크고 작아지도록 설정해 보세요

- []

## 주요 변경사항
[현재]
- 폴더 정리
- class명 변경(숫자, main 으로 되어있던 부분)
- CSS로 직접 스타일 지정했던 부분 변경(className으로 주입)
- HTML에 lang="ko" 설정
- 비밀번호 입력 부분에 눈모양 아이콘 추가
- 브라우저 화면 크기 조정

[기존]
[1-2week]
- 메인 화면 추가
- 로그인 / 회원가입 페이지 추가

## 스크린샷

![image](이미지url)
![3w-login](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152264841/9c2a2dad-55c1-4970-b232-2871067400d8)
![3w-singup](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/152264841/bdd0848a-9c55-47eb-b52d-347af9746025)

## 멘토에게
- 
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-06 06:38 UTC, kimsuns commented
1-2주차 과제 미완성인 부분 수정하여 올렸습니다.

2023-12-11 12:09 UTC, goldfrosch requested changes
이전에 남긴 PR을 제외한 나머지에 comment를 달았습니다 확인해주세요~

2023-12-11 12:09 UTC, goldfrosch commented on singup.html
> +<!DOCTYPE html>
[중요도: 높음] 파일 이름(오타) 신경써주세요 ㅎㅎ....

2023-12-11 12:09 UTC, goldfrosch commented on singup.html
> +<html>
[중요도: 높음] lang 세팅은 필요하다고 봐요~

2023-12-11 12:09 UTC, goldfrosch commented on singup.html
> +            <a href="/"><img src="/images/signin/logo.svg"></a>
[중요도: 높음] img 태그에 alt는 웬만해서는 넣어주세요. 웹 접근성에 필요합니다.

2023-12-11 12:09 UTC, goldfrosch commented on singup.html
> +            <a class="font">이미 회원이신가요?</a>
[중요도: 중간] a tag를 활용하기에는 조금 다른 목적인거 같아요. p태그가 더 어울려보이네요~ a tag는 하이퍼링크 용입니다~

2023-12-23 01:57 UTC, goldfrosch approved these changes

2023-12-23 01:58 UTC, merged