[조성경] week3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #54
Opened 2023-12-08 05:49 UTC by whtjdrud

2023-12-10 11:36 UTC, mingzzi96 commented on assets/css/index.css
<img width="350" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/1ac8466c-dd84-4d6f-b8c9-86734c5698e8">

오우 그리드 멋져요용 수고하셨습니당 ㅎㅎㅎ

2023-12-10 12:03 UTC, Jnnsu commented on assets/css/signin.css
개발자의 기본 소양인 중복제거..! 코드가 한층 더 깔끔해 지셨네요 👍

2023-12-10 13:08 UTC, shkim901112 commented on assets/css/index.css
> +  section:nth-of-type(odd),
가상선택자를 쓰셨군요 저도 잘 모르는 부분인데 배워갑니다 !

2023-12-10 15:30 UTC, whtjdrud commented on assets/css/index.css
> +  section:nth-of-type(odd),
사실 저도 잘 몰라서 검색해보는 기능입니다. 다같이 익숙해질때까지 화이팅!

2023-12-10 15:30 UTC, whtjdrud commented on assets/css/signin.css
감사합니다..

2023-12-10 15:31 UTC, whtjdrud commented on assets/css/index.css
지민님도 할 수 있습니다. 어 그러고보니 아이니는 밍지... 어?!

2023-12-10 15:49 UTC, wonsss requested changes
안녕하세요. 성경님. 이번 미션도 멋지게 잘 해주셨네요 👍 
grid를 사용하여 요구사항을 잘 풀어내려고 하신 고민이 느껴져서 좋았습니다.
반응형 디자인 작업은 요구사항을 꼼꼼히 분석하고 개발 후 잘 적용됐는지 개발자도구로 꼼꼼히 테스트도 해봐야 하는 쉽지 않은 작업입니다. 그만큼 중요하구요.
첫 작업인데 훌륭하게 잘하셨네요! 개념적 이해를 잘 하신 것 같아요. 
코멘트 드린 것뿐만 아니라 다시 한번 테스트를 해보시고, 혹시나 디자인 요구사항과 다른 부분은 없는지 확인해보시면 꼼꼼함을 기르는 데 도움이 되실 것 같습니다. 👍 

리뷰에 코멘트 달아주신 후 다시 리뷰 요청해주시면 감사하겠습니다.

2023-12-10 15:49 UTC, wonsss commented on package.json
> +{
npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 
패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다. 

https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고
`npm init` 명령어 실행한 후 커밋해주세요!. 👍

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  background: var(--linkbrary-bg, #f0f6ff);
CSS 변수 대체값을 설정하셨군요. 좋습니다!
그런데 `:root` 에 `--linkbrary-bg` CSS 변수가 현재 정의되어 있지 않네요.
:root에 정의해주시는 게 CSS 변수 사용하는 목적에 맞을 것 같아요.
확인 부탁드려요~!

2023-12-10 15:49 UTC, wonsss commented on index.html
> +  <head>
크롬 개발자도구에서 디바이스 에뮬레이션 모드로 반응형을 시연했을 했을 때, 미디어쿼리가 동작하지 않고 있습니다(아래 영상 첨부). 그 원인은 필요한 meta 태그가 없기 때문인데요. 어떤 meta 태그가 필요한지 알아보시고 적용해보시면 좋을 것 같습니다.


https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/435cfa63-8756-4164-a44d-0d32db2c2bdd

2023-12-10 15:49 UTC, wonsss commented on index.html
> +    <meta property="og:image" content="/assets/images/index/landing-image.webp" />
메타 태그를 설정함으로써 SNS 공유 시 미리보기가 잘 되네요. 멋져요!! 👍

2023-12-10 15:49 UTC, wonsss commented on index.html
> +          <span class="slogan-gradient background-clip-text"> 세상의 모든 정보</span>를 <br />
클래스 이름도 스타일 역할 단위로 잘 명명해주셨고, 그렇게 명명된 클래스들을 여러 개 조합하여 잘 사용해주셨네요 👍

2023-12-10 15:49 UTC, wonsss commented on .prettierrc
> +}
prettier 등 환경 설정 시 각각의 이유를 생각하면서 도움이 됩니다.
각각 설정 이유를 알려주시면 좋을 것 같아요.

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  }
스크린샷과 같이, 이미지의 크기가 오른쪽으로 넘치는 것을 확인하실 수 있습니다.
이 경우에 이미지의 너비와 높이에 rem 대신 어떤 단위가 적합할지 고민해보시면 좋을 것 같아요.
<img width="533" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/6bccc792-0386-48db-a7bf-4f31a1032dc7">

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +    align-content: space-between;
align-content: space-between; 이 CSS 속성이 여기서 적용 안될 것 같은데, 확인 부탁드려요.

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  }
디자인 가이드와 달리, SNS 아이콘들 우측에 여백이 더 많이 있네요. 확인해주시면 좋을 것 같아요. 😄 

<img width="592" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/d70325fa-e273-4baf-a550-c1bdc309724a">

<img width="783" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0a0ca75e-73bc-44c8-b377-9b4f7a7c847a">

2023-12-10 15:49 UTC, wonsss commented on assets/css/reset.css
> +  font-size: 62.5%;
루트에서  font-size: 62.5%; 를 하신 이유를 설명해주시면 좋을 것 같아요! 😄

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +    font-size: 1rem;
해당 디자인 요구사항을 구현할 때, font-size에 rem을 적용하는 게 적절할지 고민해보면 좋을 것 같습니다.
지금 1rem을 10px로 정의해두셔서, 해당 디스크립션 폰트의 계산된 사이즈가 10px로 표시되고 있네요. 실제 디자인 요구사항에서는 PC와 테블릿에서는 16px이고, 모바일에서만 15px이어야 한다고 명시되어 있어요. 확인 부탁드려요. 😄 

<img width="1620" alt="스크린샷 2023-12-10 오후 11 28 49" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/53dcfb11-5f8f-4a05-8398-284ac391067a">

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +    letter-spacing: -0.01875rem;
-0.01875rem이 여기서 계산된 px은 -0.1875px이네요.
참고로 PC의 대부분 브라우저에서는 1PPI 밀도가 사용되므로 1px 미만을 표현할 수 없습니다.
자세한 이유는 첨부해드린 링크 참고해보시면 좋겠습니다. 
https://mniyunsu.github.io/design-1px/


<img width="375" alt="스크린샷 2023-12-10 오후 11 36 48" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/f69a9838-4ccf-42c1-be50-6665b60f9874">

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  section:nth-of-type(odd),
가상선택자 사용 잘하셨네요. 👍

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  }
레이아웃이 요구사항과 달리 우측이 옆으로 넘칩니다.

<img width="430" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/20a47822-38fe-47be-b51d-393ae211b419">
<img width="630" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/b4e8a3d8-391b-4649-89ac-99b02fb4edf4">

그리드 내 좌측 아이템의 너비와 우측 아이템 너비를 다시 확인해주세요. 
제 생각에는 padding은 빼고 유동적으로 변할 수 있는 부분은 auto 를 주는 게 나을 것 같습니다. 참고만 해보시고 좋은 방법 찾으셔서 반영 부탁드려요 😄 

```suggestion
  section {
    height: 26rem;
    column-gap: 5.1rem;
    row-gap: 0.1rem;
  }

  section:nth-of-type(odd) {
    grid-template:
      '. image'
      'title image'
      'description image'
      '. image'
      / auto 262px;
  }

  section:nth-of-type(even) {
    grid-template:
      'image .'
      'image title'
      'image description'
      'image .'
      / 262px auto;
  }
```

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +    font-size: 3rem;
피그마에서는 태블릿의 title 폰트 사이즈는 48px이라고 정해져 있네요. 
여기서 1rem을 10px로 커스텀 정의해두셨으니, 3rem은 30px이 나옵니다. 
1rem 기본값 16px로 착각하셨을 수도 있을 것 같은데, rem을 사용하실 때는 혼동하지 않도록 주의하셔야 해요. 😮 

<img width="1105" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/b3e490c3-2e19-4e38-ab4f-ed8682ac48ab">

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  height: 28rem;
피그마 요구사항과 달리 푸터 높이가 더 큰 것 같습니다.
<img width="711" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/3f994035-1cab-4ced-a987-8117a8a222f5">

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +@media screen AND (min-width: 768px) AND (max-width: 1199px) {
미디어 쿼리를 잘 적용해주셨네요!! 🎉

2023-12-10 15:49 UTC, wonsss commented on assets/css/index.css
> +  padding: 0 20rem;
패딩을 좌우로 많이 줘서 화면 너비가 좁아졌을 때, 그 안에 있는 요소들이 찌그러지는 문제가 생기네요. 
패딩을 빼거나, span 요소에 너비를 명시하는 등 여러 가지 해결 방법을 고민해보시면 좋을 것 같습니다. 

<img width="607" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0bd0acd3-7ed7-4d27-8327-bbf6a673cb5f">

2023-12-10 15:49 UTC, wonsss commented on index.html
> +        <a class="cta cta-long" href="signup.html">
해당 링크의 경로가 올바르지 않습니다. 확인 부탁드려요. 🙏

2023-12-10 15:49 UTC, wonsss commented on assets/css/signin.css
> +/* mobie */
아래와 같은 요구사항이 적용되지 않은 것 같습니다. 확인 부탁드려요!

- Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지합니다.
- Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않습니다.

<img width="718" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/e76caee1-ed8c-47d8-a441-ee0da88e4648">

2023-12-10 16:10 UTC, whtjdrud commented on index.html
> +  <head>
아 버그일까? 라고 생각했는데 뷰포트가 없군요! 바로 추가해두겠습니다.

2023-12-10 16:13 UTC, whtjdrud commented on index.html
> +  <head>
```html
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
```
추가해두었습니다. 
02748ef37bf845ec49fe8a5fe48316d4f4c47469

2023-12-10 16:19 UTC, whtjdrud commented on assets/css/index.css
> +  height: 28rem;
pc, tablet mobile 모두 16rem 크기인것을 확인하였고 수정 완료하였습니다.

5cba70163539e70068a02854460c41d605677760

2023-12-10 16:20 UTC, wonsss commented
현재와 같은 폴더 구조를 정하신 이유도 혹시 알려주실 수 있으실까요?
pages 하위에 index 외 다른 모든 html을 모으셨던데, 이로 인해 url이 `/pages/signup` 과 같이 pages 가 앞에 더 붙게 되었습니다.
url도 적절한 의미를 지닌 위계가 있도록 만드는 것이 좋습니다. 그런데 pages는 의미가 딱히 없는 것 같습니다.
현재로서는 폴더 구조가 간단하므로 html들을 root 폴더에 모두 빼도 좋을 것 같습니다.
또는 적절한 의미의 폴더로 묶어주는 것도 가능합니다.
정답은 없습니다 ㅎㅎ 그냥 고민해보시면 좋을 것 같아 말씀드려요.
비슷한 고민을 한 질문이 스택오버플로우에도 있었네요. 
https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly

2023-12-10 16:30 UTC, wonsss commented
> 멘토에게 질문
현재 signin, signup 페이지의 inpt type password에 눈 아이콘을 넣으려고 합니다.
방법은 div로 password를 쌓아서 position:releative, 눈 아이콘을 position: absolute 로 지정하면 될것이라고 생각하고 있습니다.
그러다보니 HTML 구조가 변경되다 보니 CSS 추가 및 수정이 발생하는 상황입니다.
나중에 확장성을 위해서 각각 Input box에 div를 넣는 것이 좋을지, 어떻게 작성하고 계신지 궁금합니다.

말씀하신 것처럼 "방법은 div로 password를 쌓아서 position:releative, 눈 아이콘을 position: absolute 로 지정" 하시면 구현될 것 같습니다.
요구사항에 따라 수정은 발생할 수 있습니다.
네이버나 다른 사이트에서 어떻게 구현하고 있는지 참고해보면 더 도움이 되실 것 같네요.

<img width="1447" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/17d42d71-1f9f-40cf-aa06-b731d74ae0e5">

2023-12-10 16:35 UTC, whtjdrud commented
> 현재와 같은 폴더 구조를 정하신 이유도 혹시 알려주실 수 있으실까요? pages 하위에 index 외 다른 모든 html을 모으셨던데, 이로 인해 url이 `/pages/signup` 과 같이 pages 가 앞에 더 붙게 되었습니다. url도 적절한 의미를 지닌 위계가 있도록 만드는 것이 좋습니다. 그런데 pages는 의미가 딱히 없는 것 같습니다. 현재로서는 폴더 구조가 간단하므로 html들을 root 폴더에 모두 빼도 좋을 것 같습니다. 또는 적절한 의미의 폴더로 묶어주는 것도 가능합니다. 정답은 없습니다 ㅎㅎ 그냥 고민해보시면 좋을 것 같아 말씀드려요. 비슷한 고민을 한 질문이 스택오버플로우에도 있었네요. https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly

과거에 프로젝트 폴더구조에 관련한 글들을 찾아봤을때 리액트라던지 다른 프레임워크를 사용하게 되면서 복잡한 폴더구조가 되면서 html 파일들을 묶어놓아서 저도 역시 그렇게 진행했습니다.

root 폴더에 index.html 이 없는 경우 주소 링크로 찾을수가 없어서 index만 빼두었습니다.

그런데 현재 단계에서는 간단한 폴더구조여서 크게 문제가 없다는 부분에 크게 동의합니다.

귀찮긴 하지만 귀찮음에도 의미있게 만드는게 중요하니 빠르게 수정해두겠습니다.

cf) 더불어 제가 테스트할때 로컬에서 문제가 없었으나 netlify로 테스트 할경우 a href가 / 임에도 불구하고 홈페이지주소/pages 로 이동해서 해결 방안에 대해서 고민하고 있었는데 이 문제도 해결될 것 같습니다.

항상 좋은 링크들 남겨주셔서 감사합니다. 제가 깨닫지 못한 부분이 많으니 혹시 이런 자료나 내용들이 있으면 많이 부탁...드립니다...

2023-12-10 16:40 UTC, whtjdrud commented on package.json
> +{
항상 좋은 글 감사합니다. npm 이나 관련 글 조금 더 찾아보고 공부해보겠습니다.

npm init 후 커밋한 내용은 아래와 같습니다.

40e5403b723daded9a466788cd64da3abba01b1f

2023-12-10 16:53 UTC, whtjdrud commented on assets/css/index.css
> +  background: var(--linkbrary-bg, #f0f6ff);
처음 만들때 피그마에서 아무생각 없이  복붙했던 내용들이 계속 발견되서 너무 창피합니다.
한번 본다고 했는데도 계속 이렇게 발견되네요 ㅠㅠ

처음에는 index.css 에 변수를 만들었으나 index 뿐만 아니라 signin, signup 에도 해당 변수명이 확인되어서
color.css 를 만들고 해당 파일을 import 하는 것으로 변경하였습니다.

:root 로 색상 추가
59a46dd8e3a5c16f5c9058319418e1fe4c017f0e

color.css 생성 및 import 기재 
75bc246f6aacb13d9424974405a3a15ca6c28c04

2023-12-10 17:15 UTC, whtjdrud commented on assets/css/index.css
> +  padding: 0 20rem;
- 제가 테스트할때는 해당 증상이 발생하지 않았습니다.
- 다만  tablet 일때 일정 너비를 주기 위해 margin 값을 주어서 찌그러져 아래 tablet 미디어 쿼리내에 아래 코드를 기재했습니다.
```css
nav a {
  flex-shrink: 0;
}
```
이걸 일단 미디어쿼리가 아닌 전체로 기재했습니다.

padding 값을 빼고
```css
  justify-content: space-evenly;
```
를 통해서 비슷한 느낌을 구현하였는데요. 실제 피그마 상에서 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/3c713011-226e-4997-9daa-983bd5ce5624)

이렇게 너비가 확인되는데 이렇게 따라가야 할지
아니면 디자이너와 함께 협업하여 레이아웃을 고정할지, **space-evenly** 등으로 조정할지를 협업하면서 정리해나가야할지 궁금합니다.

아니라면 제가 생각하지 못한 다른 방법이 있는걸까요? ㅠㅠ

2023-12-10 17:17 UTC, whtjdrud commented on index.html
> +        <a class="cta cta-long" href="signup.html">
안녕하세요. 링크 수정 완료하였습니다.

00058c01bd1c0c3c5f7c95ca30a52187131b0f13

2023-12-10 17:46 UTC, whtjdrud commented on .prettierrc
> +}
최초에 npm을 사용하지 않고  전역으로 prettier 설정할때 아는 내용도 있고 모르는 내용도 있습니다.
해당 내용이랑 다른 사람의 블로그 글을 보면서 고민했던 내용도 같이 적었습니다.

- singleQuote : true / css에서는 의미없고 자바스크립트 문자열시 자동으로 작은따옴표로 지정한다는 의미입니다. html등을 문자열로 다룰시 보통 클래스를 큰따옴표로 지정하기때문에 충돌하지 않도록 작은따옴표를 선호 합니다.

- semi : true  / 각 구문의 끝에 세미콜론을 붙일지 여부

- useTabs : false 경우 들여쓰기 사용시 탭 대신 스페이스를 이용합니다.( 탭이 너무 크면 불편하더라구요)

- tabWidth : 2 / 들여쓰기에 사용되는 공백의 수를 사용합니다. 위와 같은 이유로 4에서 2로 변경

- trailingComma : 자동으로 뒤에 콤마를 추가해 주는 기능으로 이것도 자바스크립트 같은 언어에 적용

- printWidth  / 한줄의 최대 길이 설정, 기본값은 80인가 작았는데 이럴 경우 a태그 + 링크 + 이미지 가 있을 경우 중간에 잘려 보기 싫어서 140으로 늘렸습니다.

- arrowParens / 자바스크립트에서 **=>** 가 들어간 함수의 경우 파라미터가 1개인 경우 괄호를 입력할지 말지 여부라고 합니다. 여기는 나중에 사용해보고 always로 변경할지 고민해보겠습니다!

2023-12-10 17:52 UTC, whtjdrud commented on assets/css/reset.css
> +  font-size: 62.5%;
해당 부분은 10px를 1rem 으로 커스텀하기 위해서 사용하는 의미로 알고 있습니다.
reset.css 에 해당 코드를 집어 넣으면 모든 페이지나 환경에서 동일한 기준으로 적용될것을 기대하여 루트에 넣었습니다.

2023-12-11 05:33 UTC, whtjdrud commented on assets/css/index.css
> +    letter-spacing: -0.01875rem;
넵 감사합니다. 제가 알고 있는 상식으로 해도 사실 1px 미만으로 표현하지 못한다는걸 알고는 있었는데 상세하게 확인할수 있었습니다.

삭제 진행도 완료했습니다.

939e5273384efda0d98d7bdac218f61956b08760

2023-12-11 05:37 UTC, whtjdrud commented on assets/css/index.css
> +    font-size: 1rem;
저의 착오입니다.
피그마에서는 1rem을 10px로 커스텀하기 위한 62.5%가 적용되지 않는 사실을 몰라서 figma에 있는 rem으로 되어서 동일한 문제가 반복되고 있습니다. ㅠ

금요일날 해당 내용을 알고 수정을 진행하였는데 많은 부분을 누락한것 같습니다.
앞으로 잘 적용할수 있도록 노력하겠습니다.

해당 부분은 px로 적용해서 다시 완료하였습니다.

939e5273384efda0d98d7bdac218f61956b08760

2023-12-11 07:53 UTC, whtjdrud commented on assets/css/index.css
> +    align-content: space-between;
#### align-content: space-between; 사용
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/6d59edb6-e593-48ff-bf00-8d6cdb8711ac)

#### 제거
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/2bc16005-bd4c-4401-aa82-7dc340ad1511)

아마 grid 컨테이너를 선언한 부분이 PC부분이라 154줄즘에 있어서 적용된것 같습니다.
제가 아마 중복된 내용을 제거하지 못해 단순한 것임에도 너무 길어지지 않았나 싶긴 한데요..

중복된 내용 검수하기도 너무 힘들어서 시간이 허용된다면

```css
  .footer-box {
  }
  /* 모바일 화면 */
  @media screen AND (min-width: 357px) and (max-width: 767px) {
    .footer-box {
    }
  }
```
이렇게 변경해볼 생각입니다.

2023-12-11 08:28 UTC, whtjdrud commented
추가 질문 드립니다. @wonsss 

### 혹시 .description의 16px, 15px 명시 되는 부분이 피그마에서 선택시 아래와 같은 화면을 말씀하시는 걸까요?

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/b5036065-65ea-4716-a8a1-357bd7bb7076)

계속해서 어떤 단위를 쓰는게 좋을지 고민이 됩니다 ㅠ
이번 미션때 너무나도 많은 사이즈 문제와 틀어짐을 경험해서 더욱 큰 고민이 드는것 같습니다.

특별히 요구사항에 100% 단위를 요구하는 내용이 없다면

- 모든 부분을 px로 처리
- 모든 부분을 rem으로 처리
- 하지만 이렇게 할경우 font-size가 너무 커지면 오버플로우가 발생하기 쉬울것 같아서 font-size를 제외한 모든 부분을 px로 두는게 맞을것같다

등의 고민을 하고 있습니다. 사실 저는 거의 세번째로 저는 정리되고 있습니다.
그래야 모바일이나 태블릿 환경에서 화면 확대 등의 기능에도 대응이 가능할것 같고(테스트는 안해봤지만 아마 px이면 글씨 크기는 고정이지 않을까) , 그리고 나머지 레이아웃 부분을 px로 해야 확대 등의 이슈에 그나마 오버플로우가 덜 할것 같다는 생각을 하고 있습니다. (글자 크기도 커지는데 패딩도 커진다면... 아마..) 

혹시 이렇게 할 경우 문제나 우려되는 부분이 있을까요?

2023-12-11 08:33 UTC, whtjdrud commented on assets/css/index.css
> +  }
일단 해당 부분은 제가 크기를 잘못 작성하여 나온 이슈로 확인되었습니다.

px로 다시 정의해보려다가 다른 단위를 한번 사용해볼까 하여 1fr (fr 단위는 그리드 컨테이너에 남아 있는 사용 가능한 공간의 일정 비율을 나타냅니다 [출처](https://developer.mozilla.org/ko/docs/Web/CSS/CSS_grid_layout/Basic_concepts_of_grid_layout)

정확한 이유는 아직 파악하지 못했지만 auto로 하는 경우 .title, .description이 화면 끝까지 늘어나 현재 0.5fr로 수정하였습니다.

아직 레이아웃을 작성할때 쓰는 단위에 대해서 고민하고 있습니다.

2023-12-11 08:41 UTC, whtjdrud commented
### 추가 질문 2
아마 제가 잘 만들지 못해서 간단한 수준임에도 불구하고 css가 길게 늘어지고 있는것 같은데요.
천천히 보면서 중복된 것은 최대한 줄여나가볼 생각입니다.

위의 코드리뷰에도 달았지만 css 파일이 너무 길어져 개인적으로 pc, 태블릿, 화면일때의 속성이랑 값 비교가 어려워
```css
  .footer-box {
  }
  /* 모바일 화면 */
  @media screen AND (min-width: 357px) and (max-width: 767px) {
    .footer-box {
    }
  }
```
처런 변경할 계획이었는데 혹시 font.css , layout.css 등으로 파일을 분리해서 사용하는 경우도 있을까요?
물론 제가 작업하는 파일이니 저의 입맛대로 하는 것도 맞지만 이러한 경우가 현업에도 있는지 궁금합니다.
아래는 예시 입니다.
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/94d41acb-0691-4def-a4c5-7b374919284b)

물론 지금 하는 프로젝트 규모 정도에는 적합하지 않지만.. 지금의 저에게는 필요한것 같기도 하고 그렇습니다..

2023-12-11 08:42 UTC, whtjdrud commented on assets/css/index.css
> +@media screen AND (min-width: 768px) AND (max-width: 1199px) {
감사합니다!

2023-12-11 08:43 UTC, whtjdrud commented on assets/css/index.css
> +    font-size: 3rem;
넵 이 부분도 역시 제가 잘못한 부분이 맞습니다.

피그마에서 나온 rem을 이상하다고 생각하면서도 의심하지않고 그대로 적용하였습니다. 금요일날 해당 문제를 발견해서 수정한다고 했는데 수정하지 못한 부분이 있네요 ㅠ. 주의하겠습니다.

2023-12-11 08:44 UTC, whtjdrud commented on assets/css/index.css
> +  }
현재 거의 모든 값을 px로 변경하였습니다. 아직 어떤 기준으로 단위를 적용할지 고민하고 있고 거의 정리되어가고 있습니다. ㅠ

2023-12-11 08:47 UTC, whtjdrud commented on assets/css/index.css
> +  }
변경해보았습니다. ㅠ 

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/cecd255d-984b-4de0-8b34-4165c92044fe)

커밋 메시지 : 9c78caf84f4c6116aa36ac4f06f85db69620d922

2023-12-11 16:10 UTC, wonsss commented
태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.

그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.

이런 부분도 생각해보시면 좋을 것 같아서 참고차 말씀드려요. 😄

2023-12-11 17:50 UTC, whtjdrud commented
> 태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.
> 
> 그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.
> 
> 이런 부분도 생각해보시면 좋을 것 같아서 참고차 말씀드려요. 😄

오 너무 좋은 말씀이신것 같아요. 

안그래도 지민님이랑 의견 나눌때 signin, signup 페이지 body에 직접 넣은걸 보고 왜 이렇게 했지..? div 만들어서 컨테이너로 하지 div로 하지 지금 보니 너무 미운거같은데요 하면서 이야기 나눴던게 생각나네요

css는 전역으로 적용되어 쉽게 적용 가능하지만 그만큼 side-effect에 대해 지속적으로 고민해봐야된다는 생각을 하게 되었습니다.

BEM을 우연히 알게되었지만 쓰는 이유에 대해 조금 더 생각해보게 되는것 같아요

단위에 대한 고민도 나름대로 어느정도 끝나고 고칠점도 많아지네요! 처음이니 그럴수 있어라고 하면서도 나름 실망스럽기도 합니다.  리팩토링도 그만큼 중요하기에 조금 더 고민해 보고 고쳐나가보겠습니다.

코드 보시면서 조금이나마 불편하거나 이해안가는점 있으면 언제든지 리뷰 부탁드립니다.(물론 현업 우선,, 원석님 쉬는 시간 우선! ) 감사합니다!

2023-12-12 12:20 UTC, wonsss commented on package.json
> +{
성경님~ dependencies가 엄청 많은데, 다 사용하시는 라이브러리인가요? 
현재로서는 devDependencies에서 기존의 eslint, prettier 만 있어도 될 것 같아요. 
dependencies 다 지워주셔도 될 것 같아요. 혹시 어떻게 이렇게 많은 라이브러리가 설치된 건지 알 수 있을까요?

2023-12-12 12:21 UTC, wonsss commented on assets/css/index.css
> +  background: var(--linkbrary-bg, #f0f6ff);
빠른 반영 감사합니다! 확인하였어요~! 👍

2023-12-12 12:21 UTC, wonsss commented on index.html
> +  <head>
저도 원인 찾느라 ㅋㅋ시간이 좀 걸렸네요

2023-12-12 12:22 UTC, wonsss commented on assets/css/index.css
> +  padding: 0 20rem;
결국 디자이너와 협업하면서 잘 커뮤니케이션해야 하는 것 같아요. 꼼꼼히 봐야하구요 ㅎㅎ
잘  해결해주신 것 같습니다. 👍

2023-12-12 12:27 UTC, whtjdrud commented on package.json
> +{
npm init 하니 갑자기 저렇게 작성되었는데요
css 다른 강의를 결제해서 들을때 VITE를 설치한적이 있는데요. 혹시 그것 때문일까요..?

2023-12-12 12:32 UTC, wonsss commented
## 추가질문 답변
### 단위 관련
모든 부분을 특별한 니즈 없이 rem으로 처리하는 것은 좋지 않은 것 같습니다.

대신 font-size 부분만 우선 rem으로 하고 나머지는 px로 가는 것도 괜찮을 것 같아요. 이렇게 하면 전체적 레이아웃 잡는 개발도 좀 쉽고, 브라우저 글꼴 크기가 커지면 사이트에서도 자동으로 반영되니 접근성에도 도움이 되구요.

그리고 복잡하다 싶으면, font-size 포함 모두 px로 가셔도 되구요. 사실 디자인을 중시하는 사이트에서는 font-size도 px로 다 가는 것 같기도 해요. 물론 시력이 좋지 않은 분들께 접근성이 떨어지는 문제일 수도 있으나, 여러 가지 상황을 고려해서 그런 결정이 나는 것 같기도 합니다.
중요한 것은 이처럼 고민하는 과정을 가지셨다는 거에요~! 

###  css 파일 분리
네! 여러개의 CSS 파일로 분리하고 이를 합쳐서 서비스에서 사용합니다. 공통적인 CSS를 참조할 때, 중복 코드를 제거할 수 있기에 매우 유용합니다. 그리고 유지보수하는 데에도 파일이 분리되어 있어 찾기 쉬우니 도움이 되실 수 있어요.

2023-12-12 12:33 UTC, wonsss commented on assets/css/signin.css
> +/* mobie */
성경님. 이 부분은 다음 미션에서 포함해서 진행해주셔도 될 것 같습니다!

2023-12-12 12:35 UTC, wonsss approved these changes
리뷰를 빠르게 잘 반영해주셔서 감사합니다. 수고하셨습니다! 
한 가지 반영 못하신 부분은 다음 미션에서 포함해서 처리해주셔도 될 것 같아요. 😄 
어프로브 및 머지하겠습니다. 🚀

2023-12-12 12:35 UTC, merged