[권지민] week 3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #62
Opened 2023-12-09 08:49 UTC by mingzzi96

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-10 10:32 UTC, Jun-12 commented
실제 모바일 화면 확인해볼 생각 못했는데 간격 이상해지는거 저도 그러네요,, 같이 해결해보시죠!

2023-12-10 12:02 UTC, Jnnsu commented on styles/main.css
실제 모바일 화면 확인해볼 생각 못했는데 역시 꼼꼼하시네요! 확인해보니 간격 이상해지는거 저도 그러네요,, 같이 해결해보시죠😂

2023-12-10 12:03 UTC, mingzzi96 commented on styles/main.css
저도 찾아봐여겠어요 원인을 ...! (ง •̀_•́)ง

2023-12-10 12:47 UTC, shkim901112 commented
저도 실제 모바일로 확인해봤는데 웹에서 볼때랑은 전혀 다르네요😥 저도 이 부분에 대해서 한번 알아봐야 될것같습니다

2023-12-10 13:19 UTC, mingzzi96 commented
> 저도 실제 모바일로 확인해봤는데 웹에서 볼때랑은 전혀 다르네요😥 저도 이 부분에 대해서 한번 알아봐야 될것같습니다

px이나 배수로 주었더니 깔꼼하게 해결되었습니다!
여백 관련된 요소들은 rem 사용에 주의해야겠어요....

2023-12-10 18:27 UTC, wonsss requested changes
수고하셨습니다 지민님~! 디자인 요구사항을 전체적으로 꼼꼼하게 잘 적용해주신 것 같아요. 👍 
미디어쿼리나 오픈그래프도 잘 적용해주셨네요.

"[심화] 랜딩 페이지 Mobile 사이즈에서 제품 소개 영역의 순서를 제목, 설명, 이미지 => 제목, 이미지, 설명 순서로 변경했나요?" 이 심화 요구사항도 해보시면 좋을 것 같아요.
```
<li> // flex-box
  <h2/>
  <p/>
  <img/>
</li>
```
이런 태그 구조에서 PC, TABLET, MOBLIE 별 flex box 내부 속성을 변경하면서 구현할 수 있을 것 같아요. 
PC에서는  "flex-flow: column wrap;"을 사용할 수도 있을 것 같아요.
```
h2   
            img
p     
```
그리고 모바일에서는 flex-direction column으로 하고
`:nth-child(2) { order: 3; }` 처럼 flex 아이템의 order를 변경함으로써 수직으로 쌓이면서 내부 아이템의 순서를 변경할 수도 있겠네요!

화이팅!

2023-12-10 18:27 UTC, wonsss commented on index.html
>          <header>
사소한 건데 아마 이 헤더에 배경색이 있어야 하는 것 같네요. 😄 
<img width="1647" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/2b1023c8-8076-4088-922e-dc96f46c5357">

2023-12-10 18:27 UTC, wonsss commented on styles/reset.css
> +}
EOL 있네요!

2023-12-10 18:27 UTC, wonsss commented on styles/reset.css
> +        font-size: 31.25%;
모바일 크기에서 root의 font-size를 이렇게 더 줄이신 이유가 있으신가요? 🤔 
개발하시면서 1rem이 10px인지 5px인지 헷갈리진 않으셨나요?

2023-12-10 18:27 UTC, wonsss commented on styles/main.css
> +    }
요구사항에 따르면 가로가 커지는 비율에 맞춰 세로도 커져야 하는 것 같아요.
현재는 세로가 고정되어 있는 것 같네요. 확인 부탁드려요. 😄 
<img width="430" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0a37ebc0-5ddf-4bbf-874b-ced64cdd6332">

2023-12-10 18:27 UTC, wonsss commented on styles/main.css
> +}
여기도 EOL!

2023-12-10 18:27 UTC, wonsss commented on styles/sign.css
> +}
EOL

2023-12-10 18:27 UTC, wonsss commented on styles/common.css
> +}
EOL

2023-12-10 18:27 UTC, wonsss commented on index.html
>                              <div class="text_box">
text_box라는 클래스가 정의되어 있지 않는 것 같아요.

2023-12-10 18:27 UTC, wonsss commented on styles/main.css
> +    .white_sec ul li:nth-child(2n) {
2n 도 좋고 또는 even 을 사용해도 좋을 것 같습니다. 
참고만 해주세요 ㅎㅎ
https://developer.mozilla.org/ko/docs/Web/CSS/:nth-child#%EC%84%A0%ED%83%9D%EC%9E%90

2023-12-10 18:27 UTC, wonsss commented on index.html
> +        <meta property="og:type" content="website" />
open graph 메타 태그 적용을 잘 해주셨네요!

2023-12-10 18:27 UTC, wonsss commented on pages/signup.html
> +                <p class="error_msg" aria-live="asserive">
오 벌써 웹접근성을  챙기시다니 멋집니다. 👍 
해당 ARIA 속성이 여기서 어떤 역할인지 설명해주시면 감사하겠습니다.

2023-12-10 18:27 UTC, wonsss commented on styles/common.css
> +}
mob 이 무슨 의미인가요?

네이밍은 되도록 명시적으로 하면 좋습니다!

2023-12-10 18:28 UTC, wonsss commented
npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 
패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다. 

https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고
`npm init` 명령어 실행한 후 커밋해주세요!. 👍

2023-12-10 18:29 UTC, wonsss commented
현재와 같은 폴더 구조를 정하신 이유도 혹시 알려주실 수 있으실까요?  
pages 하위에 index 외 다른 모든 html을 모으셨던데, 이로 인해 url이 `/pages/signup` 과 같이 pages 가 앞에 더 붙게 되었습니다.  
url도 적절한 의미를 지닌 위계가 있도록 만드는 것이 좋습니다. 그런데 pages는 의미가 딱히 없는 것 같습니다.  
현재로서는 폴더 구조가 간단하므로 html들을 root 폴더에 모두 빼도 좋을 것 같습니다.  
또는 적절한 의미의 폴더로 묶어주는 것도 가능합니다.  
정답은 없습니다 ㅎㅎ 그냥 고민해보시면 좋을 것 같아 말씀드려요.  
비슷한 고민을 한 질문이 스택오버플로우에도 있었네요.  
[https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly](https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly)

2023-12-11 02:31 UTC, mingzzi96 commented on styles/common.css
> +}
mobile이라는 의미로 사용하였는데 확실히 다른 사람들은 이해하기 어려울 수 있겠네요!
87b356fc8a10e21ac30677c529cfcae3a286c4d4 
1. mob -> mobile로 변경
2. mob_none -> mobile_hidden (모바일에서는 숨김) 이란 클래스로 변경해 주었습니다.

2023-12-11 02:50 UTC, mingzzi96 commented
> npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다.
> 
> https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고 `npm init` 명령어 실행한 후 커밋해주세요!. 👍

739d07523dc06e5c12f35568eafb4e39cd4545b5 관련 설명글을 읽고 설정해 보았습니다. 👍🏼

2023-12-11 02:56 UTC, mingzzi96 commented on pages/signup.html
> +                <p class="error_msg" aria-live="asserive">
조금씩 써보려고 하고 있습니당 ㅎㅎㅎ 익숙해져야하는데 손에 익지가 않네용 🥲

WAI-ARIA는 검색 엔진에 노출이 잘 될 수 있도록 도와주기도 하고, 장애인 비장애인 할 것 없이 웹에 접근이 쉬워질 수 있도록 유도합니다.

- 특히 aria-live = "assertive"의 경우, 에러 메시지에 자주 사용됩니다.
스크린 리더로 읽는 와중에 에러 메시지가 떴을 경우 다른 순서를 무시하고 해당 메시지를 사용자에게 바로 읽어줄 수 있도록 합니다.
- aria-label의 경우 사용자에게 요소의 역할을 알려줍니다.
 제 코드에서는 비밀번호 숨김/표시 버튼에 label을 넣어주었습니다. img 태그로 넣은 것이 아니라서 alt 속성을 줄 수 없었기 때문에 label에 설명을 적어 스크린리더가 읽을 수 있도록 하였습니다.

많이 부족하지만 관련하여 [밸로그 포스팅](https://velog.io/@ooo3289/WAI-ARIA-웹접근성을-위해선-빠질-수-없다) 하였습니당 헿ㅎㅎㅎ🪄

2023-12-11 02:58 UTC, mingzzi96 commented on index.html
> +        <meta property="og:type" content="website" />
메타 태그가 젤 직관적이라 쉽고 재밌네용 😂

2023-12-11 02:58 UTC, mingzzi96 commented on styles/main.css
> +    .white_sec ul li:nth-child(2n) {
오오 even 이라는 것도 있었군용! 놓치고 있었는데 알려주셔서 감사합니당 🤓

2023-12-11 03:01 UTC, mingzzi96 commented on index.html
>                              <div class="text_box">
abade8f1ec91750d50fe99feb62c32be321531d5 앗 html 구조 짜면서 왠지 선택할 것 같아서 클래스 넣어주었는데 결국 사용하지 않았네요..! 삭제해 주었습니다 🪄

2023-12-11 03:03 UTC, mingzzi96 commented on styles/reset.css
> +}
87b356fc8a10e21ac30677c529cfcae3a286c4d4 어우 ㅜㅜ 머지하고 새로 브랜치 만들면서 prettier가 먹히지 않아서 node_moduels 삭제하고 npm i 다시 해주었는데 뭔가 꼬였나보네요.. 다시 제대로 재설정해서 EOL 추가했습니다..!

2023-12-11 03:06 UTC, mingzzi96 commented on index.html
>          <header>
367095de785c438b11251c74642739a3d4a83684 헤더에 배경색! 추가하였습니당 🤓

2023-12-11 03:09 UTC, mingzzi96 commented on styles/main.css
> +    }
1d3568bf100ed717e3d22f0627d596dbace32dcf 아 저거 고민하다 높이 줬었는데, 요구 사항에 적혀있었군요! 다음 부터는 요구사항 부터 꼼꼼히 읽어야겠습니다 🤔 !

2023-12-11 03:15 UTC, mingzzi96 commented on styles/reset.css
> +        font-size: 31.25%;
앗 안그래도 절반이 되어야하는 폰트 사이즈가 꽤 있어서 저렇게 일괄 변경해 주었는데, 원래는 루트 폰트는 변경하지 않고 사용하는 것인가요? 저는 rem이라는게 
1. 루트 폰트 사이즈에 따라서 일괄 변경이 쉽다
2. 반응형에서 루트 폰트 사이즈만 변경한다 
3. 나머지 애매한 것들은 직접 변경한다.

이렇게 이해를 하고 있었습니다 😱
그래서 작업하면서도 계속 이럴거면 그냥 px 쓰면서 media query 주는거랑 뭐가 다르지?? 이런 생각을 하긴 했었어요...
루트 폰트 그대로 두고 다들 10px에 맞게 rem으로 변경해 두겠습니다!

2023-12-11 03:25 UTC, mingzzi96 commented on styles/reset.css
> +        font-size: 31.25%;
716473a7fa163499f783c887c31cee4fd71675c5 변경 완료..! 🪄

2023-12-11 05:14 UTC, mingzzi96 commented
> flex-flow: column wrap;

<img width="250" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/c380f866-9994-40d4-94fd-5831282bef64">

8fbedd0f666e9a06db9e1ff3e730faa70bd3cb5f 고민 고민하다가 저도 그리드 활용해서 심화 완료해 보았습니다..! 그리드가 막상 해보니 그렇게 어렵지는 않군용 다행히..! 원석님 덕분에 눈가리고 넘어갈뻔한 심화를 완료하였습니다..! (ง •̀_•́)ง

2023-12-11 16:10 UTC, wonsss commented
태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.

그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.

이런 부분도 생각해보시면 좋을 것 같아서 참고차 말씀드려요. 😄

2023-12-12 11:42 UTC, wonsss commented on styles/reset.css
> +}
확인 감사합니다!

2023-12-12 11:51 UTC, wonsss commented on styles/reset.css
> +        font-size: 31.25%;
[브라우저 설정](chrome://settings/appearance)에서 아래 스크린샷 처럼 글꼴 크기를 변경할 수 있습니다. 이게 root font size에 영향을 미칩니다. 
시각 장애가 있으신 분들은 브라우저 설정에서 글꼴 크기를 "아주 크게"로 설정하실 가능성이 있어요. 
이에 대응하기 위해 rem 을 이용하여 폰트사이즈를 주는 것은 좋습니다. 
테스트해보니까, 지민님 사이트에서 중간값(기본)인 경우 root font size가 10px이고, "크게" 는 12.5px, "아주 크게"는 15px로 변경되고 이에 따라 rem로 지정된 폰트들도 다 같이 크기가 변경되네요.
<img width="1250" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/215aed50-ec62-4eda-9963-cd00f763d8da">

그런데 미디어쿼리 사용해서 모바일 기기의 경우에 root font size를 5px로 변경하는 것보다는 
크기를 변경하고 싶은 텍스트 부분의 rem 배율을 조정하는 것이 어떨까요?

2023-12-12 11:52 UTC, wonsss commented on styles/reset.css
> +        font-size: 31.25%;
수정 확인했습니다! 감사해요~!

2023-12-12 11:53 UTC, wonsss commented on styles/main.css
> +    }
구현도 중요하지만, 그 전에 요구사항 분석과 설계 역량도 매우 중요합니다! 수정 감사합니다.

2023-12-12 11:57 UTC, wonsss commented on pages/signup.html
> +                <p class="error_msg" aria-live="asserive">
훌륭합니다! 좋은 포스팅 감사해요!

2023-12-12 11:58 UTC, wonsss commented on styles/common.css
> +}
이름은 가능한 한 구체적인 게 좋아요!

2023-12-12 12:09 UTC, wonsss approved these changes
리뷰 잘 반영해주셨네요. grid도 잘 사용해주셨구요!
그리고 정성들인 포스팅까지~~ 💯 
수고하셨어요!

2023-12-12 12:09 UTC, merged