[이치현] Week3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #66
Opened 2023-12-09 13:58 UTC by DanteSnow

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-13 07:11 UTC, goldfrosch requested changes
고생하셨습니다.

시멘틱 마크업이 굉장히 잘 된 모습이 보였습니다. 많이 발전했네요.
og 태그도 괜찮게 쓰셨고요

이번에 PR은 과제 요청사항 위주로 확인했으니 확인 한번 부탁드립니다. 감사합니다.

2023-12-13 07:11 UTC, goldfrosch commented on index.html
> +    <div class="footer-box">
[중요도: 낮음] 이 div는 굳이 필요해보이지는 않네요~ 확인해주세요~

2023-12-13 07:11 UTC, goldfrosch commented on signin.html
> +<html>
[중요도: 높음] lang 넣어주세요~

2023-12-13 07:11 UTC, goldfrosch commented on index.html
> +      </p>
[중요도: 중간] 과제와는 좀 별개의 내용이겠네요. 요구사항 자체는 충족하셨습니다. (이미지 고정값) 하지만 이렇게 할 경우 태블릿 환경에서 가로 스크롤이 생기는 이슈를 확인했습니다. gap도 값이 고정이라서 생기는 이슈처럼 보이는데, 시간이 나신다면 고쳐보시는 것도 좋아보입니다.

[중요도: 높음] 이 경우에 화면크기 787px로 해보니 스크롤이 생기는 것과 별개로 왼쪽의 이미지가 짤려보이네요. 이 부분 확인 부탁드립니다.

2023-12-13 07:11 UTC, goldfrosch commented on index.html
> +      <img src="./images/hero.png" class="hero-image" alt="Linkbrary 서비스 소개" />
[중요도: 높음] 파일명 및 class명이 hero가 들어가네요...? 혹시 이유가 어떻게 될까요?

2023-12-13 07:19 UTC, goldfrosch commented on src/landing.css
> +  padding-top: 7rem;
[중요도: 중간] rem을 많이 활용하셨네요. 이렇게 해봤을 때 어떤 장점이 있었을까요?

2023-12-13 07:37 UTC, goldfrosch commented on signin.html
> +          <input class="sign-input" type="password" />
[중요도: 낮음] https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls%3A-the-autocomplete-attribute

이거는 저도 처음알았네요 ㅎㅎ... 구글 쪽 정책에서 비밀번호, 로그인 같은 중요 input의 경우 auto-complete를 attributes를 넣어 구글 크롬을 이용해 자동완성(이전 비밀번호 같은...)을 사용할 수 있게 해달라고 경고가 오네요.

시간 여유나실 때 해보면 좋을 것 같아요. 오래걸리는 작업은 아니라서요~

2023-12-13 07:37 UTC, goldfrosch commented on src/landing.css
> +  section {
[중요도: 낮음] 아직 element 종속된 style이 좀 보이네요...! 다음에는 번거롭더라도 class를 직접 만들어 보는게 좋아요!

2023-12-16 08:28 UTC, DanteSnow commented on index.html
> +    <div class="footer-box">
footer-box에 있는 클래스들을 footer로 그대로 옮겨가면 화면이 깨지네요!

footer-box div를 따로 잡은 이유는, 모바일 쿼리로 전환 시 display가 flex -> grid로 변해서 영역을 따로 잡았습니다!
만약 그대로 footer에 적용해도 문제 없는 것이라면, 다음부터는 footer에 그대로 클래스 적용하는 코드를 사용해 보겠습니다.

2023-12-16 08:30 UTC, DanteSnow commented on signin.html
> +<html>
네, 추가 했습니다! 전 PR 때 말씀해주신건데, 깜빡했습니다! 감사합니다!

2023-12-16 08:39 UTC, DanteSnow commented on index.html
> +      <img src="./images/hero.png" class="hero-image" alt="Linkbrary 서비스 소개" />
템플릿 코드를 받아온 거라서 정확히 이유를 모르겠습니다!
협업을 위해서 클래스 명은 최대한 연관되게 작명하는 것이 좋다는 점은 인지하고 있습니다!

2023-12-16 09:11 UTC, DanteSnow commented on index.html
> +      </p>
1. 여백 값을 줘도 변하지가 않네요, 혹시 어떻게 접근해야 할까요? ㅠㅠ
2. 사진 첨부해드렸습니다! 심화 과제에 맞게 작성했는데(제목, 이미지, 설명 순서), 혹시 제가 보이는 화면이랑 다르게 나오시나요?!  
<img width="631" alt="스크린샷 2023-12-16 오후 6 10 21" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/150772344/aa330581-51d5-40dc-bd5d-c3fd35925b5a">

2023-12-16 09:12 UTC, DanteSnow commented on src/landing.css
> +  padding-top: 7rem;
figma 에서 css 확인 후 복사/붙여넣기로 대부분 코드 작성했습니다!
만약 제가 직접 코드 전부 작성했다면 rem은 되도록이면 사용 안 할 것 같습니다!

2023-12-16 09:14 UTC, DanteSnow commented on signin.html
> +          <input class="sign-input" type="password" />
네, 감사합니다! ^^

2023-12-16 09:15 UTC, DanteSnow commented on src/landing.css
> +  section {
넵! 제가 직접 작성할 경우에는 모든 element에 class 만들어서 사용하겠습니다! 감사합니다!

2023-12-17 12:56 UTC, goldfrosch commented on index.html
> +    <div class="footer-box">
넵 확인했습니다~

2023-12-17 12:56 UTC, goldfrosch commented on index.html
> +      <img src="./images/hero.png" class="hero-image" alt="Linkbrary 서비스 소개" />
넵 확인했습니다~

2023-12-17 12:57 UTC, goldfrosch commented on src/landing.css
> +  padding-top: 7rem;
오히려 rem을 사용하는 것이 더 좋을 수 있습니다. rem의 역할에 대해 조사해보고 어떨 때 사용하는 건지 확인하면 좋을 것 같네요~

2023-12-17 12:59 UTC, goldfrosch commented on index.html
> +      </p>
엇... 지금 다시보니 고쳐졌네요...? 이전에는 옆으로 스크롤 되는 것을 보고 적어둔건데... 이부분은 넘어가겠습니다 :)
다음부터는 이런 PR일 때 첨부내용을 조금 더 적어두겠습니다

2023-12-17 12:59 UTC, goldfrosch approved these changes
고생하셨습니다 approve 드립니다!

2023-12-17 13:11 UTC, DanteSnow commented on index.html
> +      </p>
네 감사합니다!! ^^

2023-12-17 13:12 UTC, DanteSnow commented on src/landing.css
> +  padding-top: 7rem;
넵! 피드백 감사드립니다!!

2023-12-17 13:32 UTC, merged