Week 3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #69
Opened 2023-12-09 17:46 UTC by yoojungChoii

## 요구사항

### 기본

[기본] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용했나요?
PC: 1200px 이상
Tablet: 768px 이상 ~ 1199px 이하
Mobile: 375px 이상 ~ 767px 이하
375px 미만 사이즈의 디자인은 고려하지 않습니다

[랜딩 페이지] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 Linkbrary 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정했나요?

[랜딩 페이지] 미리보기에서 제목은 “Linkbrary”, 설명은 “세상의 모든 정보를 쉽게 저장하고 관리해 보세요”로 설정했나요?

[랜딩 페이지] 주소와 이미지는 자유롭게 설정했나요?

[랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 변하지 않게 고정값으로 유지하되 좌우 여백이 줄어드나요?

[랜딩 페이지] Tablet 사이즈에서 최소 좌우 여백은 “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px을 유지하고“Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지나요?

[랜딩 페이지] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용했나요?

[랜딩 페이지] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차나요?
(이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)

[랜딩 페이지] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지나요?

[로그인, 회원가입 페이지] Tablet 사이즈에서 디자인은 PC사이즈와 동일한가요?

[로그인, 회원가입 페이지] Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지하나요?

[로그인, 회원가입 페이지] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않나요?

### 심화

[심화] 팀원의 위클리 미션 PR에 코드 리뷰를 남겼나요?

[심화] 랜딩 페이지 Mobile 사이즈에서 제품 소개 영역의 순서를 제목, 설명, 이미지 => 제목, 이미지, 설명 순서로 변경했나요?

## 주요 변경사항

-
-

## 스크린샷
![스크린샷 2023-12-10 024456](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151714134/2cb49476-74d2-4819-ae51-cf156202c3d6)

## 멘토에게

- 화면을 줄이거나 늘릴 때 특정 구역에서 이미지가 다른 영역을 침범합니다. 어떻게 방지할 수 있을요?
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-13 16:06 UTC, goldfrosch requested changes
고생하셨습니다!
이전보다 많이 나아진 모습들이 보입니다 :)

항상 성장하고 열심히 하시길 바라며 밑의 PR 확인 부탁드립니다.

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +                 "e i";
[중요도: 높음] grid에 대해 변수명이 한글자네요... 이런 경우 다른 개발자와 협업할 때 이해를 잘 못할 수 있습니다. 이 부분은 변경이 필요하겠네요.

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +    font-size: 62.5%;
[중요도: 중간] 전역적으로 이렇게 font-size를 지정했을 때 어떤게 좋았었나요?

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +  max-width: 120rem;
[중요도: 높음] body의 maxWidth값이 120rem이네요...? 이 경우는 왜 120rem으로 하였는지 단위가 rem인지 이유를 알 수 있을까요?

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +    margin-left: 32px;
[중요도: 높음] 어떤 폰트의 단위는 px이고 어떤 폰트의 단위는 rem입니다. 2개의 차이점은 무엇이였으며 통일되지 않고 사용한 이유가 뭘까요?

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +  display: inline-block;
[중요도: 낮음] inline-block의 속성은 뭐였고 썻을때 어떤게 좋았었나요?

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +  Height: 3.4rem;
[중요도: 낮음] css는 앞에 대문자여도 동작하는 것은 이번에 알긴했습니다. 다만 코드라는 것은 컨벤션이 있는 만큼 하나로 통일하는 것 또한 매우 중요합니다. css 기본 컨벤션인 kebab-case로 변경해주세요 :)

2023-12-13 16:06 UTC, goldfrosch commented on css/index-style.css
> +  -webkit-background-clip: text;
[중요도: 중간] 앞에 -webkit-을 붙이는 형태는 어떨 때 쓰이는건지 알 수 있을까요?

2023-12-13 16:06 UTC, goldfrosch commented on index.html
> +      <section class= "section-left">
[중요도: 높음] 전체 컨텐츠는 article로 묶고 넣는 것을 추천드립니다. 현재 상황에서는 당연히 이런 경우 불필요한 element로 보일 수 있는데 제 경험상 article로 한번 크게 묶고 section들을 넣는게 훨씬 SEO에 도움이 됬던 것 같네요. (오피셜은 아니지만 시멘틱 마크업 권장 방식이기도 하니까 해보는 것을 추천드립니다)

2023-12-13 16:06 UTC, goldfrosch commented on signin.html
> +<html lang="kor">
[중요도: 높음] ko로 바꾸는게 좋아보입니다. kor이 먹히는 지는 찾아봤는데 현재 찾아볼때는 보이지 않습니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Global_attributes/lang

만약 먹힌다 하더라도 문서에 맞춰서 하는게 더 좋을 것 같네요 :)

2023-12-13 16:06 UTC, goldfrosch commented on signin.html
> +        <img src="img/kakao.png">
[중요도: 높음] alt 태그가 없네요 :) 확인 부탁드립니다.

2023-12-13 16:06 UTC, goldfrosch commented on signin.html
> +      </div>
[중요도: 높음] 웬만해서 html구조에 대해서는 피드백을 줄이고 있으나 이 경우는 조금 더 도움이 될 것 같아 남깁니다.
```suggestion
      <label id="password">
          <span>비밀번호</span>
          <input class="password" id="password" name="password" type="password" placeholder="비밀번호를 입력하세요.">
          </label>
          <img src="img/eye.png" class="eye">
```

이렇게만 해도 element수를 많이 줄여볼 수도 있어보입니다.
label안에 감싸는 방식으로도 줄여볼 수 있으니 이렇게 해보는 것도 좋아보입니다 :)

이견 있으시다면 말씀해주세요...!

2023-12-13 16:06 UTC, goldfrosch commented on index.html
> +
[중요도: 높음] 트위터 용 og 태그는 안보이네요...? 확인 부탁드립니다.

2023-12-15 06:42 UTC, yoojungChoii commented on css/index-style.css
> +                 "e i";
아 그렇군요! 수정하겠습니다!

2023-12-15 06:42 UTC, yoojungChoii commented on css/index-style.css
> +    font-size: 62.5%;
모바일의 경우 화면이 상대적으로 작기때문에 전체 폰트 크기의 비율을 조금 줄여보고자 저렇게 했습니다.. 따로 떼는게 좋을까요?

2023-12-15 06:43 UTC, yoojungChoii commented on css/index-style.css
> +  max-width: 120rem;
반응형의 단위를 px보단 rem으로 바꾸는게 좋다고 해서 시도하다가 이것저것 뒤섞인 것 같습니다..  일관성 있게 통일하겠습니다!

2023-12-15 06:44 UTC, yoojungChoii commented on css/index-style.css
> +    margin-left: 32px;
반응형의 단위를 px보단 rem으로 바꾸는게 좋다고 해서 시도하다가 이것저것 뒤섞인 것 같습니다.. 폰트는 rem으로 하고 나머지는 px로 하려했는데 하다보니 엉망이 되었습니다ㅠㅠ 일관성 있게 통일하겠습니다!

2023-12-15 06:45 UTC, yoojungChoii commented on css/index-style.css
> +  display: inline-block;
버튼을 만들 때 inline-block을 사용하니까 버튼영역의 크기를 지정하기가 좋아서 사용해보았습니다.....

2023-12-15 06:46 UTC, yoojungChoii commented on css/index-style.css
> +  Height: 3.4rem;
넵 알겠습니다!

2023-12-15 06:49 UTC, yoojungChoii commented on css/index-style.css
> +  -webkit-background-clip: text;
그라데이션을 배경에 주지 않고 글씨에 주기 위해 구글링해서 사용했습니다. 크롬에 적용시킬 때 필요하다고 해서 붙여보았습니다...

2023-12-15 06:54 UTC, yoojungChoii commented on index.html
> +      <section class= "section-left">
네 알겠습니다! 전체 컨텐츠를 article로 묶고 넣으라는 말씀은, section-left와 section-right를 따로 클래스를 만들어 넣고, 그냥 section으로 한번 크게 묶으라는 말씀이신건가요?

2023-12-15 06:54 UTC, yoojungChoii commented on signin.html
> +<html lang="kor">
앗 첨부해주신 사이트 읽어보았습니다! ko로 전부 바꾸겠습니다. 감사합니다.

2023-12-15 06:55 UTC, yoojungChoii commented on signin.html
> +        <img src="img/kakao.png">
또 빼먹었네요.. 다음 pr 때는 꼭 말씀 전에 챙기겠습니다!

2023-12-16 08:38 UTC, yoojungChoii commented on index.html
> +
추가했습니다!

2023-12-16 08:51 UTC, yoojungChoii commented on signin.html
> +      </div>
넵! 조언 감사합니다. 간단하게 바꿔보려 했는데 레이아웃이 꼬여서ㅜㅜ  이번주차 과제를 우선 끝낸 후 수정해보겠습니다.>!

2023-12-17 12:50 UTC, goldfrosch commented on css/index-style.css
> +    font-size: 62.5%;
아뇨 진짜 이유 여쭤봤었습니다. 다만 font-size의 경우 %보다는 vw라는 화면 너비 비율로 하는 것이 더 좋다는 개인적인 의견이 있습니다. 어떤게 더 좋을지는 차차 고민해보죠...!

2023-12-17 12:51 UTC, goldfrosch commented on css/index-style.css
> +  display: inline-block;
나중에 inline-block을 썼을 때 어떤 효과가 있어서 썻는지 조사해보는 것을 추천드립니다 :)

2023-12-17 12:55 UTC, goldfrosch commented on css/index-style.css
> +  -webkit-background-clip: text;
webkit은 크로스 브라우징을 대비하기 위함입니다. 크롬, 사파리에 적용되지 않는 특정 css를 도입하기 위해 사용하는 거죠...! (물론 이외에도 이유는 좀 있습니다)
추후에 조금 조사해보는 것을 권장드립니다!

2023-12-17 12:55 UTC, goldfrosch commented on index.html
> +      <section class= "section-left">
네 맞습니다~

2023-12-21 13:52 UTC, yoojungChoii commented on css/index-style.css
> +    font-size: 62.5%;
네! vw가 뭔지 찾아보겠습니다. 감사합니다!

2023-12-21 14:17 UTC, yoojungChoii commented on css/index-style.css
> +  display: inline-block;
네 조사해보겠습니다!

2023-12-23 01:57 UTC, merged