[백진영] Week3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #70
Opened 2023-12-09 19:25 UTC by jinyoung1018

## 요구사항

### 기본

- [x] 피그마 디자인에 맞게 랜딩, 로그인, 회원가입 페이지 반응형 디자인을 만들어 주세요.
- [x] Github에 위클리 미션 PR을 만들어 주세요.
- [x] React와 같은 UI 라이브러리를 사용하지 않고 진행합니다.

### 심화

- [ ] 팀원의 위클리 미션 PR에 코드 리뷰를 남겨 주세요.
- [ ] 랜딩 페이지, 제품 소개 영역의 mobile 사이즈에서만 제목, 이미지, 설명 순서대로 배치해 주세요.

## 주요 변경사항

- 폰트사이즈 단위 rem으로 변경

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-10 05:51 UTC, mingzzi96 commented on css/signinStyle.css
>  }
<img width="470" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/d0c9e38f-7267-405e-96aa-245e99d9c0b8">

2023-12-10 12:03 UTC, Jnnsu commented on index.html
br태그 없이 줄바꿈하게 하시고 footer 레이아웃을 grid로.. 고생하셨어요😁

2023-12-10 13:07 UTC, shkim901112 commented on css/style.css
> +.footer_item {
flex에서 grid로 바꾸셨군요! 어려운 작업이실텐데 수고하셨어요 😀

2023-12-10 13:27 UTC, whtjdrud commented on css/signupStyle.css
> +    }
width와 max-width가 같으면 ,로 묶어도 괜찮을것같아요!
물론 추후에 여러 변경될 가능성이 있으니 나눠두는것도 괜찮을것 같긴합니다.
취향차이일것같아요

2023-12-10 13:28 UTC, mingzzi96 commented on css/signupStyle.css
> +    }
<img width="150" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/e244dd62-eb91-477c-939d-396b53da5c5f">

2023-12-11 12:16 UTC, wonsss reviewed
아래와 같은 요구사항이 아직 적용되지 않은 것 같아요 😄 https://kimbiyam.me/posts/front-end/meta-tags   링크 참고해서 적용해보시면 좋을 것 같아요 
<img width="979" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/8ffddd19-96ee-4552-9a37-5c0a1e58c3c1">

2023-12-11 13:32 UTC, wonsss requested changes
수고하셨어요! 진영님 😄  미디어쿼리, flex, grid 모두 골고루 잘 활용하여 구현해주셨네요.
폰트사이즈에 rem을 적용하며 고민해주신 것 같아서 좋았습니다. 
다만, 디자인 요구사항과 달리 실제 계산된 폰트 사이즈가 상이한 부분이 있어서 이 부분 확인 부탁드릴게요. 
그리고 시간 되시면, 심화 요구사항도 한번 해보시면 좋을 것 같습니다 🚀 
리뷰 반영 완료하시면, 다시 말씀 부탁드려요 👍

2023-12-11 13:32 UTC, wonsss commented on css/signinStyle.css
>  body {
미디어 쿼리를 잘 적용해주셨어요. 👍 
그런데 크롬 개발자도구 디바이스 에뮬레이터에서 모바일 디바이스로서 반응형 화면을 확인해보면, 이와 같이 내부 요소가 화면 너비를 벗어나는 이슈가 있습니다. 

https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0b72bc1b-ae32-4706-baca-3000635125ed


이는 `box-sizing: border-box` CSS 속성이 적용되지 않은 곳들에서 박스가 화면 너비보다 커지면서 발생하는 것 같습니다.  다음과 같이 모든 요소에  box-sizing: border-box; 을 적용하면 해결될 것으로 보입니다. 이렇게 하는 이유는 인간의 인지상 더 이해하기 쉽기 때문입니다.
```
* {
    box-sizing: border-box;
}
```
이번 기회에 box-sizing에 대해서 조금 더 살펴보시면 좋겠습니다.

> box-sizing은 박스의 크기를 화면에 표시하는 방식을 변경하는 속성입니다. width와 height는 엘리먼트의 컨텐츠의 크기를 지정합니다. 따라서 테두리가 있는 경우에는 테두리의 두께로 인해서 원하는 크기를 찾기가 어렵습니다. box-sizing 속성을 border-box로 지정하면  테두리를 포함한 크기를 지정할 수 있기 때문에 예측하기가 더 쉽습니다. 최근엔 모든 엘리먼트에 이 값을 지정하는 경우가 늘고 있습니다. 
https://opentutorials.org/course/2418/13405

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +        font-size: 1.8rem;
모바일에서는 해당 버튼의 폰트 사이즈가 9px로 표시되고 있습니다. 피그마 디자인 요구사항에서는 14px로 요구되고 있으므로, 확인이 필요할 것 같습니다. 
1.8rem이 9px로 계산되고 있다는 것은 이 부분에서 1rem은 5px로 기준이 잡혀 있다는 의미입니다. 
이 버튼 말고도 다른 요소들에서도 모바일에서 전체적으로 디자인보다 너무 작은 폰트 사이즈가 표시되고 있습니다. 그 이유는 1rem이 5px이 되었기 때문입니다. 1rem을 5px이 되도록 하신 이유가 궁금하고, 이 부분 해결해주시면 좋을 것 같아요.

<img width="1390" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/5d54d4e9-b1b5-490b-8398-1208eca9f97b">

2023-12-11 13:32 UTC, wonsss commented on css/signinStyle.css
> +        font-size: 31.25%;
모바일에서는 root font-size를 5px(=16px*31.25%)로 줄인 이유가 있으신가요?

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +    font-size: 1.6rem;
모바일에서 글자 크기가 8px로 계산되며 너무 작습니다.
<img width="708" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/41e5e7e3-bb9b-412e-98bc-ce0b01f82271">

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +    .content {
심화 요구사항 중, 모바일에서는 "제목->이미지->설명" 순서로 쌓이도록 변경하라는 사항이 있습니다.[ flex 아이템 순서 변경하는 방법](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items)을 사용하여 시도해보시면 어떨까요?

<img width="423" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/fbdf7f9e-e405-46fe-8853-891d0c75e9b0">
<img width="920" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/2a431650-44c0-41a9-9a3d-7c45d992a6ca">

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +        justify-content: space-between;
103번째 줄에 있는 코드와 중복으로 보입니다. 😄 
같은 코드를 반복할 필요는 없으니 확인 후 가능하면 제거하셔도 될 것 같아요.

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +.footer_item {
grid를 잘 사용해보셨네요 👍

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +        align-items: space-between;
align-items에는 space-between 속성이 아마 없을 거예요. 확인 부탁드려요. 
https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

2023-12-11 13:32 UTC, wonsss commented on css/style.css
> +    footer {
모바일에서 footer 내 좌우 요소의 여백 및 사이즈 등이 디자인 요구사항과 상이한 부분이 있는 것 같아요. 확인 부탁드려요 😄 
<img width="1235" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/af8bc6a1-c817-441b-ae04-bdb53a18bebb">
<img width="605" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/d69130f1-5099-4335-95e6-352a4c674945">

2023-12-11 13:32 UTC, wonsss commented on css/signupStyle.css
> +    font-size: 1.4rem;
모바일에서 폰트 사이즈 확인 부탁드려요.
<img width="656" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/973ea117-9fab-4d9c-b5bc-9892c4a59fa6">

2023-12-11 13:32 UTC, wonsss commented on css/signinStyle.css
> +    font-size: 1.4rem;
모바일에서 폰트 사이즈 확인 부탁드려요.

2023-12-11 13:33 UTC, wonsss commented
npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 
패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다. 

https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고
`npm init` 명령어 실행한 후 커밋해주세요!. 👍

2023-12-11 13:34 UTC, wonsss commented
현재와 같은 폴더 구조를 정하신 이유도 혹시 알려주실 수 있으실까요?  

pages 하위에 index 외 다른 모든 html을 모으셨던데, 이로 인해 url이 `/pages/signup` 과 같이 pages 가 앞에 더 붙게 되었습니다.  
url도 적절한 의미를 지닌 위계가 있도록 만드는 것이 좋습니다. 그런데 pages는 의미가 딱히 없는 것 같습니다.  
현재로서는 폴더 구조가 간단하므로 html들을 root 폴더에 모두 빼도 좋을 것 같습니다.  
또는 적절한 의미의 폴더로 묶어주는 것도 가능합니다.  
정답은 없어요. 😄 한번 생각해보시면 좋을 것 같아 말씀드려요.  
비슷한 고민을 한 질문이 스택오버플로우에도 있었네요.  
[https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly](https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly)

2023-12-11 16:10 UTC, wonsss commented
태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.

그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.

이런 부분도 생각해보시면 좋을 것 같아서 참고차 말씀드려요. 😄

2023-12-12 17:01 UTC, jinyoung1018 commented
> 아래와 같은 요구사항이 아직 적용되지 않은 것 같아요 😄 https://kimbiyam.me/posts/front-end/meta-tags 링크 참고해서 적용해보시면 좋을 것 같아요 <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/59413128/289531729-8ffddd19-96ee-4552-9a37-5c0a1e58c3c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDA1ODMsIm5iZiI6MTcwMjQwMDI4MywicGF0aCI6Ii81OTQxMzEyOC8yODk1MzE3MjktOGZmZGRkMTktOTZlZS00NTUyLTlhMzctNWMwYTFlNThjM2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE2NTgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OGIxYzJjZDNmZjY1ZWJiNjAxNmNiNDEwYzIxOGRiODRhMjA3ZDJiMDRhOGU3ODMwMzdhNTc3MTk4OTQxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BKabPyTJIBOiToCisI4j2pQ5SpqWiN-IzMasTz8RbfY">

0d592c591e1ae181f2e18a04ed5b7567b804d511 9b9f705d0d1e6b98792eb844f60b26d84373e9ec meta tag추가하였습니다! 그런데 이미지가 제대로 뜨지않는데 왜그런걸까요??ㅠㅠ

2023-12-12 17:03 UTC, jinyoung1018 commented on css/signinStyle.css
>  body {
c87910ee4e1412782321c8017f6228a3bc85527d 알려주신 자료 잘 읽어보고 수정 하였습니다!

2023-12-12 17:04 UTC, jinyoung1018 commented on css/style.css
> +        font-size: 1.8rem;
9fc2ca399d534e97811d0961cd53f86d5cc94c0c 모바일 화면 폰트사이즈 전부 다시 설정하였습니다!

2023-12-12 17:06 UTC, jinyoung1018 commented on css/signinStyle.css
> +        font-size: 31.25%;
9fc2ca399d534e97811d0961cd53f86d5cc94c0c 화면이 모바일 사이즈로 줄어들었을 때 폰트사이즈가 너무 커서 전체적인 루트 폰트사이즈를 줄여야한다고 생각했는데 그게 아니군요!! 모두 다시 설정하였습니다!

2023-12-12 17:06 UTC, jinyoung1018 commented on css/style.css
> +    font-size: 1.6rem;
9fc2ca399d534e97811d0961cd53f86d5cc94c0c 폰트사이즈 수정하였습니다!

2023-12-12 17:11 UTC, jinyoung1018 commented on css/style.css
> +    .content {
76bc8f2659879bdd49f749af5b70629803c0b052 순서 변경하려고 order값을 적용해보았는데 아래 사진에 있는 코드처럼 텍스트 두개가 하나의 div로 묶여있어서 적용이 안되는것같습니다ㅠㅠ div를 없애면 큰 화면일 때 텍스트가 가로로 배치되는데, 그럼 grid로 바꾸는 방법 말고 다른 방법이 있을까요??
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/71465981/be5173fb-b7ff-4c04-8435-8f31a465b448)

2023-12-12 17:12 UTC, jinyoung1018 commented on css/style.css
> +        justify-content: space-between;
1e5b905840e50a29fe1087733b01c9e399b1db34 확인해보고 제거하였습니다!

2023-12-12 17:13 UTC, jinyoung1018 commented on css/style.css
> +        align-items: space-between;
40402fa7e735c68eee8a997c3a1786625a3f0117 수정하고 개념 한번 더 익혔습니다!

2023-12-12 17:13 UTC, jinyoung1018 commented on css/style.css
> +    footer {
c4c30a9326e8378bfcef1d9fc89c26d6fc725639 패딩값 수정하였습니다!

2023-12-12 17:14 UTC, jinyoung1018 commented on css/signupStyle.css
> +    font-size: 1.4rem;
9e98fa18fb5d965c6330f69057fe5cbb6e49100d 수정완료하였습니다!

2023-12-12 17:15 UTC, jinyoung1018 commented on css/signinStyle.css
> +    font-size: 1.4rem;
9e98fa18fb5d965c6330f69057fe5cbb6e49100d 수정하였습니다!

2023-12-12 17:16 UTC, jinyoung1018 commented
> npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다.
> 
> https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고 `npm init` 명령어 실행한 후 커밋해주세요!. 👍

f6c72f4d11de16f79e17e1ba6c36ad58aeff4205 관련된 개념 읽어보고 설정해보았습니다! 이렇게 하는게 맞을까용??

2023-12-12 17:19 UTC, jinyoung1018 commented
> 현재와 같은 폴더 구조를 정하신 이유도 혹시 알려주실 수 있으실까요?
> 
> pages 하위에 index 외 다른 모든 html을 모으셨던데, 이로 인해 url이 `/pages/signup` 과 같이 pages 가 앞에 더 붙게 되었습니다. url도 적절한 의미를 지닌 위계가 있도록 만드는 것이 좋습니다. 그런데 pages는 의미가 딱히 없는 것 같습니다. 현재로서는 폴더 구조가 간단하므로 html들을 root 폴더에 모두 빼도 좋을 것 같습니다. 또는 적절한 의미의 폴더로 묶어주는 것도 가능합니다. 정답은 없어요. 😄 한번 생각해보시면 좋을 것 같아 말씀드려요. 비슷한 고민을 한 질문이 스택오버플로우에도 있었네요. https://stackoverflow.com/questions/30970389/how-to-structure-my-html-files-properly

4f5522611f1732371ac00fd1765b89a6b9a8394f 단순하게 html끼리 같은 파일에 정리해둬야겠다고 생각한 것 같습니다! 원석님 말씀대로 현재는 폴더 구조가 간단해서 모두 root폴더에 두는게 맞는 것 같아서 그렇게 수정하였습니다!

2023-12-13 09:49 UTC, wonsss commented on css/signinStyle.css
>  body {
감사합니다!

2023-12-13 09:50 UTC, wonsss commented on css/signinStyle.css
> +        font-size: 31.25%;
진영님 방법이 틀렸다는 것은 아닙니다. 의도가 있고 상황에 적절하면 괜찮아요!

2023-12-13 09:55 UTC, wonsss commented on css/style.css
> +    .content {
grid로도 가능하고, flex를 유지하면서도 가능합니다.

```
<li> // flex-box
  <h2/>
  <p/>
  <img/>
</li>
```
이런 태그 구조에서 PC, TABLET, MOBLIE 별 flex box 내부 속성을 변경하면서 구현할 수 있을 것 같아요. 
PC에서는  "flex-flow: column wrap;"을 사용할 수도 있을 것 같아요.
```
h2   
            img
p     
```
그리고 모바일에서는 flex-direction column으로 하고
`:nth-child(2) { order: 3; }` 처럼 flex 아이템의 order를 변경함으로써 수직으로 쌓이면서 내부 아이템의 순서를 변경할 수도 있겠네요!

화이팅!

2023-12-13 09:57 UTC, wonsss commented
> https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/0d592c591e1ae181f2e18a04ed5b7567b804d511 https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/9b9f705d0d1e6b98792eb844f60b26d84373e9ec meta tag추가하였습니다! 그런데 이미지가 제대로 뜨지않는데 왜그런걸까요??ㅠㅠ

```
<meta property="og:image" content="/images/sec1_img.png" />
```

경로 때문에 그런 것 같네요. 
상대경로로서 `.`을 붙여서 "./images/sec1_img.png" 처럼 해보시겠어요?

2023-12-13 09:59 UTC, wonsss commented
> https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/f6c72f4d11de16f79e17e1ba6c36ad58aeff4205 관련된 개념 읽어보고 설정해보았습니다! 이렇게 하는게 맞을까용??

node_modules 폴더, package.json, package.lock.json 다 제거한 후, `npm init` 해주세요. ㅎㅎ
프로젝트 시작 시에 해야 하는 건데, 이미 노드모듈 설치된 이후에 하다보니까 불필요한 라이브러리가 dependencies에 다 포함되었네요.

2023-12-13 11:27 UTC, wonsss approved these changes
진영님~! 3주차 미션 리뷰 반영도 꼼꼼히 잘 해주셔서 감사해요.
npm init 이랑 flex 이용한 모바일 레이아웃만 추가로 수정해주시면 될 것 같아요. 
이 부분은 다음 4주차 미션 PR에 커밋으로 포함되어도 괜찮을 것 같아요.
우선 다음 4주차 미션 잘 시작하실 수 있도록 어프로브하고 머지할게요! 화이팅

2023-12-13 11:27 UTC, merged