[박준수] Week3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #72
Opened 2023-12-10 03:22 UTC by Jun-12

## 요구사항

### 기본

- [x] [기본] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용했나요?
- PC: 1200px 이상
- Tablet: 768px 이상 ~ 1199px 이하
- Mobile: 375px 이상 ~ 767px 이하
- 375px 미만 사이즈의 디자인은 고려하지 않습니다
- [x] [랜딩 페이지] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 Linkbrary 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정했나요?
- [x] [랜딩 페이지] 미리보기에서 제목은 “Linkbrary”, 설명은 “세상의 모든 정보를 쉽게 저장하고 관리해 보세요”로 설정했나요?
- [x] [랜딩 페이지] 주소와 이미지는 자유롭게 설정했나요?
- [x] [랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 변하지 않게 고정값으로 유지하되 좌우 여백이 줄어드나요?
- [x] [랜딩 페이지] Tablet 사이즈에서 최소 좌우 여백은 “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px을 유지하고“Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지나요? 
- [x] [랜딩 페이지] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용했나요?
- [x] [랜딩 페이지] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차나요? (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [x] [랜딩 페이지] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지나요?
- [x] [로그인, 회원가입 페이지] Tablet 사이즈에서 디자인은 PC사이즈와 동일한가요?
- [x] [로그인, 회원가입 페이지] Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지하나요?
- [x] [로그인, 회원가입 페이지] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않나요?

### 심화

- [ ] [심화] 팀원의 위클리 미션 PR에 코드 리뷰를 남겼나요?
- [x] [심화] 랜딩 페이지 Mobile 사이즈에서 제품 소개 영역의 순서를 제목, 설명, 이미지 => 제목, 이미지, 설명 순서로 변경했나요?

## 주요 변경사항

- 태블릿, 모바일 반응형 추가
- 불필요한 rem을 px로 변경 : 여백과 같이 레이아웃에 영향을 주는 부분은 px로 값을 고정시켜 주었습니다.
- 메타 데이터 추가

## 스크린샷
- 이미지 대신 배포된 사이트 주소로 대체하겠습니다!
- https://part1-week3-jspp.netlify.app/

## 멘토에게

- 저번 주차 브랜치가 머지되기 전에 미리 브랜치를 만들고 후에 conflict를 해결하려고 임시로 커밋을 해두고 푸시를 했었는데, 머지가 되어버려 초반 작업내용의 커밋을 수정할 수가 없었습니다.. 항상 커밋을 세부적으로 나눠서 하고 push는 신중하게 했어야 했는데 제 불찰입니다.😂  변경 내용 보시기 불편하게 된 것 같아 죄송합니다.

- 반응형을 추가하면서 가장 많이 고민했던 것은 2가지 였습니다

  - 어떤 단위를 어디에 사용할까
  
    화면크기 변경, 폰트 사이즈 변경 등을 염두해 두어야 하기에 접근성을 높이기 위해 어떤 값을 절대단위와 상대단위로 사용할지에 대해 고민 할 수 있었습니다.
 
  - Flex와 Grid 중 뭐가 더 레이아웃을 표현하기 좋을까
  
    레이아웃을 표현하기 위해 Flex와 Grid 중에 어떤 것이 나을지 저울질을 많이 했던 것 같습니다. 사실 코드잇에서 배운것만 보고 생각했을 때는 Flex가 Grid보다 반응형에 대처하기 용이할 것이라고 생각했었습니다. 하지만 이번에 구글링하면서 Grid도 Flex와 같이 정렬을 사용할 수 있다는 사실도 처음 배웠고, 정렬이 아니더라도 ``minmax()``나 ``calc()`` 등을 사용하면 반응형에 대처할 수 있다는 점도 배웠습니다.

2023-12-10 05:54 UTC, mingzzi96 commented on assets/styles/signin.css
<img width="491" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/ce32a2ba-f13b-4b19-a62a-2214dcc9b4f5">
Rem 수정하시느라 수고하셨습니다....

2023-12-10 07:08 UTC, Jun-12 commented on assets/styles/signin.css
흑흑 감사합니다..😂

2023-12-10 13:16 UTC, shkim901112 commented on assets/styles/style.css
>    display: grid;
그리드로 만드시느라 수고하셨어요 flex로 작성한 코드와는 다른점이 보이네요. 저도 grid에 대해서도 좀 더 숙지해야될거같습니다 😅

2023-12-10 13:23 UTC, whtjdrud commented on assets/styles/style.css
> +  column-gap: max(0, 157px);
column-gap 에 max(0,157)을 이용하신 이유가 있을까요???
max 함수의 경우 2개의 값중 가장 큰 값을 출력하면 157px  고정이 아닐까 해서요.

2023-12-10 13:25 UTC, mingzzi96 commented on assets/styles/style.css
> +  column-gap: max(0, 157px);
<img width="250" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/01b856b0-9776-45cf-ac63-e7f15f5b86bb">

2023-12-10 13:33 UTC, Jun-12 commented on assets/styles/style.css
>    display: grid;
감사합니다ㅎㅎ 성훈님도 grid 잘 하실 수 있으실거예요!

2023-12-10 15:53 UTC, Jun-12 commented on assets/styles/style.css
> +  column-gap: max(0, 157px);
좋은 지적 감사합니다! 해당부분은 space-between을 작성하기 전에 여러가지 시도해본 부분인데, 삭제하지 않은 작동되지 않는 코드네요.. 수정하도록 하겠습니다 😲

2023-12-10 15:53 UTC, Jun-12 commented on assets/styles/style.css
> +  column-gap: max(0, 157px);
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/0d77b99c6a212dc4183f7c80c34c1d22666cafa4](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/0d77b99c6a212dc4183f7c80c34c1d22666cafa4)
해당부분 수정했습니다!

2023-12-11 14:20 UTC, wonsss requested changes
준수님 😄 깔끔하게 잘 구현해주셨네요. 
미디어쿼리, flex, grid 모두 골고루 잘 활용해주신 것 같아요.

리뷰 드린 부분 확인해주시고, 리뷰 반영 완료하시면, 다시 말씀 부탁드려요 👍

2023-12-11 14:20 UTC, wonsss commented on index.html
> +    <meta property="og:image" content="landing-images/meta.jpg" />
오픈그래프 메타 태그를 잘 적용해주셨네요 👍

2023-12-11 14:20 UTC, wonsss commented on index.html
> +    <meta name="twitter:image" content="landing-images/meta.jpg" />
트위터 메타 태그를 잘 적용해주셨네요 👍

2023-12-11 14:20 UTC, wonsss commented on index.html
> +            src="langding-icons/linkbrary-icon.svg"
landing-icons와 landing-images 디렉터리를 루트 내에 만드셨네요.
이처럼 각각의 목적과 역할에 맞게 디렉터리를 묶어주시는 것 좋아요 👍

2023-12-11 14:20 UTC, wonsss commented on sign/common.css
> +@media (min-width: 375px) and (max-width: 767px) {
미디어쿼리를 잘 적용해주셨네요

2023-12-11 14:20 UTC, wonsss commented on style.css
> +  padding: 32px 104px 64px;
px이 필요한 곳에는 rem 대신 px로 변경하는 작업을 다 해주셨군요. 고생하셨어요 👍

2023-12-11 14:20 UTC, wonsss commented on reset.css
>  }
밑에 
```
@media (min-width: 375px) and (max-width: 767px) {
  html {
    font-size: 31.25%;
  }
}
```
에서  모바일일 때  font-size: 31.25%; 를 적용한 이유가 궁금합니다.
모바일에서는 루트 폰트 사이즈가 5px로 줄어들어야 하는 이유가 있으셨나요?

2023-12-11 14:20 UTC, wonsss commented on sign/signup.html
> +            src="eye-off.svg"
eye-off.svg, eye-on.svg, social-google.png, social-kakao.png 와 같은 이미지 파일들이 html, css 파일들과 함께 같은 위계의 폴더에 있으면, 나중에 html, css 수정하려고 하실 때 약간 힘들지 않을까요?
이러한 asset들은 별도의 폴더로 빼는 게 나을 것 같아 보입니다.

2023-12-11 14:20 UTC, wonsss commented on reset.css
reset.css가 다른 css 파일들에서 공유하여 사용하는 파일이라면, shared나 styles 같은 폴더에 넣어서 해당 파일의 성격을 암시해주는 것도 좋을 것 같아요.

2023-12-11 14:20 UTC, wonsss commented on style.css
>      max-width: 99.2rem;
여기서 rem을 사용하신 이유가 궁금합니다. ㅎㅎ

2023-12-11 14:20 UTC, wonsss commented on style.css
> +    / minmax(auto, 291px) minmax(auto, 550px);
grid template을 잘 적용해주셨네요!
minmax도 좋습니다 👍

2023-12-11 14:20 UTC, wonsss commented on index.html
>          </article>
디자인 요구사항에 명시적으로 적혀있진 않는데, 해당 article 좌우 요소의 가운데에 여백이 있는 게 나을 것 같아요.
디자이너와 협업 시 알잘딱깔센도 필요한 것 같아요.ㅎㅎㅎ
잘 모르겠으면 정확하게 문의하는 커뮤니케이션도 중요하구요.

<img width="798" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/8df6f88f-eaba-4dd1-9599-11ec2cace978">

<img width="729" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/ba3f3f91-ae75-4a86-81e3-bdb0c23a3e0d">

2023-12-11 14:20 UTC, wonsss commented on .gitignore
>  node_modules/
EOL 확인 부탁드려요

2023-12-11 14:20 UTC, wonsss commented on index.html
>      <footer>
모바일에서 footer 쪽 레이아웃이 디자인 요구사항과 다른 것 같아요. 확인 부탁드려요 🙏 
<img width="945" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/75a26a80-61f5-4d1e-a983-77933fbaeee0">
<img width="658" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/dc7789c5-33df-4a1e-b61b-1632898cfe9d">

2023-12-11 14:20 UTC, wonsss commented on style.css
>      grid-template:
코드체인지에 잡히지 않아서 밑에 부분을 선택했는데, 296~302줄에서 아래와 같은 코드를
```
  article:nth-of-type(odd),
  article:nth-of-type(even) {
    grid-template:
      'title title'
      'image image'
      'description description';
  }
  ```

이와 같이 간단히 바꿔도 되지 않을까요?
  
  ```
  article:nth-of-type(odd),
  article:nth-of-type(even) {
    grid-template:
      'title'
      'image'
      'description';
  }
  ```

2023-12-11 14:21 UTC, wonsss commented
npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 
패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다. 

https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고
`npm init` 명령어 실행한 후 커밋해주세요!. 👍

2023-12-11 16:11 UTC, wonsss commented
태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.

그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.

이런 부분도 생각해보시면 좋을 것 같아서 참고차 말씀드려요. 😄

2023-12-12 01:44 UTC, Jun-12 commented on index.html
> +    <meta property="og:image" content="landing-images/meta.jpg" />
감사합니다! 처음 적용해봤는데 잘 돼서 다행입니다ㅎㅎ

2023-12-12 01:50 UTC, Jun-12 commented on index.html
> +            src="langding-icons/linkbrary-icon.svg"
원래는 파일의 종류에 따라  pages, assets, styles로 나눠서 보관했었는데, 그렇게 하니 간단한 프로젝트인거에 비해 폴더구조가 깊어지기도 하고 여러 폴더를 자주 왔다갔다 해야돼서 변경해보았습니다! 확실히 변경한 후에 좀 더 관리하기도, 보기도 편해진 것 같습니다!

2023-12-12 01:51 UTC, Jun-12 commented on sign/common.css
> +@media (min-width: 375px) and (max-width: 767px) {
감사합니다 😊

2023-12-12 01:54 UTC, Jun-12 commented on reset.css
>  }
피그마를 확인해보니 모바일일 때 전체적으로 font-size가 절반으로 줄어들었기 때문에 루트 font-size를 절반으로 줄여주면 변경이 용이할 거라고 생각했습니다! 하지만 여백값을 px로 바꾸기 전이었기 때문에 rem을 모두 5px에 맞춰서 조정해야만 했습니다..

2023-12-12 02:24 UTC, Jun-12 commented on sign/signup.html
> +            src="eye-off.svg"
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/c0d277cd31e4eaac945bf085dbda65aac5e2a6ed](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/c0d277cd31e4eaac945bf085dbda65aac5e2a6ed) 해당부분 수정 완료하였습니다!

2023-12-12 02:30 UTC, Jun-12 commented on sign/signup.html
> +            src="eye-off.svg"
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/c0d277cd31e4eaac945bf085dbda65aac5e2a6ed](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/c0d277cd31e4eaac945bf085dbda65aac5e2a6ed) 해당부분 수정 완료했습니다!

2023-12-12 02:32 UTC, Jun-12 commented on reset.css
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/c0d277cd31e4eaac945bf085dbda65aac5e2a6ed](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/c0d277cd31e4eaac945bf085dbda65aac5e2a6ed) 수정 완료했습니다. 
수정하면서 궁금한 점이 생겼는데, 그렇다면 특정 폴더 내에서만 공유로 사용하는 css 파일이 있다면 그 css 파일도 폴더를 따로 만들어두는 것이 좋을까요..!

2023-12-12 03:08 UTC, Jun-12 commented on style.css
>      max-width: 99.2rem;
사실 이 부분이 아직 헷갈리는 부분입니다. 여백은 px로 고정시켜 두었지만, width나 height의 경우 %를 사용하는 경우를 제외하고 어떤 단위를 써야할지 고민이 있었습니다. 이 부분을 rem으로 한 이유는 접근성을 챙기기 위해 width를 font-size에 비례하게 맞추겠다고 한다면, max-width 또한 같은 비율로 늘어나는 것이 맞을 것이라고 생각했습니다. 

29cm 홈페이지를 보니 브라우저 설정에서 폰트크기를 변경하는 것에는 변화가 없고, 페이지 확대/축소에 따라 모습이 변하더라구요. 각각 설정했을 때 어떤 값들이 변화되는지도 알아야 할 것 같고, 왜 이렇게 되어있는지도 생각을 해보겠습니다..🧐

2023-12-12 03:14 UTC, Jun-12 commented on style.css
> +    / minmax(auto, 291px) minmax(auto, 550px);
grid template과 minmax 처음 사용해봤는데 아주 직관적이고 유용한 것 같습니다!ㅎㅎ

2023-12-12 07:28 UTC, Jun-12 commented on index.html
>          </article>
알잘딱깔센..!! 제가 참 좋아하는 말인데 몸소 실천하기는 쉽지 않네요ㅠ
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/6f4eb7172422a205bde241cb6454f91bad48bdee](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/6f4eb7172422a205bde241cb6454f91bad48bdee) [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/a7ce55e5f050493074d6916358ee878f5073370c](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/a7ce55e5f050493074d6916358ee878f5073370c) 수정 완료했습니다!

<img width="822" alt="스크린샷 2023-12-12 오후 4 27 23" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/98401099/ff1a887f-0d41-40bb-9564-562a4138df95">

2023-12-12 07:29 UTC, Jun-12 commented on .gitignore
>  node_modules/
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/e953f4af702c9e97ed3fe7d11f5d8aca7c1612c6](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/e953f4af702c9e97ed3fe7d11f5d8aca7c1612c6) 수정완료했습니다..! 기본적인 실수를 했네요.😂

2023-12-12 07:31 UTC, Jun-12 commented on index.html
>      <footer>
footer-container에 grid와 flex를 동시에 주고있었네요. 해당부분 수정했습니다! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/57416161ac158cff022635c020708ac30cff7650](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/57416161ac158cff022635c020708ac30cff7650)

2023-12-12 07:32 UTC, Jun-12 commented on style.css
>      grid-template:
불필요한 칸을 만들어서 사용하고 있었네요!! 수정완료했습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/ccb4912f15b085549ce9532b5c9674f21080b753](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/72/commits/ccb4912f15b085549ce9532b5c9674f21080b753)

2023-12-12 12:12 UTC, wonsss commented on index.html
> +            src="langding-icons/linkbrary-icon.svg"
네! 이렇게 이것 저것 고민하면서 시도해보는 과정이 중요한 것 같아요.
고민을 많이 하시는 것 같아요. 훌륭하십니다! 👍

2023-12-12 12:14 UTC, wonsss commented on index.html
>          </article>
킹아 👍 
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/d82b8ee6-c91d-4e60-8482-55e9027a23b8)

2023-12-12 12:14 UTC, wonsss commented on index.html
>      <footer>
확인하였습니다!

2023-12-12 12:15 UTC, wonsss commented on style.css
>      grid-template:
넵! 간결한 게 좋은 것 같아요.

2023-12-12 12:16 UTC, wonsss approved these changes
준수님! 과제를 깔끔하게 잘 해주셨네요. 
리뷰 반영해주신 것도 코멘트를 잘 달아주셔서 편하게 잘 보았습니다.
이번 미션은 어프로브하고 머지할게요. 다음 미션에서 뵈어요! 👍

2023-12-12 12:16 UTC, merged

2023-12-12 12:19 UTC, Jun-12 commented
감사합니다!! 리뷰 정말 감사드리고 다음 미션때도 잘 부탁드리겠습니다.😀


> 태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.
>그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.

그리고 말씀하신 부분은 아직 완료하지 못했지만 빠르게 반영하도록 하겠습니다!! 태그에 스타일 준 부분은 변경하고 클래스 네이밍 더 신경써야겠네요.