[김성훈 Week3
codeit-bootcamp-frontend/3-Weekly-Mission pull request #75
Opened 2023-12-10 07:25 UTC by shkim901112

## 요구사항

### 기본

- [x]  [기본] 브라우저에 현재 보이는 화면의 영역(viewport) 너비를 기준으로 분기되는 반응형 디자인을 적용했나요?
- PC: 1200px 이상
- Tablet: 768px 이상 ~ 1199px 이하
- Mobile: 375px 이상 ~ 767px 이하
- 375px 미만 사이즈의 디자인은 고려하지 않습니다
- [x]  [랜딩 페이지] 페이스북, 카카오톡, 디스코드, 트위터 등 SNS에서 Linkbrary 랜딩 페이지(“/”) 공유 시 미리보기를 볼 수 있도록 랜딩 페이지 메타 태그를 설정했나요?
- [x]  [랜딩 페이지] 미리보기에서 제목은 “Linkbrary”, 설명은 “세상의 모든 정보를 쉽게 저장하고 관리해 보세요”로 설정했나요?
- [x]  [랜딩 페이지] 주소와 이미지는 자유롭게 설정했나요?
- [x]  [랜딩 페이지] Tablet 사이즈에서 화면의 너비가 1199px 이하로 작아질 때 “Linkbrary” 로고와 “로그인” 버튼 사이의 간격은 변하지 않게 고정값으로 유지하되 좌우 여백이 줄어드나요?
- [x]  [랜딩 페이지] Tablet 사이즈에서 최소 좌우 여백은 “Linkbrary” 로고의 왼쪽에 여백 32px, “로그인” 버튼 오른쪽 여백 32px을 유지하고“Linkbrary” 로고와 “로그인" 버튼의 간격이 가까워지나요?
- [x]  [랜딩 페이지] PC, Tablet 사이즈의 이미지 크기는 고정값을 사용했나요?
- [x]  [랜딩 페이지] Mobile 사이즈의 이미지는 좌우 여백 32px을 제외하고 이미지 영역이 꽉 차나요? (이때 가로가 커지는 비율에 맞춰 세로도 커져야 합니다.)
- [x]  [랜딩 페이지] Mobile 사이즈 너비가 커지면, “Privacy Policy”, “FAQ”, “codeit-2023”이 있는 영역과 SNS 아이콘들이 있는 영역의 간격이 커지나요?
- [x]  [로그인, 회원가입 페이지] Tablet 사이즈에서 디자인은 PC사이즈와 동일한가요?
- [x]  [로그인, 회원가입 페이지] Mobile 사이즈에서 좌우 여백 32px 제외하고 내부 요소들이 너비를 모두 차지하나요?
- [x]  [로그인, 회원가입 페이지] Mobile 사이즈에서 내부 요소들의 너비는 기기의 너비가 커지는 만큼 커지지만 400px을 넘지 않나요?

### 심화

- [ ]  [심화] 팀원의 위클리 미션 PR에 코드 리뷰를 남겼나요?
- [ ]  [심화] 랜딩 페이지 Mobile 사이즈

## 주요 변경사항

-미디어 쿼리 사용
-px사이즈 rem으로 변경

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/0b583987-3939-4f15-9d0e-7f50a3c743d8)

태블릿 랜딩페이지

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/eb487e8c-b40a-4b7d-bfe2-f0183070d1c6)

모바일 랜딩페이지

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/c4e69311-46f4-4bdc-a148-7010c7eee24e)

모바일 로그인페이지

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/70473ad1-1583-495a-a198-f69f32b3d422)

모바일 회원가입페이지

##홈페이지
https://gorgeous-pavlova-360632.netlify.app/

## 멘토에게

-기존에 있던 폴더들을 변경하고 새로 올리느라 폴더가 많이 변했습니다 😥

2023-12-10 11:59 UTC, mingzzi96 commented
<img width="425" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/9b34a623-6430-4b57-9e2f-2409ca0cb018">


68d8b4559cdf790e1094548bcde45a8fb9137fbf 폴더 구조 변경 빡셨겠는데용! (ง •̀_•́)ง

2023-12-10 12:06 UTC, Jun-12 commented on signup/signup.html
id를 전부 class로 바꾸셨군요!! 수고하셨어요 👏

2023-12-10 13:17 UTC, shkim901112 commented on signup/signup.html
뭣 모르고 썼었는데 다 수정했습니다 😂

2023-12-10 13:38 UTC, whtjdrud commented on signin/signin.html
>          <form>
해당 페이지는 기능상으로 로그인 페이지이기 때문에 
- 사용자가 아이디, 비밀번호 입력
- 로그인 버튼 클릭
- 로그인을 하는 프로세스 처리 

이렇게 동작하기 때문에 이메일 부분을 password와 같이 input box로 해주시면 좋을것 같아요!

2023-12-10 13:43 UTC, mingzzi96 commented on signin/signin.html
>          <form>
<img width="150" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/134386378/b5a241d3-b5bc-49a9-be9b-b2a58448d6b4">

2023-12-10 14:06 UTC, shkim901112 commented on signin/signin.html
>          <form>
반영했습니다 !

2023-12-11 15:57 UTC, wonsss requested changes
고생 많으셨습니다. 성훈님! 
폴더 구조, id를 class로 변경하는 등 많은 변화를 주시면서, 고민도 많이 하셨을 것 같아요. 
이렇게 고민을 하시면서 더 나은 코드가 되어 가는 것 같아요. 멋집니다! 
반응형이나 플렉스박스 등도 잘 숙지하게 되신 것 같아요.

남겨 드린 리뷰 확인해주시고, 다시 리뷰 받길 원하실 때 말씀 부탁드려요 😄

2023-12-11 15:57 UTC, wonsss commented on signup/signup.css
> +  font-size: 6.25%;
font-size를 6.25% 주신 이유가 궁금합니다!

2023-12-11 15:57 UTC, wonsss commented on signup/signup.css
> +  margin: 238rem 520rem 252rem 520rem;
margin이나 padding에 px 대신 rem을 넣으신 이유가 궁금해요.

2023-12-11 15:57 UTC, wonsss commented on main.css
> +  padding: 70rem 360rem 0rem 360rem;
좌우 패딩 때문에 PC 및 태블릿 반응형에서 h1 문구의 레이아웃이 깨지고 있어요. 
패딩 확인해주세요. 🙏 
<img width="1703" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/ca950903-c17c-4d44-be9a-840f7fc7d852">

2023-12-11 15:57 UTC, wonsss commented on index.html
> +  <footer>
footer 요소는 body 요소 안에 있어야 합니다

2023-12-11 15:57 UTC, wonsss commented on index.html
> +<html lang="ko">
index.html 파일 전체적으로 코드 포매팅이 되어 있지 않은 것 같아요.  아마 태그를 열었는데 닫지 않은 것들이 있어서, 저장 시 자동 포매팅에 에러가 발생하고 있는 것 같아요. 열고 닫지 않은 태그가 있진 않은지 확인 부탁드려요.

참고로 [Auto Close Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag) 같은 VS code 익스텐션을 사용하시면 HTML 태그 작성할 때 도움이 되실 것 같아요.

2023-12-11 15:57 UTC, wonsss commented on index.html
> +      </h1>
피그마 디자인 요구사항과 달리 해당 문구가 잘못 줄바꿈되고 있습니다. 

<img width="1030" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/0e99ec81-4a0d-4581-ad8f-e8379017d634">

<img width="1470" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/912849b5-e8e6-4899-a695-ab1a7c76a47b">

2023-12-11 15:57 UTC, wonsss commented on main.css
> +  }
이 이미지들에 대한 width를 모바일 반응형에서만 주도록 설정하셨네요.
이외의 경우(PC, 태블릿)에서는 이미지에 width를 설정되어 있지 않아서, 화면 너비를 넘는 경우가 생기고 있습니다. 
모든 경우에 대해 이미지 크기가 기본적으로 부모의 100%를 넘지 않도록 최소한 width:100% 정도는 적용해주셔야 할 것 같습니다. 😄 


https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/47384b44-82b7-474e-92e4-b5834eba488b

2023-12-11 15:57 UTC, wonsss commented on index.html
> +    <header>
여는 <body> 태그가 빠져있네요

2023-12-11 15:57 UTC, wonsss commented on signin/signin.css
> +}
EOL 확인해주세요

2023-12-11 15:57 UTC, wonsss commented on index.html
> +        </p>
디자인 요구사항과 달리 글 사이 여백이 큽니다.
이는 p 태그는 기본적으로 margin의 상하값에 간격이 들어가있기 때문입니다. 
따라서 [CSS Reset](https://meyerweb.com/eric/tools/css/reset/)을 적용하여 p 태그 등의 기본 margin 등을 제거하시는 게 좋습니다. 
또는 해당 부분 클래스에 margin: 0 이라고 명시적으로 적용해주셔야 할 것 같아요.

<img width="704" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/13b2744d-7ba9-4b76-9da7-c596149b086b">

<img width="1604" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/3352aa3a-7dc3-47be-a8e1-835e91b2f194">

2023-12-11 15:57 UTC, wonsss commented on index.html
> +        <p class="codeit">@codeit - 2023</p>
codeit 클래스의 p 요소는 absolute 포지션이라서 굳이 bottom-box2 클래스의 박스 하위에 있을 필요가 없을 것 같습니다. 이런 구조로 있어서 bottom 속성에 마이너스 값을 주고 계신데 구조적으로 좋진 않을 것 같아요. 
이 보다는 codeit 클래스의 p 요소를 bottom-box2와 형제 요소가 되도록 옮기고 left:30px, bottom: 0px 과 같은 값을 적용해주셔도 될 것 같습니다. 
그리고 부모 요소에는 absolute의 기준점이 될 수 있도록 position:relative를 적용해주시구요. 😄 

<img width="1490" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/731612c9-d252-436b-9686-b86d3a6cc2f6">

2023-12-11 15:57 UTC, wonsss commented on main.css
> +    display: flex;
flex에 이제 익숙해지신 것 같네요! 👍

2023-12-11 15:57 UTC, wonsss commented on index.html
> +    <meta property="og:image" content="../image/Library.jpg">
open graph 메타 태그를 잘 적용해주셨네요 👍 
트위터용 메타 태그도 검색해서 적용해보시면 어떨까요?

2023-12-11 15:57 UTC, wonsss commented on signin/signin.html
> +          <a href="../signup/signup.html"><span class="signup">회원가입하기</span></a>
signup 폴더 내에 해당 html 파일을 넣으셨군요! 그러면 signup.html 대신에 index.html으로 이름을 변경하신 것도 괜찮습니다.

`signup/index.html` 이렇게 되면, url 라우팅이 기존의 "https://gorgeous-pavlova-360632.netlify.app/signin/signin" 대신에 "https://gorgeous-pavlova-360632.netlify.app/signin" 만으로 해당 페이지에 이동할 수 있습니다. 

폴더에서 기본적으로 index.html 을 찾도록 되어 있기 때문에 이런 동작이 가능합니다. 

참고하실 수 있도록 관련 자료 링크 첨부해드립니다.
https://htmlandcssguidebook.com/html/file-structure/

<img width="899" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/6ecadac9-43a9-49b9-b0c1-8fc516b48a07">

2023-12-11 15:57 UTC, wonsss commented on signup/signup.html
> +      <div class="sign">
id를 class로 모두 변경하셨군요. 수고 많으셨습니다. 
참고로 VSCode에서 파일 내에서 어떤 코드를 모두 선택하려고 할 때, 
`Command + D`나  `Command + Shift + L` 의 단축키를 사용하실 수 있습니다.
예를 들어, 여기서는 id를 블록 처리하고 해당 단축키를 누르면 파일 내 모든 id가 선택되어 한번에 수정하실 수 있습니다.

2023-12-11 15:58 UTC, wonsss commented
npm은 Node Package Manager의 약자로 nodejs의 모듈 관리를 하기 위해 사용합니다. package.json은 npm을 통해 설치된 패키지 목록을 관리하고 프로젝트의 정보 및 기타 실행 스크립트를 작성하는 파일입니다. 
패키지를 설치하기 전에 프로젝트를 시작하시면서 `npm init` 명령어를 실행하여, 해당 프로젝트를 설명하는 name, version, description, author, keywords 등을 지정해야 합니다. 

https://heropy.blog/2018/02/18/node-js-npm/ 읽어보시고
`npm init` 명령어 실행한 후 커밋해주세요!. 👍

2023-12-11 16:11 UTC, wonsss commented
태그에 직접 스타일을 주는 방법은 지양하면 좋을 것 같습니다. 나중에 동일 태그를 사용하는 경우가 발생할 수 있어서 유지보수가 힘들어질 수 있어요. className을 선언하여 사용하는 것을 권장드려요.

그리고 className을 포함한 여러 변수명에서 숫자나 알파벳(a,b,c) 등을 넣지 않는 것이 좋습니다. 가독성을 떨어트리고, 나중에 유지보수가 힘들어질 수 있습니다.

이런 부분도 생각해보시면 좋을 것 같아서 참고차 말씀드려요. 😄

2023-12-12 00:25 UTC, shkim901112 commented on signup/signup.css
> +  font-size: 6.25%;
font-size를 6.25%로 바꾸면 rem사이즈를 px사이즈와 동일한 수치로 바꿀수 있어서 바꿨보았습니다😅

2023-12-12 00:25 UTC, shkim901112 commented on signup/signup.css
> +  margin: 238rem 520rem 252rem 520rem;
반응형 웹페이지를 만드려면 rem사이즈를 모두 사용해야 반응이 잘 되는줄 알고 px사이즈를 모두 rem으로 바꿨습니다😂

2023-12-12 00:38 UTC, shkim901112 commented on main.css
> +  padding: 70rem 360rem 0rem 360rem;
c05a0d1a3a725291fe3f053f63e79e0fd61bdee5

수정했습니다!

2023-12-12 00:38 UTC, shkim901112 commented on index.html
> +  <footer>
c05a0d1a3a725291fe3f053f63e79e0fd61bdee5

확인하고 위치 옮겼습니다 😅

2023-12-12 00:46 UTC, shkim901112 commented on index.html
> +<html lang="ko">
네 참고하겠습니다 😥

2023-12-12 03:13 UTC, shkim901112 commented on main.css
> +    display: flex;
감사합니다 😄

2023-12-12 03:13 UTC, shkim901112 commented on index.html
> +    <meta property="og:image" content="../image/Library.jpg">
d582535640959bae2bffd1de14afcecf48de475e

트위터용 메타태그도 추가했습니다 !

2023-12-12 03:14 UTC, shkim901112 commented on signin/signin.html
> +          <a href="../signup/signup.html"><span class="signup">회원가입하기</span></a>
d582535640959bae2bffd1de14afcecf48de475e

이런 구조도 있었군요 ! 확인후에 파일명도 수정해보았습니다 😄

2023-12-12 03:15 UTC, shkim901112 commented on signup/signup.html
> +      <div class="sign">
꿀팁 감사합니다 😀

2023-12-12 06:39 UTC, shkim901112 commented on index.html
> +        <p class="codeit">@codeit - 2023</p>
89ca1cddfc033bac425277ef52e3606539484bd3

원석님이 말씀하신대로  position 변경후 수정해보았더니 잘 자리 잡았습니다. 그런데 저렇게 변경하고 데스크탑사이즈로 다시보니 사이즈가 망가지는 현상이 발생하였습니다. 어떻게 고쳐볼까 고민하다가 여러시도는 해보았는데 제 생각으로는 도저히 옮길 방법이 생각나지 않아 bottom-box부분을 grid로 수정하였습니다. 그래서 모바일부분도 grid로 조금 더 수정하였습니다! 😥

2023-12-12 12:30 UTC, huniiiiii commented on index.html
> +      </h1>
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/c05a0d1a3a725291fe3f053f63e79e0fd61bdee5

넘치지 않게 수정했습니다 ! 위에 말씀하신 레이아웃이 깨지는 현상을 해결하니 줄바꿈현상도 없어졌습니다😀

2023-12-12 12:37 UTC, wonsss commented on signup/signup.css
> +  font-size: 6.25%;
그렇게 하면 더 직관적이어서 도움이 될 수도 있겠네요! 도전 좋습니다 😄 
아직 저는 현업에서 그렇게 하는 코드는 아직 보진 못해서, 쓰시면서 장단점을 알려주시면 더 좋을 것 같아요!

2023-12-12 12:39 UTC, wonsss commented on signup/signup.css
> +  margin: 238rem 520rem 252rem 520rem;
이전에 지민님 PR에 남겼던 답변인데 참고하시면 좋을 것 같습니다!
## font-size랑 padding, margin, width, heigth에 다 rem/em 을 넣어줘야하는걸까요?
이건 상황에 따라 다른 것 같아요. 상대적인 길이가 필요한 곳인지 판단하여 상대적 단위를 사용하시면 될 것 같습니다.

일반적으로 font-size에는 접근성을 위해 rem 같은 상대단위를 사용하는 것이 좋은 것 같습니다.
그러나 padding/margin/border 같은 경우 px을 사용하는 것이 더 낫다는 의견도 많습니다.
이렇게 하면, font-size가 증가하더라도, 여백이 증가하지 않을 것이기 때문입니다. 만약 여백도 함께 증가한다면 가독성을 해칠 수도 있기 때문입니다.

절대 단위인 px, 그리고 상대 단위인 em, rem (이외에도 많음) 등의 정의를 정확히 이해하시고, 기본적인 디자인 요구사항과 더 나아가서 확장성이나 접근성까지 고려하시어 유연하게 사용하시는 게 가장 좋을 것 같습니다.

참고해보면 좋을 링크
[웹 디자이너가 PX대신 REM을 사용해야 하는 이유 | 요즘IT](https://yozm.wishket.com/magazine/detail/1410/?fbclid=IwAR0ONpKBpx5gJ_m5eFjRbDn1KP0PqvOOqYIAivq0IRYWiYbR8WkAmjVtxW8)
[Don’t use rem/em for paddings, margins and more - Medium](https://medium.com/@sascha.wolff/dont-use-rem-em-for-paddings-margins-and-more-94e19026b000)
[When to use Rem, Em, VW/VH, %, PX? - Reddit](https://www.reddit.com/r/Frontend/comments/sn2yns/when_to_use_rem_em_vwvh_px/?rdt=48405)

2023-12-12 12:40 UTC, wonsss commented on index.html
> +      </h1>
다행이네요! 수고하셨어요.

2023-12-12 13:24 UTC, shkim901112 commented on main.css
> +  }
d7110e56ec124df7fb8280524c5c82b6a56f77c0

이미지 사이즈 수정하였습니다 ! 이미지를 수정하니 태블릿페이지도 레이아웃이 깨지는 현상이 발생하여 그 부분도 처리하였습니다!

2023-12-12 13:26 UTC, huniiiiii commented on index.html
> +    <header>
여는태그가 빠져있다는게 무슨뜻인지 여쭤봐도 될까요 ?  제가 확인해봤을때 <head>부분은 위에 있어서 어떤말씀인지 제가 이해를 못했습니다 😢

2023-12-12 13:27 UTC, shkim901112 commented on signin/signin.css
> +}
42773a5a2dca3f3d6039a50924739fca542a7019

확인후 수정완료 했습니다 !

2023-12-12 13:29 UTC, shkim901112 commented on index.html
> +        </p>
42773a5a2dca3f3d6039a50924739fca542a7019

기본적으로 그런 현상이 있는줄 몰랐네요.. css reset을 추가하고 margin도 추가하여 수정하였습니다!

2023-12-13 09:39 UTC, wonsss commented on index.html
> +    <header>
body 요소에서 
`<body>` 이게 여는 태그이고
`</body>` 이게 닫는 태그입니다.
그런데 밑에 `</body>`는 있는데, `<body>`가 없어서 말씀드렸어요.

2023-12-13 09:40 UTC, wonsss commented on index.html
> +        </p>
요소별로 기본적으로 적용된 CSS 스타일이 있어요 ㅎㅎ

2023-12-13 09:48 UTC, shkim901112 commented
b3153ac0f5cf78fa09e8b21d5ff440fdd32ea52a

html 수정하였습니다😥

2023-12-13 11:20 UTC, wonsss approved these changes

2023-12-13 11:21 UTC, merged

2023-12-13 13:10 UTC, huniiiiii commented on signup/signup.css
> +  margin: 238rem 520rem 252rem 520rem;
네 다음엔 참고해서 써보도록 하겠습니다 !

2023-12-13 13:12 UTC, shkim901112 commented on index.html
> +    <header>
아 이 부분말씀이셨군요 ! 다음엔 알려주신거 확인하고 꼼꼼하게 해보겠습니다 😅