[권지민] Week 4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #90
Opened 2023-12-14 07:28 UTC by mingzzi96

## 요구사항

### 기본

- [x]
- []
- []

### 심화

- [x]
- []

## 주요 변경사항

-
-

## 스크린샷

![image](이미지url)

## 멘토에게

-
-
- 셀프 코드 리뷰를 통해 질문 이어가겠습니다.

2023-12-15 07:21 UTC, mingzzi96 commented on script/signin.js
> +} from "./common.js";
@wonsss 여기 import 관련 질문 남겨두었습니닷!

2023-12-15 07:22 UTC, mingzzi96 commented on script/common.js
> +}
@wonsss 여기는 export 해주지 않았는데 어떻게 적용되고 있는걸까요...?

2023-12-16 01:50 UTC, mingzzi96 commented on script/signin.js
>  } from "./common.js";
@wonsss `* as "something"` 이런식으로 가져오기도 하는 것 같은데
저는 가져온 변수들이 이 페이지에서 보였으면 좋겠어서 일일이 다 불러오게 되었습니다.
새로운 이름 지정해주고 객체로 뽑아오면 자꾸 파일 왔다갔다하면서 뭐가 있는지 확인하는게 귀찮을 것 같았어요.
어떤 방식이 더 나을까요?

2023-12-16 01:51 UTC, mingzzi96 commented on script/signin.js
>  let emailInputValue = "";
@wonsss let은 값이 변경될 수 있으니까 따로 export 해주지 않았습니다. 그런데 그냥 실험삼아서 export 파일에 넣고 내보내기 해줘봤는데 오류가 뜨더라구요..? 예제를 let도 export 해줄 수 있는 것 같던데 왜 안되는걸까용? 변경될 수 있는 값이라서 안되는걸까요?

2023-12-16 01:53 UTC, mingzzi96 commented on script/common.js
>  }
@wonsss 여기는 export 해주지 않았는데 어떻게 적용되고 있는걸까요...? 아무래도 함수로 감싸주는게 좋은거겠죠?

2023-12-17 18:39 UTC, wonsss requested changes
안녕하세요 지민님. 자바스크립트 첫 미션 고생 많으셨습니다. 이번에도 열심히 잘 해주셨네요 👍 

리뷰 확인 부탁드려요 😄

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +const formEl = document.querySelector("form");
태그명으로 요소를 선택하면, 나중에 동일 태그가 document 내 여러 개 있는 상황이 있을 수 있으니, id를 지정해서 선택하시는 것도 좋을 것 같아요.

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +const pwInputEl = document.querySelector("#password");
변수 이름을 지을 때 그 이름이 변수가 나타내는 것을 완전하고 정확하게 설명하는지를 가장 중요하게 고려해야 합니다.
`pw` 나 `El` 보다는 `password`와 `Element` 처럼 분명하게 적는 게 나을 것 같아요.

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +    pwConfirmInputEl,
export 했으나 import 해서 사용한 곳이 없는 것 같네요! 확인 부탁드려요

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +    pwConfirmShowButtonEl,
export 했으나 import 해서 사용한 곳이 없는 것 같네요! 확인 부탁드려요

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +const pwConfirmShowButtonEl = document.querySelector("#eyePwConfirm");
signin과 signup에서 중복될만한 코드들을 common.js 파일에 분리하여 중복을 방지하셨군요. 👍  지민님의 의도에 따르면, common.js 라는 파일명이 적절한지 고민해보면 좋을 것 같아요.
회원가입이나 로그인 외에 다른 페이지에서 공통되는 코드를 분리할 때 이 common.js에다가 함께 두게 되면 나중에 혼란스러울 수도 있지 않을까요?

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +const pwConfirmShowButtonEl = document.querySelector("#eyePwConfirm");
그리고 회원가입과 로그인이 비슷한 UI의 페이지들이긴 하지만, 기능이 완전히 동일하지도 않고 스타일도 페이지별로 달라질 수도 있는 가능성을 배제하기도 어려울 것 같아요.
그렇다면 향후 유지보수 상황을 고려한다면, 이렇게 별개의 페이지 요소 선택을 공통 모듈로 묶어서 사용하는 것보다 각 페이지별로 분리해두는 것이 나을 수도 있지 않을까 싶어요.
지민님은 어떻게 생각하시나요? 🤔

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +const pwRegex = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,25}$/;
공용으로 사용할 정규표현식을 common에 분리해주셨군요! 👍

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +}
이 for 문 로직은 common.js를 import 하자마자 바로 평가되어 실행됩니다.
그런데 명시적인 코드라고 보기 어려운 것 같아요. 

common.js를 import한 사용처에서는 common.js 파일에 와서 이 for 문을 읽어보지 않으면, 이와 같은 동작이 일어날 것이라고 생각할 수 없을 것 같아요. 지금은 로직이 많지 않아서 괜찮아 보일 수 있지만, 나중에 프로젝트 더 복잡해지고 다른 개발자가 유지보수하려고 할 때 예측하기 어려운 코드가 될 수 있어요.

따라서 이 로직을 함수 안에 넣고 해당 함수를 export 해주세요. 그리고 siginin.js 같은 사용처에서 해당 함수를 import한 후 직접 호출해주면 더 명시적으로 될 것 같아요. 😄

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +for (let pwInputContainerItem of pwInputContainer) {
"비밀번호 입력"
"비밀번호 재입력"
이 두 인풋 모두 눈 모양 버튼이 있고, 동일한 이벤트핸들러를 등록해야 하니 반복문을 사용해주셨군요! 멋지네요 😄

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +            let selectedInput = e.currentTarget.querySelector("input");
여기서 변수 선언 방식으로 const 대신 let을 사용하신 이유가 있으신가요?
const, let, var 차이와 사용하는 케이스에 대해 확인해보시면 좋을 것 같아요.

2023-12-17 18:39 UTC, wonsss commented on script/common.js
> +            let selectedInput = e.currentTarget.querySelector("input");
그리고 prefer-const 라는 eslint 옵션을 켜시는 것도 추천드립니다. 
필요하지 않은 경우에 let이나 var를 쓰면 린트에서 경고를 해줍니다. 😄 

<img width="829" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/eeb421f7-2580-4990-88b3-1bf7e010876e">

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +formEl.addEventListener("submit", handleSubmit);
핸들러 함수의 이름을 잘 지어주신 것 같아요.

첨언하자면, 규칙성을 정하여 일관성있게 적용해주시면 더 좋을 것 같습니다.
지민님께서 하신 것을 보니 아마 이런 규칙성이 추론되는 것 같네요.
`handle` + `요소` + `이벤트` 

예를 들어 이런 식으로 하면 어떨까요? 그러면 나중에 핸들러 이름만 보더라도 어떤 역할인지 바로 예측할 수 있을 것 같아요.

handleEmailnputFocusOut
handlePasswordInputFocusOut
handleEmailnputKeyUp

2023-12-17 18:39 UTC, wonsss commented on script/signup.js
> +    let target = e.target;
이 변수도 let 으로 선언하는 것이 적절한지 확인해보시면 좋을 것 같아요.

2023-12-17 18:39 UTC, wonsss commented on script/signup.js
> +let pwConfirmInputValue = "";
이러한 변수들은 아래에서 재할당(reassign)이 되고 있어서, 상수인 const가 아닌 이처럼 let으로 선언하는 것이 맞습니다! 👍

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        emailErrorMessage.textContent = "";
if, else if, else 가 많이 이어지고 있네요. 
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else문을 사용하지 않아도 됩니다.

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +    e.preventDefault();
기본동작을 방지하기 위한 preventDefault 메서드를 잘 사용해주셨네요. 😄

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +};
try catch 문을 사용해주셨군요 👍 

그런데 혹시 여기서 error가 catch 될 수 있는 코드가 있을까요?

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        formEl.mothod = "GET";
오타가 났네요 😢

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        formEl.mothod = "GET";
앗 그리고 회원가입이나 로그인 같은 중요한 작업은 일반적으로 GET 메서드를 사용하여 처리하지 않습니닷. GET 메서드는 주로 정보를 검색할 때 사용되며, URL에 데이터가 노출되므로 보안에 취약합니다. 또한 GET 메서드는 브라우저 히스토리에 파라미터를 노출시키기 때문에 사용자의 개인 정보를 보호할 수 없어요.

대신, 회원가입과 같은 작업은 POST 메서드를 사용하여 안전하게 처리하는 것이 일반적입니다. POST 메서드를 사용하면 데이터가 요청 본문에 포함되어 URL에 노출되지 않으며, 브라우저 히스토리에도 기록되지 않습니다.

https://developer.mozilla.org/ko/docs/Web/HTML/Element/button#formmethod
<img width="770" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/695304a0-03c8-40c3-9688-0dc71466d946">

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        formEl.mothod = "GET";
자바스크립트 내에서 form 요소의 속성을 지정해주는 것보다 HTML에서 미리 지정해주면 가독성이 더 좋을 것 같아요.
```html
<form action="/folder.html" method="get">
```

2023-12-17 18:39 UTC, wonsss commented on script/signup.js
> +    } else {
조건문에 부정을 사용하는 것보다 긍정 그대로 사용하는 것이 더 읽기 쉽습니다! 되도록 긍정문을 사용할 것을 추천드려요.
```js
if(emailValid) { } else { }
```

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        } else if (!pwValid) {
여기서는 else if 사용하지 않고 if 문을 종료한 후
한 줄 띄우고 바로 새로운 if 문을 사용해주시는 것이 동일한 효과를 내면서 가독성에 더 좋습니다.
다른 코멘트에서 말했던 Early Return 이에요.
``` 
if (!pwValid) {
```

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        formEl.submit();
e.currentTarget.submit(); 와 동일합니다. 해당 이벤트 객체 통해서 form 요소 가져올 수 있는데 이게 더 명시적이라고 볼 수도 있을 것 같아요.

2023-12-17 18:39 UTC, wonsss commented on script/signup.js
> +const handleSubmit = (e) => {
signin에서 코멘트 드린 내용들도 signup에서 다 동일하게 적용되겠네요.
signin 수정하시면서 signup도 같이 봐주시면 감사하겠습니다 😸

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +};
이 이벤트를 keyup에 등록하지 않고 제거하더라도 지금과 동일하게 동작할 것 같아요.
참고로 현재는 focusOut 될 때만 에러 메세지가 갱신되어 보입니다. 
그리고 emailInputValue, pwInputValue 변수 선언도 필요하지 않아 보여요.

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +    ) {
else if 문에는 조건이 필요해요. 

<img width="363" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/19339a46-3d96-498f-8c0a-181f88be3e35">

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +    ) {
그리고 관련된 요구사항을 충족하지 못한 버그가 있습니다. 특정 이메일과 비밀번호가 맞으면 로그인 시 folder 페이지로 이동시키는 로직은 submit 핸들러 내에서 해야 합니다. FocusOut 핸들러의 책임은 아니에요.

<img width="448" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/9aa1405e-86aa-4d82-a906-f3f94be86c77">
<img width="461" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/3ada6ec6-535c-46e5-8a53-41d29c823d7d">

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +        formEl.submit();
submit() 호출 여부에 특정 이메일과 비밀번호가 맞는지 조건을 걸어주셔야 할 것 같아요

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +const handleEmailFocusOut = (e) => {
해당 핸들러 함수를 제가 리팩터링해봤어요. 이런 관점도 생각해보시면 좋을 것 같아요.


```js
const handleEmailFocusOut = (e) => {
    const emailValue = e.target.value;

    try {
        if (emailValue.length === 0) {
            throw new Error("이메일을 입력해주세요.");
        }
        if (!emailRegex.test(emailValue)) {
            throw new Error("올바른 이메일 주소가 아닙니다.");
        }
        hideEmailError();
    } catch (error) {
        showEmailError(error.message);
    }
};

const showEmailError = (message) => {
    emailInputEl.classList.add("error");
    emailErrorMessage.classList.add("show");
    emailErrorMessage.textContent = message;
};

const hideEmailError = () => {
    emailInputEl.classList.remove("error");
    emailErrorMessage.classList.remove("show");
    emailErrorMessage.textContent = "";
};
```

2023-12-17 18:39 UTC, wonsss commented on script/signin.js
> +let pwInputValue = "";
전역변수는 지양하고 가능한 변수의 스코프를 좁게 가져갈 수 있도록 고민해보시면 좋을 것 같아요.

2023-12-17 18:47 UTC, wonsss commented on script/signin.js
>  } from "./common.js";
저는 import 문이 너무 길어지는 게 싫을 때, `import * as myModule from "my-module.js";` 같은 문법을 사용하여 한 문장으로 해당 모듈 전체를 가져옵니다. 이를 통해 export 한 모든 것들을 현재 범위(스크립트 파일 하나로 구분되는 모듈 범위) 내에 myModule 로 바인딩되어 들어가게 됩니다.

그리고 모듈 이름 뒤에 `.`을 붙이면 해당 모듈이 export한 모든 것들이 보여서 쉽게 선택하여 사용하실 수도 있어요.
<img width="488" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/b227f7dc-23bd-4f0d-8a6c-6e378ba1fe33">

반면, 모듈에서 하나 또는 일부 멤버만 가져오려면 아래와 같이 합니다. 해당 모듈에서 모든 멤버를 가져올 필요가 없고 무엇을 import했는지 명시적으로 보여주고 싶다면 이와 같은 방법을 사용합니다.
```js
import { foo, bar } from "my-module.js";
```

두 방법 중 뭐가 더 나은 것은 없고, 필요에 따라 적절하게 쓰시면 될 것 같아요.

2023-12-17 18:58 UTC, wonsss commented on script/signin.js
>  let emailInputValue = "";
자바스크립트의 모듈 시스템에서는 import한 변수를 재할당하는 것이 불가능합니다. emailValid 를 import한 곳에서 emailValid를 수정하는 것은 해보신 것처럼 에러가 납니다.

다만, import한 변수가 객체인 경우(Object.freeze()도 되어 있지 않아야 함) 객체 자체를 재할당하는 것이 아니라 객체의 프로퍼티를 수정하는 것은 가능합니다.

2023-12-17 18:59 UTC, wonsss commented on script/common.js
>  }
동일 내용으로 코멘트 남긴 부분 링크입니다! 😄 
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/90#discussion_r1429212485

2023-12-18 02:44 UTC, mingzzi96 commented on script/signin.js
>  let emailInputValue = "";
헉 그런 것이군요!! 완전 이해되었습니당 ! (๑˃̵ᴗ˂̵)

2023-12-18 03:05 UTC, mingzzi96 commented on script/common.js
>  }
확인하였습니다! 감사합니당! ✅

2023-12-18 03:19 UTC, mingzzi96 commented on script/common.js
> +const pwConfirmShowButtonEl = document.querySelector("#eyePwConfirm");
확실히 common은 너무 포괄적인 이름이네요. 62ecf09bcca67b4e0b7a8c76b12435dc22255cb2 script 폴더 안에 sign 이라는 폴더를 생성하구 넣어주었습니다. 그리고 common.js라고 하기 보다 signCommon.js 이렇게 파일명도 변경해 주었습니다!

2023-12-18 03:27 UTC, mingzzi96 commented on script/common.js
> +            let selectedInput = e.currentTarget.querySelector("input");
ae92717518e525d27459812d9d0b9625b11b8ac5 prefer-const!! 이런 기능도 있었군요!  바로 설정해 보았는데 정말 신세계입니당 🤩

2023-12-18 03:28 UTC, mingzzi96 commented on script/signup.js
> +    let target = e.target;
ae92717518e525d27459812d9d0b9625b11b8ac5 let으로 들어가있는 부분 확인하여 일괄 수정하였습니당!

2023-12-18 03:35 UTC, mingzzi96 commented on script/signin.js
> +        formEl.mothod = "GET";
a91a37afc07d8e55dd4b5592494f32f58ecab728 앗 저런 방법은 생각지 못했네요! 수정하였습니당

2023-12-18 05:44 UTC, mingzzi96 commented on script/signin.js
> +        formEl.mothod = "GET";
b4243bd3cffc45ae0f6d6b43251cbc0ba7592b55 오타 ㅜㅜ 수정하였고, method 역시 post로 변경해 주었습니당!

2023-12-18 10:30 UTC, mingzzi96 commented on script/common.js
> +const pwInputEl = document.querySelector("#password");
f479d957676e3f77bbac5baf1c09a738c63678b9 일괄 수정하여 반영하였습니당!

2023-12-21 05:50 UTC, wonsss commented on script/common.js
> +const pwConfirmShowButtonEl = document.querySelector("#eyePwConfirm");
넵 혹은 이렇게도 할 수 있을 것 같아요. 
`common/element.js`
나중에 공통 유틸을 분리한다면,
`common/util.js` 처럼 할 수도 있을테니까요. ㅎㅎ
정답은 없습니당. 그냥 이런 상상만 해보셔도 도움 되셔요.

2023-12-21 05:51 UTC, wonsss commented on script/common.js
> +            let selectedInput = e.currentTarget.querySelector("input");
넵 되도록 const 쓰는 게 좋아요.

2023-12-21 06:03 UTC, wonsss approved these changes
지민님. 꼼꼼하게 리뷰 반영해주셨군요 👍 
수고 많으셨어요. 다음 미션에서 뵈어요. 😄

2023-12-21 06:03 UTC, merged