Part1 조성경 week4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #92
Opened 2023-12-14 12:54 UTC by whtjdrud

## 요구사항

### 기본

- [x]  [기본]이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 input에 빨강색 테두리와 아래에 “올바른 이메일 주소가 아닙니다.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]이메일 input에서 focus out 일 때, input 값이 [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com) 일 경우 input에 빨강색 테두리와 아래에 “이미 사용 중인 이메일입니다.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, input에 빨강색 테두리와 아래에 “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input에 빨강색 테두리와 아래에 “비밀번호가 일치하지 않아요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 빨강색 테두리와 에러 메세지가 보이나요?
- [x]  [기본]이외의 유효한 회원가입 시도의 경우, “/folder”로 이동하나요?
- [x] [기본]이메일: [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com), 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동하나요?
- [x]  [기본]비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?
- [x]  [기본]이외의 로그인 시도의 경우 이메일, 비밀번호 input에 빨강색 테두리와 각각의 input아래에 “이메일을 확인해주세요.”, “비밀번호를 확인해주세요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 되나요?
- [x]  [기본]이메일, 비밀번호 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?

### 심화
- [x]  [심화]눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?
- [x]  [심화]비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?
- [x]  [심화]로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용했나요?

## 주요 변경사항

- npm init 재 작업
- 로그인, 회원가입 페이지 Form Validation
- 로그인, 회원가입 페이지 모바일 요구사항 (max-width 400px, 100%, 좌우 32px)
## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/17bece01-e40c-4d18-bae3-6a458ed5b274)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/06817c5e-9013-4925-9d28-1e9a594c468b)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/5e2f92d1-5a4d-41ba-9648-910d9b0cd338)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/876df5e4-5db7-4e43-ae3a-e2bd14af09f4)
![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/151587265/81c6cdc5-f6b2-45e5-8c9f-338fcb796dce)

## 멘토에게
- https://jobible.netlify.app/signin , https://jobible.netlify.app/signup 테스트 사이트 입니다.
- 저번주에 진행하지 못한 작업 완료 했습니다.
- 나름 중복되는 코드가 눈에 보여 최대한 검색해가며 리팩토링도 진행해보았습니다.
-

2023-12-18 02:57 UTC, Jun-12 commented on assets/js/sign/ui.js
> +        input.type = 'password';
이렇게 forEach를 사용해서 각 요소에 접는하는 방식으로 구현할 수도 있군요!! 한가지 배워갑니다👍

2023-12-18 02:57 UTC, Jun-12 commented on assets/css/sign.css
> +@import 'color.css';
공통으로 사용하는 css 파일들을 임포트하는 방식을 사용하셨네요. html을 좀 더 명시적으로 하기 위함인가요?

2023-12-18 03:06 UTC, whtjdrud commented on assets/css/sign.css
> +@import 'color.css';
reset.css, color.css 등은 모든 파일들에 공통으로 들어가는 부분이라고 생각해서 파일을 구분했습니다.
그리고 이런 파일들이 많으면 common.css 라고 파일을 하나 만들어서 거기에 공통으로 들어가는 import를 모으려고 했어요.
common.css
```css
@import 'reset.css';
@import 'color.css';
@import 'font.css';
```
이런식으로 만든 뒤에 모든 html 위에는
```css
@import 'common.css';
```
이런 식으루요 그런데 그렇게 사이즈가 크지 않은 것 같아서 저 상태로 방치되어있는 중입니다...

color는 분리한 경우는 
저번에 피그마에서 보니 공통으로 사용하는 색깔이나 그런 양식을 따로 표시해두어서
변수값으로 만들어서 써야지 하고 방치 중입니다.. 창피..

2023-12-18 07:39 UTC, Jun-12 commented on assets/css/sign.css
> +@import 'color.css';
전 범위적으로 공통으로 사용되는 css를 하나로 묶는 css를 따로 만들면 확실히 html에서 보기에는 훨씬 직관적이겠네요! 자세한 답변 감사드립니다.😀

2023-12-18 08:19 UTC, wonsss commented on assets/js/sign/main.js
> +sign.inputPassword.addEventListener('focusout', event => validatePassword(event, sign));
영문, 숫자 조합 8자 이상 비밀번호를 입력하고 focusout 했는데, 에러메세지가 사라지지 않아요. 확인 후 수정 바랍니닷

<img width="461" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/6c5e21ff-d515-447d-a316-02ebe6cf3053">

2023-12-18 10:03 UTC, wonsss requested changes
안녕하세요 성경님! 4주차 과제 수고 많으셨습니다.
로직의 중복을 줄이려고 하고 네이밍을 열심히 하신 것 같아요. 👍 

코드 리뷰 남겨드렸으니, 반영 후 재리뷰 가능할 때 노티 주세요. 😄

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +const sign_form = document.querySelector('#sign_form');
요소 변수명에 snake case 표기법을 사용하셨군요. 
자바스크립트에서는 일반적으로 camel case 표기법을 사용하는 것이 컨벤션입니다.
일관된 표기법을 사용하는 것이 나중에 혼동을 줄이기 위해 중요한데요.
요소 변수명에는 선택적으로 snake case 표기법을 사용하신 이유가 궁금합니다. 😄

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +}
조건문에서 되도록 else if 나 else 문은 사용을 지양하고,
early return 기법을 사용하는 것이 좋습니다. 
들여쓰기를 줄여 코드를 간결하고 읽기 쉽게 만들 수 있어요.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +    sign_form.submit();
이벤트 핸들러인 validateLogin 함수 내에서 전역변수로 선언한 sign_form을 굳이 가져올 필요가 없을 것 같습니다.
함수를 이벤트 핸들러로 사용하면, 해당 함수 내 this는 이벤트 핸들러가 등록된 DOM 요소를 참조하기 때문입니다. 

<img width="977" alt="스크린샷 2023-12-18 오후 5 43 53" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/67858be6-f5ad-4dc7-b0f4-35322e9c2d5d">

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/sign.js
> +export default sign;
js/sign.js 내에서 export한 변수와 여기서 export하는 변수들이 거의 비슷하네요.
중복으로 보이는데 해결이 필요할 것 같아요.

그리고 사실 이처럼 전역변수로 선언하여 사용하는 것 자체가 문제가 있을 수 있습니다.
함수 밖에서 선언한 변수는 전역 변수가 되는데, 전역 변수는 어플리케이션 전역에 공유되어 어디서나 읽고 쓸 수 있어요. 다른 모듈에서 동일한 이름으로 사용하면 덮어쓸 수 있어 조심해야 합니다.
프로젝트가 커질수록 관리하기 어려워지고 버그의 원인이 될 수 있어요.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/sign.js
> +export default sign;
이벤트 핸들러 함수 내에서 이벤트가 등록된 해당 DOM 요소를 가리키는 `this` 나 `e.currentTarget` 을 사용하는 것부터 시작해봐도 좋을 것 같습니다.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/validation.js
> +  const regex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
해당 정규표현식의 이름으로 regex보다는 해당 정규표현식의 역할을 정확히 설명하는 구체적인 이름을 붙이면 좋을 것 같아요.

그리고 이와 같은 정규표현식은 regex.js 또는 constants.js 같은 별도의 파일 모듈로 분리하고 import하여 사용하면 중복을 방지하고 관리하기도 더 쉬워질 것 같습니다.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/validation.js
> +  const errorMsg = sign.errorMessages[2];
errorMessages[0], errorMessages[1], errorMessages[2] 처럼 index에 의존하여 대상을 선택하는 것은 가독성이 떨어질 수 있어요.
정확한 이름으로 구분해주시면 좋을 것 같아요.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/sign.js
> +  errorMessages: document.querySelectorAll('.error_msg'),
클래스가 'error_msg'인 요소들을 모두 선택하여 errorMessages를 만드셨군요.
그런데 클래스는 같더라도 각각의 요소들은 '이메일 에러 메세지', '비밀번호 에러 메세지', '비밀번호 체크 에러 메세지' 처럼 각자 가진 역할이 다릅니다. 
나중에 다 구분해서 선택할 필요도 있구요. 그래서 애초에 각각을 아이디로 선택하여 명시적인 이름의 변수들을 만드는 것이 나을 것처럼 보여요. 😄

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/ui.js
> +export function errorDisplay(e, errorMsg, message) {
함수이름은 일반적으로 '동사' + '명사' 로 이루어지는 것이 좋아요.
이 함수의 역할은 "에러메세지를 표시하는 것"이죠?
그렇다면, 이름으로 showErrorMessage는 어떨까요? 😄

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/ui.js
> +export function clearDisplay(e, errorMsg) {
해당 함수의 이름으로 clearErrorMessage 는 어떨까요?

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/ui.js
> +export function eye_toogle(sign) {
자바스크립트에서 함수 이름으로 스네이크 케이스 대신 카멜 케이스를 사용해주세요.
TOAST UI에서 예시로 올린 자바스크립트 코딩 컨벤션 중 명명 규칙 부분을 참고해보시면 좋을 것 같아요.  그리고 ESlint에 camel case rule 도 추가하여 린트의 도움을 받으면 컨벤션에 금방 익숙해지실 거예요. 😄 

<img width="1079" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/90be48db-a8c3-4eb5-897f-d3e00b4fffcc">


https://ui.toast.com/fe-guide/ko_CODING-CONVENTION#%EB%AA%85%EB%AA%85-%EA%B7%9C%EC%B9%99

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/validation.js
> +  }
이렇게 리팩터링해보시면 어떨까요?
조건문이 서로 독립적으로 실행되도록 변경함으로써, 각각의 조건에 대한 로직이 좀 더 명확해보이지 않으신가요? 😄 
```suggestion
if (email.length === 0) {
    errorDisplay(e, errorMsg, '이메일을 입력해주세요');
    return false;
}

if (!regex.test(email)) {
    errorDisplay(e, errorMsg, '올바른 이메일 주소가 아닙니다.');
    return false;
}

if (email === 'test@codeit.com' && sign.currentPage.includes('signup')) {
    errorDisplay(e, errorMsg, '이미 사용 중인 이메일입니다.');
    return false;
}

clearDisplay(e, errorMsg);
return true;
```

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/validation.js
> +}
여기도 else if, else 조건문 리팩터링해보시면 좋을 것 같아요.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/validation.js
> +  console.log(password);
콘솔로그는 제거 바랍니다. 😄

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +const input_email = document.querySelector('#email');
js/sign.js 파일 내 코드가 다른 파일의 코드들과 많이 겹치는 것 같은데, 혹시 js/sign.js 파일을 지우셔야 하는데 안 지우신 것 아니신가요?

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +    sign_form.method = 'GET';
여기서 form submit method를 GET으로 사용하신 이유가 궁금해요.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/form.js
> +    sign_form.method = 'POST';
해당 프로퍼티 설정을 자바스크립트로 이렇게 나중에 하지 말고, 선언적으로 Form 태그 내에 명시해두는 것은 어떨까요?

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/form.js
> +    sign_form.method = 'POST';
> 해당 프로퍼티 설정을 자바스크립트로 이렇게 나중에 하지 말고, 선언적으로 Form 태그 내에 명시해두는 것은 어떨까요?

여기두요

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/main.js
> +}
서로 다른 이벤트 등록을 페이지 이름에 따라 분기하셨군요. 문제 해결을 하신 것 같아 좋습니다. 👍 

하지만, signin.html 과 signup.html은 서로 다른 페이지이므로, 각각 import하는 javascript 파일을 signin.js 와 signup.js 처럼 분리했으면 더 쉽고 안전한 방법이 될 것 같아요.

이렇게 페이지 이름에 의존하게 되면, 관리 포인트가 또 늘게 되어 유지보수나 가독성이 떨어집니다.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +  }
'test@codeit.com', 'codeit101' 과 같은 도메인과 관련된 `매직 리터럴`은 별도의 파일에 상수로 분리하여 모듈화한 후 관리해주시면 좋습니다.

매직 넘버(Magic number)나 매직 리터럴(Magic Literal)은 코드에서 하드 코딩된 일정한 값을 의미하는 숫자나 문자열을 의미합니다. 
예를 들어 'test@codeit.com' 코드 내에서 여러 곳에서 사용되고 있지만, 이 값의 의미나 목적은 현재 코드에서 명확하게 알려져 있지 않습니다.

매직넘버나 매직리터럴은 가독성이 떨어지고 유지보수를 어렵게 만들며, 예상치 못한 버그를 발생시키는 원인이 될 수 있습니다.

따라서 이들을 상수로 분리하고 해당 매직넘버의 역할을 정확한 이름으로 붙여서 사용하시는 것이 좋습니다. 그리고 상수로 분리해두면 값을 변경할 때 일괄적으로 변경할 수 있으므로 코드의 유지보수성과 가독성이 향상됩니다.

참고로 자바스크립트에서 상수를 선언하는 컨벤션은
`MOCK_EMAIL` 처럼 모두 영어 대문자에 띄어쓰는 부분은 언더바를 적습니다.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +const input_pw_chk = document.querySelector('#password_chk');
변수 이름을 지을 때 그 이름이 변수가 나타내는 것을 완전하고 정확하게 설명하는지를 가장 중요하게 고려하는 게 좋습니다. 
`pw` 나 `chk` 같은 약어를 사용하셨는데, 공동 작업하는 프로젝트였을 때, 다른 사람들 모두 동일하게 `pw`나 `chk`에 대해 이해하거나 사용할 수 있을까요?
이 대신에 passwordCheck 같은 정확한 이름을 쓰는 게 유지보수에 용이합니다.

2023-12-18 10:03 UTC, wonsss commented on signup.html
> +      <form id="sign_form" class="sign-form" action="">
action과 method 프로퍼티를 form 태그 인라인에 명시해주셔도 될 것 같아요.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign.js
> +const input_pw_chk = document.querySelector('#password_chk');
`Code Spell Checker` VSCode 익스텐션을 설치해서 사용하실 것을 권장드립니다.
맞춤법 틀림을 방지해주고, 불필요한 약어 사용을 하게 될 때 한번 더 생각하게 해줘서 좋습니다.

VS Marketplace 링크: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/ui.js
> +      } else if (img.src.includes('/assets/images/signin/eye-on.svg')) {
img 경로를 기준으로 토글 조건을 잡으셨네요.
나중에 img 경로가 변경되면 여기도 함께 관리해야 해서 관리가 어려울 것 같아요.

대신에 [classList.toggle(token)](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle) 을 사용해보시는 것은 어떠신가요?

그리고 토글되는 해당 CSS 내에 background image 를 두 가지 케이스의 이미지 설정되도록 하면 될 것 같아요.

input.type 또한 조건문이나 삼항연산자를 사용해서 현재 type이 'text'면 'password'로 변경시키고, 아니면 'text'로 변경시키는 간단한 조건으로 바꿀 수 있어 보입니다.

2023-12-18 10:03 UTC, wonsss commented on assets/js/sign/ui.js
> +      const input = this.previousElementSibling;
previousElementSibling 사용하셨군요! 이렇게 DOM 트리 탐색해보는 연습하는 것 좋아요.

좀 더 명시적으로 한다면 this.parentElement.querySelector('input') 도 가능하겠네요.

previousElementSibling 은 태그 순서에 의존하니까, 혹시나 중간에 다른 태그가 들어오면 버그가 발생할 수도 있을 것 같아서요.

2023-12-18 10:03 UTC, wonsss commented on signup.html
> +          <a href="https://www.kakaocorp.com/page" target="_blank"><img src="/assets/images/signin/kakao.png" alt="" /></a>
img 태그의 alt 속성은 웹접근성을 위해 가능한 입력해주시면 좋습니다.

2023-12-18 15:42 UTC, whtjdrud commented on assets/js/sign.js
> +    sign_form.method = 'GET';
405 Method Not Allowed 에러 때문입니다.

현재 피그마에서 저희에게 요구산 사항이 정상정으로 submit이 되면 /forder 로 이동하라고 명시되어있는데요.
그래서 현재 forder.html 을 만들어서 이동하도록 하였씁니다.

그 결과 405 Method Not Allowed 에러가 발생하여 확인해보지 단순 페이지 이동의 경우 GET 메소드를 이용하고 서버에서 GET 이외의 다른 요청으로 접근 할 경우 서버에서 405 Method Not Allowed 오류를 반환한다는 내용을 확인했씁니다.

그래서 테스트 때 불편하실것 같아서 일단 GET으로 사용하였습니다.

2023-12-18 16:24 UTC, whtjdrud commented on assets/js/sign.js
> +const input_email = document.querySelector('#email');
넵 최초에 모듈화 하기전에 한 파일로 작업하고 후에 모듈화로 작업하였습니다. 그 후 삭제를 진행해야되는데 하지 못했씁니다. 죄송합니다.

2023-12-19 06:22 UTC, whtjdrud commented on assets/js/sign/ui.js
> +      } else if (img.src.includes('/assets/images/signin/eye-on.svg')) {
와아.. 저는 진짜 바보 멍충이에요 원석님.. 왜 이렇게 짰을까요..? 물론 한 2시간 넘게 들여다보고 있었는데요..

2023-12-19 08:26 UTC, whtjdrud commented on assets/js/sign.js
> +const sign_form = document.querySelector('#sign_form');
넵. 해당 부분은 저도 모르게 그렇게 사용하고 있던 부분이었습니다.
이번에 리팩토링 할때도 무의식적으로 작업하다 알려주신 플러그인으로 인해 수정하였습니다. 
익숙해지도록 노력하겠습니다.

2023-12-19 08:28 UTC, whtjdrud commented on assets/js/sign/sign.js
> +export default sign;
넵 전역변수는 최대한 제거하려고 노력했하고 이벤트 태그로 하도록 노력하였습니다. 
아래와 같은 형식으로 리팩토링 하였습니다.

```javascript
export function validateEmail(e) {
  const email = e.target.value;
  ...
  }
  ```

2023-12-19 08:29 UTC, whtjdrud commented on assets/js/sign/validation.js
> +  const regex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
js 폴더 하위에 regex.js 파일을 만들었습니다.
그리고 아래와 같이 추가하였습니다.

```javascript
export const emailRegex =
  /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

export const passwordRegex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
```

2023-12-19 08:32 UTC, whtjdrud commented on assets/js/sign/ui.js
> +export function errorDisplay(e, errorMsg, message) {
안그래도 너무 느낌이 이상해서 계속 고민하다 떠오르는 아이디어가 없었는데 너무 좋았습니다!

2023-12-19 08:32 UTC, whtjdrud commented on assets/js/sign/ui.js
> +export function clearDisplay(e, errorMsg) {
이것두요! 너무 좋았습니다.

2023-12-19 08:35 UTC, whtjdrud commented on assets/js/sign/ui.js
> +export function eye_toogle(sign) {
린트에 카멜케이스 기능을 추가했습니다.
너무 좋은 기능인것 같습니다.

```json
{
  "extends": ["airbnb", "prettier"],
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": ["error", { "endOfLine": "auto" }],
    "camelcase": ["error", { "properties": "always" }]
  },
  "env": {
    "browser": true,
    "node": true
  },

  "import/extensions": ["error", "always"]
}
```

`env`의 경우 document 부분이 에러, 브라우저 환경에서도 작동하는 것이라고 알려주는 부분입니다.
 `"import/extensions": ["error", "always"]` 는 모듈에서 import 할때 .js를 삭제하라고 하지만, 실제 저의 환경에서 js 삭제시 정상적으로 import 되지 않고 404에러가 떠서 작성하였습니다.

2023-12-19 08:37 UTC, whtjdrud commented on assets/js/sign/validation.js
> +  }
아래와 같이 리팩토링하였습니다.

```javscript
if (email.length === 0) {
    return showErrorMessage(e, handleError('EMPTY_EMAIL_FIELD'));
  }

  if (!emailRegex.test(email)) {
    return showErrorMessage(e, handleError('INVALID_EMAIL'));
  }
  ```
  form에서 submit 할때 체크하는 true, false 부분은 `ui.js`에 추가해 두었습니다.
  
  ```javascript
  export function showErrorMessage(source, errorMessage) {
  const errorMessageElement = errorMessageElementFind(source);

  errorMessageElement.innerHTML = errorMessage;
  errorMessageElement.classList.add('input-error');

  return false;
}

export function clearErrorMessage(source) {
  const errorMessageElement = errorMessageElementFind(source);

  errorMessageElement.innerHTML = '';
  errorMessageElement.classList.remove('input-error');

  return true;
}
```

2023-12-19 08:37 UTC, whtjdrud commented on assets/js/sign/validation.js
> +}
https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/92#discussion_r1431081278 부분과 동일하게 리팩토링하였습니다.

2023-12-19 08:38 UTC, whtjdrud commented on assets/js/sign/validation.js
> +  console.log(password);
마지막 push 할때 오작동할때 지운다는것 지우지 못했습니다 ㅠㅠ
잘 정리하고 commit push 하도록 노력하겠습니다.

2023-12-19 08:39 UTC, whtjdrud commented on assets/js/sign.js
> +  }
root에 config.js 라는 파일을 추가해서 아래와 같이 하였습니다.

```j
export const USER_EMAIL = 'test@codeit.com';
export const USER_PASSWORD = 'codeit101';
```

이렇게하여 실제 사용시에는 아래와 같이 적용했습니다.
```javascript
import { USER_EMAIL, USER_PASSWORD } from '../../../config.js';

  if (email.value !== USER_EMAIL) {
    return showErrorMessage(email, handleError('EMAIL_NOT_FOUND'));
  }

  if (password.value !== USER_PASSWORD) {
    return showErrorMessage(password, handleError('PASSWORD_NOT_MATCH'));
  }
  ```

2023-12-19 08:40 UTC, whtjdrud commented on signup.html
> +      <form id="sign_form" class="sign-form" action="">
넵 아래와 같이 작성하였습니다.

```html
<form id="sign_form" class="sign-form" action="/folder.html" , method="post">
```

2023-12-19 08:42 UTC, whtjdrud commented on assets/js/sign/ui.js
> +      } else if (img.src.includes('/assets/images/signin/eye-on.svg')) {
일단 아래와 같은 css를 추가 하였습니다.
```css
.eye-off {
  background-image: url('/assets/images/signin/eye-off.svg');
}

.eye-on {
  background-image: url('/assets/images/signin/eye-on.svg');
}
```

그리고 이벤트 리스너는 다른 함수들과 동일하게 main.js에 해당하는 부분에서 부여하였습니다.
```javascript
eyes.forEach(button => {
  button.addEventListener('click', event => eyeToggle(event));
});
```

그리고 실제 작동하는 함수는 아래와 같이 리팩토링 했습니다.
```javascript
// 비밀번호 눈 모양, input type 변경
export function eyeToggle(e) {
  const eyeButton = e.target;
  const input = eyeButton.parentElement.querySelector('input');

  input.type = input.type === 'password' ? 'text' : 'password';

  eyeButton.classList.toggle('eye-on');
  eyeButton.classList.toggle('eye-off');
}
```

2023-12-19 08:43 UTC, whtjdrud commented on assets/js/sign/ui.js
> +      const input = this.previousElementSibling;
넵 말씀해주신 DOM 트리 탐색 방식이 훨씬 좋은것 같습니다.
생각하지 못했는데 감사합니다.

너무 단순하게 이전이라고 만 생각했던것 같은데 다른 트리 탐색법도 잘 정리해두겠습니다.

2023-12-19 08:43 UTC, whtjdrud commented on signup.html
> +          <a href="https://www.kakaocorp.com/page" target="_blank"><img src="/assets/images/signin/kakao.png" alt="" /></a>
e4486d21ebcbd34a6624b2d9ef062da0d33a3079 기재해두었습니다!

2023-12-20 15:24 UTC, wonsss commented on assets/js/sign.js
> +const sign_form = document.querySelector('#sign_form');
확인해주셔서 감사합니다!

2023-12-21 05:38 UTC, wonsss commented on assets/js/sign/sign.js
> +export default sign;
네. 여러 방법 고민해보시면 좋아요. 

그리고 클래스 문법도 활용하는 것도 고민해보시면 좋습니다. 클래스를 사용하면 연관된 기능을 단일 단위로 묶을 수 있을 것 같습니다. 이를 통해 코드의 가독성과 유지보수성을 향상시킬 수도 있을 것 같습니다.

2023-12-21 05:39 UTC, wonsss commented on assets/js/sign/validation.js
> +  const regex = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
상수는 대문자와 언더바 조합으로 네이밍하는 게 일반적인 컨벤션이에요. 이렇게 상수는 다른 컨벤션으로 해줘야 변경 가능한 변수와 다르게 인지할 수 있겠죵?

ex) EMAIL_REGEX, PASSWORD_REGEX

2023-12-21 05:40 UTC, wonsss commented on assets/js/sign/ui.js
> +export function clearDisplay(e, errorMsg) {
생각해보니까 show의 반의어는 hide라서

hideErrorMessage가 더 나은 이름일 것 같네요 ㅋㅋ
네이밍은 어려워요 ㅠ

2023-12-21 05:40 UTC, wonsss commented on assets/js/sign/ui.js
> +export function eye_toogle(sign) {
수고하셨습니당

2023-12-21 05:41 UTC, wonsss commented on assets/js/sign.js
> +const input_email = document.querySelector('#email');
확인 감사합니다!
불필요한 코드가 있는지 항상 확인해주세요. 혹시나 유지할 필요가 있으면 주석 남겨주시구요

2023-12-21 05:42 UTC, wonsss commented on assets/js/sign.js
> +    sign_form.method = 'GET';
넵 ㅎㅎ 설명 감사합니다.

2023-12-21 05:43 UTC, wonsss commented on assets/js/sign/ui.js
> +      } else if (img.src.includes('/assets/images/signin/eye-on.svg')) {
성경님 짱짱맨~! 수고하셨어요.

2023-12-21 05:43 UTC, wonsss commented on assets/js/sign/ui.js
> +      const input = this.previousElementSibling;
넵! 지금 이것 저것 시도하는 게 넘 좋아요~

2023-12-21 05:44 UTC, wonsss commented on signup.html
> +          <a href="https://www.kakaocorp.com/page" target="_blank"><img src="/assets/images/signin/kakao.png" alt="" /></a>
꼼꼼~~ 👍

2023-12-21 05:45 UTC, wonsss approved these changes
수고 많으셨습니다! 꼼꼼하고 열정적으로 해주셔서 저도 좋았어요.
추가로 리팩터링하고 싶은 부분들은 다음 주차 미션에서 이어서 해보아요. 😄

2023-12-21 05:45 UTC, merged