Part1 김성훈 week4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #97
Opened 2023-12-16 08:56 UTC by shkim901112

## 요구사항

### 기본

- [ x]  [기본]이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지가 보이나요?
- [ x]  [기본]이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 input에 빨강색 테두리와 아래에 “올바른 이메일 주소가 아닙니다.” 빨강색 에러 메세지가 보이나요?
- [ x]  [기본]이메일 input에서 focus out 일 때, input 값이 [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com) 일 경우 input에 빨강색 테두리와 아래에 “이미 사용 중인 이메일입니다.” 빨강색 에러 메세지가 보이나요?
- [ x]  [기본]비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, input에 빨강색 테두리와 아래에 “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 빨강색 에러 메세지가 보이나요?
- [ x]  [기본]비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input에 빨강색 테두리와 아래에 “비밀번호가 일치하지 않아요.” 빨강색 에러 메세지가 보이나요?
- [ x]  [기본]회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 빨강색 테두리와 에러 메세지가 보이나요?
- [ x]  [기본]이외의 유효한 회원가입 시도의 경우, “/folder”로 이동하나요?
- [ x]  [기본]이메일: [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com), 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동하나요?
- [ x]  [기본]비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?
- [ x]  [기본]이외의 로그인 시도의 경우 이메일, 비밀번호 input에 빨강색 테두리와 각각의 input아래에 “이메일을 확인해주세요.”, “비밀번호를 확인해주세요.” 빨강색 에러 메세지가 보이나요?
- [ x]  [기본]회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 되나요?
- [ x]  [기본]이메일, 비밀번호 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?

### 심화

- [ x]  [심화]눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?
- [ x]  [심화]비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?
- [ x]  [심화]로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용했나요?
## 주요 변경사항

-로그인, 회원가입 이벤트 추가

## 스크린샷

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/3d0ee910-bfb2-44db-8ba6-967e7e38bba1)

회원가입창 오류 및 눈모양 아이콘 동작

![image](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/129745640/27712c3d-0561-414d-b384-4bbf9ccfd58f)

로그인창 오류

##홈페이지

https://gorgeous-pavlova-360632.netlify.app/

## 멘토에게

-merge하기전에 week4 과제를 해버려서 파일이 통으로 올라가 보기 어려운점 죄송합니다 😥
-처음해보는 부분이라 코드가 많이 난잡해서 정리하려고 바꾸다 보니 반응 안하는 부분도 많아서 어려운 점이 많았습니다.
에러메세지 쪽에 스타일을 css쪽으로 정리하고 싶어서 시도는 해보았는데 에러메세지가 동작을 하지않아 정리하는 방법이 있을지 궁금합니다.

2023-12-18 07:51 UTC, Jun-12 commented on signin/index.js
> +    errorBox.style.borderColor = '#ff5b56';
style 프로퍼티를 활용해 태그에 직접적으로 값을 적용시키는 것보다 classList 등으로 태그의 클래스를 변경하는 방식을 사용한다면 불필요한 코드의 중복도 적어지고, style 우선순위가 높아져 발생할 수 있는 문제도 사전에 방지할 수 있지 않을까요? style 프로퍼티를 활용하는 방식을 선택하신 이유가 따로 있으신가요?

2023-12-18 08:09 UTC, huniiiiii commented on signin/index.js
> +    errorBox.style.borderColor = '#ff5b56';
저도 이 부분을 작성하고 너무 코드가 지저분해져서 고민하다가 더 깔끔하게 작성하는 방법을 찾아보고 적용해보았는데 어디선가 문제가 발생하여 적용하지 못하고 시간의 문제로 작동하는데로 올렸습니다😥 말씀하신 방법으로도 한번 자세히 찾아보고 오류없이 다시 적용하도록 해보아야겠네요. 피드백 감사합니다 😄

2023-12-18 08:31 UTC, Jun-12 commented on signin/index.js
> +    errorBox.style.borderColor = '#ff5b56';
시간 내에 구현해내는 능력은 아주 중요한 것 같아요!! 수고 많으셨어요 👍

2023-12-18 17:36 UTC, wonsss requested changes
안녕하세요. 성훈님 ~  이번 미션도 수고 많으셨습니다.  👍 
리뷰한 내용 반영 부탁드립니다. 그리고 리뷰 반영 후 다시 리뷰받길 원하시면 노티주세요 😄

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +};
변수가 정의되기 전에 사용(export) 하시면 안됩니닷. 제일 아래에 두시는 게 나을 것 같아요.
 eslint에서 https://eslint.org/docs/latest/rules/no-use-before-define 룰이 표시되고 있지 않나요?

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +});
이벤트 핸들러로 넣은 익명함수 대신에 기명 함수를 넣으시는 게 나을 것 같아요.
이벤트 핸들러 함수 네이밍 컨벤션은 일반적으로 "`handle`+`대상요소`+`이벤트`" 입니다.
여기서는 함수 이름을 `handleEmailInputFocusout` 으로 해서 아래와 같이 수정해볼 수 있겠네요 :)
```js
emailInput.addEventListener('focusout', handleEmailInputFocusout)
```

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +function isValidEmail(email) {
함수 이름은 동사로 시작해야 합니다.
`validateEmail` 은 어떤가요?

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +const errorBox2 = document.querySelector('.box5');
변수명에 숫자를 사용하는 것은 지양해주세요.
 명확하지 않습니다. 대신에 해당 변수를 더 잘 설명할 수 있는 단어를 넣어서 서술하는 게 명시적이에요.

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +passwordInput.addEventListener('focusout', function () {
이벤트핸들러를 익명함수 말고 기명함수로 분리해주세요!

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +  const passwordValue = this.value.trim();
trim 메서드를 사용하신 이유가 궁금해요. 
공백이 포함된 문자열에 대해서 아래 유효성검사 로직에서 체크해주면 되지 않을까요?

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +  }
if, else if, else 가 많이 이어지고 있네요. 
if-else 문이 너무 많으면 읽기가 어렵고 조건에 대해 명시적이지 않을 수 있어요. 이런 경우 `Early Return`기법을 활용하면 가독성이 더 나아지도록 리팩터링하실 수 있습니다.

참고로 Early Return이란 조건문에서 먼저 Return할 수 있는 부분은 분리하여 우선 if문 내에서 Return하여 함수를 미리 종료하는 것이에요. 이렇게 하면 뒤의 코드로 진입하지 않아 else문을 사용하지 않아도 됩니다.

```js
function loginService(isLogin, user) {
  // 1. 로그인 여부 확인
  if (!isLogin) {
    // 2. 토큰 존재 확인
    if (checkToken()) {
      // 3. 가입 여부 재확인
      if (!user.nickName) {
        return registerUser(user);
      } else {
        refreshToken();

        return '로그인 성공';
      }
    } else {
      throw new Error('No Token');
    }
  }
}
```
예를 들어 위와 같은 코드를 Early Retrun으로 아래처럼 리팩터링하실 수 있어요. 참고해 보세요! 😄 
```js
function loginService(isLogin, user) {
  // 1. 로그인 여부 확인
  if (!isLogin) {
    // 2. 토큰 존재 확인
    if (checkToken()) {
      // 3. 가입 여부 재확인
      if (!user.nickName) {
        return registerUser(user);
      } else {
        refreshToken();

        return '로그인 성공';
      }
    } else {
      throw new Error('No Token');
    }
  }
}
```

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +function isValidPassword(password) {
함수 이름을 동사로 시작하도록 수정해주세요!

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +}
함수를 순수하게 잘 작성하셨네요 :)

참고로 순수함수란 동일한 인수가 전달되면 언제나 동일한 값을 반환하는 함수이며 부수 효과(Side Effect)가 없어야 합니다.
순수함수로 작성하려고 노력해야, 부수 효과(Side Effect)가 없어야 합니다.
순수함수로 작성하면, 다음과 같은 장점이 있어요.
- 동일한 입력에 대해 항상 동일한 결과를 반환합니다. 이는 예측 가능성을 높이고 디버깅 및 테스트를 용이하게 합니다.
- 순수 함수는 다른 함수와 조합하여 더 복잡한 로직을 만들 수 있습니다. 이는 모듈화와 코드 재사용성을 높여줍니다.
- 함수가 외부 상태를 변경하지 않고, 함수 외부의 상태에 영향을 주지 않습니다. 이로써 코드의 복잡성이 감소하고 예상치 못한 동작이 발생할 확률이 낮아집니다.

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +const passwordBtn = document.querySelector('.password-box');
클래스 대신에 아이디로 DOM 요소 선택하는 것이 더 좋습니다.

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +    window.location.href = '../etc/folder.html'; // 로그인 성공 시 페이지 이동
이처럼 location 객체의 href 속성을 통해 페이지를 이동시킬 수도 있습니다.

그런데 여기서는 form 태그를 사용하고 있고, form 태그의 submit 이벤트 발생 시 action 을 활용하여 페이지를 이동시킬 수도 있습니다.
등록된 이메일과 올바른 패스워드라면, form.submit() 메서드를 호출하는 식으로 변경해보는 것은 어떨까요?
그리고 form 요소 내에 method와 action 속성을 인라인으로 지정해주세요.

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +  const eyeIcon = document.querySelector('.eye-icon');
eyeIcon 변수를 전역 스코프와 함수 내 스코프에서 각각 선언하셨네요.

dom 요소 선택하여 변수 선언은 파일의 최상단에 모으시는 것은 어떠실까요?

2023-12-18 17:36 UTC, wonsss commented on signup/index.js
> +  }
else if 문 대신에 early return 패턴으로 리팩터링해보시겠어요?

2023-12-18 17:36 UTC, wonsss commented on signup/index.js
> +function isValidPassword2(password) {
함수 이름에도 숫자를 넣지 말아주세요

2023-12-18 17:36 UTC, wonsss commented on signup/index.js
> +});
form submit 이벤트를 사용하면 이와 같은 코드는 필요하지 않습니다. 

form submit 이벤트는 submit button 클릭 외에도 enter key 입력 시에도 동작하기 때문입니다.

2023-12-18 17:36 UTC, wonsss commented on signup/index.js
> +loginButton.addEventListener('click', login);
이와 같이 로그인 버튼에 클릭 이벤트를 등록하지 않으셔도 돼요.

대신에 form 요소의 submit 이벤트에 다음과 같은 이벤트 핸들러 함수를 넣어보세요.

```js
const signinForm = document.getElementById('signin-form');

function handleFormSubmit (event) {
  event.preventDefault();
  login();
}

signinForm.addEventListener('submit', handleFormSubmit);
```

아 그리고 HTML에서 form 요소 내에 submit type의 button을 넣어주세요.
```js
  <form id="signin-form">
      <-- 생략 -- >
    <button type="submit" class="box3" id="login-button">회원가입</button>
  </form>
```

아래 링크 등을 통해 form에 대해 더 알아보시면 좋을 것 같아요.
https://tecoble.techcourse.co.kr/post/2021-05-22-html-form-tag/
https://developer.mozilla.org/ko/docs/Web/HTML/Element/form
https://developer.mozilla.org/ko/docs/Glossary/Submit_button

2023-12-18 17:36 UTC, wonsss commented on signup/index.js
> +    window.location.href = '../etc/folder.html'; // 로그인 성공 시 페이지 이동
>중복된 리뷰이지만 참고하실 수 있도록 추가했어요

이처럼 location 객체의 href 속성을 통해 페이지를 이동시킬 수도 있습니다.

그런데 여기서는 form 태그를 사용하고 있고, form 태그의 submit 이벤트 발생 시 action 을 활용하여 페이지를 이동시킬 수도 있습니다.
등록된 이메일과 올바른 패스워드라면, form.submit() 메서드를 호출하는 식으로 변경해보는 것은 어떨까요?
그리고 form 요소 내에 method와 action 속성을 인라인으로 지정해주세요.

2023-12-18 17:36 UTC, wonsss commented on signin/index.html
> +            <label for="email"></label>
label이 쓸모가 있도록 해당 텍스트를 label 내에 넣어주세요.
```suggestion
          <div class="box2">
            <label for="email">이메일</label>
```

2023-12-18 17:36 UTC, wonsss commented on signin/index.html
> +            <label for="password"></label>
여기도 마찬가지로 label에 텍스트 넣어주세요

2023-12-18 17:36 UTC, wonsss commented on signin/index.html
> +            <img src="../image/eye-off.png" class="eye-icon" />
img 에 alt 속성을 넣어주세요. 웹접근성에 도움이 됩니다

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +    errorBox.style.borderColor = '#ff5b56';
준수님 좋은 리뷰를 해주셨네요 👍 

아래 첨부해드린 관련 자료를 읽어봐주세요.
https://ko.javascript.info/styles-and-classes
<img width="932" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/126683f1-16fe-49ae-b300-72a5018ed527">

2023-12-18 17:36 UTC, wonsss commented on signin/index.js
> +  const password = 'codeit101';
'test@codeit.com', 'codeit101' 과 같은 도메인과 관련된 `매직 리터럴`은 별도의 파일에 상수로 분리하여 모듈화한 후 관리해주시면 좋습니다.

매직 넘버(Magic number)나 매직 리터럴(Magic Literal)은 코드에서 하드 코딩된 일정한 값을 의미하는 숫자나 문자열을 의미합니다. 
예를 들어 'test@codeit.com' 코드 내에서 여러 곳에서 사용되고 있지만, 이 값의 의미나 목적은 현재 코드에서 명확하게 알려져 있지 않습니다.

매직넘버나 매직리터럴은 가독성이 떨어지고 유지보수를 어렵게 만들며, 예상치 못한 버그를 발생시키는 원인이 될 수 있습니다.

따라서 이들을 상수로 분리하고 해당 매직넘버의 역할을 정확한 이름으로 붙여서 사용하시는 것이 좋습니다. 그리고 상수로 분리해두면 값을 변경할 때 일괄적으로 변경할 수 있으므로 코드의 유지보수성과 가독성이 향상됩니다.

참고로 자바스크립트에서 상수를 선언하는 컨벤션은
`MOCK_EMAIL` 처럼 모두 영어 대문자에 띄어쓰는 부분은 언더바를 적습니다.

2023-12-18 17:36 UTC, wonsss commented on signup/index.html
> +            <input class="password-box" name="password" />
type="password" 속성이 누락되었습니다.
비밀번호의 경우 이와 같은 속성이 필수적입니다.

2023-12-18 17:36 UTC, wonsss commented on signup/index.html
> +            <input class="password-box2" name="password" />
type="password" 속성이 누락되었습니다.
넣어주세요

2023-12-18 17:36 UTC, wonsss commented on signup/index.html
> +            <input type="email" class="email-box" name="email" />
input 태그에 autofocus 속성을 주시면 페이지가 새로고침되자마자 이 첫 input에 focus가 있어서 사용자가 인풋을 클릭할 필요 없이 바로 입력할 수 있어서 사용자 경험에 좋을 것 같아요.

<img width="923" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/799de619-e497-4137-b355-7e4c7a8301ce">

2023-12-18 17:36 UTC, wonsss commented on package.json
> +  "dependencies": {
지금 여기에 적힌 dependencies는 모두 불필요합니다.
node module 이 이미 설치된 이후에 npm init을 하게 되어 이런 문제가 발생한 것 같아요.
단순하게 해결한다면 dependencies 를 다 지우셔도 돼요.

2023-12-20 02:43 UTC, shkim901112 commented on signin/index.js
> +};
ead2aab2e2dbc990c58bd2a500f03f29f4b153f7

룰이 없어서 확인하고 추가했습니다 !
export의 위치도 중요하군요 !! 수정했습니다

2023-12-21 02:13 UTC, shkim901112 commented on signin/index.js
> +});
26531785922e1b573a0b105b6f08d20446eb4399

익명함수를 주는거보단 이름을 주는게 관리하는편에서는 훨씬 낫겠군요 ! 수정하였습니다

2023-12-21 02:15 UTC, shkim901112 commented on signin/index.js
> +const errorBox2 = document.querySelector('.box5');
이름을 짓는게 항상 어렵네요 ㅜㅜ 단어의 의미를 찾아보고 연습해보도록 하겠습니다

2023-12-21 02:20 UTC, shkim901112 commented on signin/index.js
> +  const passwordValue = this.value.trim();
26531785922e1b573a0b105b6f08d20446eb4399

비밀번호에 공백이 없어야 된다고 해서 생각해서 그랬는데 생각해보니 공백도 검사를 해야되겠군요!
유효성검사에 추가했습니다

2023-12-21 02:21 UTC, shkim901112 commented on signin/index.js
> +  }
26531785922e1b573a0b105b6f08d20446eb4399

알려주신대로 early return을 하니 훨씬 편하고 가독성도 좋은거같습니다 😄

2023-12-21 02:24 UTC, shkim901112 commented on signin/index.js
> +    window.location.href = '../etc/folder.html'; // 로그인 성공 시 페이지 이동
583a647e4e110d316d5b739e29a2efe05dd078c5
c3f6fc2172231b4b1bf1501b475cb391880bb995

html 작성할때 form으로 지정만 해놓고 써먹질 못했군요 
submit으로 수정했습니다 !

2023-12-21 02:28 UTC, shkim901112 commented on signup/index.html
> +            <input type="email" class="email-box" name="email" />
이런 디테일도 신경쓰도록 하겠습니다 😄

2023-12-21 02:35 UTC, shkim901112 commented
원석님 모듈을 관리할때 export를 어떤형식으로 하는게 가장 깔끔한걸까요 ? named로 묶으니 파일갯수가 많아지면 지저분해보이는 느낌이 있는데  좋은 방법이 있는지 궁금합니다 !

2023-12-21 06:31 UTC, wonsss commented on signin/index.js
> +};
네 선언되기 전에 사용하면 안 되어서요 ㅎㅎ

2023-12-21 06:32 UTC, wonsss commented on signin/index.js
> +  }
수고하셨습니다!

2023-12-21 06:32 UTC, wonsss commented on signin/index.js
> +    window.location.href = '../etc/folder.html'; // 로그인 성공 시 페이지 이동
수고하셨습니다!

2023-12-21 06:37 UTC, wonsss approved these changes
리뷰 꼼꼼히 반영해주셔서 감사합니다. 성훈님 👍 
수고 많으셨어요.
다음 미션에서 뵈어요. 😄

2023-12-21 06:37 UTC, shkim901112 commented on signin/index.js
> +    errorBox.style.borderColor = '#ff5b56';
확인 후 수정했습니다 !

2023-12-21 06:39 UTC, shkim901112 commented on signin/index.js
> +function isValidEmail(email) {
함수이름에 동사로 시작하는것은 잘 몰랐는데 좀 더 생각해서 이름을 지어야겠군요
vaildateEmail로 수정하였습니다 !

2023-12-21 06:39 UTC, shkim901112 commented on signin/index.js
> +passwordInput.addEventListener('focusout', function () {
확인후 수정했습니다 !

2023-12-21 06:40 UTC, shkim901112 commented on signin/index.js
> +function isValidPassword(password) {
수정하였습니다 !

2023-12-21 06:41 UTC, shkim901112 commented on signin/index.js
> +}
감사합니다 ! 자세한 명칭에 대해선 몰랐는데 이런부분도 뜻이 있었군요😀

2023-12-21 06:41 UTC, shkim901112 commented on signin/index.js
> +const passwordBtn = document.querySelector('.password-box');
확인후 수정하였습니다 !

2023-12-21 06:41 UTC, wonsss commented
> 원석님 모듈을 관리할때 export를 어떤형식으로 하는게 가장 깔끔한걸까요 ? named로 묶으니 파일갯수가 많아지면 지저분해보이는 느낌이 있는데 좋은 방법이 있는지 궁금합니다 !

같은 성격끼리 객체로 묶어서 export하셔도 좋을 것 같아요. 또는 아까 말씀드렸던 클래스 방법을 쓰실 수도 있구요.

https://velog.io/@teo/oop 이 글 내용을 읽어보시면 좋을 것 같아요.

<img width="734" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/e7e644b1-ad25-42ac-84ee-426056fd53a2">


<img width="749" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/4b7440f1-b2c5-48e3-8cae-697f015218b3">

<img width="744" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/a88d37c5-f73a-4a0a-a472-a5d04f0dd096">

2023-12-21 06:42 UTC, shkim901112 commented on signin/index.js
> +  const eyeIcon = document.querySelector('.eye-icon');
하나로 묶어서 최상단으로 다른파일들도 함께 모아서 수정했습니다😄

2023-12-21 06:43 UTC, wonsss approved these changes

2023-12-21 06:43 UTC, shkim901112 commented on signup/index.js
> +  }
early return으로 signin, signup 모두 수정하였습니다 !

2023-12-21 06:44 UTC, shkim901112 commented on signup/index.js
> +function isValidPassword2(password) {
확인후 수정하였습니다 !

2023-12-21 06:45 UTC, merged

2023-12-21 06:46 UTC, shkim901112 commented on signup/index.js
> +});
form submit으로 수정하였습니다 !

2023-12-21 06:46 UTC, shkim901112 commented on signup/index.js
> +loginButton.addEventListener('click', login);
알려주신 코드를 바탕으로 수정하였습니다 !

2023-12-21 06:46 UTC, shkim901112 commented on signup/index.js
> +    window.location.href = '../etc/folder.html'; // 로그인 성공 시 페이지 이동
확인후 수정하였습니다 !

2023-12-21 06:47 UTC, shkim901112 commented on signin/index.html
> +            <label for="email"></label>
확인 후 수정하였습니다 !

2023-12-21 06:47 UTC, shkim901112 commented on signin/index.html
> +            <label for="password"></label>
확인 후 수정하였습니다 !

2023-12-21 06:48 UTC, shkim901112 commented on signin/index.html
> +            <img src="../image/eye-off.png" class="eye-icon" />
네! 알겠습니다 앞으로는 속성추가할때 입력해보는 습관을 가져야겠네요 😅
수정하였습니다 !

2023-12-21 06:48 UTC, shkim901112 commented on signin/index.js
> +  const password = 'codeit101';
850fb04d819fda4fc3c16900dedbd9b4cf8b5e3f

생각해보니 지금은 수가 적어서 그렇지만 매직리터럴은 많아지면 그만큼 관리가 힘들겠군요. 앞으로는 모듈로 따로 관리하겠습니다 !

2023-12-21 06:48 UTC, shkim901112 commented on signup/index.html
> +            <input class="password-box" name="password" />
확인후 수정하였습니다 !

2023-12-21 06:48 UTC, shkim901112 commented on signup/index.html
> +            <input class="password-box2" name="password" />
확인 후 수정하였습니다 !

2023-12-21 06:48 UTC, shkim901112 commented on package.json
> +  "dependencies": {
확인 후 수정하였습니다 !