[박준수] Week4
codeit-bootcamp-frontend/3-Weekly-Mission pull request #99
Opened 2023-12-16 12:40 UTC by Jun-12

## 요구사항

### 기본
- [x]  [기본]이메일 input에서 focus out 할 때, 값이 없을 경우 input에 빨강색 테두리와 아래에 “이메일을 입력해주세요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]이메일 input에서 focus out 할 때, 이메일 형식에 맞지 않는 값이 있는 경우 input에 빨강색 테두리와 아래에 “올바른 이메일 주소가 아닙니다.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]이메일 input에서 focus out 일 때, input 값이 [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com) 일 경우 input에 빨강색 테두리와 아래에 “이미 사용 중인 이메일입니다.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]비밀번호 input에서 focus out 할 때, 값이 8자 미만으로 있거나 문자열만 있거나 숫자만 있는 경우, input에 빨강색 테두리와 아래에 “비밀번호는 영문, 숫자 조합 8자 이상 입력해 주세요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]비밀번호 input과 비밀번호 확인 input의 값이 다른 경우, 비밀번호 확인 input에 빨강색 테두리와 아래에 “비밀번호가 일치하지 않아요.” 빨강색 에러 메세지가 보이나요?
- [ ]  [기본]회원가입을 실행할 경우, 문제가 있는 경우 문제가 있는 input에 빨강색 테두리와 에러 메세지가 보이나요?
- [x]  [기본]이외의 유효한 회원가입 시도의 경우, “/folder”로 이동하나요?
- [x]  [기본]이메일: [[test@codeit.com](mailto:test@codeit.com)](mailto:test@codeit.com), 비밀번호: codeit101 으로 로그인 시도할 경우, “/folder” 페이지로 이동하나요?
- [x]  [기본]비밀번호 input에서 focus out 할 때, 값이 없을 경우 아래에 “비밀번호를 입력해주세요.” 에러 메세지가 보이나요?
- [x]  [기본]이외의 로그인 시도의 경우 이메일, 비밀번호 input에 빨강색 테두리와 각각의 input아래에 “이메일을 확인해주세요.”, “비밀번호를 확인해주세요.” 빨강색 에러 메세지가 보이나요?
- [x]  [기본]회원가입 버튼 클릭 또는 Enter키 입력으로 회원가입 되나요?
- [x]  [기본]이메일, 비밀번호 input에 에러 관련 디자인을 Components 영역의 에러 케이스로 적용했나요?

### 심화

- [x]  [심화]눈 모양 아이콘 클릭시 비밀번호의 문자열이 보이기도 하고, 가려지기도 하나요?
- [x]  [심화]비밀번호의 문자열이 가려질 때는 눈 모양 아이콘에는 사선이 그어져있고, 비밀번호의 문자열이 보일 때는 사선이 없는 눈 모양 아이콘이 보이나요?
- [ ]  [심화]로그인, 회원가입 페이지에 공통적으로 사용하는 로직이 있다면, 반복하지 않고 공통된 로직을 모듈로 분리해 사용했나요?

## 주요 변경사항

- 이메일, 비밀번호, 비밀번호 확인 input 유효성 검증 기능 추가
- 비밀번호, 비밀번호 확인 표심/숨김 기능 추가

## 스크린샷

## 멘토에게

-
-
-

2023-12-18 13:51 UTC, Jun-12 commented on sign/script/signup.js
> +});
이 부분은 이벤트 핸들링 중복을 없애고, 표시/숨김 아이콘이 많아져도 적용할 수 있게 하려고 변경 해보았습니다. 
하지만 정확히 어떤 아이콘이 해당되고, 그 아이콘들의 previousElementSibling이 무엇인지 확인하기 위해 html도 확인해야 하며, 그 자리에 반드시 input이 있어야 된다는 단점이 있습니다. 이런 경우에는 명시적으로 보이게 하기 위해 아이콘이 생길 때마다 중복적으로 핸들링을 생성하여  input과 icon 아규먼트를 직접 전달하는 방식이 더 바람직할까요? 

제가 고민해본 바로는 두 가지 방법을 모두 염두해 두고 있다가, 아이콘의 갯수가 적을 때는 명시적인 방법을, 예상보다 갯수가 많아진다면 재사용성을 높이는 방법을 사용하는 것이 좋을 것 같은데 어떻게 생각하시나요?

2023-12-18 15:36 UTC, Jun-12 commented on sign/script/signup.js
> +});
해당 부분 수정해 보았습니다!
```JS
visibilityIconList.forEach((icon) => {
  icon.addEventListener('click', ({ target }) => {
    const targetInput = target.previousElementSibling;
    togglePasswordVisibility(target, targetInput);
  });
});
```

2023-12-18 16:14 UTC, wonsss requested changes
안녕하세요! 준수님 😄 클린한 코드를 짜려고 많이 노력하신 것 같아요! 👏 👏 
수고 많으셨습니다.
리뷰 반영 후 재리뷰 필요하시면 노티 주세요!

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +const passwordRegex = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,25}$/;
요구사항은 "영문, 숫자 조합 8자 이상" 이더라구요.
그런데 비밀번호로 "abcd1234$#$" 처럼 특수문자를 넣어도 허용이 되네요.  :)
특수문자는 허용되지 않도록 정규표현식을 확인해주시면 좋을 것 같아요.

2023-12-18 16:14 UTC, wonsss commented on sign/signin.html
> +      <form id="form-list">
form 태그 인라인에 method 속성과 action 속성을 지정하는 것은 어떨까요?
submit handler 함수 내에서 자바스크립트로 form 태그 속성을 submit 직전에 지정해주고 있더라구요. 그런데 이 form에서 method와 action이 여러 케이스로 분기될 가능성이 없을 것 같습니다.
그렇다면 명시적으로 HTML 내에 적는 게 나을 것 같아요. 😄

2023-12-18 16:14 UTC, wonsss commented on shared/color.css
> +:root {
root css 변수를 별도의 파일로 분리하셨군요. 
이렇게 별도 관리해주는 것도 좋은 것 같아요.

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +const visibilityIconList = document.querySelectorAll('.switch-icon');
요소에 대한 변수명을 규칙성 있게 잘 지으신 것 같네요 👍

2023-12-18 16:14 UTC, wonsss commented on sign/script/signin.js
> +}
멋진 방법을 시도하셨네요 👍 
위와 같이 코드를 작성하신 이유가 궁금해요. 

이와 같이 요소에 따라 해당 함수로 분기하는 역할을 지닌 checkFocusOutError 함수를 만들어서 사용하게 되면, 나중에 수정사항이 생길 때, 이 함수도 관리해야 하는 관리포인트가 늘게 되어 가독성이 떨어질 것 같아요. 해당 함수를 통해 중복을 줄이고 있는 것도 아닌 것 같구요.

그보다는 아래와 같이 요소별로 해당 이벤트 핸들러를 각각 직접 등록시키는 게 가독성이 더 좋을 것 같아요. 준수님 생각은 어떠신가요? 😄 

```js
emailInput.addEventListener('focusout', validateSignInEmail);
passwordInput.addEventListener('focusout', validatePassword);
passwordRepeatInput.addEventListener('focusout', validatePasswordRepeat);
```

2023-12-18 16:14 UTC, wonsss commented on sign/script/signup.js
> +formElement.addEventListener('submit', checkSubmitError);
이벤트핸들러 함수의 네이밍 컨벤션을 정해두는 것은 어떨까요?
일관된 네이밍 컨벤션을 정해두면, 어떤 함수의 이름만 보더라도 이벤트핸들러이며 어떤 요소의 무슨 이벤트가 발생했을 때 쓴다는 것을 알 수 있습니다.

예를 들어, `checkFocusOutError` 대신 `handleEmailInputFocusout' 로 이름을 쓸 수 있어요.
```
emailInput.addEventListener('focusout', checkFocusOutError);
```

`handle` + `이벤트 발생하는 요소` + `이벤트 이름` 
이러한 방식으로 이벤트핸들러 이름을 일관되게 지으시는 것을 제안드려요.

[관련 링크](https://blog.sonim1.com/220#google_vignette)를 공유드려요. 리액트 관련이긴 하지만, 맥락만 읽어보셔도 좋습니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/signin.js
> +  });
visibilityIconList의 이벤트 핸들러 내부에서 함수를 익명 함수로 정의하셨군요.
이 경우, 함수를 따로 정의하고 그 함수를 이벤트 핸들러로 전달하는 것은 어떠신가요?
이를 통해 가독성을 향상시킬 수 있을 것 같아요.

```js
function handleVisibilityIconClick() {
  togglePasswordVisibility(this, this.previousElementSibling);
}

visibilityIconList.forEach((icon) => {
  icon.addEventListener('click', handleVisibilityIconClick);
});
```

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +}
else if와 else 문이 계속해서 이어지네요. 

가독성을 더 좋게 하려면 Early return 패턴을 사용해서 리팩터링해보시는 것을 추천드립니다.

Early return 패턴은 코드의 가독성과 유지보수성을 향상시킬 수 있는 패턴 중 하나입니다. 코드에서 조건이 충족되지 않으면 함수의 실행을 즉시 종료하고, 조건이 충족될 때만 나머지 로직을 실행하는 방식입니다. 이 패턴을 사용하면 중첩된 if-else 구문을 피하고 코드의 흐름을 단순화할 수 있습니다.

```suggestion
function validateSignUpEmail() {
  const emailValue = emailInput.value;

  if (!emailValue) {
    // input 공백 시 실행
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '이메일을 입력해주세요.';
    isValidEmail = false;
    return;
  }

  if (emailRegex.test(emailValue) === false) {
    // 이메일 유형이 아닐 시 실행
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '올바른 이메일 주소가 아닙니다.';
    isValidEmail = false;
    return;
  }

  if (emailValue === 'test@codeit.com') {
    // test@codeit.com 입력 시 실행
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '이미 사용 중인 이메일입니다.';
    isValidEmail = false;
    return;
  }

  // 유효성 검사 통과
  emailErrorText.textContent = '';
  emailInput.classList.remove('error-border');
  isValidEmail = true;
}
```

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +}
else if와 else 문이 계속해서 이어지네요. 

가독성을 더 좋게 하려면 Early return 패턴을 사용해서 리팩터링해보시는 것을 추천드립니다.

Early return 패턴은 코드의 가독성과 유지보수성을 향상시킬 수 있는 패턴 중 하나입니다. 코드에서 조건이 충족되지 않으면 함수의 실행을 즉시 종료하고, 조건이 충족될 때만 나머지 로직을 실행하는 방식입니다. 이 패턴을 사용하면 중첩된 if-else 구문을 피하고 코드의 흐름을 단순화할 수 있습니다.

```suggestion
function validateSignUpEmail() {
  const emailValue = emailInput.value;

  if (!emailValue) {
    // input 공백 시 실행
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '이메일을 입력해주세요.';
    isValidEmail = false;
    return;
  }

  if (emailRegex.test(emailValue) === false) {
    // 이메일 유형이 아닐 시 실행
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '올바른 이메일 주소가 아닙니다.';
    isValidEmail = false;
    return;
  }

  if (emailValue === 'test@codeit.com') {
    // test@codeit.com 입력 시 실행
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '이미 사용 중인 이메일입니다.';
    isValidEmail = false;
    return;
  }

  // 유효성 검사 통과
  emailErrorText.textContent = '';
  emailInput.classList.remove('error-border');
  isValidEmail = true;
}
```

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +function validateSignInEmail() {
early return 패턴으로 리팩터링 제안드립니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +function validatePassword() {
early return 패턴으로 리팩터링 제안드립니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +function validatePasswordRepeat() {
early return 패턴으로 리팩터링 제안드립니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +  console.log(icon);
불필요한 console.log 는 배포 시에 제거해주시는 게 좋습니다. 😄

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +    isValidEmail = false;
그리고 이 함수는 인자를 받지 않고 모두 전역변수를 읽고 쓰고 있네요.
전역변수는 사용을 지양하는 것이 좋습니다. 전역변수를 지양해야 하는 이유에 대해서 찾아보시면 좋을 것 같아요!

이 함수도 인자로 event를 받게 하고, 인자로 받은 event 객체를 통해 currentTarget이나 주위의 다른 요소를 탐색하여 선택할 수도 있습니다. 
그리고 이벤트 핸들러 내에서 `this` 는 이벤트를 바인딩한 해당 DOM 요소를 참조합니다. event.currentTarget과 동일해요.

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/this#dom_%EC%9D%B4%EB%B2%A4%ED%8A%B8_%EC%B2%98%EB%A6%AC%EA%B8%B0%EB%A1%9C%EC%84%9C

2023-12-18 16:14 UTC, wonsss commented on sign/script/signup.js
> +    formElement.action = '/folder.html';
form 태그 인라인에 속성으로 지정해도 될 것 같아요

2023-12-18 16:14 UTC, wonsss commented on sign/script/signin.js
> +  }
중첩된 조건문은 가독성에 좋지 않습니다.
조건문이 중첩되지 않도록 1depth로 풀면 좋을 것 같아요.


```js
function handleSigninFormSubmit(e) {
  e.preventDefault();

  if (emailInput.value !== 'test@codeit.com') {
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '이메일을 확인해 주세요.';
    return;
  }

  if (passwordInput.value !== 'codeit101') {
    passwordInput.classList.add('error-border');
    passwordErrorText.textContent = '비밀번호를 확인해 주세요.';
    return;
  }

  if (emailInput.value === 'test@codeit.com' && passwordInput.value === 'codeit101') {
    formElement.method = 'POST';
    formElement.action = '/folder.html';
    formElement.submit();
    return;
  }

  emailInput.classList.remove('error-border');
  passwordInput.classList.remove('error-border');
  emailErrorText.textContent = '';
  passwordErrorText.textContent = '';
}
```

2023-12-18 16:14 UTC, wonsss commented on sign/script/signin.js
> +  }
함수 이름 checkSubmitError 이 함수 내 로직을 모두 포괄하는 이름이 아닌 것 같아요.
submit 시 error를 체크하는 역할만 하고 있는 것이 아니라, 
통과할 수 있는 이메일과 비밀번호이면 submit 메서드를 호출하여 로그인을 시키는 중요 로직도 포함되어 있네요. 이외에도 DOM 을 변경하는 로직도 함께 있구요.
그래서 이벤트 핸들러 이름으로는 `handleSigninFormSubmit` 이 적절해보입니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/signin.js
> +  }
```js
function handleSigninFormSubmit(e) {
  e.preventDefault();

  if (emailInput.value !== 'test@codeit.com') {
    emailInput.classList.add('error-border');
    emailErrorText.textContent = '이메일을 확인해 주세요.';
    return;
  }

  if (passwordInput.value !== 'codeit101') {
    passwordInput.classList.add('error-border');
    passwordErrorText.textContent = '비밀번호를 확인해 주세요.';
    return;
  }

  if (emailInput.value === 'test@codeit.com' && passwordInput.value === 'codeit101') {
    formElement.method = 'POST';
    formElement.action = '/folder.html';
    formElement.submit();
    return;
  }

  emailInput.classList.remove('error-border');
  passwordInput.classList.remove('error-border');
  emailErrorText.textContent = '';
  passwordErrorText.textContent = '';
}
```

2023-12-18 16:14 UTC, wonsss commented on sign/script/signin.js
> +  if (emailInput.value === 'test@codeit.com' && passwordInput.value === 'codeit101') {
'test@codeit.com', 'codeit101' 처럼 도메인과 관련된 `매직 리터럴`은 별도의 파일에 상수로 분리하여 모듈화한 후 관리해주시면 좋습니다.

매직 넘버(Magic number)나 매직 리터럴(Magic Literal)은 코드에서 하드 코딩된 일정한 값을 의미하는 숫자나 문자열을 의미합니다. 
예를 들어 'test@codeit.com' 코드 내에서 여러 곳에서 사용되고 있지만, 이 값의 의미나 목적은 현재 코드에서 명확하게 알려져 있지 않습니다.

매직넘버나 매직리터럴은 가독성이 떨어지고 유지보수를 어렵게 만들며, 예상치 못한 버그를 발생시키는 원인이 될 수 있습니다.

따라서 이들을 상수로 분리하고 해당 매직넘버의 역할을 정확한 이름으로 붙여서 사용하시는 것이 좋습니다. 그리고 상수로 분리해두면 값을 변경할 때 일괄적으로 변경할 수 있으므로 코드의 유지보수성과 가독성이 향상됩니다.

참고로 자바스크립트에서 상수를 선언하는 컨벤션은 `MOCK_EMAIL` 처럼 모두 영어 대문자에 띄어쓰는 부분은 언더바를 적습니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +let isValidPasswordRepeat = false;
이와 같은 전역변수는 사용을 지양해야 합니다.
현재 해당 변수들은 validate 함수 내에서 조건의 결과로 값이 변경되고, 이 변수들이 submit 핸들러 내에서 참조되어 submit 여부 조건으로 사용되고 있는 것 같네요.

대안으로서, 해당 전역변수들을 제거하고, validate 함수 내에서 `isValidEmail = false` 같으 변수 값 변경 대신 `return false` 처럼 boolean 값을 return 하도록 변경해보세요.
그러면 submit 핸들러 함수 내에서는 validate 함수를 불러서 실행합니다. validate 함수의 결과값이 boolean이며 이전의 isValid 전역변수와 같은 역할을 할 수 있습니다.

2023-12-18 16:14 UTC, wonsss commented on sign/script/common.js
> +  icon.src = type === 'password' ? 'icons/eye-off.svg' : 'icons/eye-on.svg';
`element.attribute = value` 와 `element.setAttribute(attribute, value)` 방식을 혼용하여 사용하셨네요. 

저는 element에 있는 표준 속성이라면, `element.attribute = value`을 사용할 것입니다.
이외에 커스텀으로 추가한 속성이라면, `element.attribute = value`를 사용할 수 없으므로
`element.setAttribute(attribute, value)`을 사용할 것입니다.

준수님은 어떻게 생각하세요?

참고할 수 있는 링크 전달드립니다.

https://stackoverflow.com/questions/3919291/when-to-use-setattribute-vs-attribute-in-javascript

https://www.rahmandawibowo.com/blog/en/modifying-styles-with-setattribute-is-bad/

2023-12-18 16:14 UTC, wonsss commented on sign/signin.html
>          </label>
label 태그가 input 태그 등을 감싸고 있네요.

input 태그의 부모가 label 태그가 되어선 안되고, 둘은 형제 관계 요소로 두는 것이 적절합니다.
https://developer.mozilla.org/ko/docs/Web/HTML/Element/label
<img width="984" alt="image" src="https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/assets/59413128/55e72a3e-d6cc-4f8b-9a62-11a596b5511a">

2023-12-18 16:14 UTC, wonsss commented on sign/script/signup.js
> +});
중복을 줄이기 위해 노력하셨군요 👏 

제 생각엔 명시적인 방법을 쓰는 게 나을 것 같습니다. 
말씀대로 previousElementSibling 가 무엇인지 예측하기 어려워 보입니다.

더 좋은 방법도 많겠지만, 이 상황에서 아래와 같이 리팩터링 해볼 수도 있겠네요. 참고로 봐주세요.

```js
function togglePasswordVisibility() {
  const input = this.parentElement.querySelector('input');
  const icon = this.parentElement.querySelector('img');

  input.type = input.type === 'password' ? 'text' : 'password';
  icon.src = input.type === 'password' ? 'icons/eye-off.svg' : 'icons/eye-on.svg';
}

const passwordVisibilityIcon = document.getElementById('password-visibility-icon');
const passwordRepeatVisibilityIcon = document.getElementById('password-repeat-visibility-icon');

passwordVisibilityIcon.addEventListener('click', togglePasswordVisibility);
passwordRepeatVisibilityIcon.addEventListener('click', togglePasswordVisibility);
```

2023-12-18 16:22 UTC, wonsss commented
> 처음에 제가 의도한 것은 사실 html은 수정하지 않고 JS로만 구현해보는 것이었습니다. 하지만 html에 에러메세지를 담을 태그를 미리 넣어두지 않으니, 구현하는 과정이 어렵게 느껴졌습니다.. 태그를 만들어서 유효한 상황에만 넣어주고 싶은데, 막상 구현을 해보려니 레이아웃도 틀어지고 중복으로 태그가 만들어지는 등 생각보다 고려해야될 것들이 많다는 것을 알았습니다. 중간에 구현과정이 너무 오래걸리는 것 같아 html에 에러메세지를 담을 태그를 미리 작성하고 구현하니, 훨씬 빠른 시간에 구현이 가능했고 불필요한 코드들도 많이 삭제되니 더 직관적이게 된 것 같습니다. 이처럼 지금은 무언가를 구현하거나 어떤 문제를 해결할 때, 더 직관적이고 명시적일 것이라고 생각했던 방식이 생각했던 것 만큼은 아닌 경우가 많고 이것 저것 시도해보면서 방법을 찾아나가다 보니 시간이 배 이상으로 소요되는 것 같습니다. 이건 경험만이 해결해주는 문제겠죠?

왜 html은 수정하지 않고 JS로만 구현하는 것을 처음에 목표로 두셨었나요? 그렇게 할 수는 있으나, 현재 굳이 그럴 필요는 없을 것 같아요. HTML 구조만 보고도 대략적인 구조가 보이면 좋은데, HTML에 없던 요소를 자바스크립트를 통해 동적으로 추가/제거하는 것은 필요한 경우에 한하여 적용하시는 것이 나을 것 같아요. 
고민 없이 하는 것보다 고민하면서 하는 게 훨씬 낫습니다 ㅎㅎ
그 고민의 기준을 "내가 코드 짜기 쉬운 방법"만이 아닌 "다른 사람이 이 코드를 유지보수한다면?", "사용자들이 이상한 방식으로 이 서비스를 사용한다면?" 으로 맞춘다면 좋은 코드를 짜는 태도가 될 것 같아요.

2023-12-19 05:50 UTC, Jun-12 commented on sign/script/signup.js
> +});
역시 명시적인 방법은 쓰는게 맞았군요.. 그리고 `this.parentElement`를 활용하는 방법도 있었네요!! 제시해 주신 코드가 훨씬 깔끔하고 읽기 좋네요. 해당부분 참고하여 리팩토링 해보았습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/72d772e71bac658f525342b1a9539a4f67dfc3d0](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/72d772e71bac658f525342b1a9539a4f67dfc3d0)

2023-12-19 05:51 UTC, Jun-12 commented on sign/script/common.js
> +const passwordRegex = /^(?=.*[a-zA-Z])(?=.*[0-9]).{8,25}$/;
꼼꼼히 테스트 해보았어야 했는데 놓쳤군요..😱 특수문자는 허용되지 않도록 수정하였습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/03404a90e2e85817f07b303bcb559bd8f7bae03b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/03404a90e2e85817f07b303bcb559bd8f7bae03b)

2023-12-19 05:54 UTC, Jun-12 commented on sign/signin.html
> +      <form id="form-list">
HTML에 자체적으로 적어주는 것이 훨씬 직관적이네요!! method와 action이 여러 케이스로 분기될 가능성이 있을 수 있다는 점도 공부를 더 해봐야겠습니다..! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/f7bbfc1ec8fcc18396eb45fb97c1dedec197cd82](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/f7bbfc1ec8fcc18396eb45fb97c1dedec197cd82)

2023-12-19 05:57 UTC, Jun-12 commented on sign/script/common.js
> +const visibilityIconList = document.querySelectorAll('.switch-icon');
사실 제가 느끼기엔 변수명이 너무 길어진다고 생각했기에 처음에는 처음에는 password => pw 처럼 줄임말을 사용했다가, 다른 분들 리뷰를 보고 급하게 수정해보았습니다.😂 아무리 일상에 통용되고 있는 줄임말이라고 하더라도 최대한 지양하는 것이 좋은 것 같네요.

2023-12-19 06:05 UTC, Jun-12 commented on sign/script/signin.js
> +}
단순히 에러를 체크하는 부분을 하나로 묶어주면 유지보수가 용이할 것이라고 생각했습니다.. 이 부분에서 코드를 전체적으로 작성해나가는 방식 부분에서 하나 배웠습니다. 이전에는 함수를 호출하는 경우 비슷한 역할을 하는 함수들을 묶어서 하나의 기능을 하는 함수로 호출한다면 더 알아보기 쉬울 것이라고 생각했지만, 피드백 해주신 내용을 보고 다시보니 확실히 불필요하게 작성된 부분이라는 것을 깨달았습니다. 각각의 기능을 하는 함수를 하나로 묶는 것이 아니라 차라리 이벤트가 해당하는 부분에 알맞는 함수를 각각 호출하는 것이 더 나은 작성 방법이라는 걸 알게됐습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/5a158b9c26022905b22a0b6be27ffb3b88379a5c](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/5a158b9c26022905b22a0b6be27ffb3b88379a5c)

2023-12-19 06:08 UTC, Jun-12 commented on sign/script/signup.js
> +formElement.addEventListener('submit', checkSubmitError);
확실히 네이밍 컨벤션에 따라 네이밍을 변경해보니 훨씬 직관적이고 다른 사람이 제 코드를 봤을 때도 이해하기 쉽겠더라구요..
앞으로는 네이밍 컨벤션을 정해두어 일관되게 네이밍 해보겠습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/3195c55f7585e335e27bcd6341a41a11681cf9f1](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/3195c55f7585e335e27bcd6341a41a11681cf9f1)

2023-12-19 06:11 UTC, Jun-12 commented on sign/script/signin.js
> +  });
이 부분도 가독성이 좋은 것은 어떤 것인지 명확하게 알지 못해 발생한 문제 같습니다..단순히 코드의 길이를 짧게 하는 것보다는 시간이 지나서 제가 작성한 코드를 제가 다시 보거나, 다른 사람이 보아야 한다는 관점에서 작성해보아야 할 것 같습니다!

2023-12-19 06:13 UTC, Jun-12 commented on sign/script/common.js
> +}
아무 생각없이 당연하게 else if 문을 사용했는데, Early return 패턴을 사용하니 훨씬 가독성이 좋네요!!!😲

수정 완료했습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b), [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e)

2023-12-19 06:14 UTC, Jun-12 commented on sign/script/common.js
> +}
위와 동일하게 수정 완료했습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b), [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e)

2023-12-19 06:14 UTC, Jun-12 commented on sign/script/common.js
> +function validateSignInEmail() {
위와 동일하게 수정 완료했습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b), [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e)

2023-12-19 06:14 UTC, Jun-12 commented on sign/script/common.js
> +function validatePassword() {
위와 동일하게 수정 완료했습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b), [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e)

2023-12-19 06:14 UTC, Jun-12 commented on sign/script/common.js
> +function validatePasswordRepeat() {
위와 동일하게 수정 완료했습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b), [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e)

2023-12-19 06:16 UTC, Jun-12 commented on sign/script/common.js
> +  console.log(icon);
아이고 테스트 해본다고 넣어두었던 것을 삭제를 안했네요..😱 
해당부분을 전체적으로 수정하면서 삭제하였습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/72d772e71bac658f525342b1a9539a4f67dfc3d0](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/72d772e71bac658f525342b1a9539a4f67dfc3d0)

2023-12-19 06:17 UTC, Jun-12 commented on sign/script/signup.js
> +    formElement.action = '/folder.html';
수정 완료했습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/f7bbfc1ec8fcc18396eb45fb97c1dedec197cd82](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/f7bbfc1ec8fcc18396eb45fb97c1dedec197cd82)

2023-12-19 06:20 UTC, Jun-12 commented on sign/script/signin.js
> +  }
중첩 if문의 사용을 지양해야 겠네요.. 괜히 함수를 깊에 만들 필요가 없는 것 같습니다!!
[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/879c4b7184429115da6a4939a3eaae656b828c1e)

2023-12-19 06:21 UTC, Jnnsu commented on sign/script/signin.js
> +  }
제시해주신 네이밍 컨벤션에 따라 수정해보았습니다!! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/ae09be3097074ddf76b93c69655806575fe86501](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/ae09be3097074ddf76b93c69655806575fe86501)

2023-12-19 06:23 UTC, Jun-12 commented on sign/script/common.js
> +let isValidPasswordRepeat = false;
좋은 지적 감사합니다. 함수 자체를 boolean 타입으로 return하면 불필요한 전역변수를 사용하지 않아도 되겠네요.

수정완료했습니다.[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/961a6bcd9a904afae85cb71f4c214f4eec1d239b)

2023-12-19 06:26 UTC, Jun-12 commented on sign/script/common.js
> +  icon.src = type === 'password' ? 'icons/eye-off.svg' : 'icons/eye-on.svg';
확실히 말씀하신 방법이 맞는 것 같습니다. element에 있는 표준 속성인데 굳이 커스텀으로 추가한 것처럼 사용할 필요는 없었네요..!!

해당부분을 전체적으로 수정하면서 같이 수정하였습니다. [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/72d772e71bac658f525342b1a9539a4f67dfc3d0](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/72d772e71bac658f525342b1a9539a4f67dfc3d0)

2023-12-19 06:27 UTC, Jun-12 commented on sign/signin.html
>          </label>
해당부분 수정 완료하였습니다! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/662e985c63a5a1bb446b3db083fb6086c3ad95b6](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/662e985c63a5a1bb446b3db083fb6086c3ad95b6)

2023-12-19 06:39 UTC, Jun-12 commented
> 왜 html은 수정하지 않고 JS로만 구현하는 것을 처음에 목표로 두셨었나요? 그렇게 할 수는 있으나, 현재 굳이 그럴 필요는 없을 것 같아요. HTML 구조만 보고도 대략적인 구조가 보이면 좋은데, HTML에 없던 요소를 자바스크립트를 통해 동적으로 추가/제거하는 것은 필요한 경우에 한하여 적용하시는 것이 나을 것 같아요.
고민 없이 하는 것보다 고민하면서 하는 게 훨씬 낫습니다 ㅎㅎ
그 고민의 기준을 "내가 코드 짜기 쉬운 방법"만이 아닌 "다른 사람이 이 코드를 유지보수한다면?", "사용자들이 이상한 방식으로 이 서비스를 사용한다면?" 으로 맞춘다면 좋은 코드를 짜는 태도가 될 것 같아요.

html은 수정하지 않고 JS로만 구현하려고 했던 이유는 화면에 있을 수도, 없을 수도 있는 에러 메세지의 자리를 html에 항상 만들어 둔다면 혼동될 수 있다고 생각했습니다. 그래서 에러 메세지 표시 기능을 html에서 완전히 분리해 보려고 했던 것 같습니다.

하지만 잘못된 생각이었네요.. html만 보고도 어디에 에러 메세지가 들어갈 자리인지 파악할 수 있는 것이 훨씬 명시적일 것 같습니다. 또 말씀하신대로 html에 없던 요소를 동적으로 추가/제거하는 것은 필요한 경우에만 사용한다는 것도 배웠습니다!! 감사합니다😂

2023-12-19 07:15 UTC, Jun-12 commented on sign/script/signin.js
> +  if (emailInput.value === 'test@codeit.com' && passwordInput.value === 'codeit101') {
덕분에 새로운 개념을 알았습니다!! 감사합니다. 매직 리터럴을 별도의 파일에 분리하고, 상수에 담아주었습니다! [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/e4dc3cad4ee03feb8c4975888b6525b232899a4c](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/e4dc3cad4ee03feb8c4975888b6525b232899a4c)

2023-12-19 15:57 UTC, Jun-12 commented on sign/script/common.js
> +    isValidEmail = false;
전역변수를 사용하면 다른 라이브러리나 코드와 충돌할 수 있기 때문에 최대한 지양해야 하는군요!! 피드백 해주신 내용을 바탕으로 최대한 리팩토링 해보았습니다.. 그리고 순수함수를 만들어 필요한 곳에 사용하는 방식으로 변경해 보았습니다!!

[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/fb340a946e540ed403bb77178522e96245f334d7](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/fb340a946e540ed403bb77178522e96245f334d7)

2023-12-19 16:15 UTC, Jun-12 commented
## 변경점 총정리
- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/72d772e71bac658f525342b1a9539a4f67dfc3d0](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/72d772e71bac658f525342b1a9539a4f67dfc3d0): 비밀번호 표시/숨김 기능을 하는 함수를 명시적으로 변경하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/961a6bcd9a904afae85cb71f4c214f4eec1d239b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/961a6bcd9a904afae85cb71f4c214f4eec1d239b)[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/879c4b7184429115da6a4939a3eaae656b828c1e](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/879c4b7184429115da6a4939a3eaae656b828c1e): else if 대신 Early return을 사용하여 가독성을 높였습니다. 

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/03404a90e2e85817f07b303bcb559bd8f7bae03b](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/03404a90e2e85817f07b303bcb559bd8f7bae03b): 비밀번호 특수문자가 허용되던 문제를 수정하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/f7bbfc1ec8fcc18396eb45fb97c1dedec197cd82](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/f7bbfc1ec8fcc18396eb45fb97c1dedec197cd82): form 태그 인라인에 method 속성과 action 속성을 지정하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/5a158b9c26022905b22a0b6be27ffb3b88379a5c](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/5a158b9c26022905b22a0b6be27ffb3b88379a5c): 불필요한 switch문을 제거하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/3195c55f7585e335e27bcd6341a41a11681cf9f1](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/3195c55f7585e335e27bcd6341a41a11681cf9f1)[https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/ae09be3097074ddf76b93c69655806575fe86501](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/ae09be3097074ddf76b93c69655806575fe86501): 네이밍 컨벤션에 따라 네이밍을 변경하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/72d772e71bac658f525342b1a9539a4f67dfc3d0](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/72d772e71bac658f525342b1a9539a4f67dfc3d0): 테스트를 위한 console.log를 삭제하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/662e985c63a5a1bb446b3db083fb6086c3ad95b6](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/662e985c63a5a1bb446b3db083fb6086c3ad95b6): label이 요소를 감싸던 것을 수정하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/e4dc3cad4ee03feb8c4975888b6525b232899a4c](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/e4dc3cad4ee03feb8c4975888b6525b232899a4c): 매직 리터럴을 상수에 담고, 별도의 파일에 분리하였습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/fb340a946e540ed403bb77178522e96245f334d7](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/commit/fb340a946e540ed403bb77178522e96245f334d7): 
  - 전역변수 선언을 최대한 줄여 보았습니다. (혹시 보시기에 더 줄일 요지가 있다고 생각되는 곳이 있으시다면 말씀해주시면 감사하겠습니다!!)
  - 순수함수를 만들어 필요한 곳에 사용할 수 있도록 해보았습니다.

- [https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/3085554abfa03509bfde387296323a297b33ac60](https://github.com/codeit-bootcamp-frontend/3-Weekly-Mission/pull/99/commits/3085554abfa03509bfde387296323a297b33ac60): Enter키 입력 시 에러를 체크하는 이벤트 핸들링을 추가하였습니다.

2023-12-21 05:57 UTC, wonsss commented on sign/script/common.js
> +}
좋아요~!

2023-12-21 06:00 UTC, wonsss commented on sign/script/signin.js
> +  }
if-else hell 을 피해야 해요 ㅎㅎ

2023-12-21 06:02 UTC, wonsss approved these changes
준수님. 꼼꼼하게 리뷰 반영해주셨군요. 👍 
수고 많으셨습니다. 어프로브할게요.
다음 미션에서 뵈어요.

2023-12-21 06:02 UTC, merged